### PR TITLE
[#11212] Mention suggestions based on names parts

### LINKED ISSUE #11212: Mention suggestions based on letter occuring in ENS, random, or nickname
Follow up to #11206

# Problem
As a user I want to see suggestions if I start typing @ followed any letter that occurs in the random name, nickname or ENS name, because I might not recall the full name to trigger the mention suggestions list

## Future Steps
Enter @ followed by any letter that occurs in ENS, random or nickname you want to mention. Suggestion list should include all names that contain this character set

### PR DESCRIPTION
**Pull request by rasom**
fix #11212

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
@errorists please let me know whether this matches behavior you expected

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
#### ISSUE 1: if first enter ENS name to the input field, then type `@` and start typing the next any user name, `@` will be inserted three times with each next letter. If try to delete this text, it will continue to multiply.

Android, iOS.

ezgif com-gif-maker (1)

**Comment by rasom** [comment]
@qoqobolo can you reproduce this in develop (nightly)?

**Comment by qoqobolo** [comment]
@rasom nope, in this build only.

**Comment by rasom** [comment]
@qoqobolo ISSUE 1 is fixed now (could be reproduced with nicknames in `develop`, at least theoretically)

**Pull request merged**
