### PR TITLE
IOS PNs

### PR DESCRIPTION
**Pull request by flexsurfer**
### Testing

This applies only to IOS, android behavior is unchanged.

What should work:

- Receiving a push notification from a one-to-one message
- Receiving a push notification from a group chat
- No notifications from blocked users
- No notifications from muted users (setting in profile)
- Notifications from contacts only
- After logout (explicit logout, not app being killed), no notifications should be received

Known limitations:
- PN just opens the app, does not direct you to the right chat etc
- If you create multiple accounts, the app is killed, login to another account and enable push notification, you will receive PN for both until you explicitly logout (There are some technical challenges for this, and we might have to find a compromise)
- Changes to PN notification settings will only be reflected once the user is back online if set when the app is offline (unavoidable, this is the same as whatsapp etc)
- Muting a user will also block mentions from that user (desired behavior maybe?)

### CODE REVIEW

**Comment by hesterbruikman** [comment]
Are you still working on this @flexsurfer ?

**Comment by cammellos** [comment]
I have taken over @hesterbruikman , I am actively working on this

**Comment by Serhy** [comment]
@cammellos @flexsurfer I've tested the `fafdb26` build - https://i.diawi.com/Z5G7Tk build (and same for Android)

For iOS there are a couple of bugs:

**Issue 1** 
Notification appears from the users which not added in my contact list (`Notifications from contacts only` item doesn't work I mean)

**Issue 2** 
Notification appears from blocked user

**Issue 3** 
Notification appears which sent in the Group chat I did not accepted the invite yet.

**Issue 4** 
There are no notifications for received 'Sent/Request' command messages

**Comment by Serhy** [comment]
Looks good for merge. Separately will be addressed issues: when account first blocked and for it sent some messages, - after unblocking the contact notifications for those messages sent while contact was clocked will appear (but not the messages)

Thanks a lot @cammellos ! Please mind my commit when merging fixing some e2e tests.

**Comment by cammellos** [comment]
Thanks @Serhy for testing!
I have to merge status-go and do a bit more clean up on the PR (just re-enable fleets etc), but I'll merge in tomorrow.

**Review by rasom — APPROVED** [review]

**Comment by flexsurfer** [comment]
image
image
@Serhy @cammellos is that expected ?

**Pull request merged**
