### PR TITLE
fix status bar colors and launch screen

### PR DESCRIPTION
**Pull request by flexsurfer**
galaxy s10

| before  | after |
| ------------- | ------------- |
| image | image |

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by churik** [comment]
Failures:
1)  test_modify_transaction_fee_values - not related to your PR
Device 1: 'BaseText' is not found on the screen; also Unexpected Alert is shown: 'request failed or timed out' - not related to PR, probably broken in develop by other PR or temporary fail due to Ropsten response, will take a look today.

2) test_block_user_from_one_to_one_header - known failure, will be fixed after merging https://github.com/status-im/status-react/pull/9279

3) test_logcat_backup_recovery_phrase - known possible failure, when 2 words from passphrase are found in logcat

4) test_insufficient_funds_wallet_positive_balance - failure due to https://github.com/status-im/status-react/issues/9280

5)  test_offline_status - seems to be false failure, will take a look

**Comment by yenda** [comment]
@churik can we merge this?

**Comment by Serhy** [comment]
No, there are some regressions appeared. 

While it seem OK with iOS (iOS 12.4 tested on iPhoneX) on Androids along with the changing colour values it affected some elements
1) On any Android (6.0.1, 8.1, 9.0 tested) below elements are white now:
 a) cursor in the any of input fields (should be kept blue one)
  b) spinners when sign in transaction or when login in (navigation from password -> Chats view)
Screenshot 2019-11-01 at 16 51 58


 c) blue drop-icon when selecting text in input fields
 d) selected text shadowing
Screenshot 2019-11-01 at 16 52 16



2) On Android 6.0.1 only. Text in the actionable buttons in pop-up (Log Out, change network and similar pop-ups) are white and so not visible:

 
Screenshot 2019-11-01 at 16 52 08

**Comment by flexsurfer** [comment]
thanks @Serhy , fixed

**Comment by yenda** [comment]
Tested on OP7P lgtm, issues are gone

**Review by yenda — APPROVED** [review]

**Comment by Serhy** [comment]
No issues with Android 8.1, Android 6.0.1, iOS12 which was before.

**Pull request merged**
