### PR TITLE
Patch for 8718

### LINKED ISSUE #8718: App is shown in English instead of device language for some languages
### Description

*Type*: Bug
*Summary*: for some languages (translations are presented in https://github.com/status-im/status-react/tree/develop/translations) app is still shown in English after setting device language. Randomly checked several languages - all fine with Russian\Korean (so device settings are applied to app language), but not with French, Vietnamese, Danish.
Reproducible on 0.13.0 and later.

#### Expected behavior
app language is changed

#### Actual behavior
app is still in English

### Reproduction
- Change your phone language to French, Vietnamese or Danish
- Open Status app and check language

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: release 0.13.0, nightly 07/08/2019
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by AlphaSerpentis**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Fixes #8718 

### Summary

Defined both translations and languages.
Fixed a JSON error in translations/fr.json

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

- Step 1, change device language to something else.
- Step 2, launch Status
- Step 3, verify language changes to the appropriate one.

status: ready

### CODE REVIEW

**Comment by Serhy** [comment]
@AlphaSerpentis when squashing you seem grabbed few more commits that were already merged in Develop.
Thats why there are conflicts now.

In that case, when there are no big changes I do copy of my edits (in your case it's those in `translations/fr.json` and `prod/status_im/i18n_resources.cljs` files), then reset --hard on your branch on origin develop (but pull recent changes in your local `develop` branch from origin), then update files, commit your changes and force push.
There should be better way, but above should definitely update your PR with single commit.

**Comment by yenda** [comment]
@Serhy best way is to do `git pull --rebase origin develop` before squashing, and if you have a proper git tool you can also do an interactive rebase prior to that, where you mark all your commits but the first as fixup, so that they are squashed, and then you do `git pull --rebase origin develop`

**Comment by AlphaSerpentis** [comment]
I just came back from isolation, couldn't respond to any of ya'll.

Should I edit the pull request?

**Comment by flexsurfer** [comment]
@Serhy @yenda  ^

**Comment by Serhy** [comment]
@AlphaSerpentis yes please, could you rebase develop, commit and push only changes from `translations/fr.json` and `prod/status_im/i18n_resources.cljs`?

**Comment by AlphaSerpentis** [comment]
I'm quite confused honestly, sorry, I'm new to this and I'm getting some GPG errors with GitHub Desktop so I have to do this by the command line

**Comment by AlphaSerpentis** [comment]
At this point, I feel like I should make a new PR because this looks like a big mess.

**Comment by Serhy** [comment]
@AlphaSerpentis no worries! No need new PRs. Let's solve together it here.
I do it via cherry-pick in similar cases.
Taking that you are working from command line and that this commit https://github.com/status-im/status-react/pull/9286/commits/2022618ecd96801fe3b993345e44d0225870ba2f is the only one you want to have in this PR:

1) `git checkout patch-for-8718` (checkout to your branch)
2) `git checkout -b patch-for-8718-2` (this will be separate local branch from where will take single commit later)
3) `git checkout patch-for-8718` (switch to your branch back)
4) `git fetch --all`
5) `git reset --hard origin/develop` (reset everything in this branch so it's same to origin develop)
6) `git cherry-pick 2022618ecd96801fe3b993345e44d0225870ba2f` (to take and apply only this single commit to your patch-for-8718 branch - which is tracked in `patch-for-8718-2` branch)
7)  `git push origin +patch-for-8718` (should push this commit only)

**Comment by AlphaSerpentis** [comment]
Is this correct this time..? I'm still seeing conflicts

Should I revert the develop branch on my end to where it was before I did a "catch-up"?

**Comment by AlphaSerpentis** [comment]
Okay, I am really lost. Sorry for the confusion. @Serhy

**Comment by Serhy** [comment]
@AlphaSerpentis have you tried the cherry-pick https://github.com/status-im/status-react/pull/9286#issuecomment-549413796 approach? 
You won't need to `revert` anything if you `reset --hard` your branch in that case

Maybe it would may be easier in your branch to reset everything to origin develop (`git reset --hard origin/develop`) edit files again, commit, force push (`git push origin +patch-for-8718`)

**Comment by AlphaSerpentis** [comment]
@Serhy Do I do this on the `patch-for-8718` branch or `develop` branch (on my fork)?

**Comment by Serhy** [comment]
In your branch `patch-for-8718`. 
`git reset --hard` will reset all your work and make branch "a copy" of what is used after `--hard` key (in that case `origin/develop`). So you will start from scratch in `patch-for-8718` branch.

**Comment by AlphaSerpentis** [comment]
> In your branch `patch-for-8718`.
> `git reset --hard` will reset all your work and make branch "a copy" of what is used after `--hard` key (in that case `origin/develop`). So you will start from scratch in `patch-for-8718` branch.

THANK YOU! @Serhy

**Review by Serhy — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@AlphaSerpentis please, rebase your work on current develop branch. Thanks!

**Comment by Serhy** [comment]
Can confirm Status language changes to French, Deutsch, Hindi, Vietnamese, Korean when device (iOS 12 and Android 8.1 tested) language has changed. 
@AlphaSerpentis to rebase develop use what yenda suggested in above https://github.com/status-im/status-react/pull/9286#issuecomment-548889424 i.e. in your branch (`git checkout patch-for-8718`) then `git pull --rebase origin develop` and push. It should allow us to run updated e2e tests and then merge this PR.

**Comment by AlphaSerpentis** [comment]
@Serhy @churik Done!

Also, thank you for the amazing support, even if I was really _dumb at points._

**Comment by Serhy** [comment]
Tests failed not due to this PR changes, will be looked separately
This one ready to merge. 
Thanks @AlphaSerpentis !

**Pull request merged**
