### PR TITLE
[#9636] Remove chat menu item and toggle app switching privacy on by …

### LINKED ISSUE #9636: Remove chat menu item and toggle app switching privacy on by default
# Problem

Combination issue spanning two product areas:

1. Chat `+` menu—remove an option
2. `Profile` > `Privacy and security`—turn a setting ON by default, alter copy

## Implementation

- Remove the `Scan a QR code` option from the chat menu

image

- Change the copy of `Hide content when switching apps` to `White out Status when switching apps`
- Set this toggle to be ON by defautl
image

## Acceptance Criteria

- No more scan QR code option in chat menu
- New copy for Privacy and security option
- White out setting is on by default

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #9636

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer issue in PR: can't login after logout. 
See results of [ test_install_pack_and_send_sticker](https://ethstatus.testrail.net/index.php?/tests/view/1031278)

Steps + logs: https://saucelabs.com/jobs/9bd3dde84bc74c3098710114b81f11c1?auth=c3021d252828d09cb2e333ff685295b5

**Comment by flexsurfer** [comment]
@churik can't reproduce, could you help?

**Comment by flexsurfer** [comment]
@churik  thanks, fixed

**Comment by churik** [comment]
@rachelhamlin 
I'm against merging this PR as it is.
The reason is that when  "Hide content" is ON by default it is not possible to make a screenshots of application. Hence 
1) 7 tests in PR (based on screenshots comparing) will always fail 
2) making screenshots in case of test failure will be useless

Suggested solution:
- Make e2e build separately with this setting turned off by default or to make separate parameter (loke NETWORK in https://ci.status.im/job/end-to-end-tests/job/status-app-prs/build?delay=0sec) to have a possibility to make such build 
- Postpone turning it on by default until we will find proper solution


cc @corpetty

**Comment by flexsurfer** [comment]
@churik disabled for e2e builds

**Comment by churik** [comment]
Tested on IOS and Android 9, looks good to me.
e2e build doesn't have this option enabled.
Failed tests are not related to this PR.
Thanks for fix @flexsurfer and ready to go

**Pull request merged**
