### PR TITLE
[keycard] fix NFC detection

### LINKED ISSUE #8703: NFC setting on/off is not detected dynamically
Verified on Oneplus 6, and Samsung J5

When trying to onboard on a android phone with Keycard, the user goes through three screens 
i. Select Key storage
ii. Store your key on Keycard information screen 
iii. "Hold card to the back of your phone" (if NFC is on), or "Turn NFC on to continue" (if NFC is off)

Problem: if the user NFC is off, and is prompted to turn it on on step ii, then he turns it on, the change is not detected by Status. This is quite disturbing and could make the user abandon onboarding.

Remark on reproduction: it seems the detection is done at step i. (user must go back to step i for Status to detect a setting change), although it should be done when in step iii. dynamically

@dmitryn 
@asemiankevich

### LINKED ISSUE #8704: if NFC is off,  user is not prompted to turn NFC on at login
Tested on oneplus 6 

- user has a keycard multiaccount 
- NFC is turned off 
- user tries to login 
- user is asked to tap his Keycard and is not prompted to turn his NFC on 

cc @asemiankevich

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #8703 
fixes #8704

### Summary

Fix NFC setting enabled/disabled detection during keycard login and onboarding/recovery.

#### Platforms

- Android

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Comment by asemiankevich** [comment]
@dmitryn this still does not work properly on my phone when i try to login with NFC = OFF (https://github.com/status-im/status-react/issues/8704).

I do see screen prompting me to enable NFC, but when i enable it -> I can't proceed further, next screen is not shown.

Steps:
1. create keycard account
2. logout
3. turn off nfc
4. go to login screen
5. on the NFC enabling prompt go to device setting and enable NFC
6. go back to login

User stuck on the NFC enabling prompt even the setting is now active.

Video: https://drive.google.com/open?id=1H4xE6RzzzyoZoxHNQaPqSFfreYWSdqWh

Logs:

```
2019-08-15 10:56:23.103 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.logging.core:26] - 
2019-08-15 10:56:23.132 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :init/app-started
2019-08-15 10:56:23.168 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.keychain.core:173] - PERF initializing realm encryption key... 1565855783162
2019-08-15 10:56:23.178 27265-27321/? D/ReactNativeJS: DEBUG [status-im.notifications.core:331] - Init notifications
2019-08-15 10:56:23.187 27265-27321/? D/ReactNativeJS: DEBUG [status-im.notifications.core:312] - calling onMessage
2019-08-15 10:56:23.191 27265-27321/? D/ReactNativeJS: DEBUG [status-im.notifications.core:300] - calling onNotification
2019-08-15 10:56:23.196 27265-27321/? D/ReactNativeJS: DEBUG [status-im.notifications.core:325] - setup-on-notification-opened-callback
2019-08-15 10:56:23.207 27265-27321/? D/ReactNativeJS: DEBUG [status-im.notifications.core:279] - Handle initial push notifications
2019-08-15 10:56:23.214 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.callback/on-register-card-events
2019-08-15 10:56:23.227 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :update-window-dimensions
2019-08-15 10:56:23.369 27265-27321/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:107] - :main-component-did-mount nil
2019-08-15 10:56:23.375 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.universal-links.core:155] - universal-links: initializing
2019-08-15 10:56:23.409 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :set-two-pane-ui-enabled
2019-08-15 10:56:23.422 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :set-initial-props
2019-08-15 10:56:23.442 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :network/connection-status-changed
2019-08-15 10:56:23.461 27265-27321/? D/ReactNativeJS: DEBUG [status-im.network.net-info:17] - Is connected? true
2019-08-15 10:56:23.467 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :network/connection-status-changed
2019-08-15 10:56:23.486 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :init.callback/get-supported-biometric-auth-success
2019-08-15 10:56:23.496 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :init.callback/get-device-UUID-success
2019-08-15 10:56:23.510 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :init.callback/get-encryption-key-success
2019-08-15 10:56:23.562 27265-27321/? D/ReactNativeJS: DEBUG [status-im.notifications.core:211] - Notification channel created: status-im
2019-08-15 10:56:23.567 27265-27321/? D/ReactNativeJS: DEBUG [status-im.notifications.core:284] - getInitialNotification nil
2019-08-15 10:56:23.585 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.universal-links.core:98] - universal-links: no url
2019-08-15 10:56:23.592 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :network/network-status-changed
2019-08-15 10:56:23.610 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :network/network-status-changed
2019-08-15 10:56:23.634 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.callback/check-nfc-support-success
2019-08-15 10:56:23.646 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.callback/check-nfc-enabled-success
2019-08-15 10:56:23.656 27265-27321/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:123] - realm: moving all realms
2019-08-15 10:56:23.675 27265-27321/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:199] - Opening base realm... (first run)
2019-08-15 10:56:23.678 27265-27321/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:177] - migrate-realm
2019-08-15 10:56:23.687 27265-27321/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:147] - migrate schemas 31
2019-08-15 10:56:23.694 27265-27321/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:46] - Opening realm at  /data/user/0/im.status.ethereum.pr/files/../no_backup/realm/default.realm ...
2019-08-15 10:56:23.701 27265-27321/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:48] - Using encryption key...
2019-08-15 10:56:23.711 27265-27321/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:203] - Created @base-realm
2019-08-15 10:56:23.721 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :init.callback/init-store-success
2019-08-15 10:56:23.795 27265-27321/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :keycard-login-pin nil
2019-08-15 10:56:23.822 27265-27321/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:213] - :component :keycard-login-pin
2019-08-15 10:56:24.115 27265-27321/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:213] - :component :keycard-login-pin
2019-08-15 10:56:25.134 27265-27321/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:32] - :on-will-focus :keycard-login-pin
2019-08-15 10:56:25.142 27265-27321/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:137] - :main-component-did-update :keycard-login-pin
2019-08-15 10:56:25.155 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :screens/on-will-focus
2019-08-15 10:56:26.582 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-08-15 10:56:26.818 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-08-15 10:56:27.120 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-08-15 10:56:27.461 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-08-15 10:56:27.825 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-08-15 10:56:28.352 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-08-15 10:56:28.380 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet/process-pin-input
2019-08-15 10:56:28.386 27265-27321/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :keycard-nfc-on nil
2019-08-15 10:56:28.570 27265-27321/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:32] - :on-will-focus :keycard-nfc-on
2019-08-15 10:56:28.577 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :screens/on-will-focus
2019-08-15 10:56:28.595 27265-27321/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:137] - :main-component-did-update :keycard-nfc-on
2019-08-15 10:56:30.651 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :keycard.onboarding.nfc-on/open-nfc-settings-pressed
2019-08-15 10:56:30.699 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :app-state-change
2019-08-15 10:56:34.097 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :app-state-change
2019-08-15 10:56:38.574 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :app-state-change
2019-08-15 10:56:40.570 27265-27321/? D/ReactNativeJS: DEBUG [status-im.utils.universal-links.core:165] - universal-links: finalizing
```

**Comment by dmitryn** [comment]
@asemiankevich fixed, please check.

**Comment by asemiankevich** [comment]
@dmitryn For some reason i can't login in keycard account -> error that connection is lost is shown

is it something we can look into in terms of this PR or it could be a next task? 

when i was testing Recovery 1 flow, i was able to log in, not sure where it got broken

image

**Comment by dmitryn** [comment]
@asemiankevich I'll take a look in current PR

**Comment by annadanchenko** [comment]
I can log in successfully and do not experience issue described in https://github.com/status-im/status-react/pull/8741#issuecomment-521627423 on Android build 4, using Galaxy S10, Android9 if follow these steps:
1. Create keycard account 
2. log out
3. turn off NFC
4. try to log in
5. on the screen asking to turn on NFC - go to settings and turn NFC on
6. try to sign in again. As a result can sign in and see Chats tab

**Pull request merged**
