### PR TITLE
[#10914] Show proper username in chat on opening from background

### LINKED ISSUE #10914: Chat header of current user is shown in case of opening PN from another user if app was on background with 1-1 chat with current user
# Bug Report

## Problem
If app was on background with `User A`, and then user tap on notification from `User B` - app redirects to messages with `User B` and chat header from `User A`,

#### Expected behavior
chat view of `User B`

#### Actual behavior
photo_2020-07-06 11 43 19 jpeg 2020-07-06 12-05-55

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- User C: Open Status
- User C: turn on notifications on Profile
- User C: start chat with `User A`(don't go back to home view)
- User C: put app to background
- User B: send message to User C

### Additional Information

- Status version: nightly 06/07/2020
- Operating System: Android

### LINKED ISSUE #10943: Chat headers are messed up after opening app from background on IOS and navigating to 1-1 chat and back
# Bug Report

## Problem
When app is on background  and several 1-1 chats are opened, after getting back from background and navigating back-forth to 1-1 chats and back, after second attempt `User A` chat header is shown for `User B`.

ezgif com-video-to-gif (2)
Issue is not reproducible on 1.4, so I guess it is another regression from QUO (though not sure) 

#### Expected behavior
`User A` chat header

#### Actual behavior
`User B` chat header, but in fact chat view with `User A`

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

1) Open Status, create multiaccount
2) Start chat with `User A` and `User B` (with ENS or using chat key, both cases are working), go back to home view
3) Put app to background,
4) Put app back from background
5) Navigate to chat with `User B` and back (can use swipe gesture or button)
6) Navigate to chat with `User A` 

### Additional Information

- Status version: nightly 13/07/20
- Operating System: iOS

### PR DESCRIPTION
**Pull request by rasom**
fix #10914
fix #10943

status: ready

### CODE REVIEW

**Review by Ferossgp — APPROVED** [review]
:+1: Also fixed this: https://github.com/status-im/status-react/issues/10943 
If we have problem with letsubs, we may need somewhere in future to review all the places where we use it?

**Comment by rasom** [comment]
> we may need somewhere in future to review all the places where we use it

@Ferossgp specifically places where we have parametrised subs I suppose, otherwise it should work as expected.

**Comment by churik** [comment]
both issues are fixed, tested on IOS13 and Android10. Waiting for e2e to pass

**Comment by churik** [comment]
failed e2e are not related (should be fixed in : #10960) 
Ready to merge

**Pull request merged**
