### PR TITLE
Update launch logo

### LINKED ISSUE #8130: [Onboarding] Splash screen
Implement splash screen for ios and Android

image

Figma: https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A14702

### PR DESCRIPTION
**Pull request by vitvly**
Fixes #8130

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
@siphiuel would you mind to rebase here? Sorry for delay

**Comment by vitvly** [comment]
Rebased.

**Comment by asemiankevich** [comment]
@siphiuel for some reason this Splash screen is not shown on iOS 13.

it is shown fine on:
- android 8

image

- ios 12.3.1, however i can't make a screenshot - it is too fast

@flexsurfer should we investigate it (iOS 13 issue) in separate PR?

**Comment by flexsurfer** [comment]
let's take a look in this one

**Comment by asemiankevich** [comment]
so on iOS 13 i see white screen instead of splash screen logo , then i see welcome screen. Please see the screen recording. @siphiuel 

https://drive.google.com/open?id=1ECrBs6wnt9NzaCQZ64uBI57YrAvNzmce

**Comment by vitvly** [comment]
Looking into it.

**Pull request merged**
