### PR TITLE
update the Russian, Korean and Chinese translations

### PR DESCRIPTION
**Pull request by jinhojang6**
Deleted some outdated keys based on [this commit](https://github.com/status-im/status-react/commit/2c5e985cb3c366b4cbec87defd8e694fe4b68cbc)

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by jinhojang6** [comment]
The iOS build is done but Android builds failed?

**Comment by flexsurfer** [comment]
@jinhojang6 please rebase

**Review by jakubgs — APPROVED** [review]

**Comment by jinhojang6** [comment]
@flexsurfer The builds look good this time.

**Comment by jinhojang6** [comment]
Can I merge this pull request? @jakubgs @flexsurfer

**Comment by flexsurfer** [comment]
@jinhojang6 don't we need to test it? @annadanchenko

**Comment by jinhojang6** [comment]
The testing is in progress

**Comment by churik** [comment]
failed e2e are not related to PR
@jinhojang6 thank you, ready to be merged.

**Comment by jinhojang6** [comment]
@churik Thank you for letting me know that.

**Pull request merged**
