### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by jinhojang6**
Updated 15 languages

- ar.json (Arabic) 
- de.json (German)
- es_419.json (Latin American Spanish)
- es.json (Spanish)
- fil.json (Filipino)
- fr.json (French)
- id.json (Indonesian)
- it.json (Italian)
- ko.json (Korean)
- pt.json (Portuguese)
- pt_BR.json (Brazilian Portuguese)
- ru.json (Russian)
- tr.json (Turkish)
- zh.json (Simplified Chinese)
- zh_TW.json (Traditional Chinese)

### CODE REVIEW

**Review by hesterbruikman — APPROVED** [review]
Looks good to me! Thanks @jinhojang6. I'll keep you posted if anything changes on the referral screens

**Comment by jinhojang6** [comment]
@hesterbruikman Thanks Hester!

**Comment by jinhojang6** [comment]
Can we merge this PR before v1.6? @Serhy @churik

**Comment by Serhy** [comment]
@jinhojang6 sorry, the 1.6 being sent to review already (yesterday), so this will go in next release.

**Review by Serhy — APPROVED** [review]

**Comment by jinhojang6** [comment]
@Serhy Thanks for the heads-up! I wish we could merge our translation updates more frequently as it hardly impact our frontend or backend logic.

**Pull request merged**
