### PR TITLE
Shadow cljs fix find-ns-obj

### PR DESCRIPTION
**Pull request by hlolli**
### Summary

Admit that I didn't test this (nixos stuff is missing on this branch) but this seems a bit obvious looking at it here https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/core.cljs#L11649

And @thheller was right, that in the case of an advanced compilation, this makes no sense.

cc #8286 @yenda

### CODE REVIEW

**Comment by yenda** [comment]
@hlolli thanks, let see if it works. However the PR can't be merged as is, how could we keep this code for dev where it is needed?

**Comment by rasom** [comment]
Hey @hlolli!

It definitely fixes the issue and works fine with both `:none` and `:advance` optimization levels. 

Thanks

**Review by rasom — APPROVED** [review]

**Comment by yenda** [comment]
@rasom I think you already merged that one so it can be closed right? we just need to see with @StatusSceptre how we pay up a bounty for it to @hlolli

**Comment by rasom** [comment]
@yenda no I didn't and it is not needed anymore as I decided to not use `shadow-cljs`.

**Comment by rasom** [comment]
can be closed

**Pull request closed without merging**
