### PR TITLE
nix: use overlays instead of packageOverrides

### PR DESCRIPTION
**Pull request by jakubgs**
General Nix refactoring that I did while working on refactoring `status-go` builds.
Main changes:
- Started using `overlays` for cleaner `pkgs`
- Dropped `target` in favor of using `--attr`
- Renamed a bunch of `config` variables
- Updated Jenkins lib to https://github.com/status-im/status-react-jenkins/pull/3

All changes:
- Add `nix/DETAILS.md` for more in-depth info
- Rename some of `config.status-im` variables
- Drop `env` argument for Android build
- Use `overlays` instead of `packageOverrides`
- Move the `pkgs` overlay to `nix/overlay.nix`
- Move `nix/status-go/utils.nix` to `nix/tools`
- Make `shell.nix` use the `shells.default` only
- Use `default.nix` as target for `nix/scripts/shell.sh`
- Make `nix/scripts/shell.sh` use `--attr` instead of `target`
- Drop the `target` argument in favour of using `--attr`
- Drop unnecessary `src` from `nix/mobile/ios/default.nix`
- Move `mkShell` and `mergeSh` under `lib`
- Move `patched-go` package to `nix/pkgs` directory
- Move `gomobile` package to `nix/pkgs` directory
- Move `ANDROID_ABI_SPLIT` to `config.status-im.android.abi-split`
- Move `ANDROID_ABI_INCLUDE` to `config.status-im.android.abi-include`

Happy to hop on a call and explain what's happening.

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Comment by jakubgs** [comment]
Looks like I broke the Android build:
pr_error_hermes
pr_error_log
Probably something I changed in `nix/mobile/android/targets/release-android.nix`.

**Comment by jakubgs** [comment]
I see now, the issue was the format of the `status-im.android.abi-include` argument, which was provided in CI as a Nix list, but should be provided as a string separated by semicolons.

**Comment by churik** [comment]
failed e2e is unrelated, so ready to be merged (of no manual testing needed)

**Comment by jakubgs** [comment]
I did some basic testing myself. Looks fine.

**Pull request merged**
