### PR TITLE
[#9233, #9173] fix overlapping on some screens

### LINKED ISSUE #8738: Translated text from description and section title overlap each other on screen `Select key storage`
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: on Samsung galaxy S6, Android 6.0.1 with Russian translation, text "By default" and "only you have access" overlap each other
Screenshot_20190813-100913

#### Expected behavior

no overlap

#### Actual behavior

text "By default" and "only you have access" overlap each other 

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Change device language to Russian
- install and launch Status
- Create new account and go to Select a key storage sceeen

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly from August 13
- Operating System: Samsung galaxy S6, Android 6.0.1

### Same screen in English
Screenshot_20190813-101906

### LINKED ISSUE #9173: Onboarding screens UI glitches
# Bug Report

## Problem

image
image

#### Expected behavior

Screens must look great

### LINKED ISSUE #9233: Overlapping on some screens (onboarding, wallet -  English, Galaxy S7)
# Bug Report

It is very visible and in happy-path flow, so should be fixed in v1 IMO.
## Problem
On "Send Transaction" screen:
App Live Dashboard 2019-10-17 13-54-43

On "Select key storage" (during onboarding):
s7_overlap

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 17/10/2019
- Operating System: Android (small screens)
For me reproducible on Samsung Galaxy S7 (5,5'')

### PR DESCRIPTION
**Pull request by rasom**
status: ready

fix #9233 
fix #9173 
fix #8738

## `develop`
 galaxy s9:

Samsung a500d (640px screen height):

iPhone SE simulator (the list can't be scrolled):

iPhone X 

- - -

### CODE REVIEW

**Comment by hesterbruikman** [comment]
Checked on:
iPhone 8 (iOS 13)
Galaxy s10e (UI 1.1 - Android 9)
Fairphone 2 (Android 7)

1. iOS build seems to skip Storage selection in onboarding cc @churik 
2. Select name & key - Double space in "This is your identity in Status.`  `It can't be changed once you choose one.`  `Learn more. 
3. Send transaction - Could use spacing between icon and "You're on Mainnet. Real ETH will be sent." I realize it's not part of this issue :/
4. Select name & key - can't scroll indeed. Does that need a seperate issue?

**screenshot for point 2**


**screenshot for point 3**

**Comment by rasom** [comment]
@hesterbruikman PR is not ready for review/testing

**Comment by rasom** [comment]
@hesterbruikman 
I can't repro 4 on the device with a small screen, the list is scrollable

**Comment by rasom** [comment]
@hesterbruikman 
1. works that way by design on iOS, can be re-implemented
2. fixed
3. fixed
4. I can't reproduce

**Comment by rasom** [comment]
galaxy s9
image-2

So now first items in the lists are actually aligned.

**Comment by hesterbruikman** [comment]
Thanks @rasom 

> works that way by design on iOS, can be re-implemented

For reference: https://github.com/status-im/status-react/issues/9289

**Review by vitvly — APPROVED** [review]

**Comment by rasom** [comment]
@errorists can you please take a look please at these screens in the last build? Should I change anything there or it's fine for now?

**Comment by vitvly** [comment]
@rasom I did notice a slight shift in top rows on Pixel 2 emulator. Top account row has y:232.4, and top storage row has y:241.1.

**Comment by rasom** [comment]
@siphiuel yup that's true, can be fixed though. I hoped nobody will notice :D

**Comment by rasom** [comment]
@siphiuel could you please attach the screenshots?

**Comment by vitvly** [comment]
img

**Comment by errorists** [comment]
@rasom looks ok on an iPhone X. only thing I found, can I ask you to insert a non breaking space character in `Learn More` so it doesn't get split in two? 
IMG_1138

**Comment by errorists** [comment]
I won't split hairs over this but here, the entire view should be scrollable starting from the 'Choose a key name', not only the list. not really a bug tho

**Comment by rasom** [comment]
> can I ask you to insert a non breaking space character 

sure

> the entire view should be scrollable starting from the 'Choose a key name', not only the list

we can fix this in a separate PR, I just want to finish with changes we already have here

**Comment by rasom** [comment]
@errorists nbsp added

**Comment by vitvly** [comment]
@rasom i think your PR also fixes https://github.com/status-im/status-react/issues/8738

**Comment by churik** [comment]
Retested all mentioned flows on Samsung Galaxy S7 (5.1'') with Russian and English languages - no overlapping anymore.
thanks @rasom !

**Pull request merged**
