### PR TITLE
[#10880] Expanded view with public chat categories

### LINKED ISSUE #10880: Expanded view with public chat categories
# Problem
When joining Status is difficult for people to understand what to do next; especially if they were not invited by a friend and are therefor not deeplinked into a chat.

There is a list of hardcoded channels, this list can be expanded on a new screen to show a categorized and more extensive list of public chats.

Follow up from #8845 

## Implementation

- Designs to be added (imagine something similar to [earlier design](https://github.com/status-im/status-react/issues/8845#issuecomment-543589234))
- _Content (i.e. public chats) to populate lists needs to be updated_

## Acceptance Criteria

- Implementation follows design 
- There is a suggested flow for contributors to update the list

## Notes
It's not possible to get a list of 'most popular' channels by traffic. In the future this hardcoded list could be dynamic based on user curation (e.g. staking to promote channels)

## Future Steps

Steps which should be taken after this issue has been resolved.

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #10880

### CODE REVIEW

**Comment by hesterbruikman** [comment]
Thank you @flexsurfer !

- UI looks good to me. Some images below for @errorists to verify
Category header font should be 15, medium. Can you confirm @errorists?
- Functionality (tap on channel opens channel) looks good to me
- Localization; will check now with different language settings

Tested on Samsung S10e (Android 10), iPhone 8 (iOS 13.0), Fairphone 2 (Android 7)

Frame 1

**Comment by errorists** [comment]
@flexsurfer awesome job, do you think we could get those guys fixed before your well deserved vacation?

Screenshot 2020-07-10 at 14 00 47

So the margin surrounding the text is too large, it's 8 vertical on top and bottom of the image - text - 16 from text to chat input
somehow our `#` hash icon didn't get updated to the new design, if you'd like to update it, it's [here](https://www.figma.com/file/cb4p8AxLtTF3q1L6JYDnKN15/Index?node-id=5026%3A3382) 
and as Hester already said, the typography on the index is a font-size: 15 font-weight: medium. 
In the future we probably should make a global List Index component out of those as we could use them for long contact lists too.

**Comment by errorists** [comment]
@flexsurfer also if you could update the resources/images/ui/empty-chats-header with [this one](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=15633%3A0), that would be dope, I made it clearer that chat is for sharing images now too

**Comment by hesterbruikman** [comment]
Checked the languages:
- status-nl is shown instead of status-dutch. Can be either (neither have activity currently), but the `Language` category includes status-dutch
- status-fi is shown instead of status-filipino. This should be status-filipino as it is currently an active channel
- status-hi should be status-indian, also currently an active channel

**Comment by flexsurfer** [comment]
all done

**Comment by churik** [comment]
Please mind my commit when squashing.
Tested on IOS 13, Android 10 on Russian / English on dark / light mode, LGTM.
Thank you @flexsurfer

**Review by churik — APPROVED** [review]

**Pull request merged**
