### PR TITLE
nix: upgrade gomobile to 2022-05-18 version

### PR DESCRIPTION
**Pull request by jakubgs**
Possible fix fix failing `status-go` builds: https://github.com/status-im/status-react/issues/13346

Other notable upgrades:

* NodeJS `16.15.0` to `16.15.1`
* Yarn `1.22.18` to `1.22.19`
* Clojure `1.11.1.1113` to `1.11.1.1129`

Depends on: https://github.com/NixOS/nixpkgs/pull/172355

### CODE REVIEW

**Comment by jakubgs** [comment]
Now this is an interesting failure:
```
error: Package ‘auto-patchelf-hook’ in /nix/store/qkvkqhb32bjzfkq1rn3z4ccf15v3kfh8-nixpkgs-source/pkgs/build-support/trivial-builders.nix:73 is not supported on ‘x86_64-darwin’, refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

**Comment by jakubgs** [comment]
Looks like the issue is due to this change:

* https://github.com/NixOS/nixpkgs/pull/163924
* https://github.com/NixOS/nixpkgs/commit/d2f26874 - treewide: autoPatchelfHook only on Linux

Which appears to have caused some package maintainers to [drop their dependency on `autoPatchelfHook`](https://github.com/NixOS/nixpkgs/commit/b529464b).

**Comment by jakubgs** [comment]
Okay, I see what's happening. It's the `androidenv` package that makes use of `autoPatchelfHook`:
```
~/work/nixpkgs/pkgs/development/mobile/androidenv gomobile-2022-05-04
 > ag autoPatchelfHook | grep buildInputs
tools/26.nix:6:  buildInputs = [ autoPatchelfHook makeWrapper ]
ndk-bundle/default.nix:12:  nativeBuildInputs = [ autoPatchelfHook makeWrapper ];
cmake.nix:5:  nativeBuildInputs = [ autoPatchelfHook ];
tools/25.nix:5:  buildInputs = [ autoPatchelfHook makeWrapper ]
emulator.nix:5:  buildInputs = [ autoPatchelfHook makeWrapper ]
platform-tools.nix:5:  buildInputs = lib.optionals (os == "linux") [ autoPatchelfHook pkgs.glibc pkgs.zlib pkgs.ncurses5 ];
```

**Comment by jakubgs** [comment]
Another interesting error:
```
gomobile: invalid -target="ios/arm64,ios/amd64": unsupported platform/arch: "ios/amd64"
```
And it appears the cause for this issue is this commit:
https://go.googlesource.com/mobile/+/6d8ad35e460371e979b330d80492cba19676f933

>This is is a follow-up from my previous PR (#65). It makes gomobile
aware of GOOS=ios and adds support for specifying specific Apple
platforms, instead of overloading the "ios" platform.
>
>Supported platforms: ios, iossimulator, macos, and maccatalyst
>
>These can now be specified the -target argument to gomobile, e.g.:
gomobile build -target=ios,iossimulator,macos,maccatalyst
>
>It preserves the current behavior of -target=ios, which will build for
ios and iossimulator on supported architectures (arm64 and amd64).

Which indicates that either we replace `ios/arm64,ios/amd64` with just `ios`or `ios,iossimulator`.

**Comment by jakubgs** [comment]
Another issue I found out is that this PR has made `apksigner` be built from source:

* https://github.com/NixOS/nixpkgs/pull/174082

But this build fails if it's using Gradle 5 or older:
```
> Task :startScripts FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':startScripts'.
> No value has been specified for property 'mainClassName'.
```
But we are stuck with Gradle 5 until this dependency issue is resolved:

* https://github.com/wix/react-native-navigation/issues/7527

__EDIT:__ But we have a fix for Gradle 5 now:

* https://github.com/NixOS/nixpkgs/pull/176853

**Comment by jakubgs** [comment]
The iOS builds of `status-go` fails with:
```
post-installation fixup
strip is /nix/store/by2gg5mdrh03n7vvigqi1wyqkaxcyzhn-Toolchains/XcodeDefault.xctoolchain/bin/strip
patching script interpreter paths in /nix/store/9hly5jk4ga5brzy7ss2gcgzpysmv1zb4-status-go-0.100.2-ed67cc2-ios
error: output '/nix/store/9hly5jk4ga5brzy7ss2gcgzpysmv1zb4-status-go-0.100.2-ed67cc2-ios' is not allowed to refer to the following paths:
         /nix/store/sm1cnnjp434ms6i2mywfs2585lm2v5jd-go-1.17.10
make: *** [jsbundle-ios] Error 1
```
Which is weird, because Go interpreter is stripped fine from resulting binaries on Linux.

**Review by cammellos — APPROVED** [review]

**Pull request merged**
