### PR TITLE
[#10891] Add 'Add new contact' and 'Invite friends' button to Contact…

### LINKED ISSUE #10891: Add 'Add new contact' and 'Invite friends' button to Contact screen
Issue within epic #7234 

# Problem
We've received more than one report of people struggling to add contacts. An explicit `Invite friends` button on the Contact screen can support users that are accustomed to inviting friends before starting a chat

## Implementation

- Add an invite friends button to the Contacts screen
- Invite friends button generates referral url

Designs on [Figma](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=510%3A4233) 
Profile -_ Contacts

## Acceptance Criteria
Follow design on Figma

## Notes
Adding contacts is not center stage in the UI as starting a chat does not require 'friending' or 'being contacts'. `Contacts` rather serves as a phonebook. Adding an explicit `Invite friends` button to the `Contacts` view, makes starting a chat easier for those under the impression that it is required.

## Future Steps
Add remaining features to contact management as found in the design and epic #7234

### LINKED ISSUE #10892: Add 'Add new contact' flow to Contact screen
Issue within epic #7234

# Problem
Currently there are two ways to add a new contact to Contacts:
- Inside a 1:1 chat, tap the Add to contacts bar at the top of the chat screen
- Tap on a username to view their Profile and tap `Add to contacts`

This does not accommodate the workflow of adding contacts to a phonebook without starting a chat. 

## Implementation

- Add a `Add new contact` button to the contact screen
- Allow search by ENS username
_Input here is a direct replica of the one we currently have in New Private Chat, but it does tell you if a name exists as you type and to which public key it maps to, so in a way it's doing a search after each letter you type_

Designs on [Figma](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=510%3A4233) 

Frame 165

## Acceptance Criteria
Follows designs on Figma

## Notes
Adding contacts is not center stage in the UI as starting a chat does not require 'friending' or 'being contacts'. Contacts rather serves as a phonebook. Adding an explicit `Add new contact` button to the Contacts view, makes starting a chat easier for those under the impression that it is required.

## Future Steps
Add remaining features to contact management as found in the design and epic #7234

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #10891
fixes #10892

### CODE REVIEW

**Comment by errorists** [comment]
@flexsurfer is it possible to flex vertically center the `Invite Friends` container in the available space here, similar to how it's in the issue?

also, in this instance, can we use the `add` icon instead of `arrow_right`? It makes more sense for adding contacts

IMG_1564

**Comment by flexsurfer** [comment]
@errorists yes its possible but i trust only figma :)

**Comment by flexsurfer** [comment]
done

**Comment by oskarth** [comment]
Small request - could you please rebase to latest master so this commit https://github.com/status-im/status-react/commit/b5fda1234e5447cbc626059dfc78fcfbabc9e926 gets included? This means we aren't running E2E tests on eth.prod cluster anymore, and since this happens on every push, the impact is quite big. This ensures we have more accurate metrics going forward from Jul 1 onward, which would be awesome. See https://discuss.status.im/t/user-growth-and-retention/1782 for more

EDIT: Since this is a recent PR, it might've been included already. All good if so

**Review by cammellos — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer please rebase it to current develop, I'll take it.
Thanks!

**Comment by churik** [comment]
@flexsurfer tappable area for "Add new contact":
Monosnap 2020-07-06 16-35-43
should be changed.

BTW: when I tap on it second time, the tappable area is changed to expected.
So it is a case only when you open contact view for the first time

**Comment by flexsurfer** [comment]
@churik its regular list item, it worked before quo merge, so its not in the scope of this PR

**Comment by churik** [comment]
@Ferossgp let me know when I can retest.
Tappable area doesn't match button only when list is empty

**Comment by Ferossgp** [comment]
@churik I fixed the list item component here https://github.com/status-im/status-react/pull/10916 so if we merge this it will be ok when we merge both.

**Pull request merged**
