### PR TITLE
update Itanlian, Arabic, Spanish, Chinese and Korean

### PR DESCRIPTION
**Pull request by jinhojang6**
Italian : Enrico & Rachid (it.json)
Chinese: Steven (zh.json)
Korean: Jinho (ko.json)
Arabic: Daoud (ar.json)
Spanish: Lalo (es_419.json)

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by jinhojang6** [comment]
When I locally built this PR through the iOS simulator, it showed all the `es_419`(Latin American Spanish) translations well.
Screen Shot 2020-01-25 at 2 48 59 PM

But when I downloaded the Jenkins build #5 (https://i.diawi.com/imSkTj) on my iPhone,
Screen Shot 2020-01-25 at 2 47 42 PM

it didn't update `es_419` copy and showed only old translations as below (partially translated)


I think it uses [es.json](https://github.com/status-im/status-react/blob/update-translations/translations/es.json) in the production mode.

@flexsurfer @jakubgs 
Do you know the reason why?

I found that we replace `_` with `-`  in [dev/status_im/i18n_resources.cljs](https://github.com/status-im/status-react/blob/5203fc6fd81012bd49f337526541a5d7c08f1180/dev/status_im/i18n_resources.cljs#L11) but  don't do it in [prod/status_im/i18n_resources.cljs](https://github.com/status-im/status-react/blob/5203fc6fd81012bd49f337526541a5d7c08f1180/prod/status_im/i18n_resources.cljs#L76).

(def translations-by-locale)

**Comment by jakubgs** [comment]
@jinhojang6 my guess would be that the automatic rebase fucked up:
```
05:32:24  + git rebase develop
05:32:24  First, rewinding head to replay your work on top of it...
05:32:24  Applying: update Itanlian, Arabic, Spanish(LatAm), Chinese and Korean
```
https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-9899/5/consoleFull

I'd start by rebasing your branch on most recent `develop`.

**Comment by jinhojang6** [comment]
@jakubgs I did it just before but `es_419` still doesn't work.

@flexsurfer Do you remember that `zh_` files didn't work before? I guess the production build cannot handle a locale with an underscore `_` well.

**Comment by flexsurfer** [comment]
@jinhojang6 added a change. lets try it

**Comment by flexsurfer** [comment]
@jinhojang6 please try latest build

**Comment by jinhojang6** [comment]
@jakubgs Unfortunately, it doesn't work as expected. I guess it refers to [es.json](https://github.com/status-im/status-react/blob/develop/translations/es.json) instead of [es_419.json](https://github.com/status-im/status-react/blob/update-translations/translations/es_419.json) in the production mode.

**Comment by jakubgs** [comment]
Well, I don't know how translations work in our App, so you'll have to ask a Clojure dev.

**Comment by flexsurfer** [comment]
image
it seems like it works for me, @jinhojang6  can you try latest #11  build ?

**Comment by jinhojang6** [comment]
@flexsurfer Yes, it works well! Amazing :)

**Pull request merged**
