### PR TITLE
Check tribute if contact was added

### LINKED ISSUE #8406: No input field in 1:1 chat is shown for some of the contacts
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Input field is not shown for some of the contacts in 1:1 chat. Maybe, it's because of the way they are added I(I've used universal link from status.im/about page). Tried for Anna, Rachel, Igor, Nastya, Jarrad - for all of them no input field in 1:1 if open their profile from about page, add them to contacts and only after this open 1:1 chat with them

#### Expected behavior

[comment]: # (Describe what you expected to happen.)
There is input field in 1:1 chat, so user can type and send a message
#### Actual behavior

[comment]: # (Describe what actually happened.)
no input field is shown
### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and sign in
-  in browser open https://dev.status.im/about/ scroll to Core Contributors, tap on Adam's picture (first icon in the list)  and tap on Status icon, as a result Profile for "High Happy Noolbenger" will be opened in Status app
- tap on Add to contacts to add Adam to contacts
- tap on < to go to Chats list
- tap on + to start new chat, select "Start new chat" and tap on "High Happy Noolbenger". As a result, 1:1 chat is opened
- check if you can see input field 

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly build from June 12, https://i.diawi.com/ZHJUYp Note: it works fine on 0.13.0 version in ios
- Operating System: iOS and Android

### PR DESCRIPTION
**Pull request by vitvly**
Fixes #8406

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Review by cammellos — CHANGES_REQUESTED** [review]
seems like a test would have been helpful catching this, please add some covering the function.

**Comment by cammellos** [comment]
@flexsurfer @jeluard please do not approve PRs if no tests, a fix should come with a test covering the case when it makes sense (in this case for example). thanks

**Comment by vitvly** [comment]
@cammellos added tests for check-tribute.

**Review by cammellos — APPROVED** [review]

**Comment by asemiankevich** [comment]
@siphiuel what should happen if i add a contact who has Ttribue to talk = On ? I think i have it enabled on my account but if i add myself using build from this PR - it does not ask for payment. However chat input is working fine. Could you please elaborate?

**Comment by vitvly** [comment]
@asemiankevich if you're both on the same network (Ropsten), and your contact has tribute-to-talk on and didn't add you as a contact before, you should see a payment option and the chat input should be hidden.

**Comment by asemiankevich** [comment]
> @asemiankevich if you're both on the same network (Ropsten), and your contact has tribute-to-talk on and didn't add you as a contact before, you should see a payment option and the chat input should be hidden.

nevermid, i forgot about ropsten , sorry for false alarm

**Comment by asemiankevich** [comment]
i've checked there:
- adding a contact who does not have TTT enabled previously (chat input is enabled fine)
- adding a contact who has TTT enabled (chat input is disabled, message shown for TTT payment)
- pairing the devices
- messaging 1x1, group chats, public chats - looks fine
- looks there is known issue with TTT that i can't chat after payment done https://github.com/status-im/status-react/issues/8346, but i was able to - at least i can exchange some messages with desktop after i paid tribute on mobile

Looks good to me to be merged as is.

tests are failed to known reason, we are working on fixing this as soon as possible.

**Pull request merged**
