### PR TITLE
Remove insets from image selector

### LINKED ISSUE #14611: Graphical glitch on image picker
The image has graphical glitches at the bottom on Android. Haven't tested iOS, I don't own Apple stuff

Screenshot_2022-12-21-13-31-19-16_65ad86f86fd2321a85272a99323da10f

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #14611
status: ready

### CODE REVIEW

**Comment by du82** [comment]
Now it goes below the screen

Screenshot_2022-12-21-15-16-05-80_65ad86f86fd2321a85272a99323da10f

**Comment by ibrkhalil** [comment]
> Now it goes below the screen
> 
> Screenshot_2022-12-21-15-16-05-80_65ad86f86fd2321a85272a99323da10f

I think this fix should be Android only

**Review by J-Son89 — APPROVED** [review]

**Comment by J-Son89** [comment]
Screenshot 2022-12-21 at 23 33 00
so much responsibility :)

**Review by yqrashawn — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by flexsurfer** [comment]
> > Now it goes below the screen
> > Screenshot_2022-12-21-15-16-05-80_65ad86f86fd2321a85272a99323da10f
> 
> I think this fix should be Android only

i believe its Android on the screenshot

**Comment by ibrkhalil** [comment]
> > > Now it goes below the screen
> > > Screenshot_2022-12-21-15-16-05-80_65ad86f86fd2321a85272a99323da10f
> > 
> > 
> > I think this fix should be Android only
> 
> i believe its Android on the screenshot

I mistakenly thought it was iOS from how the bottom navigation looks like, @du64 Please check again

**Comment by flexsurfer** [comment]
I remember seeing a similar issue from @du64 , but it solved itself somehow? its some specific Android device which has similar to ios gesture

**Comment by du82** [comment]
Looks good! @ibrkhalil @flexsurfer 

Also, I'm running Android 11, the iOS-style nav bar was introduced on all phones, but is off by default on some phones. It's the only option on mine, there is no three button layout anymore.

https://support.google.com/android/answer/9079644

**Pull request merged**
