### PR TITLE
temporary fix for app crash if chat has long ens names

### PR DESCRIPTION
**Pull request by flexsurfer**
temporary fix for app crash if chat has long ens names

### CODE REVIEW

**Comment by cammellos** [comment]
What works slow here? have you checked the performance of `stateofus/username`? 

```
(defn username [name]
  (when (and name (string/ends-with? name domain))
    (first (string/split name "."))))
```
If not I would first remove that, and try the ellipsis (as I understand that's preferrable if performance are ok) https://github.com/status-im/status-react/pull/10021 . If performance are acceptable then the issue is in `username` function, which looks fairly inefficient.

Split is not lazy, so it will go through the whole string regardless, if we really wants to keep exactly the same behavior we can use either `loop/recur` or `reduce/reduced`, which both short circuit at the first `.`. Otherwise if we are not concerned about names such as `foo.bar.stateofus.eth` we an just take a substring `(subs name 0 (- (count name) state-of-us-length))` which should also be more performant.
`ends-with?` is likely performant enough, but worth checking.

**Comment by flexsurfer** [comment]
@cammellos because it works slow only on android, i believe problem in text component on Android, probably it ellipsize every component and its slow, and still its just a simple and quick fix for v1, we must prepare proper fix in v1.1.

**Review by cammellos — APPROVED** [review]

**Comment by Serhy** [comment]
App doesn't crash for me on Samsung J7 (Android 8.1) and Galaxy Note 4 (Android 6.0.1) in status chat with loong ENS (fetched messages and scrolled up to 7th of February morning time history).
iOS is OK too (but I had no problems with release build there as well)

**Comment by flexsurfer** [comment]
@Serhy try to join #status-chinese and fetch history for 3-4days

**Comment by flexsurfer** [comment]
increased length up to 80

**Comment by Serhy** [comment]
@flexsurfer with 40 char-long-ens build ```#status-chunese``` works even better for me for the last 5 days than ```#status``` (messages loads quicker, less chat-message-dancing behavior)

**Comment by flexsurfer** [comment]
@Serhy and what about #status-chunese in latest nightly or RC ?

**Comment by flexsurfer** [comment]
chat still pretty fast with 80 so lets keep 80

**Comment by Serhy** [comment]
In RC, can't fetch and scroll to the top of 4 days history in ```#status-chinese```.  I gave up after 5 appearing `Status isn't responding` pop-ups -> tap `Wait`

**Pull request merged**
