### PR TITLE
[WIP] Make blocking logout call

### LINKED ISSUE #8799: Can't login to application
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: sometimes after creating an account I can see endless spinner instead of + button and after logout, I can't log in. If I try to create new account - after logout  I also can't login to the app, it shows "Processing" state.
I couldn't find a way to recover from this state - only reinstalling app helped

#### Expected behavior
can login to app

#### Actual behavior
pr

### Reproduction

- Open Status
- Create an account
- Logout
- Login

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 21/08/2019
- Operating System: Android

#### Logs
Geth.log: 
[geth (1).log](https://github.com/status-im/status-react/files/3524821/geth.1.log)
Logcat: 
[logcat_processing.log](https://github.com/status-im/status-react/files/3524823/logcat_processing.log)

### LINKED ISSUE #8806: Unknown in Profile and "null is not an object" at attempt to log out after log out from offline
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: when log out without network, after login instead of username "Unknown" is shown without user picture and also at attempt to log out "null is not an object(evaluating 'n.toLowerCase''"
Network settings are empty for such users.

#### Expected behavior
Can log out;
usename \ userpicture is valid;
network settings are shown

#### Actual behavior
photo_2019-08-21 16 00 18

### Reproduction

- Open Status
- Create new account
- Turn on Airplane mode
- Log out
- Login
- Turn off Airplane mode

### Additional Information

- Status version: nightly 21/08/2019
- Operating System: Android, iOS

#### Logs

[status_logs.zip](https://github.com/status-im/status-react/files/3525698/status_logs.zip)

### PR DESCRIPTION
**Pull request by yenda**
This avoids allowing the user to relogin before the node is already stopped

fix #8799
fix #8806

status: ready

### CODE REVIEW

**Comment by rachelhamlin** [comment]
@yenda is anything you're doing here relevant to #8702? I think that one is also a priority for audit.

**Comment by yenda** [comment]
> @yenda is anything you're doing here relevant to #8702? I think that one is also a priority for audit.

No it's unrelated but I can have a look at this issue as well

**Comment by rachelhamlin** [comment]
@yenda that'd be great, I believe it is a blocker.

**Comment by yenda** [comment]
this one is already merged in develop

**Pull request closed without merging**
