### PR TITLE
[Fixes: #1520] Enable ens

### PR DESCRIPTION
**Pull request by cammellos**
Enable ENS in chat, and enable appium tests.

status: ready

### CODE REVIEW

**Review by churik — APPROVED** [review]
Smth else apart from ENS to check in upgrade?

**Review by vitvly — APPROVED** [review]

**Comment by Serhy** [comment]
@cammellos there are issues with Groupchat: when contact receives Invite or any further messages in GroupChat he was invites to the errors appears (actual Group Chat is not displayed on Chats screen)

To reproduce:
1) UserA creates a group chat with UserB
**Actual Result:** No GroupChat is shown on Chats view. Error appears:
Screenshot 2019-11-08 at 11 59 35

2) UserA sends a text message in this GroupChat
**Actual result:** Error appears:
Screenshot 2019-11-08 at 11 59 41

**Comment by cammellos** [comment]
@Serhy thanks, looking into it

**Comment by cammellos** [comment]
@Serhy should be fixed in the next build, how do I re-run the failed tests without running the whole suite?

**Comment by Serhy** [comment]
To rerun specific tests there is a https://ci.status.im/job/end-to-end-tests/job/re-run-e2e-tests/build?delay=0sec 
testrail_case_ids are ids of specific tests we want to rerun which could be found in TestRail.
I'll rerun all above failed tests once new build is finished.

**Comment by cammellos** [comment]
@Serhy it was missing some externs, so wasn't building properly,  could you re-run once the build is ready? Thanks!

**Comment by Serhy** [comment]
Failed e2e in https://github.com/status-im/status-react/pull/9410#issuecomment-551551944 test_pair_devices_sync_one_to_one_contacts is a bug. 
As I see on video for what happed was that 1-1 chat with user on paired device displayed as my own account.

**Comment by Serhy** [comment]
> @Serhy it was missing some externs, so wasn't building properly, could you re-run once the build is ready? Thanks!

Sure, OK!

**Comment by Serhy** [comment]
Thanks @cammellos !

**Comment by cammellos** [comment]
Thank you @Serhy !

**Pull request merged**
