### PR TITLE
ci: use different IPFS gateway for release builds

### LINKED ISSUE #13794: Stickerpacks are not loaded in stickermarket (endless loader is displayed)
Stickers are not loaded in stickermarket. Endless loader is displayed. 

**Preconditions:** mainnet network is selected

**Steps:**

1. Open any chat
3. Open stickermarket (Tap on stickers icon -  Get stickers)
4. Observe the result

**Actual result:**  endless loader, stickers are not loaded

**Expected result:**  list of stickerpacks are loaded

### Additional Information

- Status version: latest nightly 
- Operating System: Android, iOS

https://user-images.githubusercontent.com/97245802/184086591-408a7c35-77e7-4308-9fa5-56f456637808.mp4

[geth.log](https://github.com/status-im/status-mobile/files/9307002/geth.log)

### PR DESCRIPTION
**Pull request by jakubgs**
fixes: #13794

__WARNING:__ Do not merge until the https://github.com/status-im/status-go/pull/2795 PR is merged and `status-jenkins-lib` tagged.

Depends on:
- https://github.com/status-im/status-jenkins-lib/pull/44
- https://github.com/status-im/status-go/pull/2795

### CODE REVIEW

**Comment by jakubgs** [comment]
Appears to be working:
```
nix-build \
  --show-trace --impure --no-out-link \
  --arg config '{status-im.build-type="pr";status-im.build-number="2022082413";status-im.commit-hash="42cc5ae1b3374d2391fdb696a071d7e4c1c6d41e";status-im.android.gradle-opts="-PbuildUrl=[https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-13850/1/";status-im.android.abi-split="false";status-im.android.abi-include="armeabi-v7a;arm64-v8a";status-im.status-go.ipfs-gateway-url="https://ipfs.status.im/](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-13850/1/%22;status-im.android.abi-split=%22false%22;status-im.android.abi-include=%22armeabi-v7a;arm64-v8a%22;status-im.status-go.ipfs-gateway-url=%22https://ipfs.status.im/)";}' \
  --argstr secretsFile /tmp/nix-env-220824-131408-8kZoArXi.tmp \
  --option sandbox true \
  --option extra-sandbox-paths /tmp/nix-env-220824-131408-8kZoArXi.tmp \
  --attr targets.mobile.android.release \
  /home/jenkins/workspace/atus-mobile_prs_android_PR-13850/default.nix
```
Since we can see `status-im.status-go.ipfs-gateway-url` being provided.

**Comment by flexsurfer** [comment]
we need somehow to make sure infura is used in prod

**Review by flexsurfer — APPROVED** [review]

**Comment by jakubgs** [comment]
@flexsurfer the way the check is one in `status-jenkins-lib` is like this:
```groovy
def isReleaseBuild() {
  return (
    params.RELEASE == true ||
    params.BUILD_TYPE == 'release' ||
    env.JOB_NAME.startsWith('status-mobile/release') ||
    env.JOB_NAME.startsWith('status-desktop/release') ||
    env.JOB_NAME.startsWith('status-node/release')
  )
}
```
https://github.com/status-im/status-jenkins-lib/blob/d4e698806ad54a7543ce2bcb40e9a6ca43c6e3ed/vars/utils.groovy#L151-L159

**Comment by qoqobolo** [comment]
Tested displaying stickers on Goerli and Mainnet in different types of chat and buying a sticker pack on Goerli.
Works great.
E2e failures are not PR-related.

@jakubgs PR can be merged.
Thank you

**Pull request merged**
