### PR TITLE
v1 Copy Changes - Round 1

### LINKED ISSUE #9672: v1 Copy Changes - Bits & Pieces
# Problem
App copy has never been reviewed holistically, end-to-end. 

I did so over the past week to ensure clarity, brevity and good grammar. Kept language neutral due to a) time constraint, b) lack of formal brand/creative process and c) desired ease of translation. 

Reviewed with Jonny, Graham, Hester and Maciej in phases.

Additional edits to come in separate issues. This first round is low-hanging fruit, with easy consensus to change.

## Implementation
[This PDF](https://drive.google.com/file/d/1NdrEBrcMvqyNGUednHrMe02UfFqGDuhP/view?usp=sharing) shows various screens in their current state, with desired copy alongside them. 

[This additional PDF](https://drive.google.com/file/d/10rcCsMP9Z7Jh-JYjGjKmjQm9N_pL1Pg4/view?usp=sharing) contains edits to the seed phrase backup flow.

## Acceptance Criteria
Please match desired changes exactly, including capitalization and punctuation.
**There are two changes to ignore in the PDF: please leave `Manage assets` on wallet menu, and ignore the change from `mail servers` to `history nodes`.**

**Keycard onboarding step 3**

* `Backup "Seed" phrase` > Back up seed phrase
* `With this seed phrase you can always get your key back. Write the seed phrase down. Keep it safe, offline, and separate from this device.` > You need this seed phrase to get your key back. Write it down. Keep it safe, offline, and separate from this device.
* `You cannot do this later. Without the seed phrase you will not be able to access your key or any assets associated with it if you loose your device.` > You won’t have a second chance! If you lose or change your device, you will not be able to access your key or any assets associated with it unless you have your seed phrase.

**Chat**

Opening screen

* `Chat and transact privately with your friends.` > `Chat and transact privately with friends`
* `Follow your interests in one of the many public chats.` > Jump into a public chat and meet new people

Join public chat

* `A public chat is where you get to hang out with others, make friends and talk about subjects of your interest.` > Join public chats for your interests! Anyone can start a new one.

Mobile syncing pop-up

* `Sync using Mobile data` > Sync using mobile data?
* `Status tends to use a lot of data when syncing chats. You can choose not to sync when on mobile network.` > Status uses a lot of data when syncing chats.
* `You can change this later in settings` > You can change this later in settings
* `Until connected to Wi-Fi?` > Until connected to Wi-Fi
* ~`You can configure syncing in more detail in settings`~

**Profile**

Privacy and security

* `White out Status when app switching` > Hide Status previews when app switching

About

* `Privacy Policy` > Privacy policy

Sync settings

_Not enough consensus on this yet, please ignore._

* ~`mailserver` > History node~
* ~`Mailserver settings` > History node selection~

**Wallet**

Signing phrase pop-up

* `You should see these 3 words before signing each transaction` > These three words prove that a transaction is safe.
* `If you see a different combo, cancel the transaction and logout.` > You should see these words before signing each transaction. If you don't, cancel and sign out.
* `Remind me later` > Show me this again
* `OK, got it` > Okay, got it

Menu options

IGNORE ONE CHANGE

* ~`Manage assets` > Manage tokens~
* `Set currency` > `Set default currency`
* `Backup your seed phrase` > Back up your seed phrase

Browser

* `Browsed websites will appear here.` > Browser history will appear here

Seed Phrase Backup

* `If you lose your seed phrase you lose your data and funds` > If you lose your seed phrase you lose everything
* `Status can't help you recover your multiaccount if you lose your seed phrase. You are in charge of the security of your data, and backing up your seed phrase is the best safeguard.` > Money, messages, all of it. Status can't access your data nor help you retrieve it. You are in charge of your keys, and your seed phrase is how you recover them. Back it up somewhere safe!
* `OK, continue` > Okay, continue
* `Backup seed phrase` > Back up seed phrase
* `This is your seed phrase. You use it to prove that this is your wallet. You only get to see it once! Write it on paper and keep it safe in a secure place. You will need it if you lose or reinstall your wallet.` > These 12 words are your seed phrase. You need it to recover your account when you change phones or reinstall. Write it on paper and keep it safe. **You only get to see it once!**

### PR DESCRIPTION
**Pull request by hesterbruikman**
fixes #9672 

### Summary
Updates to Keycard onboarding, Chat, Profile, Wallet and Browser
Follows copy in pdf of #9672 

##### Additions
Mnemonic phrase >  Seed phrase

##### Exceptions
- Additional edit **Keycard back up seed phrase**: "You won’t have a second chance! If you lose or change your device, you will not be able to access your key`s` or any assets associated with it unless you have your seed phrase."
- Partial edit **Sync using mobile data?** content: `You can change this later in [settings](URL)` cannot add url in translations file. Kept settings link in existing copy below `Remember my choice`
- Not edited **Set DApp access permissions**: Is crossed out in pdf. Not sure why. If I understand it correctly, also with privacy enabled by default you still need access to revoke permissions. Also, couldn't change in language file @rachelhamlin 
- Not edited **History node selection**: ongoing discussion, not sure about the latest
- Not edited **Manage assets**: Proposal `Manage tokens` wouldn't cover ETH.

#### Areas that maybe impacted
- Keycard onboarding
- Settings
- Sync over mobile data modal
- Chat (Empty screen + New public chat)
- Wallet (overview and signing phrase modal)
- About
- Browser home

##### Non-functional
- copy

status: ready

### CODE REVIEW

**Comment by yenda** [comment]
@hesterbruikman who needs to confirm these changes?

**Comment by hesterbruikman** [comment]
> 
> 
> @hesterbruikman who needs to confirm these changes?

@rachelhamlin

**Review by rachelhamlin — APPROVED** [review]

**Comment by rachelhamlin** [comment]
I completely missed this. Thank you so much @hesterbruikman!

**Comment by hesterbruikman** [comment]
Thanks for merging these @yenda

**Pull request merged**
