### PR TITLE
[#8624] Disable stickers in testnet

### LINKED ISSUE #8624: Disable stickers in testnet
# Problem

It's possible to send test stickers from ropsten network

## Implementation

It should be not possible to select and send stickers from testnets

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #8624

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by churik** [comment]
Tested on IOS 11.4.1 (IPhone 7), Android 8 (LG V20):
- sticker icon is visible on Mainnet;
- can't buy stickers on Mainnet (no packs available);
- no stickers are available on Ropsten and in other networks;

Question:
stickers that are purchased on Ropsten on previous builds, are available on Mainnet if you update your app to current PR build.
From https://github.com/status-im/status-react/issues/8624#issuecomment-514551494 is it not clear for now should it be removed in terms of this PR or not.
@rachelhamlin can you clarify?

**Comment by flexsurfer** [comment]
@churik i'm not sure if there is a solution for this

**Comment by flexsurfer** [comment]
hm we need to check one more case, we still show stickers in testnet in chat, what if someone sends sticker from mainnet and another user who doesn't have this pack clicks on it in a testnet

**Comment by rachelhamlin** [comment]
Yes, please check that case @flexsurfer. Otherwise @churik it's okay if stickers from previous testnet builds are still available since it's just us testing anyway. Let's let it go.

On a related note, Ricardo registered the packs on mainnet so we should be able to test those soon.

**Comment by churik** [comment]
@flexsurfer I checked the case as described here: https://github.com/status-im/status-react/pull/8627#issuecomment-515000456, and yes, the sticker pack is shown on Ropsten, and I can tap on it, buy it and after installing use on Mainnet.
I guess should be fixed here.
Please, confirm @flexsurfer 
Thanks for a clue!

**Comment by flexsurfer** [comment]
@churik yes ill fix it here, thanks!

**Comment by oskarth** [comment]
What's the state of this PR @flexsurfer?

**Comment by flexsurfer** [comment]
@oskarth all release PRs on pause, we'll continue with them when v1 code freeze will be done

**Comment by flexsurfer** [comment]
@churik fixed https://github.com/status-im/status-react/pull/8627#issuecomment-515000456

**Review by yenda — APPROVED** [review]

**Comment by churik** [comment]
No available stickers on other networks (not Mainnet), issues is fixed.

**Pull request merged**
