### PR TITLE
fix nix/clean.sh race condition

### PR DESCRIPTION
**Pull request by jakubgs**
To avoid trying to remove stuff that an ongoing `nix-build` process might be using we call `wait-for.sh`.

Possible fix for #8757.

### CODE REVIEW

**Review by pedropombeiro — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by jakubgs** [comment]
>we can simplify and use openjdk instead of pkgs.openjdk here.

~~How would that work? If it's under `pkgs` why would it not fail?~~
EDIT: Oh, I'm a moron, I didn't notice the `with pkgs`.

**Comment by jakubgs** [comment]
I couldn't make the `wait-for.sh` script to find `pod install` properly without the `-f` option so i decided to upgrade CocoaPods from `1.5.3` to `1.7.5` in https://github.com/status-im/infra-ci/commit/4786581c.
Hopefully they fixed the race conditions when running multiple instances of `pod install`, if they didn't I will find a different solution.

**Comment by jakubgs** [comment]
Okay, I changed it so that `wait-for.sh` takes as arguments after the timeout not just process name but whole `pgrep` options. So in `nix/mobile/ios/install-pods-and-status-go.sh` we can pass the `-f` flag.

**Comment by jakubgs** [comment]
I don't like how this delays the `e2e` builds by quite a bit waiting for the android build for finish.
I might still merge this anyway and find a better solution later, just to avoid failed builds.

**Comment by jakubgs** [comment]
I've decided to use a different approach. Now the `nix/clean.sh` script can be run without any arguments and then it uses the regex as before to clean everything, but if a path to a nix store entry is given(like we do now with the result path) then only that and it's related paths are cleaned.

I've checked the builds and even if `android` and `android-e2e` run on the same host, they still show up as different result paths, as they should:
```
Cleanup of /nix/store...
Searching by result: '/nix/store/s17r0vpyy109hxv5dil26gxhss8cwgnb-status-react-build-jsbundle-android'
 ? Checking:   /nix/store/s17r0vpyy109hxv5dil26gxhss8cwgnb-status-react-build-jsbundle-android
 - Derivation: /nix/store/jvjf8f7fd5rxah0vjpxgfrayvx0ygmyg-status-react-build-jsbundle-android.drv
 - Source:     /nix/store/wmzcjws14zxxzcr07whbc79k5is9c101-status-react-source-jsbundle
Deleting...
```
This should be much better than adding any silly blocking waits.

**Pull request merged**
