### PR TITLE
Update status-go to v0.24.0-beta.1

### PR DESCRIPTION
**Pull request by dshulyak**
Feature:

* Expose vanilla ECDSA signing (#1444)

Other fixes:

* If whisper peers are communicating and their time is not synced they will not disconnect from one another
* signal that history request was completed is sent only after all relevant envelopes were added to the whisper filters

Link to status-go release: https://github.com/status-im/status-go/releases/tag/v0.24.0-beta.1

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Comment by dshulyak** [comment]
Changed release version to v0.24.0-beta.1 . It includes one more important fix.

**Comment by dshulyak** [comment]
I restarted tests. Doesn't seem like failure is caused by changes in this PR.
What else needs to be done before it will be merged?
@annadanchenko do you think that update needs to be tested separately before merge?

**Comment by mandrigin** [comment]
@annadanchenko I marked it as a release blocker because it contains the fix for never-ending progressbar for private messages.

**Comment by annadanchenko** [comment]
@dshulyak yes it should be tested before merge

**Comment by annadanchenko** [comment]
@mandrigin @dshulyak when tested ok - let's included it in the next nearest release after 0.12.0

**Comment by pedropombeiro** [comment]
`STATUS_GO_SHA256` also needs to be updated. FWIW, the official way to update status go is to use `scripts/update-status-go.sh` which takes care of everything, regardless of the implementation details.

**Comment by Serhy** [comment]
No regressions found with Develop build.
@mandrigin could you merge it and cherrypick in release branch please?

**Pull request merged**
