### PR TITLE
Feature/use separate e2e token

### PR DESCRIPTION
**Pull request by cammellos**
This separates the token used for dev,e2e and release.
For those builds the infura token will be passed at build time on CI.
status: ready

### CODE REVIEW

**Review by Samyoul — APPROVED** [review]
Looks good.

**Review by jakubgs — APPROVED** [review]
Logs indicate it works as intended:
```
[2020-06-19T14:42:13.092Z] Using infura token: devel
```
```
[2020-06-19T14:42:11.945Z] Using infura token: e2e
```
But please __don't merge__ until I merge https://github.com/status-im/status-react-jenkins/pull/8 and tag the commit as `v1.1.7`.

**Comment by jakubgs** [comment]
I updated the branch with the `v1.1.7` tag for `status-react-jenkins` library and squashed the commits.

**Comment by cammellos** [comment]
Can this be merged now @jakubgs ?

**Comment by jakubgs** [comment]
I think so.

**Pull request merged**
