### PR TITLE
Fix replies messages

### LINKED ISSUE #10371: Message that contains only emoji are shown as replies to "Unknown" in all chats
# Bug Report

## Problem

photo_2020-04-20 16 44 59

#### Expected behavior
ordinary message, not reply

#### Actual behavior
message is shown as reply from unknown

### Reproduction

- Open Status
- Join any chat
- Send emoji

### Additional Information

- Status version: RC 1.3 #5 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #10371 

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@cammellos still see the same behavior in builds with https://github.com/status-im/status-react/commit/cdf9ab33f3dd6c165cfa329b130deaef9f9d559a commit - so issue is not fixed
photo_2020-04-21 13 37 33

**Comment by churik** [comment]
#### Messages-replies, sent from restored accounts don't change state to "Sent" (endless spinner)

Reproducible only with accounts restored from seed phrase.
**Steps:**
1) Restore multiaccount from seed phrase
2) Join any public chat
3) Reply to any message

**Expected:**
message-reply is sent

**Actual:**
Monosnap 2020-04-21 14-40-27

Logs: 
[status_logs-1.zip](https://github.com/status-im/status-react/files/4510011/status_logs-1.zip)

**Comment by churik** [comment]
UPD: also in develop, not really a blocker.

**Comment by churik** [comment]
@cammellos please cherry-pick it to v 1.3  branch
Thank you!

**Pull request merged**
