### PR TITLE
Add new UI for mailserver selection, Add feature to disable mailserve…

### LINKED ISSUE #11035: Allow choosing to not use a mailserver
# Problem
From a privacy perspective, it's important, for the user to be able to opt out of using a mailserver to collect history (i.e. messages sent while you were offline). 

## Implementation
Designs to be added (@errorists can you please add the final design in the comments?)

## Acceptance Criteria
User is able to disable use of a mailserver

## Notes
Giving the user control makes a stronger case in terms of privacy policy that the user controls their personal data (IP address)

## Future Steps

### PR DESCRIPTION
**Pull request by cammellos**
fixes #11035 

### Summary
Connecting to a mailserver (or history node from UX perspective) logs the users IP address. This feature gives an option to opt-out. It also implements updates the UI for mailserver selection to use switch and radio buttons.

By default, mailservers usage will be turned on. Relevant changes to Status Go repo were made by @cammellos [here](https://github.com/status-im/status-go/tree/feature/use-mailservers).

### Testing notes
We need to make sure that no historical messages are fetched while joining a public chat room when `use-mailservers?` (or `use history nodes`) is disabled.

#### Platforms
- Android
- iOS

#### Areas that maybe impacted
- Public Chats

##### Functional
- public chats
- mailservers

status: ready

### CODE REVIEW

**Comment by cammellos** [comment]
This is just a copy of https://github.com/status-im/status-react/pull/11191 cc @shivekkhurana

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@cammellos 
### ISSUE 1: after disabling toggle "Use history" node needs to relogin for taking it to effect
**Steps:**
- create new multiacount
- disable "Use history node"
- join status chat
**Expected result:**
no history is fetched
**Actual result:**
history is fetched
Logs: [status_logs.zip](https://github.com/status-im/status-react/files/5378339/status_logs.zip)
So in any case we need to relogin user to make it work

### ISSUE (question) 2: after adding custom mailserver is it invisible until disabling autoselection
For the user it seems that nothing happens after adding custom mailserver
image


### Question 3: As I understood from the description, only history should be affected (so new messages in 1-1, public and group chats should still be sent)?
What about offline inboxing?

### Issue 4: getting Error connecting to mailserver with disabled toggle "Use history" 

**Steps:**
- create new multiacount
- disable Auroselection in Profile > Sync settings > Mailserver
- select mailserver which is hardly reachable (in my  case `03.ac-cn-hongkong`)
- disable "Use history node"
- relogin
**Expected result:**
no error, as no attempt to connect to mailserver
**Actual result:**
IMAGE 2020-10-14 16:35:25

Logs:  [Status-debug-logs.zip](https://github.com/status-im/status-react/files/5378915/Status-debug-logs.zip)

**Comment by cammellos** [comment]
Thanks for testing

> ISSUE 1: after disabling toggle "Use history" node needs to relogin for taking it to effect

I will either make it so that it automatically logout, or preferably just disconnect from mailserver.
> ISSUE (question) 2: after adding custom mailserver is it invisible until disabling autoselection

thanks, I think we need @errorists input here :)
> Question 3: As I understood from the description, only history should be affected (so new messages in 1-1, public and group chats should still be sent)?

Correct, that's the behavior, you will not fetch history, but the messages you send should be stored on mailserver regardless

> Issue 4: getting Error connecting to mailserver with disabled toggle "Use history"

I will fix it

**Comment by cammellos** [comment]
@churik 
issues 1 & 4 should be fixed in the next build,
2 is still pending but I think it should be fine to merge as it is, imo.

One minor issue is that if you open a public chat when the toggle is off, it will show a message:
`There are no messages in the past 0 hours`, but to me seems acceptable, as toggling mailservers off is a fairly advanced feature.

**Comment by churik** [comment]
@cammellos continuation of issue 1: when after re-disabling toggle "Use history" it also has no effect until manual re-login.

**Steps:**
- create new multiacount
- disable "Use history node"
- enable "Use history node"
- join status chat

**Expected result:**
history is fetched
**Actual result:**
no history is fetched

other issues are fixed, thanks!

**Comment by cammellos** [comment]
@churik I can't replicate using the e2e apk, it takes a bit of time for the history to be fetched, sometimes it shows the connecting banner, but eventually once connected to the mailserver history is retrieved (I have tried a few times and similar results), could you please double check?

**Comment by churik** [comment]
@cammellos I investigated issue, it is reproducible only while trying to fetch history. 
So full steps:

**Steps:**
- create new multiacount
- join # status
- disable "Use history node"
- try to fetch more history for pub channel
- enable "Use history node" anf try to join another public channel

**Expected result:**
history is fetched
**Actual result:**
no history is fetched
The issue is a bit tricky and we can postpone it, don't think it is a blocker.

**Comment by cammellos** [comment]
@churik thanks, that's indeed the case, essentially the chat will be marked as "fetched" and history won't be fetched when back online, as the app will think it has already been fetched. 
I'd agree that is a bit of an edge case, so if you are ok, I would merge without fixing it.
Let me know if it's ready to be merged (I see 3 tests failed, not sure if it's related).
Thank you!

**Comment by churik** [comment]
Ready to be merged then, e2e are passed now

**Comment by cammellos** [comment]
@shivekkhurana merged, thanks for your contribution!

**Comment by shivekkhurana** [comment]
@cammellos Thanks for polishing and fixing my PR!

**Pull request merged**
