### PR TITLE
[fix #8609] Remove realm

### LINKED ISSUE #8609: Update account storage from Realm to go
### Description

*Summary*: Placeholder issue corresponding with (and blocked by) [#11 in /status-protocol-go](https://github.com/status-im/status-protocol-go/issues/11).

#### Expected behavior

[comment]: # (Describe what you expected to happen.)

#### Actual behavior

### PR DESCRIPTION
**Pull request by yenda**
fix #8609 

##### Functional

- 1-1 chats
- public chats
- group chats
- mailservers

##### Non-functional

- CPU performance / speed of the app

### Steps to test

Tested on iPhone 6Plus and android emulator

The only remain of realm was mailserver ranges so playing around with chats, going offline, going back online and recovering messages while offline should work.

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by churik** [comment]
Keep track on full TC set: https://ethstatus.testrail.net/index.php?/runs/view/4112

**Comment by churik** [comment]
@yenda 
#### Issue: messages are not fetched from offline if they are sent from device B (when device A and B are in sync)

**Steps:**

- install build on devices A and B
- pair devices
- sync all
- device A: create 1-1 chat, send several messages
- device B: go offline
- device A: send several messages to 1-1 chat
- device B: go online

**Expected result:**
can see messages sent from device A
**Actual result:**
messages are never fetched
**NOTE:** if I enable on this builds "DataSync", in this case I'll see additional chat with myself on "Device B" with fetched from 1-1 chat messages
Reproducible for 1-1 and group chats.
**Log(from device B):** 
[ssss.zip](https://github.com/status-im/status-react/files/3589517/ssss.zip)

**Comment by yenda** [comment]
@churik isn't it also in develop? this PR only moves chat-ranges from realm to status-go so I don't see how it could impact sync

**Comment by churik** [comment]
@yenda 
no, it is not. Tested on nightly 09/09/2019 - messages are fetched.

**Comment by churik** [comment]
OK, didn't manage to reproduce it with new account as well. 
So nothing prevent merging from my side.
@asemiankevich do you have smth?

**Comment by churik** [comment]
Tested:
- fetching messages from offline
- resending messages
- device pairing and datasync

**Comment by churik** [comment]
confirmed by @asemiankevich - can be merged

**Comment by ghost** [comment]
`desktop_files/yarn.lock` and `mobile_files/yarn.lock` changed. Pinging @jakubgs, @PombeirP, and @corpetty

**Pull request merged**
