### PR TITLE
All strings removed from translations

### LINKED ISSUE #8727: Remove unused strings
# Problem

The following strings are not used in the code anymore and should be removed from
- translations/en.json
- test/cljs/status_im/test/i18n.cljs
- rest of the files in translations if present there (e.g. ko.json, fr.json and the rest)

Strings:
{'no-hashtags-discovered-title', 'no-more-participants-available', 'and-you', 'wallet-transaction-fee', 'contacts-syncronized', 'faucet-error', 'currency-display-name-kyd', 'tribute-to-talk-sign-and-set-tribute', 'wallet-set-up-safe-transactions-title', 'add-existing-multiaccount', 'add-new-contact', 'currency-display-name-gyd', 'leave-confirmation', 'currency-display-name-bmd', 'removed-from-chat', 'device-to-device-warning-content', 'update-status', 'postponed', 'error-unable-to-get-transactions', 'leave-chat', 'search-chats', 'your-wallets', 'delete-group', 'status-not-sent', 'device-to-device-warning-title', 'mute-notifications', 'reorder-groups', 'status-not-sent-tap', 'signing-phrase-warning', 'transaction-moved-title', 'transactions-delete', 'error-cant-send-transaction-offline', 'no-statuses-found', 'available-participants', 'wallet-transaction-fee-details', 'delete-contact-confirmation', 'is-typing', 'create-new-multiaccount', 'wallet-set-up-confirm-description', 'move-to-internal-failure-message', 'status-failed', 'passcode-error', 'leave-group-chat', 'wallet-onboarding-description', 'delete-group-chat-confirmation', 'popular-tags', 'enter-dapp-url', 'wallet-onboarding-set-up', 'secure-your-assets', 'search-tags', 'wallets', 'pin-unblocked', 'add-new-network', 'status-delivered', 'currency-display-name-srd', 'multiaccount-not-listed', 'currency-display-name-mkd', 'unsigned-transaction-expired', 'wallet-deposit', 'enter-valid-public-key', 'suggestions-requests', 'search-for', 'leave-group-title', 'empty-topic', 'status-prompt', 'phone-significant', 'wallet-add-asset', 'existing-networks', 'edit-chats', 'keycard-applet-will-be-installed', 'other-multiaccounts', 'currency-display-name-ltl', 'secret-keys-confirmation-cancel', 'secret-keys-confirmation-confirm', 'transactions-unsigned-empty', 'no-multiaccount-on-card', 'switch-users', 'status-hardwallet-capitalized', 'edit-contacts', 'status-sent', 'delete-contact', 'invalid-phone', 'status-not-sent-without-tap', 'recover-access', 'wallet-set-up-signing-explainer', 'make-sure-you-trust-dapp', 'not-implemented', 'add-a-status', 'currency-display-name-yer', 'new-transaction', 'enter-pin-description', 'address-explication', 'currency-display-name-mnt', 'edit-network-config', 'request-qr-legend', 'no-pairing-on-device', 'transaction-moved-text', 'phone-number', 'not-specified', 'no-multiaccount-on-card-text', 'tribute-to-talk-you-can-leave-a-message', 'debug-enabled', 'edit-network-warning', 'suggestions-commands', 'intro-text-description', 'transactions-sign-later', 'mobile-network-use-mobile-details', 'chat-send-eth', 'faucet-success', 'no-statuses-discovered', 'phone-international', 'sign-later-text', 'here-is-your-signing-phrase', 'remove-from-contacts', 'fetching-messages', 'ens-names', 'ens-username-owned-continue', 'default-dapps-marketplaces', 'leave-public-chat', 'tribute-to-talk-message-placeholder', 'connection-problem', 'edit-group', 'phone-national', 'dapp-profile', 'default-dapps-social-utilities', 'error-processing-json', 'default-dapps-social-networks', 'no-statuses-discovered-body', 'transactions-sign-all', 'wallet-exchange', 'members-none', 'delete-group-confirmation', 'currency-display-name-nio', 'leave-group-chat-confirmation', 'wallet-address-from-clipboard', 'transactions-unsigned', 'wallet-backup-recovery-description', 'sign-later-title', 'process-json', 'multiaccount-not-listed-text', 'notifications-title', 'delete-chat-title', 'paste-json-as-text', 'view-transaction-details', 'existing-mailservers', 'you-will-need-this-code', 'delete-group-prompt', 'transactions-delete-content', 'status-seen', 'contact-already-added', 'choose-from-contacts', 'remove-from-group', 'view-my-wallet', 'wallet-set-up-confirm-title', 'default-dapps-fun-games', 'wallet-set-up-signing-explainer-warning', 'currency-display-name-sos', 'status-seen-by-everyone', 'already-have-multiaccount', 'wallet-choose-from-contacts', 'leave-group-action', 'wallet-send-token', 'syncing-disabled', 'incorrect-code', 'type-a-command', 'currency-display-name-lrd', 'currency-display-name-bzd', 'wallet-browse-photos', 'wallet-onboarding-title', 'search-chat', 'selected-dapps', 'request-feature', 'phone-number-required', 'default-dapps-media', 'begin-keycard-setup-confirmation-text', 'no-hashtags-discovered-body', 'specify-mailserver-address', 'manage-permissions', 'dont-allow', 'add-json-file', 'leave-group-confirmation', 'syncing-enabled', 'shake-your-phone', 'wallet-error', 'topic-format', 'error-cant-sign-message-offline', 'search-contacts', 'unknown-address', 'link-card', 'contacts-group-new-chat', 'wallet-set-up-title', 'reset-default', 'signing-message-phrase-description', 'currency-display-name-gmd', 'status-console', 'currency-display-name-lak', 'buy-with-snt', 'twelve-words-in-correct-order', 'transactions-filter-tokens', 'status-sending', 'default-dapps-exchanges', 'status-not-sent-click', 'specify-bootnode-address', 'empty-chat-description-console', 'tribute-to-talk-sample-text', 'received-invitation', 'delete-chat-action', 'pin-unblocked-description', 'enter-address', 'public-chat-user-count'}

## Acceptance Criteria

Listed strings are not present in the listed files

## Note
unused strings are found by the test test/appium/tests/atomic/test_translations.py

### PR DESCRIPTION
**Pull request by yenda**
@acolytec3 I rebased and fixed your commits here, errors were caused by leftover `,` at the end of some files and extra labels that had not been remove. Also the script you used to remove the labels was leaving empty lines behind so I cleaned that up.

Fixes #8727 

### Summary

Removes all unused strings identified by test/appium/tests/atomic/test_translations.py

### Review notes
I've removed all the unused strings and make test does not produce any errors when run locally.

### Testing notes
Ran make test and have verified that no failures are produced.

##### Non-functional

 -Removes unused strings from translation jsons

### Steps to test

Run make test-auto and verify that all tests pass.

status: Ready for review

### CODE REVIEW

**Comment by yenda** [comment]
@flexsurfer taking this one over so we merge it quickly because otherwise it is going to be an endless cycle of rebase

**Comment by yenda** [comment]
@rachelhamlin how does it work with gitcoinbot it should still send bounty to @acolytec3

**Review by flexsurfer — APPROVED** [review]

**Comment by acolytec3** [comment]
@yenda, thanks! I evidently missed something in the regex matching I was using.  Status is a very different project than I'm used to working on so this has been a challenging but good learning experience for me. Hopefully can contribute in a more meaningful way next go round.  To confirm, I should go ahead and close my other PR?

**Comment by yenda** [comment]
@churik looks like the failed e2e tests aren't related?

@acolytec3 please do not hesitate to provide feedback on how we could make the on boarding easier for first time contributors. Regarding your PR it is already closed.

**Comment by churik** [comment]
@yenda yes, they are not related to this PR.

**Comment by rachelhamlin** [comment]
@yenda I'll take care of it. Usually I wait till PRs are merged. Thanks for helping out.

And @acolytec3 thanks for your first PR! I can point you to some other issues you could get involved in if you're interested.

Something funny is up with Gitcoin right now; our bounties aren't appearing and I'm looking into it. Will get you paid ASAP.

**Comment by acolytec3** [comment]
@rachelhamlin Any luck on figuring the gitcoin issue?  I can see the status bounties when I look at the explorer.

To your other point, would definitely be interested in potentially working some other ones.  Should I just look at the "good first issue" ones for now?

**Comment by rachelhamlin** [comment]
Fixed and paid @acolytec3! Sorry for my delay - we're on our team offsite this week.

I'm going to set up some more urgent bounties shortly, but there are a few open ones that don't have people on them yet and which are important. Would you be interested in any of these?

https://github.com/status-im/status-react/issues/5242
https://github.com/status-im/status-react/issues/7990
https://github.com/status-im/status-react/issues/8443 (adding bounty now)

**Comment by acolytec3** [comment]
Thanks!

I just applied for one of the open ones so looking forward to working on
something else!

**Pull request merged**
