### PR TITLE
[#11046] Add local contact names

### LINKED ISSUE #11046: Add local contact names
## Add local contact names
Source: Roadmap planning workshop item #37 and [Discuss](https://discuss.status.im/t/add-local-contact-names/1789)

### User stories
- As a user, I want to add a nickname to my contacts so that I don’t get confused about who I’m chatting to or struggle to find the person I want to chat with in my contact list.

#### Use cases
- Add local name in `Contacts`
- View local name in chat
- View local name in chat list
- View local name in notifications
- View local name in user profile
- View local name in contact list

Preliminary [designs](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4067%3A2905)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #11046

### CODE REVIEW

**Comment by errorists** [comment]
the iOS build is already gone :(

**Comment by flexsurfer** [comment]
@errorists restarted

**Comment by churik** [comment]
### ISSUE 1: ENS names are not shown in profile details popup
**Steps:**
- join to #status chat
- tap on profile photo of any user with ENS > Profile details

**Expected result:**
ENS name is shown
**Actual result:**
no ens name

**Comment by errorists** [comment]
@flexsurfer you might've skipped my comment in Figma. 

IMG_1625

here let's remove the second, greyed out username
so it's either
Nickname or ENS username or 3W, not both

---

After pressing 'Add to contacts' I wanted the snack bar to persist for 4 seconds and show the 'Add nickname' button. If no action is taken it disappears after 4 seconds. [Figma](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=5004%3A18819)

Screenshot 2020-08-24 at 12 23 08


--- 

In the profile list item, if there's no nickname set it should say 'None' [Figma](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4067%3A2905)

---

It should be possible to tap 'Done' on an empty input field, this way clearing any nickname and setting it to 'None'

---

the profile details list item is empty for me

IMG_1627

**Comment by churik** [comment]
@errorists what is preffered length of username?
Probably better to restrict it to avoid this?
IMAGE 2020-08-24 12:35:15

**Comment by errorists** [comment]
yea, I'm starting to think we should put a cap on number of characters so it doesn't get out of hand. wdyt, 32 chars max?

Screenshot 2020-08-24 at 12 41 36

**Comment by churik** [comment]
### ISSUE 2: No nicknames in group chats during chat creation and for system messages
**Steps:**
- set nickname for some contact
- create group chat with that contact

**Expected result:** nicknames are using everywhere
**Actual result:**  Nicknames are not using for contact list, for system messages 

IMAGE 2020-08-24 13:06:27
IMAGE 2020-08-24 13:59:16

**Comment by churik** [comment]
### ISSUE 3: No ENS name is shown in ENS usernames after setting it up
**Steps:**
- set ENS name in  Profile > ENS usernames
- Go back and reopen ENS usernames

**Expected result:** no ENS-username is shown under message
**Actual result:**  
Monosnap 2020-08-24 14-37-05

**Comment by churik** [comment]
### ISSUE 4: Can't search for nicknames
**Steps:**
- set nickname for some contact
- open home view and try to search for chat using nickname

**Expected result:** chat is shown
**Actual result:**  no results

**Comment by churik** [comment]
### ISSUE 5: Blocked usernames list show only chat keys
**Steps:**
- block any user
- open contacts > Blocked users

**Expected result:** nicknames, 3-random or ENS names are shown
**Actual result:**  
IMAGE 2020-08-24 16:09:33

**Comment by flexsurfer** [comment]
@churik thanks! all should be fixed now

**Comment by hesterbruikman** [comment]
@flexsurfer great work! 

Sorry to add one more: Group chat member list view
(In example below Loose Golden Snake has a nickname)
Screenshot_20200827-130037_Status PR

**Comment by flexsurfer** [comment]
thanks Hester, and I'm falling into a rabbit hole, found more and more places :)

**Comment by flexsurfer** [comment]
fixed

**Comment by hesterbruikman** [comment]
fyi, if we can merge this by tomorrow it can go along in release 1.7

**Comment by flexsurfer** [comment]
latest build has failed :( can't be tested yet

**Comment by flexsurfer** [comment]
ok , can be tested now

**Comment by churik** [comment]
@flexsurfer 
### ISSUE 6: Empty profile details for users with ENS names

IMAGE 2020-08-31 14:28:07
Steps:
- start 1-1 with ENS name ( + > Start new chat > type ENS, i.e. `sergey`)
- navigate to user profile through  chat header

**Comment by churik** [comment]
@flexsurfer 
https://github.com/status-im/status-react/pull/11106#issuecomment-679046301
>  After pressing 'Add to contacts' I wanted the snack bar to persist for 4 seconds and show the 'Add nickname' button. If no action is taken it disappears after 4 seconds

this will be added separately?

**Comment by errorists** [comment]
@churik absolutely, that's cool, it's very much the definition of a 'nice to have'

**Comment by flexsurfer** [comment]
thanks @churik issue 6 fixed, Add to contacts will be added separately

**Comment by churik** [comment]
@flexsurfer 
which is the best approach when user with nickname is removed from contacts?
In that case 'Nickname' is preserved but it is not very clear that it is nickname, as the field is hidden.
IMAGE 2020-08-31 18:12:48

**Comment by flexsurfer** [comment]
@errorists ,hm i think we need to remove nickname if user is removed from contacts, wdyt ?

**Comment by errorists** [comment]
@flexsurfer why do you think so? nicknames are independent of whether you're contacts with someone or not, you can assign nicknames to people without adding them to contacts

**Comment by churik** [comment]
@errorists currently if user is not added to contacts, Nickname is not shown.
From my POV it sounds great to add nicknames regardless of user is added to contacts or not, I was just under impression that it is by design

**Comment by errorists** [comment]
@churik thank you, if we were to proceed with having nicknames only for contacts then I'd need to change the design, basically it would be a next step in 'Add to contacts' button. 
Can we confirm first if nicknames can be shown regardless of contact status?

**Comment by qoqobolo** [comment]
### ISSUE 7: Nickname removed after tapping "Done" without making any changes

If nickname has already been set before, and if open the nickname screen, and tap Done without making any changes, nickname will be removed.

#### Expected behavior
Nickname isn't removed after tapping Done.

#### Actual behavior: 

ezgif com-resize (6)

**Comment by flexsurfer** [comment]
@churik all comments issues addressed , thanks

**Comment by churik** [comment]
### ISSUE 8: after removing nickname it is not synced on paired device
*Steps:*
- device 1: pair device with device 2
- device 1: add contact and set nickname
- device 2: check that contact with nickname is shown
- device 1: open the same contact, clear value and tap on done
- device 2: check contact

*Expected result:*
nickname is removed for contact on both devices

*Actual result:*
nickname is not removed on paired device
Note: all fine if changing nickname

### ISSUE 9: no restrictions for char amount if adding contact through Add new contact > Nickname
Expected 32 chars, the same as for nickname field

**Comment by flexsurfer** [comment]
thanks @churik 8 and 9 have been fixed

**Comment by qoqobolo** [comment]
### ISSUE 10: Blank values in the member list of group chat if open it as a member (not admin).

_Steps:_

- Device1: Add several users to contacts, including Device2, and create a group chat with them;
- Device2: Open this group chat -> Tap three dots on the top right -> Tap "Group info" -> Check the member list


ezgif com-resize (7)

**Comment by flexsurfer** [comment]
thanks @qoqobolo fixed

**Comment by flexsurfer** [comment]
ios is failed because of certificate

**Review by cammellos — APPROVED** [review]

**Comment by flexsurfer** [comment]
ios fail not related to this PR, so android build can be tested

**Comment by flexsurfer** [comment]
ios build succeed

**Pull request merged**
