### PR TITLE
Add Bloom token

### PR DESCRIPTION
**Pull request by m0ar**
### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
The wallet doesn't support the Bloom token (BLT). This PR adds it. 

### Review notes (optional):
The icons are missing since I couldn't find a graphical resources pack from Bloom. Can we roll with the default for now?

status: ready

### CODE REVIEW

**Comment by hesterbruikman** [comment]
@goranjovic anything blocking here?

@m0ar could you please add an a screenshot to the thread here?

**Comment by oskarth** [comment]
@m0ar  Thanks for your patience and contributions!

@goranjovic Please lets try to follow what we agreed upon here https://github.com/status-im/status-react/blob/develop/doc/decisions/0011-tweak-pr-process.md and make sure reviews happen in a timely manner. If you are unable to review, please request some other contributors.

**Comment by m0ar** [comment]
@hesterbruikman A screenshot of what exactly?

**Review by goranjovic — APPROVED** [review]

**Comment by hesterbruikman** [comment]
> 
> 
> @hesterbruikman A screenshot of what exactly?

Wasn't sure what you meant with default token. Can you update to this one?
BLT

**Comment by m0ar** [comment]
@hesterbruikman That I did find, but it's also both low-res and only in one size. Was afraid it'd look awful in the app? If you still want to, I'll include it in the PR :)

**Comment by hesterbruikman** [comment]
@m0ar I created this one. 'Should' be the same as other tokens in the wallet. Let me know if you see a difference compared to other tokens, I can provide other dimensions and formats.

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@hesterbruikman we have other tokens without icons as well.
What's now - we can merge without icon or should wait for an icon?

@m0ar
Can you please rebase it to current develop?

**Review by yenda — APPROVED** [review]

**Comment by hesterbruikman** [comment]
> @hesterbruikman we have other tokens without icons as well.

I'd rather have the icon included now. At the moment it's ok that we have more tokens with default icons as people add them and are therefore more aware of what they are looking for. When we expand features of wallet in the coming months this is not necessarily the case.

@m0ar: I'll contact Bloom to see if we can get a better image from them.

**Comment by m0ar** [comment]
@churik Rebase done :ok_hand:

**Comment by churik** [comment]
@hesterbruikman any news on icon?

**Comment by asemiankevich** [comment]
@m0ar Edvard, could you please rebase again? Seems this PR was in queue for a long time . Thanks!

**Comment by m0ar** [comment]
@asemiankevich Rebase done :heavy_check_mark:

**Comment by hesterbruikman** [comment]
@m0ar does either of these images work for you? Vector based an bigger.

BLT@3x
BLT@2x

**Comment by m0ar** [comment]
@hesterbruikman Nice, thanks. Added!

**Comment by churik** [comment]
@hesterbruikman I'm not sure that we can leave icon without border. All other tokens have grey margin.
dskkkjkkj

What do you think?

**Comment by hesterbruikman** [comment]
Good catch @churik 

Gave it the tiniest bit of Bloom background and a .5 border. Can you please update @m0ar?

BLT@2x
BLT@3x

**Comment by churik** [comment]
@m0ar can you please replace icon?
Thanks for your patience!

**Comment by m0ar** [comment]
@churik Haha, sure. All done.

Sorry for anyone who got a code-owner auto review call, screwed up a rebase somehow but I've fixed it now.

**Comment by churik** [comment]
Tested on IOS 11.4.1 (IPhone 7), Android 8 (LG V20):
- bloom token is added
- can enable it in assets
- verified that data matches https://etherscan.io/token/0x107c4504cd79c5d2696ea0030a8dd4e92601b82e
- verified that token is listed in https://www.cryptocompare.com/

**Comment by flexsurfer** [comment]
sorry @m0ar , could you squash commits please

**Comment by m0ar** [comment]
@flexsurfer All done :blush:

**Pull request merged**
