### PR TITLE
[DO NOT MERGE!][8566] Feature - Build v1.0 banner & modal to highlight breaking change

### LINKED ISSUE #8566: Build v1.0 banner & modal to highlight breaking change
### User Story

As a user, I want to receive a heads up about what I can do to prepare for breaking changes coming in the public release (v1.0) later this year, so that I don't lose any of my funds.

### Description

*Type*: Feature

*Summary*:
In v1.0, we're forcing users to create new Status 'accounts' on our new key structure - separating the Whisper ID and wallet ID. No Whisper data (contacts, messages) from a beta version of Status can be recovered.

A user _can_ recover their Ethereum address & any funds associated by recovering their seed phrase. Any user that owns an ENS name must have the seed phrase of the associated address in order to recover that as well.

In our final beta release, v0.14.0, we'll notify users of these impending changes. Users who have lost their seed phrase should transfer funds to another wallet ahead of v1.0.

#### Expected behavior

Banner and modal alert users that they need to have their seed phrase in order to recover their wallet + ENS name when v1.0 is launched.

[Figma designs](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=2591%3A22425)

- Banner should persist across all tabs (chat, wallet, etc.).
- If the user taps, the modal is opened.
- Once the user closes the banner or modal, it is gone unless they delete and re-install.

Note: Minor copy changes might be required. Mention of sticker market in list of `What's new` depends on whether that work will be included in this pending release. @rachelhamlin to follow up.

#### Actual behavior

No warning to users exists yet.

### PR DESCRIPTION
**Pull request by bitsikka**
Fixes #8566

### Summary
- Given the temporary nature of this feature, all new styles were applied inline instead of separating them in separate styles namespace
- Image assets were optimized using https://github.com/chrissimpkins/Crunch
- TODO: Link
- Target branch set to release/0.14.x
### Testing
Tested in iOS only

status: ready for review

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
@bitsikka please run `lein cljfmt check` locally and fix formatting, when rebasing, don't forget to rebase onto release, not develop, thanks

**Comment by bitsikka** [comment]
> @bitsikka please run `lein cljfmt check` locally and fix formatting, when rebasing, don't forget to rebase onto release, not develop, thanks

@flexsurfer done!

**Comment by asemiankevich** [comment]
@bitsikka i now can see [Search] bar is enabled after V1 banner is closed. It does not happen in nightly (search is not enabled by default ). Could you please take a look?

image

**Comment by bitsikka** [comment]
> @bitsikka i now can see [Search] bar is enabled after V1 banner is closed. It does not happen in nightly (search is not enabled by default ). Could you please take a look?
> 

@asemiankevich there are definitely bugs related to search bar. In nightly, search bar gets activated unintentionally, when you delete chat by long pressing on chat in home screen as well. I discovered the long-press-delete search-bar activation bug in https://github.com/status-im/status-react/pull/8589#issuecomment-512364989.

I have fixed the discovered issue (and other subtle search-bar related issues) in #8589 PR as it was entangled with that issue. Since issue that #8589 fixes is also release tagged issue, I'm hoping once we merge that and this PR, this issue(I'm positively sure) will go away.

**Comment by asemiankevich** [comment]
> > @bitsikka i now can see [Search] bar is enabled after V1 banner is closed. It does not happen in nightly (search is not enabled by default ). Could you please take a look?
> 
> @asemiankevich there are definitely bugs related to search bar. In nightly, search bar gets activated unintentionally, when you delete chat by long pressing on chat in home screen as well. I discovered the long-press-delete search-bar activation bug in [#8589 (comment)](https://github.com/status-im/status-react/pull/8589#issuecomment-512364989).
> 
> I have fixed the discovered issue (and other subtle search-bar related issues) in #8589 PR as it was entangled with that issue. Since issue that #8589 fixes is also release tagged issue, I'm hoping once we merge that and this PR, this issue(I'm positively sure) will go away.

thanks for clarifying that

**Comment by asemiankevich** [comment]
@Serhy @yevh-berdnyk could you please take a look into 2 failed tests?

**Comment by Serhy** [comment]
test_public_chat_messaging failed because rebase is required (https://github.com/status-im/status-react/commit/9fa964a8eda7a05686abaedebe37dd9969cb0032)
test_manage_assets failed because due to 'build v1.0 banner' we need to scroll to the top to access 'AccountsMoreOptions' the second time.

Manually tests passing. No worries, since it's "temp" feature (for release 0.14 only) I'll take a look at it separately, not in this PR. 

This one looks good from me to merge.

**Pull request merged**
