### PR TITLE
Add safearea for Android and remove statusbar component

### PR DESCRIPTION
**Pull request by flexsurfer**
new safearea component manages statusbar area as well, so we don't need empty view anymore, and status-bar component has been removed

DEMO: https://www.youtube.com/watch?v=0k3hjC4HrEI

for QA: test all screens on different devices with a notch and without, and make sure all screens look great!

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by flexsurfer** [comment]
@churik @Serhy could you please take this one ?

**Comment by Serhy** [comment]
Tested Android 8.1 (Samsung J7), Android 6.0.1 (Note 4) and iOS 13 (iPhoneX)
There is only one issue:

On `Wallet view` -> `Send` -> `Select recipient` -> `Scan QR code` device status bar is blank white (vs nightly where device status bar transparent and all items are visible). And also status bar on this screen apparently narrowed down camera view so focus area became rectangular (vs square like on nightly build view)
 
Screenshot 2019-11-25 at 14 20 26

**Comment by flexsurfer** [comment]
thanks @Serhy , qr screen will be fixed here https://github.com/status-im/status-react/pull/9499

**Comment by Serhy** [comment]
test_contact_profile_view will be fixed separately.
Lets' merge, @flexsurfer, thanks!

**Pull request merged**
