### PR TITLE
Update Arabic, French, Korean, Italian, and Chinese translations

### PR DESCRIPTION
**Pull request by jinhojang6**
Reviews WIP with the translators below

A big shout out to:

Italian - Enrico Del Fante, Solexplorer
Chinese - Steven

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]

**Comment by jinhojang6** [comment]
@jakubgs it doesn't build mobile apps now, which worked well about an hour ago.

**Comment by jakubgs** [comment]
It's just a Nix cache error:
```
warning: unable to download 'https://nix-cache.status.im/46h6r7f9v52h073l2nzs00kk7s47zkrj.narinfo': HTTP error 502; retrying in 254 ms
```
I was resizing the volume at the time. Try amending the commit without any changes and force pushing again.

**Comment by jinhojang6** [comment]
only iOS build failed

**Comment by jakubgs** [comment]
Yeah, `nightly` build failed the same way, so I don't think it's because of anything in this branch:
https://ci.status.im/blue/organizations/jenkins/status-react%2Fcombined%2Fmobile-ios/detail/mobile-ios/7153/pipeline
It's probably an issue in the CI itself, or `develop`.

**Comment by flexsurfer** [comment]
@jinhojang6 if we have only one Chinese translation may be better to use root key `:zh` for it instead of  `zh_Hans_CN` , wdyt ?

**Comment by jinhojang6** [comment]
@flexsurfer Good idea and it is much better for me, do you mean having a single translation file, `zh.json`?

**Comment by flexsurfer** [comment]
@jinhojang6 i've added zh support, please try

**Comment by jinhojang6** [comment]
@flexsurfer It shows still English. Checked it with a Chinese community member as well.

**Comment by flexsurfer** [comment]
@jinhojang6 weird, this build 0bff3cb ? it shows Chinese for me

**Comment by flexsurfer** [comment]
@jinhojang6 I've removed all other Chinese translations, and only kept zh one, let's try

**Comment by jinhojang6** [comment]
Awesome! `b951ebd` works @flexsurfer

**Comment by jinhojang6** [comment]
@flexsurfer Can we merge this pull request?

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
It's not tested manually, e2e failures are not related to this PR.

**Pull request merged**
