### PR TITLE
[#8877] account balance is not recalculated

### LINKED ISSUE #8877: Account balance is not recalculated without relogin if sending all available tokens amount
# Problem

I have ETH > 0 to pay for gas
I have 100 STT on my balance for Status account
I have Account 1 added to my multiaccount

If i send 1000 STT (all the amount i have) from Status account to my Account 1, i can see the that amount is duplicated in Total balance, as well as Status account is not deducted with this 1000 STT.

image

## Steps

- open status
- switch to ropsten
- add account1 to multiaccount
- faucet ETH and STT in simpledapp.eth
- send 1000 STT from Status account to Account 1 and wait for txn to be mined
- check: total balance, Status account balance, Account 1 balance

**NOTE: the balance is correct after user logs out and log in back**

## Expected result

1. status account is deducted with 1000 STT
2. account 1 is debited with 1000 STT
3. total STT value is 1000 for multiaccount

## Notes

build: nightly 30-Aug-2019
device: Huawei P10 Lite, Android 8

### PR DESCRIPTION
**Pull request by tbenr**
fixes #8877 

I moved the `pos?` check  in the inner `if`, so it should honor the function doc

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by tbenr** [comment]
@churik do i need to rebase to fix e2e?

**Comment by churik** [comment]
@tbenr 
in all builds error after login:
"Cannot read property 'g' of null"
Logs / Video: https://saucelabs.com/jobs/a017749510b54969965d933a8fb3f80c?auth=e89e505b348e96ad52e1ec7b586844f1

Not sure that rebasing can help here.
Thanks!

**Comment by tbenr** [comment]
@churik ok let me check

**Comment by tbenr** [comment]
@churik should be fixed now. You can rerun e2e.

**Comment by churik** [comment]
failed e2e are due to missing accessibility-id, so not related to PR.

There is one issue that is not presented in current develop - balance is not updated after sending transaction

Steps:
- create multiaccount
- switch to Ropsten
- request ETHro  from status-im.github.io/dapp
- request STT  from status-im.github.io/dapp
- send STT to any address
- wait until the transaction is completed 
- wait in Status

Expected result:
wallet balance is updated
Actual result:
individual and overall balance remains the same until relogin

**Comment by tbenr** [comment]
@churik cannot replicate https://youtu.be/Z-IaCidUbzE
i did also tests with a physical android device with no issues...

**Comment by churik** [comment]
@tbenr you are right, sorry for false alarm - I didn't think that https://github.com/status-im/status-react/issues/9361 is platfrom-version specific.
Will recheck your PR shortly.

**Comment by churik** [comment]
Issue is fixed on both Android and IOS

**Pull request merged**
