### PR TITLE
Add members key to the chat-preview flow to show count of members on chat preview

### LINKED ISSUE #14271: 0 members in group chat and chat input is not shown in group chat after re-login
# Bug Report

## Problem 
After the successful creation of a group chat and exchanging messages, there are no members and no message input in the chat view after re-login

https://user-images.githubusercontent.com/4557972/198600333-21cb9bbb-d0c9-4313-9160-b4080c5ca862.mp4

#### Expected behavior
- 2 members
- when opening group chat, can see chat input

#### Actual behavior
- 0 members (IOS, Android)
- no chat input (Android)

### Reproduction
**Prerequisites:** User A and User B are mutual contacts

1) User A: open group chat with User B, send couple of messages
2) User A: relogin

### Additional Information

- Status version: nightly 28/10/22 (appeared earlier)
- Operating System: Android, iOS (partially)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #14271 

status: ready

### CODE REVIEW

**Comment by ibrkhalil** [comment]
Can someone please test if this is resolved ?
cc: @churik @qoqobolo

**Comment by churik** [comment]
@ibrkhalil thank you for fix!
Tested basic flows, LGTM, issue is fixed

**Devices:**
- IPhone 12 Mini (IOS 15)
- Xiaomi Mi Note 9 Pro (Android 10)

**Comment by ibrkhalil** [comment]
> @ibrkhalil thank you for fix!
> 
> Tested basic flows, LGTM, issue is fixed
> 
> 
> 
> **Devices:**
> 
> - IPhone 12 Mini (IOS 15)
> 
> - Xiaomi Mi Note 9 Pro (Android 10)

Thank you so much Tetiana 🙏🏻

**Review by yqrashawn — APPROVED** [review]
LGTM! :thumbsup:

**Pull request merged**
