### PR TITLE
Update token icons

### PR DESCRIPTION
**Pull request by Ferossgp**

### CODE REVIEW

**Comment by flexsurfer** [comment]
could you please fix formatting? btw do we have an issue ?

**Comment by Ferossgp** [comment]
@flexsurfer what problem with formatting? 
There is an issue https://github.com/status-im/status-react/issues/10283 but it is broader, in this PR it is just a small patch to add for now just new icons

**Comment by flexsurfer** [comment]
@Ferossgp formatting is ok
> in this PR it is just a small patch to add for now just new icons

but I can see you also have added new tokens not only icons ?

**Comment by Ferossgp** [comment]
Yes, I added new tokens from the icon pack which @simonricoo has sent to me

**Review by simonricoo — CHANGES_REQUESTED** [review]
1. Please, delete 1px boarder on ETH (only appears on ETH token IMG)
scrrenshot-2
2. RLC token appears 4 times in the list. Aren't these the same token? 
IMG_4516-2

**Comment by Ferossgp** [comment]
@simonricoo fixed

**Comment by flexsurfer** [comment]
@andremedeiros @corpetty @hesterbruikman i'm not sure who should approve new tokens addition?

**Comment by hesterbruikman** [comment]
If we can technically support them, I see no reason not to. I wonder if we have all addresses though. @Ferossgp have you added those? Could you find them?

**Comment by Ferossgp** [comment]
@hesterbruikman yes, I've written a script which automatically pulled info based on file name

**Comment by hesterbruikman** [comment]
We do need a process for this going forward 🤔, but we can tackle that in #10283. Happy to see this merged, but let's wait for @corpetty and/or @andremedeiros in case we need any security checks on addresses

**Review by simonricoo — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Pull request merged**
