### PR TITLE
Fix failed tests for navigation

### PR DESCRIPTION
**Pull request by Ferossgp**

### CODE REVIEW

**Review by Serhy — APPROVED** [review]

**Comment by Serhy** [comment]
E2E passed. 
Manually with iOS13.3 and Android 8 looks good to me.

**Comment by churik** [comment]
Tested creating account with kk and recovering accout with keycard (pairing)
After recovering app redirects to empty screen, but after switching to other tab and going back to chat it is OK.
photo_2020-03-18 12 31 26

Can be reported separately I believe, because it fixes https://github.com/status-im/status-react/issues/10178 - blocker for KK.

WDYT @Ferossgp?

**Review by churik — APPROVED** [review]

**Comment by rasom** [comment]
@Ferossgp @churik @Serhy are failed tests related to PR?

**Comment by churik** [comment]
@rasom  yes, we are on it

**Comment by Serhy** [comment]
Looks good to me with Android 8 and Android 8  and iOS. 
Can't reproduce `The 'navigation' object hasn't been initialised yet....` crash error (neither autotests can)

**Pull request merged**
