### PR TITLE
Add support for SAI/DAI

### LINKED ISSUE #9491: Support for multicollateral DAI
# Problem

Multi-collateral DAI launched on November 18th. Changes to the DAI token are required to support this shift.

## Implementation

- The current DAI token is now 'single collateral DAI' and should be renamed to `SAI`. 
- In addition to `SAI`, we should add the new `DAI` to our hardcoded token list. 
- The address for multi-collateral `DAI` is [0x6b175474e89094c44da98b954eedeac495271d0f](https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f)
- The image assets are found [HERE](https://www.notion.so/Maker-Brand-ac517c82ff9a43089d0db5bb2ee045a4)

## Acceptance Criteria

Status default assets list should include both DAI and SAI with the appropriate addresses & logo images.

Other wallets are representing DAI and SAI like so:
image

## Notes

- [Link to full migration guide from Maker](https://github.com/makerdao/developerguides/blob/master/mcd/upgrading-to-multi-collateral-dai/upgrading-to-multi-collateral-dai.md#as-a-non-custodial-wallet)
- Status will not have a publicly available update for SAI until version 1 is released in early January.

### PR DESCRIPTION
**Pull request by acolytec3**
Fixes #9491 

### Summary

Adds support for Multicollateral DAI and renames single collateral DAI to SAI

### Review notes
Make sure to look at the new DAI icons and make sure they look right.  I used GIMP to resize the provided DAI badge to the right pixel sizes but want to make sure there aren't any distortions.

#### Platforms
- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

1. Open Status
2. Go to Wallet screen
3. Tap "..." in upper right corner and select Manage Assets from the Bottom Sheet
4.  Add DAI and SAI to Assets and verify that they appear in the Wallet

status: ready 

Screenshot_20191119-210157

### CODE REVIEW

**Review by errorists — APPROVED** [review]
I added the requested assets [here](https://github.com/status-im/status-react/issues/9491#issuecomment-555906212) but those you used look correct too, there's so many versions of the SAI badge circling around I can't tell which one is 'right'.

**Comment by acolytec3** [comment]
> I added the requested assets [here](https://github.com/status-im/status-react/issues/9491#issuecomment-555906212) but those you used look correct too, there's so many versions of the SAI badge circling around I can't tell which one is 'right'.

Thanks!  I'll use yours just to be safe.  Never trust a newb with GIMP to get the pixel count right! :)

**Comment by acolytec3** [comment]
Here's what it looks like with the new PNGs from @errorists. 
Screenshot_20191120-054843

**Review by flexsurfer — APPROVED** [review]

**Comment by acolytec3** [comment]
@flexsurfer @3esmit See the error logs.  It's complaining about the name for DAI not matching what's being returned by the contract-name?  Presumably this just means that Maker set the `name` method in the contract to "Dai Stablecoin".  I assume we want this to match what we display in the app, right?  If so, I'll update for both DAI and SAI since looks like they updated the name of the SAI contract too.

**Comment by acolytec3** [comment]
@flexsurfer Went ahead and updated the token names based on what Etherscan provided.

**Review by 3esmit — APPROVED** [review]
Everything looks good. I checked the addresses and decimals, all looks good.

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
Tested on IOS 13 (IPhone 11) and on Android 8.1 (Samsung Galaxy S9)
Looks good to me.

**Pull request merged**
