### PR TITLE
Send logs on shaking device

### PR DESCRIPTION
**Pull request by rasom**
review only the last commit, merge after #8133 

status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by churik** [comment]
@rasom 
several questions / issues:
#### 1) Can't get dialog on shaking device (Android 8 (LG V20))
**Steps:**
- create account
- shake device

**Expected result:** get dialog about sending logs
**Actual result:** debug console is shown. Switched `Debug` mode on my phone and can't get this console in nightly - so I believe it is in-app for `Status PR`
sfdsfsdfsdfsfgfdgfg

So not sure how I can get `.apk` for testing.

#### 2) If a dialog appears on other popup, it moves on the corner of the screen after getting back to app 
**Steps:**
- create account
- when beta alert is still shown, shake device
- send logs
- get back to the app

**Expected result:** beta alert didn't change position
**Actual result:** 
sdfsdfsddfsdsf
**OS:** IOS 11.4.1 (IPhone 7)
This issue also can be reproduced on `develop` after sending logs when see error. 
Here it becomes more visible, so I suggest to fix it here before merging this PR.

#### 3) Can't send logs twice in a row until logout

**Steps:**
- create account
- shake device
- send logs
- get back to the app
- shake device again

**Expected result:** get dialog about sending logs
**Actual result:** no dialog is shown until you relogin, after this can trigger dialog again.
**OS:** IOS 11.4.1 (IPhone 7)

**Comment by mandrigin** [comment]
@churik @annadanchenko this one either is worth adding to 0.13.0 or making 0.13.1... that's a marketable feature.

**Comment by rasom** [comment]
I can switch to this task later today

**Comment by rasom** [comment]
@churik all issues should be fixed now

**Comment by asemiankevich** [comment]
@rasom 

`could not attach file` shown when i shake device -> select gmail -> email body is opened. Reproduced on Android 7 and 8.

image

Please, take a look

**Comment by rasom** [comment]
@asemiankevich and it works just fine in nightly, right?

**Comment by rasom** [comment]
I mean sending logs using button in profile

**Comment by asemiankevich** [comment]
> @asemiankevich and it works just fine in nightly, right?

no :( just checked in nightly , it is there too , sorry. Will add separately.

**Comment by rasom** [comment]
@asemiankevich I'm also not sure it is related specifically to os version, it might be related to specific devices. I tested it on 6 and 8 during development and it worked on both (galaxy a500d and galaxy s9). I have s9 with android 9 now and it works there too.

**Comment by asemiankevich** [comment]
> @asemiankevich I'm also not sure it is related specifically to os version, it might be related to specific devices. I tested it on 6 and 8 during development and it worked on both (galaxy a500d and galaxy s9). I have s9 with android 9 now and it works there too.

true, it could be related to the devices i am testing on only

**Comment by annadanchenko** [comment]
@rasom @mandrigin please, do not include it in the release yet. We need to investigate how many other devices are getting https://github.com/status-im/status-react/issues/8276 - if most of them are affedcted there is no point to add shake to release and announce the feature widely

**Pull request merged**
