### PR TITLE
nix: upgrade Gems, Pods, and Gradle dependencies

### PR DESCRIPTION
**Pull request by jakubgs**
Upgrade all deps to simplify debugging of https://github.com/status-im/status-react/pull/13303.

Looks like some things were missed, like removal of `react-native-dark-mode` or addition of `react-native-randombytes` to `nix/deps/gradle/proj.list`.

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by jakubgs** [comment]
Looks like the package upgrades broke a bunch of stuff. That's not good.

**Comment by jakubgs** [comment]
Looks like the app gets stuck at login with the `Just a moment` spinner. New account creation works just fine though.

Here's the log for the failure to log in: https://gist.github.com/jakubgs/fd5b9683f5811d1dd6862725e95383ff

**Comment by jakubgs** [comment]
I started a PR build of `develop` to see if this issue is present there too: https://ci.status.im/job/status-react/job/manual/231/

**Comment by jakubgs** [comment]
I installed a [`develop` build](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-Mobile-220426-105055-acf7d1-pr-universal.apk) but it has the same issue, account creation works, but logins gets stuck on `Just a moment` spinner.

@cammellos it appears `develop` branch is broken.

**Pull request merged**
