### PR TITLE
[#8548] No 'Paste' native Android option on longtap in the app input …

### LINKED ISSUE #8548: No 'Paste' native Android option on longtap in the app input fields (conract-code, wallet recipient address etc)
***Type***: Bug

***Summary***: Some of the input fields of the mobile app on Android does not show native Android `Paste-Clipboard-Select_All` dialogue.
In the URL browser and message input box - it's shown on the long tap fine, but the same doesn't work with:
- `Chats` -> `Start new chat` -> long tap in `Enter contact code` field
- `Profile` -> `Mailserver` -> `+` -> long tap in `Mailserver address` and name fields
- `Profile` -> `Extension` -> `+` ->  long tap in `Enter extension URL`
- `Profile` -> `Bottnode` -> `+` ->  long tap in `Bootnode address`
- `Wallet` -> `Status account` -> `Send` -> `Specify recipient` -> `Enter recipient address` -> long tap to paste the address 

Everything is OK on iOS 

#### Expected behavior
Native Android `Paste-Clipboard-Select_All` dialogue appears on long tap in the app input fields 

#### Actual behavior
No native Android `Paste-Clipboard-Select_All` dialogue appears on long tap in the app input fields 

### Reproduction

- Open Status and create new account
- Navigate to `Chats` -> `+` -> `Start new chat`
- Put cursor in `Enter conntact code or username` field
- Make a long tap (>1s) in this field

### Additional Information
- Status version: Develop 0.14.0 (nightly 9th of July)
- Operating System: Android

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
07-10 11:28:15.628 24266 24266 D ViewRootImpl@e1088cc[MainActivity]: ViewPostIme pointer 0
07-10 11:28:16.130 24266 24266 D TextView: performLongClick() is called
07-10 11:28:16.130 24266 24266 D TextView: handled is false
07-10 11:28:16.131 24266 24266 W TextView: TextView does not support text selection. Selection cancelled.
07-10 11:28:17.250 24266 24266 D ViewRootImpl@e1088cc[MainActivity]: ViewPostIme pointer 1
```

### PR DESCRIPTION
**Pull request by flexsurfer**
QA: Implemeted workaround only for chats and wallet

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Review by yenda — CHANGES_REQUESTED** [review]
Since it is a workaround I think it is better to have it in one place, I would suggest to rewrite `react/text-input` so that it includes the workaround wdyt?

**Comment by flexsurfer** [comment]
@yenda i hope it's temporary, and will be fixed with a react-native update, I just want to unblock QA for now

**Comment by flexsurfer** [comment]
so i just want to fix locally two input fields, don't want to affect all test inputs

**Comment by asemiankevich** [comment]
@flexsurfer android build was not built

**Comment by flexsurfer** [comment]
@asemiankevich restarted

**Comment by asemiankevich** [comment]
Paste option is back for chats and wallet thank Andrey. 

Please check this: it happens when i create group chat.

image

@flexsurfer

**Comment by flexsurfer** [comment]
@cammellos i believe it's in develop ?

**Comment by asemiankevich** [comment]
i still can reproduce the issue in this PR, but not in nightly https://ci.status.im/job/status-react/job/nightly/1221/

**Review by yenda — APPROVED** [review]

**Comment by flexsurfer** [comment]
removed https://github.com/status-im/status-react/issues/8548 from the description, let's do not close it, just to fix it properly later

**Pull request merged**
