### PR TITLE
replace camera library

### PR DESCRIPTION
**Pull request by flexsurfer**
replace camera library https://github.com/status-im/status-react/issues/11010

### CODE REVIEW

**Comment by hesterbruikman** [comment]
@flexsurfer does this library change how camera permissions are handled on Android?
regarding: https://github.com/status-im/security-reports/issues/24 cc @vkjr

**Comment by flexsurfer** [comment]
@hesterbruikman no it's different components, security report is  related to webview component, and it seems webview has access to device camera, but i can't reproduce on my device btw probably its only on specific android version

**Comment by vkjr** [comment]
@flexsurfer, in order to reproduce it please make sure that you already granted camera access earlier, for example when were scanning qr-code.

**Comment by hesterbruikman** [comment]
@churik 

Tested for basic QR code scanning cases
Tested on Galaxy S10e (Android 10), iPhone 8 (iOS 13), Fairphone 2 (Android 7), Fairphone 3 (Android 8 - no Google services)
Found no issues

- [x] Start new chat > Scan chat key
- [x] Start new chat > Scan ENS name
- [x] Wallet > Send > Select recipient > Scan wallet address
- [x] Wallet > Scan wallet address
- [x] Wallet > Scan chat key >  `error invalid address` (expected)
- [x] Start new chat > Scan Wallet address > `unable to read` (expected)
- [x] Start new chat > Scan chat key Join.status.im 
- [x] Start new chat > Scan ENS name Join.status.im 
- [x] Wallet > Scan ENS name Join.status.im >  `error invalid address` (expected)

**Review by hesterbruikman — APPROVED** [review]
Thanks for the swift action @flexsurfer!

**Comment by churik** [comment]
@flexsurfer can you rebase it please and we'll take in testing?

**Comment by jakubgs** [comment]
So I guess this won't be included in `1.5.0`.

**Comment by churik** [comment]
@jakubgs no, it will not

**Comment by flexsurfer** [comment]
@churik done

**Comment by Serhy** [comment]
Tested on Android 6.0.1 and confirm below scnearios working as expected:
 * Start new chat > Scan chat key
 * Start new chat > Scan ENS name
 * Wallet > Scan wallet address
* Wallet -> Send -> Choose recipient -> Scan public key QR code (error popup as expected)
 * Start new chat > Scan chat key Join.status.im
 * Start new chat > Scan ENS name Join.status.im
 * SimpleDapp -> Status API -> Scan QR

**Comment by churik** [comment]
Tested on Xaiomi Mi Note 9 (Android 10), IPhone 7 (IOS 13), Iphone 6 (IOS 11):
- allowing / denying access to the camera / photos
- scanning QRs from different views: 
1) universal links (chat)
2) EIP links (wallet)

No issues found.

**Pull request merged**
