### PR TITLE
Loading indicator shown when prices loading is in progress

### LINKED ISSUE #8026: [Wallet] Sign transaction module
Implement a new module, it should 

- [x] get tx data map on input
- [x] show title (1)
- [x] show tx details on the bottom sheet (details should be different for sending eth or calling contract (2))
- [x] it's only possible to change one field -  network fee in this module
- [x] sign with password
- [x] show sent popup

this issue doesn't include:
- USD values (3)  https://github.com/status-im/status-react/issues/8027
- sent popup design [GHI]
- tx fee slider [GHI]
- to field details [GHI]
- approveAndCall detection (showing token amount) [GHI]
- prompts for signing phrase, gas and gas price [GHI]

image

### LINKED ISSUE #8443: [#8026] Add loading state for currency conversion
### Description

*Type*: Feature

*Summary*: Continuation of the work done in [this PR](https://github.com/status-im/status-react/pull/8361#issuecomment-500465251) for #8026. 

New overview screen shows fiat values for the total amount + gas. This can sometimes take time to load, so we need to add a loading state.

#### Expected behavior

Designs found here: [preferred implementation](https://github.com/status-im/status-react/issues/8443#issuecomment-504438031), [back-up option](https://github.com/status-im/status-react/issues/8443#issuecomment-528930247) 

When converted currency in the following fields is not yet available, we display a loading state instead.

image
_Loaded currencies_

image
_Preferred design is an in-line animation (see [commen](https://github.com/status-im/status-react/issues/8443#issuecomment-504438031)t)_

### PR DESCRIPTION
**Pull request by vkjr**
fixes #8443 

### Summary

Loading spinner shows instead of fiat value when prices are loading

Screenshot 2020-03-23 at 13 31 19
Screenshot 2020-03-23 at 13 31 37
Screenshot 2020-03-23 at 13 31 24

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by errorists — APPROVED** [review]

**Review by hesterbruikman — APPROVED** [review]
Works like a charm on Android and iOS! Thanks @vkjr

**Comment by Serhy** [comment]
All e2e tests are failing because one valid issue. 
When list of assets are opened while selecting token from `Send transaction` bottom sheet, - there are endless spinners on all assets. And asset is not selectable while there is a spinner. 
It's reproducible on Android 9 for me with the https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200324-144117-aa31e8-pr-universal.apk build

**To reproduce:**
1) Install https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200324-144117-aa31e8-pr-universal.apk build
2) Create new account
3) Open `Wallet` -> `Status account` -> `Send`
4) Tap `ETH` dropdown to see the list of assets and check there is endless spinner
**Actual result:** Endless spinners. Tapping any asset does nothing.
**Expected result:** If on Wallet view Fiat conversion succeeded then the same should be on Asset selection while sending transaction. Also, disregard there is endless spinner or fiat value is shown, - user should be able to select an asset.  

Logcat: 
[LogcatEndlessSpinner.txt](https://github.com/status-im/status-react/files/4380669/fiatendlessspinner.txt)

**Comment by Serhy** [comment]
@vkjr sorry I mistapped and closed this PR. 
Reopened now. 
There is an issue with e2e tests and I reproduced the same on real device Galaxy S8 (Android 9) and Android 8.1: details in https://github.com/status-im/status-react/pull/10196#issuecomment-603797659

**Comment by vkjr** [comment]
@Serhy, thanks, will check!

**Comment by vkjr** [comment]
@Serhy, fixed issue and rebased.

**Comment by Serhy** [comment]
Testing is blocked now by https://github.com/status-im/status-react/issues/10230 issue (which is in develop)

**Comment by Serhy** [comment]
@vkjr could you rebase develop please (that blocker was fixed)

**Comment by vkjr** [comment]
@Serhy, done

**Comment by Serhy** [comment]
Looks good to me on iOS and Android 9 (and Android 8.1)!
Spinners appears upon navigations to views
Updated e2e test test_add_account_to_multiaccount_instance_generate_new so @vkjr please mind my commit when merging.

**Comment by vkjr** [comment]
@Serhy, thanks a lot!

**Pull request merged**
