### PR TITLE
validate links before opening

### PR DESCRIPTION
**Pull request by cammellos**
fixes: https://github.com/status-im/security-reports/issues/10
fixes:  https://github.com/status-im/security-reports/issues/9

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]
I assume this comes from the security tasks, could you add in docstring/comment the explanation for these filters?

**Comment by asemiankevich** [comment]
@cammellos any description would be helpful here

**Comment by cammellos** [comment]
@asemiankevich , sorry I left it blank, I have linked the relevant issues in the description with a description of the fixes, @annadanchenko should have access in case you can't see them

**Comment by yenda** [comment]
@cammellos I don't have access to this repo, I think a comment in the code would be better though, finding back PRs and then an issue in another repo will be tedious for someone who wonders about this code in the future

**Comment by asemiankevich** [comment]
@annadanchenko if you dont mind to help here

**Comment by cammellos** [comment]
@yenda updated with docstrings and comments

**Comment by churik** [comment]
Both issues are not reproducible on Android 8 and IOS 11.4.1

**Pull request merged**
