### PR TITLE
[DEBUG] disable signals

### PR DESCRIPTION
**Pull request by cammellos**

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] **Docs**: Updated the [documentation](https://status.im/build_status/), if affected
- [ ] **Docs**: Added or updated inline comments explaining intention of the code
- [ ] **Tests**: Ensured that all new UI elements have been assigned accessibility IDs
- [ ] **Tests**: Signaled need for E2E tests with label, if applicable
- [ ] **Tests**: Briefly described what was tested and what platforms were used
- [ ] **UI**: In case of UI changes, ensured that UI matches [Figma](https://www.figma.com/)
- [ ] **UI**: In case of UI changes, requested review from a Core UI designer
- [ ] **UI**: In case of UI changes, included screenshots of implementation

**Comment by Serhy** [comment]
Tested the latest build on Galaxy Note 4 (http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-191018-135824-745f5b-pr-universal.apk)

No messages are received by that build, neither from offline inbox nor when two contacts (nightly build and PR build) exchange messages in public chat (but user using nightly develop build receives messages from 745f5b-pr-universal.apk user)

**Comment by cammellos** [comment]
ouch something went wrong, this build was supposed to receive messages, i
will take a look at it Monday

**Comment by cammellos** [comment]
@Serhy this is ready to be tested again, it should receive messages, and should be better then current develop, although it stutters still a bit locally.

**Comment by cammellos** [comment]
@Serhy should be working now, sorry, there was some issues with building production code that I did not address

**Comment by Serhy** [comment]
Latest build, http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-191021-100023-54e761-pr-universal.apk tested, and indeed it's become better. Same scenario repeated 5 times and in average the time of app freezes are ~1.6-1.8 sec when receive 100 text messages from public chat (which ~40-45% faster than develop build!)
That looks great as for me, @cammellos !

**Comment by cammellos** [comment]
@Serhy thanks for the good news! 
Could you try the last one as well (building now) to see if there's any noticeable improvement? (I struggle to tell anymore locally)
Thanks!

**Comment by Serhy** [comment]
@cammellos very last build (https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-191021-133824-792df3-pr-universal.apk) looks definitely better for me! When 100 test messages fetching from offline app may freeze for ~1-1.2 sec which is almost **three** times better than develop! 
That's great result as for me!

**Pull request closed without merging**
