### PR TITLE
[WIP] Change App ID for PR builds of iOS app

### PR DESCRIPTION
**Pull request by jakubgs**
Sister PR to https://github.com/status-im/status-react/pull/7287 for changing App ID of iOS PR builds to `im.status.ethereum.pr`.

I've added the necessary profile in `ios-certificates` repo here: https://github.com/status-im/ios-certificates/commit/6c3104907319a45efc72f05dc98ad1714d4560b3

State: WIP

### CODE REVIEW

**Comment by jakubgs** [comment]
The way I made the `PR` config is by cloning it from `Release` in Xcode and then adding the `xcconfig` files to manage the different values. The issue is, it fails to build due to:
```log
ld: library not found for -lReact
```
It's related to the flags given to `clang`. So my guess would be that the issue is some kind of search path for linking.

**Comment by mandrigin** [comment]
@jakubgs do you need any help with that?

**Comment by jakubgs** [comment]
I kinda put it on hold for a while. Now that the Android one has been fixed I can take a look at it again.

I tried make a separate ID and name using the XCode UI and then look at the changes in the `project.pbxproj`, but I also found this article about using `*.xcconfig` files to hold settings for those:
https://www.appcoda.com/xcconfig-guide/
If we could use those it would be much easier to modify those settings just using a text editor without having to touch XCode.

**Comment by mandrigin** [comment]
@jakubgs yeah, I think we should use it. It is a better approach than doing everything in pbproj file

**Comment by jakubgs** [comment]
My main issue is that `fastlan ios pr` fails with;
```
 ▸ ld: warning: directory not found for option '-L/Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-cemtcnxulcxvltemyqrvchrqxjzr/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/BuildProductsPath/PR-iphoneos/React'
 ▸ ld: library not found for -lReact
 ▸ clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
This must be caused by some of the changes in `ios/StatusIm.xcodeproj/project.pbxproj` but I can't tell which ones. I'm going to try to fix this today.

**Comment by jakubgs** [comment]
Aaaaand we're back to the same old bullshit:
```
00:11:44  ▸ Compiling main.m
00:11:44  ▸ Linking StatusIm
00:11:44  ⚠️  ld: directory not found for option '-L/Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-cemtcnxulcxvltemyqrvchrqxjzr/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/BuildProductsPath/PR-iphoneos/React'
00:11:44  
00:11:44  ❌  ld: library not found for -lReact
00:11:44  ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
00:11:44  
00:11:44  ** ARCHIVE FAILED **
00:11:44  
00:11:44  The following build commands failed:
00:11:44  Ld /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-cemtcnxulcxvltemyqrvchrqxjzr/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/InstallationBuildProductsLocation/Applications/StatusIm.app/StatusIm normal arm64
00:11:44  (1 failure)
00:11:44  [23:11:43]: Exit status: 65
```
every day is a new horror

**Comment by jakubgs** [comment]
As far as I can tell this is related to `React` provided by `pod`:
https://github.com/status-im/status-react/blob/a436793fa0be0220cc0fc934bc1106558d0c4afb/ios/Podfile#L15
and found via `HEADER_SEARCH_PATHS`:
https://github.com/status-im/status-react/blob/a436793fa0be0220cc0fc934bc1106558d0c4afb/ios/StatusIm.xcodeproj/project.pbxproj#L2046-L2049

**Comment by jakubgs** [comment]
So I lookad at what's in `node_modules/react-native/React` and I found this:
```
administrator@macos-03.ms-eu-dublin.ci.misc:/Users/jenkins/workspace/status-react_prs_ios_PR-7479/node_modules/react-native/React % ls -l
total 8
drwxr-xr-x  76 jenkins  staff  2432 Apr 15 23:01 Base
drwxr-xr-x  12 jenkins  staff   384 Apr 15 23:01 CxxBridge
drwxr-xr-x  11 jenkins  staff   352 Apr 15 23:01 CxxModule
drwxr-xr-x   4 jenkins  staff   128 Apr 15 23:01 CxxUtils
drwxr-xr-x  12 jenkins  staff   384 Apr 15 23:01 DevSupport
drwxr-xr-x  19 jenkins  staff   608 Apr 15 23:01 Fabric
drwxr-xr-x   6 jenkins  staff   192 Apr 15 23:01 Inspector
drwxr-xr-x  48 jenkins  staff  1536 Apr 15 23:01 Modules
drwxr-xr-x  12 jenkins  staff   384 Apr 15 23:01 Profiler
drwxr-xr-x   3 jenkins  staff    96 Apr 15 23:01 React.xcodeproj
drwxr-xr-x   4 jenkins  staff   128 Apr 15 23:01 UIUtils
drwxr-xr-x  91 jenkins  staff  2912 Apr 15 23:01 Views
-rw-r--r--   1 jenkins  staff   443 Apr  7 11:38 third-party.xcconfig
```
And looked inside of `React.xcodeproj`, which appears to be this file:
https://github.com/status-im/react-native/blob/master/React/React.xcodeproj/project.pbxproj
Which contains its own `buildConfigurations`:
https://github.com/status-im/react-native/blob/2249af16b7ee84d3e25ca7e827e725c7994f936d/React/React.xcodeproj/project.pbxproj#L3109-L3117
Not sure if this makes sense, but maybe the issue is that it doesn't contain a `PR` build configuration?

**Comment by jakubgs** [comment]
I recall Senpai @yenda worked on #4819 which upgraded `react-native`. Maybe you have some idea why `React` can't be found? Any suggestions where I should be looking?

**Comment by jakubgs** [comment]
Ah I see, `97` was multiplied by `3` message types, which gives `291`. So yeah, that adds up to `291` unique queries which takes a minute.

**Comment by flexsurfer** [comment]
@jakubgs is this still relevant?

**Comment by jakubgs** [comment]
@flexsurfer I wish. I've been so busy with a lot of other things which are more related to infra that I haven't had the time to work on this at all. Now I'm busy helping with new development infra for future version of https://dap.ps/. I do want to finish this, but don't have the time.

I was also pretty darn stuck the last time I looked at this as far as I recall.
I really can't figure out this `ld: library not found for -lReact` error.

**Comment by oskarth** [comment]
I suggest closing this if we can't get it merged this week, and we can reopen it when it is more of a priority.

**Comment by jakubgs** [comment]
Fine by me.

**Pull request closed without merging**
