### PR TITLE
[#9954] Add 'view profile' to message long tap

### LINKED ISSUE #9954: Add 'view profile' to message long tap
# Problem

This is being done largely as a counter spam mechanism, so that users can easily load up a person's profile and subsequently block them if they are flooding a chat. 

Also, you can not currently long tap a sticker, because the `reply` and `copy` UI is not built yet. The `view profile` option is valid for stickers now though.

Note: labeled v1 release, but not a v1 hard blocker.

## Implementation

Use the same menu option that we do in overflow menus:

image

## Acceptance Criteria

1. New option to `view profile` is available when you long tap on a message
2. When you long tap on a sticker, you get the `view profile` option only

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #9954

Stickers
image

Text
image

### CODE REVIEW

**Review by errorists — APPROVED** [review]

**Comment by flexsurfer** [comment]
@Serhy could you take a quick look ?

**Comment by Serhy** [comment]
@flexsurfer can we not show `View profile` option if I long-tap own message? OR as an option to show but redirect to `Profile` main tab in that case (like we do if to open universal link with own ENS/public key)
Because now I can open profile screen where Send Message/Add to contacts has no effect and can block myself in chat :)

Everything else looks good to me on iOS and Android 8!

**Comment by errorists** [comment]
oh absolutely. long press your own message, you don't get to see 'View profile'. thanks for spotting @Serhy

**Comment by rachelhamlin** [comment]
Agreed with @Serhy. Otherwise great work! 👏

**Comment by flexsurfer** [comment]
thanks, @Serhy fixed

**Comment by Serhy** [comment]
Lgtm, no issues, e2e rechecked manually (one of it already updated in develop)

**Pull request merged**
