### PR TITLE
[#10744] Error at attempt to set custom-domain ENS as main

### LINKED ISSUE #10744: Error at attempt to set custom-domain ENS as main
# Bug Report

## Problem

photo_2020-06-03 09 58 23 at attempt to set `.eth` name as main

#### Expected behavior
no error

#### Actual behavior
Null is not an object

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Add ENS name with custom domain

### Additional Information

- Status version: release 1.4 (build 2)
- Operating System: Android, iOS

#### Logs

[status_logs_b.zip](https://github.com/status-im/status-react/files/4721793/status_logs_b.zip)

### LINKED ISSUE #10755: ENS name with custom domain is not resolved in public and 1-1 chats
# Bug Report

## Problem
ENS name with custom domain is not resolved in public and 1-1 chats

**Steps:**
- as user A: add ENS-name with custom domain
- as user A: send message to public chat
- as User B: join public chat, waiting for name to be resolved
or
- start chat with ENS-name with custom domain 
- pay attention to chat header (should be ENS name)

**Actual result:** ENS name isn't shown in wallet

**Expected result:** ENS-name is resolved

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: release 1.4
- Operating System: Android, iOS

All fine with `stateofus.eth` names
ezgif com-video-to-gif (18)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #10744 
fixes #10755

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer currently ENS-name with custom domain is not resolved in public chat (all fine on 1.3)
**Steps:**
- as user A: add ENS-name with custom domain
- as user A: send message to public chat
- as User B: join public chat, waiting for name to be resolved
**Actual result:** ENS name isn't shown in wallet
**Expected result:** ENS-name is resolved
It can be that it is not related to your PR directly, but it is still the blocker.


All fine with `stateofus.eth` names
ezgif com-video-to-gif (18)

**Comment by churik** [comment]
UPD: created https://github.com/status-im/status-react/issues/10755

**Comment by churik** [comment]
This PR can be merged and cherry-picked in 1.4.
Thanks @flexsurfer !

**Comment by churik** [comment]
@flexsurfer chat-name is not updated on home view:
ezgif com-video-to-gif (19)
In public chat, 1-1 header, contact list it is updated.

**Comment by flexsurfer** [comment]
@churik  thanks fixed

**Comment by churik** [comment]
IOS can't be built (not related to this PR).
On Android works as expected, so can be merged and cherry-picked.
Thank you @flexsurfer !

**Pull request merged**
