### PR TITLE
Allow group creation without contacts

### LINKED ISSUE #11139: Allow creating group chat without inviting contact
As a user
I want to create a group chat with not members
So I don't have to invite someone to create an invite link

# Problem
The current flow of creating a group chat enforces inviting at least one contact. This made sense when inviting contacts was the only way to start a group chat. Now that members can be invited through a group chat invite link (any chat key), it no longer makes sense to enforce inviting a contact.

## Acceptance Criteria
Next button on `New group chat` is always enabled, and an empty group chat is created.

### PR DESCRIPTION
**Pull request by vkjr**
fixes #11139

### Summary

Now group can be created without inviting any contacts since we already have invitations via link.

#### Platforms

- Android
- iOS

##### Functional
- group chats

### Steps to test

- Open Status
- Select `start group chat`
- Ensure that `Next` button enabled when no contacts selected
- Press `Next`
- Fill in group name
- Ensure that `Create group chat` button enabled

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
### ISSUE 1: System message "_Chat creator_ has invited ..." when creating a group chat without members

Screenshot 2020-10-29 at 17 20 54

**Comment by vkjr** [comment]
@qoqobolo, I've seen same behaviour before introducing these changes - creator was among invited. So I believe it would be more logical to create a separate issue if that is a problem, wdyt?

**Comment by qoqobolo** [comment]
@vkjr do you mean in develop? Currently, I only see a message in Nightly that the creator **_has invited_** _another user_ (Little Failing Auklet has invited tanyatest8). There is no message that the chat creator **_has been invited_** (or _was invited_).
In Issue 1 we see that there is no username after **_has invited_** ('cause group chat was created without members).

Screenshot 2020-10-30 at 09 37 10

**Comment by vkjr** [comment]
@qoqobolo, thanks for explanation, I understood the issue incorrectly! Good catch, will fix!

**Comment by vkjr** [comment]
@qoqobolo, could you please recheck? Changes were made on `status-go` side to fix this - https://github.com/status-im/status-go/pull/2063 So no worries about conflicting `status-go-version.json`

**Comment by cammellos** [comment]
>  So no worries about conflicting status-go-version.json


@vkjr you might have to solve conflicts in any case, as otherwise it won't build

**Comment by vkjr** [comment]
@cammellos, yeah, just realized it 😁

**Comment by qoqobolo** [comment]
@vkjr Thank you, works great!

**Comment by cammellos** [comment]
@vkjr I have tagged this as not merge yet, when you are happy you can merge the status-go changes and update `status-go-version.json` and merge,nice work!

**Pull request merged**
