### PR TITLE
update language zh_TW 

### PR DESCRIPTION
**Pull request by ystartgo**
Please update zh_TW.json 
Fix some words from Simplified Chinese to Traditional Chinese.
EX 
添加 to 新增
你 to 您
显示 to 顯示
编辑 to 編輯

### CODE REVIEW

**Review by jinhojang6 — COMMENTED** [review]
Thanks @ystartgo for the updates!

**Comment by jinhojang6** [comment]
Hey @ystartgo! Your translations have been successfully reviewed and will be applied to v1.7.

My PR https://github.com/status-im/status-react/pull/11198 includes all the updates of this PR so you can close this PR. Thanks for your contribution again!

**Comment by jinhojang6** [comment]
Let me close this instead

**Review by ystartgo — COMMENTED** [review]
Updated

**Pull request closed without merging**
