### PR TITLE
Add referral share link ui

### LINKED ISSUE #10346: Build front-end user referral flow
# Problem

Chat platform success is in network effects. The user referral program rewards Android users for bringing their friends and family into Status. 100 SNT to the referrer for each new user who creates an account.

App store rules prevent us from being able to offer this scheme on iOS.

## Implementation

3 separate entry points for the invite flow:
- From app intro screen, [in existing `Invite Friends` bubble](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=8738%3A128)
- From [the `+` menu in chat section](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=8738%3A295)
- As [an empty state](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=12%3A127) on the `Profile` > `Contacts` screen, `Start group chat` flow, and `Start new chat flow`

Past the entry point, there are three more steps:
- https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=8738%3A597
- [User invites someone out of app](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=8738%3A1064)
- [Confirmation screen displayed](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=8738%3A435)

## Acceptance Criteria

- Please match [Figma designs](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=12%3A127)

## Notes

Are there any steps missing from code perspective?
When is account creation by another user actually confirmed? Once user generates a key?

### PR DESCRIPTION
**Pull request by Ferossgp**
Closes #10346
Add loaders while waiting API responses

### CODE REVIEW

**Comment by hesterbruikman** [comment]
@Ferossgp thanks for your patience! What feedback are you helped with most? 
- I noticed not all entry points (#10346) are covered. Do you have that planned for later?
- Copy in bottom sheet is too long, at least on my galaxy which does have a smaller screen. @errorists any thoughts on a copy change or text wrapping
Screenshot_20200512-175347_Status PR

**Comment by Ferossgp** [comment]
@hesterbruikman waiting for the contract to be deployed, then I will add usage everywhere.
The feedback mostly on the UI and feel, the bottom sheet is a bit buggy when dragging because we do not support atm multiple bottom sheet at the same time, adding that separately.

**Comment by errorists** [comment]
@hesterbruikman normally if it doesn't fit we run the text into a second line

**Comment by oskarth** [comment]
Small request - could you please rebase to latest master so this commit https://github.com/status-im/status-react/commit/b5fda1234e5447cbc626059dfc78fcfbabc9e926 gets included? This means we aren't running E2E tests on eth.prod cluster anymore, and since this happens on every push, the impact is quite big. This ensures we have more accurate metrics going forward from Jul 1 onward, which would be awesome. See https://discuss.status.im/t/user-growth-and-retention/1782 for more

**Review by andremedeiros — APPROVED** [review]

**Comment by hesterbruikman** [comment]
As already discussed with @Ferossgp. These are my findings from testing cc @Serhy 

#### 1. Use advertiser referral link - Decline attribution
_Samsung Galaxy s10e_
- [ ] Needs copy update. I can do this separately after this PR is merged as well _(Must have)_
- [ ] Can't `Dismiss` which is a big ask upon onboarding. I think we might want to replace Decline with something like `Ask me again later`. Let's see how it goes first and then revisit if this is necessary. _(Nice to have)_

#### 2. Use advertiser referral link - Accept attribution
_Samsung Galaxy s10e_
(reinstall PR)
- [ ] Likely due to contract on Rinkeby being empty, or contract address having changed, not receiving funds, so not seeing notification. Check again with new contract
- [x] Other than that looks good

#### 3. Use a previously used referral link
_Samsung Galaxy s10e_
- [x] Nothing happens aside from regular use which is expected 

#### 4. Invite friends
_Samsung Galaxy s10e_ + _Fairphone Android 7_
- [ ] Text overflow `Earn 0.001 ETH for every friend you invite`; looks like this only happens when opening from invite
- [ ] _Should be SNT, DAI and (partner token). As discussed, best to avoid amount here._ _(Must have)_
- [ ] Needs latest update with `How it works banner` and minor copy changes _(Must have)_
- [ ] Limit in contract needs to be set to 10 (cc @richard-ramos ) _(Must have)_
- [ ] Terms and conditions should prompt to opt opening in Status. Needs investigation as modal needs to stay open  _(Helpful to have, not required)_
- [ ] Remove the UI altogether on iOS? Terms overview doesn't explicitly state it will not work if the referrer is on iOS and I can generate and use the referral URL, which implies to me I will also get the referral bonus _(Must have)_

#### 5. Receive friend invite 
Need some more attempts to understand the logic of testing for this

**Comment by churik** [comment]
@hesterbruikman 
referral flow is available on start page on mainnet:
IMAGE 2020-07-31 16:36:35

**Comment by Ferossgp** [comment]
@churik this is expected, the UI is hidden only for release build by env var https://github.com/status-im/status-react/pull/10620/files#diff-95f82adffc4221e092a1ff1a67cef1c5R19

**Comment by churik** [comment]
Apart from chenging invite link from general http://status.im to deeplink - no more regression is found

**Pull request merged**
