### PR TITLE
 Integrate status-go protocol library

### LINKED ISSUE #8604: Integrate status-go and status-protocol-go
# Problem

We want to centralize all protocol-related stuff into a single repository and move as much of business logic as possible from status-react there.

## Implementation

The first step is to clean up Go code and use https://github.com/status-im/status-protocol-go library. This is being worked on https://github.com/status-im/status-go/pull/1526 and the current version is ready to be tested with status-react.

There might be minimal changes required from status-react when integrating status-go from https://github.com/status-im/status-go/pull/1526. If anything requires more work, please report it in that PR so that it's fixed there. We *don't want* to change status-react much at this stage.

## Acceptance Criteria

Everything related to messaging works.

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #8604 

This commits integrates status-go-protocol library.

No behavioral changes to the app, everything should work just as before.

### Testing

1) Sending messages (group chats, public, one-to-one, device-to-device enabled one-to-one)
2) Upgrades from current nightly/develop and making sure pairing still works/group chats works
3) Pairing

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by adambabik** [comment]
@cammellos where does `0.30.1-alpha.3` come from? In `VERSION` in `status-go@integrate-status-protocol-go` I see `0.30.0-beta.3`.

Commit hash is correct but I would like to update it with https://github.com/status-im/status-go/pull/1526/commits/0e4ba0f317301278e9ef32fa350156107ffda8e5.

**Comment by cammellos** [comment]
@adambabik it's just a tag I pushed, you can update the version in `VERSION` and then we can either create a release or push a tag so it's picked up

**Comment by Serhy** [comment]
@cammellos, when login into account after upgrade (from todays nightly builds https://i.diawi.com/npfoxm / https://status-im.ams3.digitaloceanspaces.com/StatusIm-190723-042339-688baf-nightly.apk) I'm getting "The problem occurred" error.
Right after tap on 'Submit' password button -> I navigated to Chats view - redirect back to Account login screen happens followed by the error

Screenshot 2019-07-23 at 16 02 33

**To reproduce:**
1) Install https://i.diawi.com/npfoxm / https://status-im.ams3.digitaloceanspaces.com/StatusIm-190723-042339-688baf-nightly.apk build
2) Create new account (or recover the account)
3) Upgrade to this PR build (there is a nightly version made of this PR branch: 
https://status-im.ams3.cdn.digitaloceanspaces.com/StatusIm-190723-082854-27e890-nightly.apk / https://i.diawi.com/HMShsm )

Here is a the geth.log log with Debug level when this error happens: 
[geth.log](https://github.com/status-im/status-react/files/3422183/geth.42.log)

**Comment by cammellos** [comment]
@Serhy thanks, cc @adambabik , another issue I have noticed is that if you login->logout->login again on a fresh account you have a constant spinner on the `+` button.

**Comment by Serhy** [comment]
> @Serhy thanks, cc @adambabik , another issue I have noticed is that if you login->logout->login again on a fresh account you have a constant spinner on the `+` button.

Yes, I've seen it too. Or, the endless spinner and staying on Login view (`Processing...`)
But I could not reproduce all the time...

**Comment by jakubgs** [comment]
Looks like you updated the nightly page by using `BUILD_TYPE` set to `nightly` in a manual build:
https://ci.status.im/job/status-react/job/manual/414/parameters/

I already started another nightly build to fix that:
https://ci.status.im/job/status-react/job/nightly/1184/

**Comment by Serhy** [comment]
App crashes when it gets list of devices it can pair with. Confirmed with the latest (
http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190723-150945-215159-pr.apk /
https://i.diawi.com/G3USX7 ) builds

To reproduce:
1) Open Status on Device1 and Device2
2) Recover the same account on both devices
3) Both devices navigate to `Profile` -> `Devices`
4) Device2 taps `Advertise device`
**Actual result:** On Device1 screen
Screenshot 2019-07-23 at 18 07 51


No crash with nightly develop build for the same scenario

**Comment by Serhy** [comment]
> Looks like you updated the nightly page by using `BUILD_TYPE` set to `nightly` in a manual build:
> https://ci.status.im/job/status-react/job/manual/414/parameters/
> 
> I already started another nightly build to fix that:
> https://ci.status.im/job/status-react/job/nightly/1184/

Thank you @jakubgs. Sorry, I really thought build_type in manual job means useing .env settings only for a custom build, not the whole pipeline.

**Comment by adambabik** [comment]
It looks like handling a pairing message does not work. However, this error should be handled first to be able to debug what's wrong.

I will add some unit tests for that.

We also need https://github.com/status-im/status-go/issues/1533 to be done otherwise we won't collect logs from status-protocol-go.

**Comment by cammellos** [comment]
@adambabik @Serhy Pairing messages should be fixed in the latest build, so no changes are required for that issues.
Outstanding there's 1) Upgrades result in Realm password error 2) Login->Logout->Login node crashes

1) I haven't replicated, but what I know is that is not really a realm error, likely is status-go, I will try to get the actual error out

2) I checked against develop status-go and does not happen, so must be something related to this PR, I could not replicate in `status-go` (although `logger.Sync` throws errors on `Stop` sometimes)

Could you please have a look at the outstanding issues? Thanks!

**Comment by cammellos** [comment]
@adambabik the actual error on upgrade is:
`failed to create a WhisperServiceTransport: file does not exist`

**Comment by cammellos** [comment]
@Serhy all outstanding issues should be fixed in the latest build, ready to be tested again, thanks!

**Comment by Serhy** [comment]
No regression found with the latest builds:
- Upgrade from develop build with paired accounts (iOS and Android) - can continue messaging
- Upgrade from develop build with not paired accounts but pairing both devices (iOS and Android and MacOS) -  - can continue messaging
- With enabled device-to-device setting can message in 1-1 chat
- Public/Group/1-1 chats messaging working

**Comment by cammellos** [comment]
@Serhy thanks, I will prepare a release and merge!

**Pull request merged**
