### PR TITLE
[#7911 #7894] delete account and logout after keycard reset

### LINKED ISSUE #7894: After 'Reset card' the user status account is kept on the mobile
Type of issue: UX

After a successful reset of the card:
- the user is kept logged in his account
- the account still exists on the phone and to log in the user is asked to enter a password 

Problem: 
- it's confusing for the user to be kept login in his account since he deleted his unique way to login his account (note: except if he has several keycard with the same hd wallet)
- the user has no way to login again in his account since he does not know the password that is asked of him after card deletion 

Suggested solution: 
- after successful reset of a card, the user should be logged out of his account, the account removed from the mobile app
-  the warning message should become 'This operation will reset your card to its initial state, and delete your private keys.  Your account will be removed from this phone."

### LINKED ISSUE #7911: "Status-unknown go error" at attempt to log in to account when card is reset
### Description
_Type_: Bug

_Summary_: when I reset a card, I actually accept the fact that the account will not be useful anymore (or it should be usable?), but it is not handling in app.
I would expect that after I reset card I automatically logged out and redirected to initial screen without any accounts, where I can create new account.
For this:
1) we need explicitly warn users, that account will be deleted
2) implement actual logout and deleting account
For now if I reset card and the logout, at attempt to log in "Unknown status-go error" is shown.

#### Expected behavior
 after I reset card I automatically logged out and redirected to initial screen without any accounts, where I can create new account

#### Actual behavior
Unknown status-go error.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status
* Create account with card
* Go to Profile > Status keycard
* Reset card
* Log out
* try to log in

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190403-181003-8b6ae2-pr.apk
* Operating System: Android 8, LG V20

#### Logs
[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
04-04 13:15:49.099 23108 23805 I GoLog : ssdp: got unexpected search target result "upnp:rootdevice"
04-04 13:15:49.100 23108 23805 I GoLog : ssdp: got unexpected search target result "uuid:2f402f80-da50-11e1-9b23-00178840f5e3"
04-04 13:15:49.100 23108 23805 I GoLog : ssdp: got unexpected search target result "urn:schemas-upnp-org:device:basic:1"
04-04 13:15:49.101 23108 23803 I GoLog : ssdp: got unexpected search target result "upnp:rootdevice"
04-04 13:15:49.101 23108 23805 I GoLog : ssdp: got unexpected search target result "upnp:rootdevice"
04-04 13:15:49.101 23108 23805 I GoLog : ssdp: got unexpected search target result "uuid:2f402f80-da50-11e1-9b23-00178840f5e3"
04-04 13:15:49.101 23108 23803 I GoLog : ssdp: got unexpected search target result "uuid:2f402f80-da50-11e1-9b23-00178840f5e3"
04-04 13:15:49.105 23108 23803 I GoLog : ssdp: got unexpected search target result "urn:schemas-upnp-org:device:basic:1"
04-04 13:15:49.110 23108 23805 I GoLog : ssdp: got unexpected search target result "urn:schemas-upnp-org:device:basic:1"
04-04 13:15:49.500 2541 2541 I NetworkController.WifiSignalController: Change in state to: connected=true,enabled=true,level=3,inetCondition=1,iconGroup=IconGroup(Default Wi-Fi Icons),activityIn=true,activityOut=true,rssi=-54,,ssid="MiFibra-EBF7",badgeEnum=0,isTransient=false,isGigaWiFi=false,isAttWifiCall=false,detailedState=CONNECTED

```

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #7894 
fixes #7911 

### Summary:

Delete account and logout after keycard reset.

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by churik** [comment]
@dmitryn 
#### 1) After logout bottom panel is visible and can't login and use app again until manual restart
Steps:
- create account with keycard
- login with keycard
- logout
- try to login
After logout bottom panel is visible, an user is redirected to account list instead of "sign in" screen for last used account:
sdfsfd
At attempt to login user is redirected to endless spinner:
weer
and when try to switch to profile application asks for PIN again.
The same happening after reset card when you have one account - bottom panel is visible (it shouldn't)
Expected: after logout can login and use app, no bottom panel is shown after logout

**Comment by dmitryn** [comment]
If i remove `intro` from profile-stack, i get:

```
There is no route defined for key intro.
04-09 16:06:28.657  4899  4947 E ReactNativeJS: Must be one of: 'currency-settings','show-extension','about-app','blocked-users-list','network-settings','fleet-settings','edit-mailserver','reset-card','hardwallet-success','qr-scanner','ma
nage-dapps-permissions','my-profile','log-level-settings','dapps-permissions','hardwallet-connect','keycard-settings','offline-messaging-settings','network-details','contacts-list','hardwallet-setup','installations','edit-network','enter-
pin','profile-photo-capture','mobile-network-settings','bootnodes-settings','tribute-to-talk','help-center','hardwallet-authentication-method','backup-seed','edit-extension','edit-bootnode','extensions-settings'
```

@rasom do you have an idea how to fix it? We need to navigate from profile to intro screen after deleting the account (in case app has no other accounts)

**Comment by rasom** [comment]
@dmitryn will check later today

**Comment by rasom** [comment]
@dmitryn should be fixed now.

The problem is that we didn't add `:intro` screen to stack if app was opened with existing accounts, and when you removed the last one that screen couldn't be found.

**Comment by dmitryn** [comment]
@rasom "There is no route" error is still there. 

You can reproduce this way:
* comment out https://github.com/status-im/status-react/blob/24282f0815c45a70fd0693cfe101cc71d18846f3/src/status_im/hardwallet/core.cljs#L450
* comment out https://github.com/status-im/status-react/blob/f8674c0ee10fcf6ac1fbb3bf227d2897fc23cdf1/src/status_im/init/core.cljs#L163
* call `(re-frame/dispatch [:hardwallet.callback/on-delete-success])` from Profile screen

**Comment by dmitryn** [comment]
@rasom please hold on, i haven't applied your commit. Let me test again.

**Comment by dmitryn** [comment]
@rasom it works fine, thank you!

**Comment by rasom** [comment]
huh, I was a bit puzzled already. Good! :)

**Comment by dmitryn** [comment]
@churik please take a look once builds will be ready

**Comment by jakubgs** [comment]
Took the liberty of rebasing the branch to fix the iOS builds.

**Comment by churik** [comment]
@dmitryn  on log out from account, created with the card, the user is redirected to screen with list of accounts with the opened keyboard. 
Expected that if the user logs out from the exisiting account - app redirects to screen with "sign in" screen for last used account.
Or we should change this logic for accounts, created with password as well - IMO it is not a good idea to redirect to account screen when you log out from keycard account and to "sign in" screen when logging out from the account, created with a password.

**Comment by rasom** [comment]
@churik just pushed another commit which probably fixes the issue

**Comment by churik** [comment]
@rasom @dmitryn now on logout app requests PIN and if I tap "Back" - there is no profile picture / username, and app is not usable. After repening app is opening with PIN screen and opened keyboard.

**Comment by dmitryn** [comment]
>on log out from account, created with the card, the user is redirected to screen with list of accounts with the opened keyboard.
Expected that if the user logs out from the exisiting account - app redirects to screen with "sign in" screen for last used account.

@churik on log out from keycard account we redirect to "Accounts list" screen because keycard account doesn't have "Sign in" screen. Do you think we should change it? Where should we redirect?

**Comment by dmitryn** [comment]
If we agree on that, i can revert last commit. So after the logout from keycard account, user will be redirected to "Accounts list" screen (or to "Intro" screen if keycard was reseted and account was deleted)

**Comment by churik** [comment]
@dmitryn I would expect that it should be similar for the account created with keycard and account created with password to have consistency.
So, before last commit:
1) If you have account created with password ->  logout -> redirect to "Sign in" screen, where you need only to enter a password.
2) If you have account created with keycard ->  logout -> redirect to "Account list" screen with opened keyboard (opened keyboard is definitely an issue), where you need select an account -> and then you will be redirected to "Sign in" screen.

Let's ask @hesterbruikman where the user should be redirected after logout in both cases.

**Comment by guylouis** [comment]
let me try to summarize the decision to take. There are two cases, where we have to define where the user is pointed to:
i - user logs out from a keycard account - this was not a reset from the card - the account still exists on the phone after the logout 
ii - user resets his keycard, his keycard is reset, and his account on the phone deleted (because he can't access it anymore)

User can be pointed to 
a - onboarding screen 
b - list of accounts 
c - the account login screen (enter PIN)

ii->c doesn't make sense of course, since the given account has been suppressed

**Comment by dmitryn** [comment]
```
let me try to summarize the decision to take. There are two cases, where we have to define where the user is pointed to:
i - user logs out from a keycard account - this was not a reset from the card - the account still exists on the phone after the logout
ii - user resets his keycard, his keycard is reset, and his account on the phone deleted (because he can't access it anymore)

User can be pointed to
a - onboarding screen
b - list of accounts
c - the account login screen (enter PIN)

ii->c doesn't make sense of course, since the given account has been suppressed
```

Just to clarify on how it works now:

i -> b
ii -> b (if other accounts exist)
ii -> a (if no accounts exist)

@hesterbruikman @andmironov what do you think?

**Comment by hesterbruikman** [comment]
Apologies for the delay on this. I agree with @churik that logout-login ideally works the same as 'regular' accounts.

i -> c
ii -> b (if other accounts exist)
ii -> a (if no accounts exist)

Do I understand correctly that the issue is that there is no PIN sign in screen? @andmironov can you provide this? If my understanding is correct we will need the same screen for all accounts to go in sync with the onboarding implementation.

As a sidenote I noticed a glitch in our sign in screens. We seem to have 2 (one right after login, the other after the account list screen. Not a usability issue as both make sense in context, but their similarity can lead to inconsistent behavior. This is a good time to unify them.

**Comment by dmitryn** [comment]
There are still 2 issues which i cannot resolve without hacks/workarounds:

* keyboard is shown on Accounts screen when tap navigate back from Enter Pin screen after logout
* after app restart, Login screen is shown, but not Enter Pin screen for last used account. From what i see in the logs, `:screens/on-will-focus :login` gets dispatched that changes that screen. 

@rasom i'd like to get your ideas on these issues.
Also, i did a hack to prevent bottom bar from showing on Enter Pin screen. Not sure it's right way to resolve it.

**Comment by rasom** [comment]
@dmitryn will take a look today or tomorrow in the morning

**Comment by rasom** [comment]
> after app restart, Login screen is shown, but not Enter Pin screen for last used account. From what i see in the logs, :screens/on-will-focus :login gets dispatched that changes that screen.

should be fixed now

**Comment by rasom** [comment]
> keyboard is shown on Accounts screen when tap navigate back from Enter Pin screen after logout

I can't reproduce this one now

**Comment by rasom** [comment]
@churik @dmitryn can you test it again?

**Comment by dmitryn** [comment]
@rasom looks good to me, thank you!

@churik can you please check on your side.

**Comment by asemiankevich** [comment]
@dmitryn @guylouis after i reset the card - the applet is completely removed. So for end user the card is not usable because if i want to create a new account with the card which i just reset -> i need to get the applet first somehow to this card.

Is it okay? I mean it is not something introduced with this PR, but a good thing to know. Please advise.

**Comment by guylouis** [comment]
well that's definitely problematic :) since we don't allow download of the applet any more, reseting the card should mean removing the account, and not removing the applet

**Comment by asemiankevich** [comment]
@dmitryn could this be done in scope of the PR?

**Comment by dmitryn** [comment]
@asemiankevich yes, i'll be using `removeKey()` sdk method which only removes keys from card. 
Also, installation flow should be changed for this case – we need to skip pik/pun/pairing screens as card already initialized.

**Comment by guylouis** [comment]
"Also, installation flow should be changed for this case – we need to skip pik/pun/pairing screens as card already initialized."
cool good for me ! 
@hesterbruikman , if you think otherwise let us know !

**Comment by dmitryn** [comment]
@asemiankevich now card reset unpairs card and removes key, but leaves card in initialized state.
During setup, such card will be asked to be paired with pairing password, then asked for PIN and then new key will be generated  and loaded to card.

**Comment by asemiankevich** [comment]
@dmitryn 

1. user is asked for PIN again after codes screen is shown
2. error is shown when PIN is entered, exit closes the app

image

Here is the video https://drive.google.com/open?id=10Eu1C9c7lUVeCG5P-NgD6wKPlcHR4eL7

**Comment by dmitryn** [comment]
@gravityblast can you please approve? Goran was removed from status org and his approval is no longer valid.

**Comment by dmitryn** [comment]
@asemiankevich i've fixed the errors, but i need to get more approvals to start build

**Comment by dmitryn** [comment]
@flexsurfer @rasom can you guys re-approve please as old approval is no longer valid.

**Comment by dmitryn** [comment]
@asemiankevich build is ready http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190506-123255-b477fa-pr.apk

**Review by rasom — APPROVED** [review]

**Pull request merged**
