### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by jinhojang6**
- Turkish translation update by Erol
- Arabic translation update by Nasib
- French translation update by Musaraigne furtive
- Indonesian translation update by Albed
- Russian translation update by @flexsurfer
- Tagalog translation update by Ken
- Korean translation update by me

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
I see nothing wrong.

**Comment by jinhojang6** [comment]
@flexsurfer Can you please take a look at this PR?

**Comment by flexsurfer** [comment]
@jinhojang6 i would like to make some changes in Russian, because the latest translation not good. i made some changes long time ago, is it possible to make changes from core contributors fixed I mean so nobody can change them , for example "Submit" in Russian translated as "Send" it's completely wrong, a user might think we send his password somewhere

**Comment by jinhojang6** [comment]
@flexsurfer @hesterbruikman 
 Oops.. the paid service from Lokalise was not the best. Thanks for letting us know that.

**Comment by flexsurfer** [comment]
@jinhojang6 thanks, i've made some changes in Russian in lokalise, could you please apply them here?

**Comment by jinhojang6** [comment]
@flexsurfer No problem. Let me apply those soon.

**Comment by hesterbruikman** [comment]
Thanks for taking a look @flexsurfer It was worth a shot, but no more Lokalize paid translations in that case

**Comment by jinhojang6** [comment]
@flexsurfer 
I applied your updates in this PR. Can you please look over this?

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
thanks @jinhojang6

**Pull request merged**
