### PR TITLE
Add accessability label to Quo tooltip

### LINKED ISSUE #10813: "Wrong password" tooltip is not accessible by e2e
# Bug Report

## Problem
Appeared in nightly 12/06/2020
Part of https://github.com/status-im/status-react/issues/8567 

"Wrong password" on login screen tooltip is not presented in  XML of page (e2e tests also don't see the text from those tooltips)

#### Expected behavior
'Wrong password' tooltip is accessible by e2e 

#### Actual behavior
Can't find element on page

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status, create multiaccount, log out
- Try to login with wrong password

### Additional Information

- Status version: nightly 15/06/2020
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by Ferossgp**
Fixes #10813

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@Ferossgp 
something is wrong with this particular tooltip - it is still not presented in XML.
Appium 2020-06-17 11-10-05
using this XPath element can't be found (tried with `//*[contains(@text,"Wrong")]` - the same)

All fine with tooltips for example `passwords doesn't match` during account setup

**Comment by Ferossgp** [comment]
@churik can you access it by using accessibility content-description="password-input-error"?
It should be a ViewGroup
Screenshot 2020-06-17 at 13 29 28
Inside it has a TextView with this text
Screenshot 2020-06-17 at 13 29 37

If that will not be accessible, I will check a different approach to make it

**Comment by churik** [comment]
No, on build https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200617-061004-793bb3-x86.apk it is not accessible.
What I did:
- create account on e2e build
- log out
- enter wrong password
XML source is here: [s.txt](https://github.com/status-im/status-react/files/4791985/s.txt)

**Comment by churik** [comment]
Tried on https://github.com/status-im/status-react/commit/4df7a8eab5c9a01e61b27db3084d787ac365deb8 - still no success

**Pull request merged**
