### PR TITLE
Update ko.json

### PR DESCRIPTION
**Pull request by jinhojang6**
Update the Korean translations

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Comment by jakubgs** [comment]
I've rebased it but it still fails on Clojure ocmpilation:
```
Compiling ["index.desktop.js" "status-modules/cljs/i18n-raw.js" "status-modules/cljs/network-raw.js" "status-modules/cljs/extensions-raw.js"] from ["components/src" "react-native/src/cljsjs" "react-native/src/desktop" "src" "env/prod" "prod"]...
WARNING: Use of undeclared Var status-im.utils.handlers/register-handler-fx at line 13 /home/jenkins/workspace/status-react_prs_windows_PR-8553/src/status_im/wallet/accounts/core.cljs
Error encountered performing task 'cljsbuild' with profile(s): 'prod'
Subprocess failed
make: *** [Makefile:125: prod-build-desktop] Error 1
```
Which doesn't make much sense since none of `cljs` files are being modified in this PR.

**Comment by jakubgs** [comment]
Apparently this is the problematic line(13):
https://github.com/status-im/status-react/blob/28f7ea0408aa308056108b38b222fefb6a0694cd/src/status_im/wallet/accounts/core.cljs#L13-L16
But I don't even know what that part does, I can't read Clojure at all.
@flexsurfer do you have any idea about this? I'm lost.

**Comment by flexsurfer** [comment]
thanks @jakubgs i'll take care of it

**Comment by flexsurfer** [comment]
@jakubgs @jinhojang6 rebase should fix it

**Comment by asemiankevich** [comment]
i've checked several random places where new strings should be applied, for example:

- advance -> device-to-device enabled

image

- wallet history

image

new strings are applied and match the expectations (checked agains Changed files in the PR). Lets merge this one, seems it is getting more and more outdated since we are adding new screens.

**Pull request merged**
