### PR TITLE
[#9542] Make "Sync over mobile network" modal even less annoying

### LINKED ISSUE #9542: Make "Sync over mobile network" modal even less annoying
Let's make the "Remember my choice" checkbox checked by default to make the modal less annoying.

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #9542

### CODE REVIEW

**Comment by Serhy** [comment]
@flexsurfer checkbox is checked not by default at the first time mobile sync pop-up appears, but it's not applied (choice not remembered, while  'Remember my choice' = 'True'). If to uncheck it and check again - then yes, selection is remembered and mobile sync pop-up does not appear. But not when it's checked by default.

**To reproduce:**
1) Open Status with Wifi mode 
2) Create new account
3) Being on Chats main screen disable WiFi and enable 3G/4G mode
**Note**: `Remember my choice` is checked = good
4) Tap `Continue syncing` OR `Stop syncing`
5) Enable WiFi mode and wait for `Connected` status
6) Disable WiFi and enable mobile network
**Actual result:** "Sync over mobile network" pop-up appears.


NOTE: just in case we need to include scenario of when user neither taps 'Continue syncing' nor 'Stop syncing' and just closes this pop-up (via tap outside the pop-up). In that case nothing should be applied and pop-up have to appear over and over again until user *confirms* the action with 'Stop'/'Continue' syncing

**Comment by Serhy** [comment]
Update: https://github.com/status-im/status-react/pull/9552#issuecomment-560379342 was with first build. I ignore it please (I'll check second build )

**Comment by Serhy** [comment]
No, it's actually the same commit, and I rechecked with the builds https://i.diawi.com/gqEyuP and https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-191202-120249-0d159b-pr-universal.apk on iOS 13 and Android 8.1, and can confirm issue https://github.com/status-im/status-react/pull/9552#issuecomment-560379342 is actual

**Comment by flexsurfer** [comment]
thanks @Serhy fixed

**Comment by Serhy** [comment]
Looks good to me! Tested with iOS 13 and Android 8.1.
@flexsurfer please mind my commit when merge. 
Thanks!

**Review by Serhy — APPROVED** [review]

**Pull request merged**
