### PR TITLE
Macros

### PR DESCRIPTION
**Pull request by yenda**
@flexsurfer please try it in dev and let's merge it

### CODE REVIEW

**Comment by yenda** [comment]
@flexsurfer @Serhy I added another commit which might bring some nice perf improvements. I rewrote safe-merge so that it is only using reduce and conditionals instead of complex functions and at the function level it is 10 times faster. There is some places like when adding messages where it can be called 100 times in a row which on desktop used to take 180ms and now takes 19ms for simple test values, so the real results on real devices might be even better

**Comment by flexsurfer** [comment]
image

**Comment by yenda** [comment]
@flexsurfer yes it is fixed already in the latest commit, forgot special case for db

**Comment by flexsurfer** [comment]
i use latest commit

**Comment by yenda** [comment]
@jakubgs jenkins didn't start a build again on latest commit

**Comment by yenda** [comment]
@flexsurfer @jakubgs lol I forgot to push

**Comment by flexsurfer** [comment]
idk if its your PR or develop, but app is broken, there is no account in the wallet, and app is crashing on log out

**Review by flexsurfer — APPROVED** [review]

**Pull request merged**
