### PR TITLE
keycard login v1

### PR DESCRIPTION
**Pull request by dmitryn**
### Summary

Implements keycard login screens

https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=1007%3A299&viewport=4147%2C349%2C0.667277991771698

#### Platforms

- Android

status: ready

### CODE REVIEW

**Comment by hesterbruikman** [comment]
Can you please help me out in getting setup @dmitryn? I recovered my keycard account in the build. When I go to the login screen of this account and tap the card to my phone. The screen doesn't respond. Phone does vibrate as though the card is detected.

**Comment by dmitryn** [comment]
@hesterbruikman i'm trying to reproduce this bug to understand the issue.

**Comment by dmitryn** [comment]
@hesterbruikman please try new build http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190729-150027-b13a7c-pr.apk

Screenshot_20190729-145949

Also, just to make sure you tap card on this screen? 

Did you recover or create new keycard account? Recovery option is not available in current build (until https://github.com/status-im/status-react/pull/8519 gets merged), it's only possible to create new keycard account with onboarding flow.

**Comment by hesterbruikman** [comment]
Thanks @dmitryn that party explains as I wass trying recover. Running into another issue now.

When I try to create a new Keycard account I can't get past `Hold card to the back of your phone to start`. I see the 3 steps, when I hold the card to the back of the phone I get the popup `Connection with the card has been lost` (sometimes, most of the time nothing happens on the screen although the phone vibrates. Any advice?

Fyi I'm on Samsung Galaxy s10e. Using an initialized blue/grey/black card and a white test card.

**Comment by andmironov** [comment]
Thanks, Dmitry, awesome changes!
Here are some UX/UI issues I've spotted so far:

- If I tap the card before I've chosen "Keycard" as storage, I get a popup "Connection with the card has been lost"';
- If I try to set up a card, which has been already been used, I see an alert "This card has already a miltiaccount on it, please login...". I think the copy has to be changed and we should offer a "Login" button, as the only way to log in from here is to tap "back" several times;
- There is no way (i did not find it) to log in without a password (with keycard + passcode);
- PUK code and Pair code typeface
should be monospaced (Roboto Mono) to make it easy to tell whether it's a zero or an "O";
- Maybe let's add spaces to the PUK code? 068091011194 -> 0680 9101 1194;
- The keyboard is not shown on seed phrase word confirmation screen right away;
- The text not centered on seed phrase word confirmation screen;



Also, I got a bug, after signup is complete, there's this infinite "welcome to status" screen.

**Comment by andmironov** [comment]
Something else regarding the Keycard setup. I've noticed that on smaller screens there's no room for both the list of upcoming steps and the keycard + phone image. I think both are important.
Also, i've just noticed the welcome screen is missing now.

What I suggest is that instead of this:
Screen Shot 2019-08-01 at 12 58 47

We do this:
Screen Shot 2019-08-01 at 12 59 01

**Review by yenda — APPROVED** [review]
I just add a quick look, doesn't seem to affect the changing login flow so lgtm.
Since we have broken develop already we could QA this and merge asap, then a second PR could fix the designs

**Comment by asemiankevich** [comment]
@dmitryn i can't finish set up on my phone for brand new account (https://github.com/status-im/status-react/issues/8608)

image

@annadanchenko would you mind to give it a try on your device?

**Comment by annadanchenko** [comment]
@asemiankevich @dmitryn  I have same issue after creating the new account with keycard as in https://github.com/status-im/status-react/pull/8618#issuecomment-517280298 on Samsung S10 with build4

**Comment by dmitryn** [comment]
@asemiankevich should be fixed now, please try again.

**Comment by asemiankevich** [comment]
@dmitryn login is broken, i can't login properly with newly created keycard account

image

image


```
2019-08-02 12:47:22.511 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-08-02 12:47:23.038 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-08-02 12:47:23.518 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-08-02 12:47:23.988 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-08-02 12:47:24.431 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-08-02 12:47:24.888 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-08-02 12:47:24.897 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet/process-pin-input
2019-08-02 12:47:24.904 5426-5486/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :keycard-login-connect-card nil
2019-08-02 12:47:25.050 5426-5486/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:32] - :on-will-focus :keycard-login-connect-card
2019-08-02 12:47:25.054 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :screens/on-will-focus
2019-08-02 12:47:25.064 5426-5486/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:137] - :main-component-did-update :keycard-login-connect-card
2019-08-02 12:47:31.112 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.callback/on-card-connected
2019-08-02 12:47:31.114 5426-5486/? D/ReactNativeJS: DEBUG [status-im.hardwallet.core:1360] - [hardwallet] card connected
2019-08-02 12:47:31.120 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet/get-application-info
2019-08-02 12:47:31.673 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.callback/on-get-application-info-success
2019-08-02 12:47:31.708 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet/login-with-keycard
2019-08-02 12:47:34.983 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :hardwallet.callback/on-get-keys-success
2019-08-02 12:47:34.991 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.keychain.core:191] - initializing realm encryption key...
2019-08-02 12:47:34.993 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.keychain.core:173] - PERF initializing realm encryption key... 1564739254991
2019-08-02 12:47:34.997 5426-5486/? D/ReactNativeJS: DEBUG [status-im.data-store.core:28] - changing multiaccount to:  2de4dfc0c25cd11874766cdf5782ee5dbd1e42f1
2019-08-02 12:47:34.999 5426-5486/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:194] - closing account realm
2019-08-02 12:47:35.007 5426-5486/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:245] - try to encrypt with password
2019-08-02 12:47:35.024 5426-5486/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:247] - try to encrypt with password success
2019-08-02 12:47:35.032 5426-5486/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:274] - open-account
2019-08-02 12:47:35.034 5426-5486/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:177] - migrate-realm
2019-08-02 12:47:35.038 5426-5486/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:147] - migrate schemas -1
2019-08-02 12:47:35.042 5426-5486/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:46] - Opening realm at  /data/user/0/im.status.ethereum.pr/files/../no_backup/realm/accounts/0x38e1f2c5eb3daf5ed67be752f6ef78770c13b43f3041480d304cca80f0615d11 ...
2019-08-02 12:47:35.048 5426-5486/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:48] - Using encryption key...
2019-08-02 12:47:35.065 5426-5486/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:277] - account-realm  false
2019-08-02 12:47:35.068 5426-5486/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :init.callback/multiaccount-change-success
2019-08-02 12:47:35.091 5426-5486/? I/ReactNativeJS: INFO [status-im.node.core:179] - Node config:  {"ClusterConfig":{"Enabled":true,"Fleet":"eth.beta","BootNodes":["enode://5395aab7833f1ecb671b59bf0521cf20224fe8162fc3d2675de4ee4d5636a75ec32d13268fc184df8d1ddfa803943906882da62a4df42d4fccf6d17808156a87@206.189.243.57:443","enode://e8a7c03b58911e98bbd66accb2a55d57683f35b23bf9dfca89e5e244eb5cc3f25018b4112db507faca34fb69ffb44b362f79eda97a669a8df29c72e654416784@47.91.224.35:443","enode://7427dfe38bd4cf7c58bb96417806fab25782ec3e6046a8053370022cbaa281536e8d64ecd1b02e1f8f72768e295d06258ba43d88304db068e6f2417ae8bcb9a6@104.154.88.123:443","enode://43947863cfa5aad1178f482ac35a8ebb9116cded1c23f7f9af1a47badfc1ee7f0dd9ec0543417cc347225a6e47e46c6873f647559e43434596c54e17a4d3a1e4@47.52.74.140:443"],"TrustedMailServers":["enode://7de99e4cb1b3523bd26ca212369540646607c721ad4f3e5c821ed9148150ce6ce2e72631723002210fac1fd52dfa8bbdf3555e05379af79515e1179da37cc3db@35.188.19.210:443","enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@206.189.243.162:443","enode://015e22f6cd2b44c8a51bd7a23555e271e0759c7d7f52432719665a74966f2da456d28e154e836bee6092b4d686fe67e331655586c57b718be3997c1629d24167@35.226.21.19:443","enode://7aa648d6e855950b2e3d3bf220c496e0cae4adfddef3e1e6062e6b177aec93bc6cdcf1282cb40d1656932ebfdd565729da440368d7c4da7dbd4d004b1ac02bf8@206.189.243.169:443","enode://531e252ec966b7e83f5538c19bf1cde7381cc7949026a6e499b6e998e695751aadf26d4c98d5a4eabfb7cefd31c3c88d600a775f14ed5781520a88ecd25da3c6@35.225.227.79:443","enode://da61e9eff86a56633b635f887d8b91e0ff5236bbc05b8169834292e92afb92929dcf6efdbf373a37903da8fe0384d5a0a8247e83f1ce211aa429200b6d28c548@47.91.156.93:443"],"StaticNodes":["enode://b33dc678589931713a085d29f9dc0efee1783dacce1d13696eb5d3a546293198470d97822c40b187336062b39fd3464e9807858109752767d486ea699a6ab3de@35.193.151.184:443","enode://a80eb084f6bf3f98bf6a492fd6ba3db636986b17643695f67f543115d93d69920fb72e349e0c617a01544764f09375bb85f452b9c750a892d01d0e627d9c251e@47.89.16.125:443"],"RendezvousNodes":["/ip4/174.138.105.243/tcp/30703/ethv4/16Uiu2HAmRHPzF3rQg55PgYPcQkyvPVH9n2hWsYPhUJBZ6kVjJgdV","/ip4/206.189.243.57/tcp/30703/ethv4/16Uiu2HAmLqTXuY4Sb6G28HNooaFUXUKzpzKXCcgyJxgaEE2i5vnf"]},"DataDir":"/ethereum/mainnet_rpc","LogLevel":"INFO","Rendezvous":true,"WhisperConfig":{"Enabled":true,"LightClient":true,"MinimumPoW":0.001,"EnableNTPSync":true},"LogEnabled":true,"BrowsersConfig":{"Enabled":true},"RequireTopics":{"whisper":{"Min":2,"Max":2}},"UpstreamConfig":{"Enabled":true,"URL":"https://mainnet.infura.io/v3/f315575765b14720b32382a61a89341a"},"PermissionsConfig":{"Enabled":true},"NetworkId":1,"Name":"StatusIM","NoDiscovery":false,"ShhextConfig":{"BackupDisabledDataDir":"/data/user/0/im.status.ethereum.pr/files/../no_backup","InstallationID":null,"MaxMessageDeliveryAttempts":6,"MailServerConfirmations":true,"DataSyncEnabled":false,"DisableGenericDiscoveryTopic":false,"SendV1Messages":false,"PFSEnabled":true},"WalletConfig":{"Enabled":true},"StatusAccountsConfig":{"Enabled":true}}
2019-08-02 12:47:35.112 5426-5486/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :home nil
2019-08-02 12:47:36.032 5426-5486/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:32] - :on-will-focus :home
2019-08-02 12:47:36.079 5426-5486/? E/ReactNativeJS: ERROR [status-im.utils.async:19] - failed to run task Error: Missing value for property 'account.address'
2019-08-02 12:47:36.099 5426-5487/? E/unknown:ReactNative: console.error: "ERROR [status-im.utils.async:19] - failed to run task Error: Missing value for property 'account.address'", stack:
    error@345.js:96:29
    hca@7201:45
    a@7303:53
    c@91454:136
    b@91449:24
    <unknown>@33369:26
    <unknown>@33654:52
    Jb@11905:35
    ec@3075:47
    me@5574:26
    DO@33612:11
    CNb@44275:16
    <unknown>@45401:135
    p@45358:32
    JT@43955:23
    <unknown>@43966:16
    <unknown>@43701:42
    cNb@43587:40
    _callTimer@112272:17
    _callImmediatesPass@112308:19
    callImmediates@112527:33
    callImmediates@-1
    __callImmediates@106773:35
    <unknown>@106594:34
    __guard@106756:15
    flushedQueue@106593:21
    flushedQueue@-1
    invokeCallbackAndReturnFlushedQueue@-1
```

Steps:

1. create account with keycard
2. profile -> logout 
3. enter PIN and login to this keycard account

please take a look

**Comment by dmitryn** [comment]
@asemiankevich fixed, please check
http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190802-110034-f19bf4-pr.apk

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
i can create and login with keycard account. 

recover account will be done in next PRs .

**Pull request merged**
