### PR TITLE
nix: upgrade nixpkgs, extract gomobile

### PR DESCRIPTION
**Pull request by jakubgs**
I've created PRs to include gomobile in official nixpkgs:

* https://github.com/NixOS/nixpkgs/pull/116747
* https://github.com/NixOS/nixpkgs/pull/131042

Hence I'm removing our own implementation to use that one.

Notable upgrades:

| Package        | Previous    | Current     |
|----------------|-------------|-------------|
| `glibc`        | `2.32`      | `2.33`      |
| `git`          | `2.31.1`    | `2.32.0`    |
| `clojure`      | `1.10.3.855`| `1.10.3.943`|
| `nodejs`       | `12.22.1`   | `12.22.6`   |
| `yarn`         | `1.22.10`   | `1.22.11`   |
| Platform Tools | `31.0.2`    | `31.0.3`    |
| Build Tools    | `30.0.3`    | `31.0.0`    |

### CODE REVIEW

**Comment by jakubgs** [comment]
For some reason I'm getting these when switching to `gomobile` from `nixpkgs`:
```
▸ /Users/jenkins/workspace/status-react_prs_ios_PR-11900/ios/Pods/Target Support Files/Pods-Status-StatusImPR/Pods-Status-StatusImPR.release.xcconfig:1:1: error: unable to open file (in target "StatusImPR" in project "StatusIm")
▸ /Users/jenkins/workspace/status-react_prs_ios_PR-11900/ios/Pods/Target Support Files/Pods-Status-StatusImPR/Pods-Status-StatusImPR.release.xcconfig:1:1: error: unable to open file (in target "StatusImPR" in project "StatusIm")
▸ /Users/jenkins/workspace/status-react_prs_ios_PR-11900/ios/Pods/Target Support Files/Pods-Status-StatusImPR/Pods-Status-StatusImPR.release.xcconfig:1:1: error: unable to open file (in target "StatusImPR" in project "StatusIm")

⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
📋  For the complete and more detailed error log, check the full log at:
📋  /Users/jenkins/Library/Logs/gym/Status PR-StatusImPR.log
```
Makes no sense to me.

**Comment by jakubgs** [comment]
Ok, looks like what triggers this error aren't my `gomobile` or Android SDK changes, but the `nixpkgs` upgrade itself.

**Comment by jakubgs** [comment]
I think I know the reason for the issues:
```
Traceback (most recent call last):
	3: from /nix/store/h8jnd6248jy62hh8mhi4hsk9pribmqrb-cocoapods-1.10.1/bin/pod:18:in `<main>'
	2: from /opt/nix/store/2zfhccgh63jy1d4bfis83pgabg8pdkza-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler.rb:149:in `setup'
	1: from /opt/nix/store/2zfhccgh63jy1d4bfis83pgabg8pdkza-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/runtime.rb:13:in `setup'
/opt/nix/store/2zfhccgh63jy1d4bfis83pgabg8pdkza-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/definition.rb:439:in `ensure_equivalent_gemfile_and_lockfile': You are trying to install in deployment mode after changing (Bundler::ProductionError)
your Gemfile. Run `bundle install` elsewhere and add the
updated ../../../../../nix/store/y8qw7d242qrrqfld7pycyj3myaiq20q1-gemfile-and-lockfile/Gemfile.lock to version control.

If this is a development machine, remove the /nix/store/y8qw7d242qrrqfld7pycyj3myaiq20q1-gemfile-and-lockfile/Gemfile freeze 
by running ``.

The list of sources changed

You have added to the Gemfile:
* source: locally installed gems
```
Looks like this is caused by an upgrade to Bundler, from `2.1.4` to `2.2.20`:
```
[nix-shell:~/repos/status-react]$ bundle --version
Bundler version 2.2.20
```

**Comment by jakubgs** [comment]
Or maybe this issue is more related to Ruby upgrade from `2.7.3` to `2.7.4`, it seems like simply Cocoapods are broken:
```
[nix-shell:~/repos/status-react/ios]$ pod --help
Traceback (most recent call last):
	3: from /nix/store/h8jnd6248jy62hh8mhi4hsk9pribmqrb-cocoapods-1.10.1/bin/pod:18:in `<main>'
	2: from /opt/nix/store/2zfhccgh63jy1d4bfis83pgabg8pdkza-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler.rb:149:in `setup'
	1: from /opt/nix/store/2zfhccgh63jy1d4bfis83pgabg8pdkza-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/runtime.rb:13:in `setup'
/opt/nix/store/2zfhccgh63jy1d4bfis83pgabg8pdkza-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/definition.rb:439:in `ensure_equivalent_gemfile_and_lockfile': You are trying to install in deployment mode after changing (Bundler::ProductionError)
your Gemfile. Run `bundle install` elsewhere and add the
updated ../../../../../nix/store/y8qw7d242qrrqfld7pycyj3myaiq20q1-gemfile-and-lockfile/Gemfile.lock to version control.

If this is a development machine, remove the /nix/store/y8qw7d242qrrqfld7pycyj3myaiq20q1-gemfile-and-lockfile/Gemfile freeze 
by running `bundle config unset frozen`.

The list of sources changed

You have added to the Gemfile:
* source: locally installed gems
```
It might be better to just leave this be for a while and try a newer version of `master` from `nixpkgs` at a later date.

**Comment by jakubgs** [comment]
Looks like someone reported this issue: https://github.com/NixOS/nixpkgs/issues/132049

And it appears they have fixed it by upgrading Cocoapods to `1.10.2`: https://github.com/NixOS/nixpkgs/pull/134396

**Comment by jakubgs** [comment]
Now I'm getting something interesting when I try to upgrade Pods:
```
Traceback (most recent call last):
	3: from /nix/store/jrmpad6ad86ml15i6rlsgq0y6n611h3c-cocoapods-1.10.2/bin/pod:18:in `<main>'
	2: from /opt/nix/store/fkyskhqm4jhrqqqvpfg98nn2h1mzxppl-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler.rb:143:in `setup'
	1: from /opt/nix/store/fkyskhqm4jhrqqqvpfg98nn2h1mzxppl-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/definition.rb:444:in `validate_runtime!'
/opt/nix/store/fkyskhqm4jhrqqqvpfg98nn2h1mzxppl-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/definition.rb:475:in `validate_platforms!': Your bundle only supports platforms ["arm64-darwin-20"] but your local platform is x86_64-darwin-17. Add the current platform to the lockfile with `bundle lock --add-platform x86_64-darwin-17` and try again. (Bundler::ProductionError)
```

**Comment by jakubgs** [comment]
Opened an issue about these failures: https://github.com/NixOS/nixpkgs/issues/136971

**Comment by jakubgs** [comment]
Looks like there's a fix for the Cocoapods platform issue: https://github.com/NixOS/nixpkgs/pull/137240

**Comment by jakubgs** [comment]
It works!

image

**Review by rasom — APPROVED** [review]

**Pull request closed without merging**
