### PR TITLE
ci: upgrade Xcode from 13.4 to 14.2

### PR DESCRIPTION
**Pull request by jakubgs**
Depends on: https://github.com/status-im/infra-role-bootstrap-macos/commit/fefb0081

### CODE REVIEW

**Comment by flexsurfer** [comment]
image

**Comment by jakubgs** [comment]
Looks like we are getting some signing errors from some pods:
```
admin@maci7-03.ms-eu-dublin.ci.devel:~/status-react % grep err '/Users/jenkins/Library/Logs/gym/Status PR-StatusImPR.log'
error: Signing for "RNImageCropPicker-QBImagePicker" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'RNImageCropPicker-QBImagePicker' from project 'Pods')
error: Signing for "React-Core-AccessibilityResources" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'React-Core-AccessibilityResources' from project 'Pods')
error: Signing for "TOCropViewController-TOCropViewControllerBundle" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'TOCropViewController-TOCropViewControllerBundle' from project 'Pods')
```
This issue has some potential solutions:

* https://github.com/facebook/react-native/issues/34673
* https://github.com/CocoaPods/CocoaPods/issues/11402

**Comment by jakubgs** [comment]
I tried using this solution: https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1149585364
```ruby
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["DEVELOPMENT_TEAM"] = " Your Team ID  "
         end
    end
  end
end
```
But it resulted in:
```
error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "8B5X2M6H2Y" with a private key was found. (in target 'RNImageCropPicker-QBImagePicker' from project 'Pods')
error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "8B5X2M6H2Y" with a private key was found. (in target 'TOCropViewController-TOCropViewControllerBundle' from project 'Pods')
error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "8B5X2M6H2Y" with a private key was found. (in target 'React-Core-AccessibilityResources' from project 'Pods')
```

**Comment by jakubgs** [comment]
Instead I've tried this: https://github.com/facebook/react-native/issues/34673#issuecomment-1247944398
https://github.com/status-im/status-mobile/blob/59e9abb99eb17a838086b1f7691ffadc6991d1c8/ios/Podfile#L47-L55
And it appears to work.

**Review by siddarthkay — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Comment by pavloburykh** [comment]
@jakubgs failed e2e tests are not PR related. I've performed smoke test on IOS. Ready to be merged.

**Pull request merged**
