### PR TITLE
Fix tab not selecting and Error: No protocol method IDeref.-deref defined for type string: 

### LINKED ISSUE #14153: Selected tab not highlighting
# Bug Report

## Problem 
When user navigates from Tab A to Tab B, the selected Tab B fails to highlight. This way is difficult for the user to know which tab is currently active

#### Expected behavior
Tab B background color should change to show that is the current active tab

#### Actual behavior
Tab B background color  does not highlight to show that its active

### Reproduction

1) Open Status
2) Quo2 Preview
3) Tabs
4) Select another tab 

https://user-images.githubusercontent.com/28704507/195412279-559dbf2a-e285-4f7c-987f-bdae0f614b62.mov

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes: #14153 
status: ready

### CODE REVIEW

**Comment by OmarBasem** [comment]
I believe this issue is already fixed. Component was updated in this [PR](https://github.com/status-im/status-mobile/commit/153dbb2de1fa803fec5e3107afdbc7b99da0c522) under quo2.

**Comment by flexsurfer** [comment]
@ibrkhalil pls fix lint

**Comment by flexsurfer** [comment]
> I believe this issue is already fixed. Component was updated in this [PR](https://github.com/status-im/status-mobile/commit/153dbb2de1fa803fec5e3107afdbc7b99da0c522) under quo2.

looking at the PR it was broken in that PR

**Review by flexsurfer — APPROVED** [review]

**Comment by OmarBasem** [comment]
> > I believe this issue is already fixed. Component was updated in this [PR](https://github.com/status-im/status-mobile/commit/153dbb2de1fa803fec5e3107afdbc7b99da0c522) under quo2.
> 
> looking at the PR it was broken in that PR

Is this for the bottom tabs navigation or the top tabs like on Messages and Communities screen?

**Comment by ibrkhalil** [comment]
> > > I believe this issue is already fixed. Component was updated in this [PR](https://github.com/status-im/status-mobile/commit/153dbb2de1fa803fec5e3107afdbc7b99da0c522) under quo2.
> > 
> > 
> > looking at the PR it was broken in that PR
> 
> Is this for the bottom tabs navigation or the top tabs like on Messages and Communities screen?

It was calling `@` on an integer, `deref`ing can only happen on atoms

**Pull request merged**
