### PR TITLE
[#10899] Enable notifications during onboarding

### LINKED ISSUE #10899: Enable notifications during onboarding
Figma:  [here](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4540%3A13229)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #10899

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer  can you please rebase your PR and then I'll take it to testing?

**Comment by churik** [comment]
@flexsurfer currently screen in onboarding:
image
Also please add accessibility-ids to `Enable notifications` and `Maybe later`

**Comment by flexsurfer** [comment]
yeah that because of quo merge :(

**Comment by flexsurfer** [comment]
@churik fixed

**Comment by churik** [comment]
@flexsurfer no screen is shown in case of Access Existing keys > Recover with keycard.
All fine with other flows.

Can you please take a look?

**Pull request merged**
