### PR TITLE
Improve notifications

### PR DESCRIPTION
**Pull request by yenda**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

If you submit PR for issue with bounty then write here Fixes #NN where NN is issue number

*otherwise*

fixes #...

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
...

Documentation change PR (review please): https://github.com/status-im/status.im/pull/xxx

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

- Open Status
- ...
- Step 3, etc.

status: ready

### CODE REVIEW

**Comment by hesterbruikman** [comment]
Great work @yenda !

Tried on Android 7 and Android 10 

- #10762 seems fixed to me. Would wait on @errorists eyes to verify though
- #10766 seems fixed to me. 🙌
- `Label translation`; Don't believe there's a GH issue for this. How would this work? Are there specific keys that need translation, Lokalise process, or is a manual effort required (e.g. like is done for play store content)
- `Remove notification badge for persistent notification` With this, do you mean #4187 ? If so, lgtm. It is a feature to see the notification badge, but if there's no way to get rid of the badge always showing 1, I don't think it's worth having

cc @Serhy

**Comment by hesterbruikman** [comment]
Out of scope for this PR. @yenda I realized we're showing random name and message content in the notification. Do you foresee a feature where users can set whether they want to show this in the notification? If so, it would be good to think through if/how to show a potential nickname as well.  @errorists @0kok0 curious to hear your thoughts on this as well

Please let me know if you already have future plans so I can plan for it ☺️

**Comment by yenda** [comment]
@hesterbruikman 

- regarding label we could do it with the other translation files and use some script in the build to get the strings into the android specific files

- yeah I still don't know what launcher @flexsurfer has to see a number in the badge, but stock Android and most launcher cannot show more than a dot. This PR should make sure the dot isn't shown for the service notification which is up all the time.

- for showing name and message content I suppose you are talking about hiding it when the screen is locked? if that is the case then Android already offers that option in the settings.

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
Tested on Android 10:
- #10762 fixed 
- #10766 fixed
- retested PNs with stickers, images, long PNs (several issues will be added separately)
- several options to close service
- biometric authentication
- enable notification service on several multiaccounts
- open PNs from different places

Didn't find new issues related to this PR.

**Comment by flexsurfer** [comment]
@yenda could you squash commits pls ?

**Pull request merged**
