### PR TITLE
[#9583] Overlapping with system bar on "Send transaction" screen (LG …

### LINKED ISSUE #9583: Overlapping with system bar on "Send transaction" screen (LG phones)
# Bug Report

## Problem

On LG phones due to keyboard "Send transaction" screen is overlapping with system bar.
Probably can ve reproduced on some other models - verified that on Samsung, Xiaomi, OneNote and Google Pixel (tried smallest screens) - the issue is not reproducible.

LG V20 and LG G5:
photo_2019-12-04 16 40 41

#### Expected behavior
no overlapping

#### Actual behavior
screenshots are attached

### Reproduction

- Open Status
- Go to wallet > Send

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 04/12/2019

- Operating System: Android

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #9583

### CODE REVIEW

**Comment by churik** [comment]
@flexsurfer 
it is better now but still can see overlapping
photo_2019-12-11 18 26 31

**Comment by flexsurfer** [comment]
@churik oh wow, why do they have so big keyboard, i've tested on really small screens and old devices and it looks good, hm, i'll think what we could do

**Comment by flexsurfer** [comment]
thanks @churik , one more try! please share screenshots

**Comment by churik** [comment]
Looks good to me!
photo_2019-12-12 18 13 04

Also rechecked on Xiaomi Mi Note 9.

**Review by churik — APPROVED** [review]

**Pull request merged**
