### PR TITLE
[#10699] Balance of custom tokens is not updated until app restart

### LINKED ISSUE #10699: Balance of custom tokens is not updated until app restart
# Bug Report
## Problem
If you have some custom tokens in your account their balance is not shown just after adding, only after app restart.

#### Expected behavior
Can see balance after adding

#### Actual behavior

The actual of custom tokens amount is shown only after app restart

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status
* Deposit some custom tokens to Status account(i.e. https://github.com/bokkypoobah/WeenusTokenFaucet )
* Go to Manage Assets -> Add custom token
* Pay attention to balance

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: nightly 21/052020
* Operating System: Android, iOS

#### Logs
[status_logs-2.zip](https://github.com/status-im/status-react/files/4663604/status_logs-2.zip)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #10699

### CODE REVIEW

**Comment by Serhy** [comment]
Something wrong, @flexsurfer 
- non-zero balance of tokens fails to be displayed.
- Conversion to fiat value fails (endless spinner) and whenever navigation to wallet (with >0 balance of assets happens) there is an error appears:

Screenshot 2020-06-16 at 19 55 20

Account with 0 balance does not have any issue.
On Ropsten all positive token balances are 0

To **reproduce** above:
Recover an account with assets and navigate to Wallet view

With latest develop (`29508c`) all fine

**Comment by flexsurfer** [comment]
@Serhy thanks fixed

**Comment by Serhy** [comment]
@flexsurfer all works great and I can't reproduce initial issue anymore on iOS and Android, thanks! 
The next is a out of scope of original issue, but if it's possible to do in the scope of current PR would be awesome (else - will go separately):

Even after custom token is added, in the History tab transactions with this token still displays as ERC-20 (instead of proper token name). After re-login it's all fine. 

1)Open Status
2)Deposit some custom tokens to Status account(i.e. https://github.com/bokkypoobah/WeenusTokenFaucet )
3) Go to Manage Assets -> Add custom token
4) Send any transaction with this token
5) Open History tab (and Transaction details) and check transaction with this token
Screenshot 2020-06-17 at 18 28 07

**Comment by Serhy** [comment]
Will log above issue separately.

**Pull request merged**
