### PR TITLE
Handle new universal links

### LINKED ISSUE #10083: Implement new shorter universal links
# Feature Issue

The current form of links is too verbose and long. After discussing this with @jarradh and some others we've decided to use shorter forms, like so:

* https://join.status.im/markets in favour of https://join.status.im/chat/public/markets
* https://join.status.im/u/0x04abcXYZ123... in favour of https://join.status.im/user/0x04abcXYZ123...
* https://join.status.im/u/jakubgs in favour of https://join.status.im/user/jakubgs
* https://join.status.im/u/jakubgs.eth in favour of https://join.status.im/user/jakubgs.eth
* https://join.status.im/b/ens.domains in favour of https://join.status.im/browse/ens.domains

These were implemented in https://github.com/status-im/universal-links-handler/pull/29 and are already deployed.

### User Story

As a user, I want to shorter universal links so that it's easier to remember them and make them yourself. They also produce more readable QR codes. 

### Description

We will have to support both the old and the new way for at least one release to not break the old links. After that we can see in server logs how many people still use them and we can retire them eventually in a later release to avoid maintaining dead code.

### Acceptance Criteria

New forms of universal links are supported on Android and iOS, in addition to old forms.

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #10083

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Comment by cammellos** [comment]
@Serhy @churik would you mind manually testing this one please? 
Using universal link in both old and new format, from within and outside status.
Thanks!

**Review by rasom — APPROVED** [review]

**Comment by churik** [comment]
all failed e2e are not related to this PR, but please wait for us to adjust our universal links e2e to this PR.

**Comment by Serhy** [comment]
@cammellos that mostly works with the new build! Old and new universal links supported which is great!

However, there is an issue with iOS13 and Android10 (looks good on Android9 and Android8.1):
**Issue 1:** New universal links for ENS names fail to be handled and open user profile page. But public_key universal link works.
To reproduce:
1) Open Status and create new account
2) In external browser open `https://join.status.im/@statuse2e` OR `https://join.status.im/@statuse2e.eth`
3) Tap `Open in Status` button and check the `Legal Vibrant Indianabat` user profile is opened.
**Actual result:** No user profile page is opened. Logcat logs:  
[logcat17.txt](https://github.com/status-im/status-react/files/4410125/logcat17.txt) (startingn from lines `....event received for  status-im://@statuse2e`

 

**Issue 2** Second issue I'd be extra happy if we resolve in this PR as well if possible. That part mentioned in https://github.com/status-im/status-react/issues/10192 about opening universal link while Status is closed.

Nothing happens after login if universal link was opened while Status was closed:
1) Close Status app
2) In external browser open any universal link
3) Tap `Open in Status` (Status app should be opened)
4) Login to account
5) Check the respective behavior universal link in app worked after login (expected results per link are in https://github.com/status-im/status-react/issues/10192 description)

**Comment by Serhy** [comment]
@cammellos Latest builds greatly works with opening universal link while Status is closed (Issue2 - fixed!) 
But **Issue 1** still reproducible for me. 

Can't reproduce on Android 10 on real device, but reproducible on Android10 in emulator (even when Status is running). And the same reproduced with iOS build.

So, with the latest builds (https://i.diawi.com/3eq1mu / https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200401-084046-b4ec4d-pr-x86.apk ) universal links doesn't work in iOS (real device iPhoneX) and Android 10 emulator even when opening the link while Status is running. 
Same steps as in Issue1 of https://github.com/status-im/status-react/pull/10222#issuecomment-606696361

**Comment by Serhy** [comment]
Logs with the 8th build https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-10222/8/ for iOS:
For the next steps:
1) Install Status and create new account
2) Switch to TRACE log level mode
3) Close Status app
4) In Chrome browser open `https://join.status.im/@statuse2e` link
5) Tap `Open in Status` button
6) Log in to account
**Actual result:** Redirect to public chat `#statuse2e`. Video: https://drive.google.com/file/d/1TeNorbKnG8FZ3im_NIn1Vw1Eos4lFrRQ/view
Logs (sent from Profile -> Need help? -> Submit a bug): 
[Status.log](https://github.com/status-im/status-react/files/4415036/Status.log)


Same scenario but for the external ENS:
1) Install Status and create new account
2) Switch to TRACE log level mode
3) Close Status app
4) In Chrome browser open `https://join.status.im/@statuse2e.eth` link
5) Tap `Open in Status` button
6) Log in to account
**Actual result:** No redirect. I stay on Chats screen.
Logs (sent from Profile -> Need help? -> Submit a bug): 
[Status.log](https://github.com/status-im/status-react/files/4415048/Status.log)

**Comment by Serhy** [comment]
Thanks a lot @cammellos !!
All works fine with iOS and Androids! All universal links behave as they should when open them while Status closed.
And all works with emulators (the reason there were issues with emulators are because universal links with ENS names does not recognised in e2e builds which use Ropsten as default network)

Fixes https://github.com/status-im/status-react/issues/10192 too.

**Comment by Serhy** [comment]
I've edited existing e2e tests. And started the e2e job...

**Comment by Serhy** [comment]
Failed test test_refresh_button_browsing_app_webview is known issue in GH.

Ready for merge! Thank you a lot @cammellos ! Please mind my commit when merging.

**Pull request merged**
