### PR TITLE
[DO NOT MERGE][#8629] Fixes to v1 warning

### LINKED ISSUE #8629: Fixes to v1 warning
# Problem

We have a few issues that need fixing in the v1 notification screen:

1) Any instance of `seed phrase` must be changed to `recovery phase`.
2) The red background warning about phrase backup is easy to miss on small screens.
3) We need to point the links on the page to the right URLs.

[Figma link](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=2591%3A22548)

## Implementation

- Update spacing between image & header 
- Update copy in top paragraph (awaiting changes in Figma):
`Status is taking important steps toward a more secure, censorship resistant network. Thanks for being part of beta; we're sure you'll love v1.0!`
- Route `Learn more` to a link redirect that can be pointed at the blog post when ready. With help from @jakubgs 
- Link `#status` to https://get.status.im/chat/public/status
- Link `Twtitter` to https://twitter.com/ethstatus
- Warning text in the red box says `recovery phrase` rather than `seed phrase`.
- Move `Got it` button to bottom of page, rather than leaving it fixed on screen, to increase odds of people seeing the full text. 

## Acceptance Criteria

- Less spacing at top of screen
- Copy reads the following at top:
`Status is taking important steps toward a more secure, censorship resistant network. Thanks for being part of beta; we're sure you'll love v1.0!`
- Links work.
- Warning text in the red box says `recovery phrase` rather than `seed phrase`.
- `Got it` button is below the scroll, not fixed.

## Notes

The blog post won't be published until next week. Can start draft to use as a placeholder today.

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #8629

Image

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Comment by errorists** [comment]
Please bring back the close button, thanks!

**Comment by rachelhamlin** [comment]
@flexsurfer sorry to do this but can we make one more copy change? 

`Status 1.0 public launch` to `Status 1.0 coming` at the top 🙏To make sure no one confuses this version of the app for 1.0.

**Comment by flexsurfer** [comment]
@errorists @rachelhamlin done
image

**Review by dmitryn — APPROVED** [review]

**Comment by Serhy** [comment]
Restarting e2e tests from current PR branch (tests were taking above from `develop`, where we expect the 'Enable fingerprint' screen)

**Comment by annadanchenko** [comment]
I can scroll and read on iphone 5s.
1.  However, I still do not see red warning with most important part of our message on 1st screen and can close the warning using x in top left corner without getting to the important message.
2. Banner title says "Status 1.0 is coming" while screen says "Status 1.0 coming". Should we add "is" to that screen?

### Screen 1:
IMG_4323

### Screen 2:
IMG_4324

### Screen 3
IMG_4325

**Review by asemiankevich — APPROVED** [review]

**Comment by rachelhamlin** [comment]
@annadanchenko it's okay without the 'is' imo :)

**Comment by asemiankevich** [comment]
so any decision here @rachelhamlin @annadanchenko @flexsurfer ?

**Comment by rachelhamlin** [comment]
@asemiankevich yes - leave as is.

**Comment by asemiankevich** [comment]
> @asemiankevich yes - leave as is.

so we can merge? @rachelhamlin

**Comment by rachelhamlin** [comment]
@asemiankevich it's a green flag from me, although I'm not sure where it should be merged. To the release branch or develop?

**Pull request merged**
