### PR TITLE
Fix ENS name display

### LINKED ISSUE #14051: ENS name turns into public key after editing message containing mention with this ENS
**Steps:**

1. Open any chat with member having ENS name
2. Send some message containing ENS name
3. Edit the sent message
4. Pay attention at ENS name in edited message

**Actual result:** private key and part of 3 random name is displayed instead of ENS name. 

**Expected result:** ENS name should be preserved in edited message

https://user-images.githubusercontent.com/97245802/191309513-1f5b8587-51b5-405f-9a2b-bf5fffd4161a.mp4

[geth.log](https://github.com/status-im/status-mobile/files/9609444/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/9609445/Status.log)
me

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by audriu**
fixes #14051
this is a recreation of #14093 because of some of my mistakes

### Summary
Fixes edited messages mentions

#### Platforms
- Android
- iOS

##### Functional
- 1-1 chat
- public chats
- group chats
- account recovery
- new account
- user profile updates

### Steps to test
- Open Status
- Send messages that mention other users (with and without ENS usernames)
- Edit those messages
- See if edited messages with ENS names are displayed correctly
- Also check if anywhere the username is mentioned is displayed correctly
- Have a nice day

status: Stuck. Maybe someone else wants to give it a try...

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Comment by pavloburykh** [comment]
@audriu bug is still reproducible for me in public and group chats. 

Use @pavlo ENS for reproduction. Don't forget to switch to mainnet first, because this is ENS registered on mainnet. 

**Steps:**

1. Login multiaccount
2. Switch to Mainnet if needed
3. Join #pavlotest public chat
4. Fetch messages
5. Mention @pavlo user and send message with mention
6. Edit message
7. Observe the result

**Actual result:** public key instead of ENS in edited message. 

https://user-images.githubusercontent.com/97245802/193865295-006fc7c5-75a6-4b80-b753-1eea7911ab18.mp4

**Comment by pavloburykh** [comment]
@audriu now I am reproducing the bug in all kinds of chats. Steps are the same as I mentioned [above](https://github.com/status-im/status-mobile/pull/14106#issuecomment-1267213880)

The problem is that ENS mention turns into 3 random name after message is sent. And after editing it turns into a public key. 

https://user-images.githubusercontent.com/97245802/194083322-bd71d4df-a87a-4708-8df8-c229d73a6916.mp4

**Comment by pavloburykh** [comment]
Hi @audriu 
Unfortunately both me and @qoqobolo are still reproducing the bug on latest PR builds.

**Comment by audriu** [comment]
Ok. Failed on this one. This PR works for me but not for QAs. I tried hard to reproduce but still works ok for me. Maybe someone with a fresh look can see wtf. Ping me if you need any help...

**Comment by Parveshdhull** [comment]
> Ok. Failed on this one. This PR works for me but not for QAs. I tried hard to reproduce but still works ok for me. Maybe someone with a fresh look can see wtf. Ping me if you need any help...

Hi @audriu, should we close this PR?

**Comment by audriu** [comment]
IDK. Maybe someone will want to see the work I have done when they start working.
I will definitely close it when it is no more relevant...

**Comment by Parveshdhull** [comment]
will be fixed in https://github.com/status-im/status-mobile/pull/14149

**Pull request closed without merging**
