### PR TITLE
Get rid of form-2 subs in defview

### PR DESCRIPTION
**Pull request by rasom**
We don't need form-2 subs and those subs cause bugs in `defview` when they have parameters. This PR solves it. Next step would be removing `defview` from code. 

status: ready

### CODE REVIEW

**Comment by flexsurfer** [comment]
i still think form-2 should be used, if you need to pass a parameter from another subscription, that means subscriptions was incorrectly designed

**Comment by rasom** [comment]
@flexsurfer please elaborate why form-2 should be used [(just reminder)](https://github.com/day8/re-frame/issues/218)

**Comment by rasom** [comment]
> that means subscriptions was incorrectly designed

We have a safe way to not care about "incorrect design" (that's kind of arguable) and bugs caused by it, so what's the reason to not use it?

**Comment by flexsurfer** [comment]
yeah i know it will work, and its not critical, it's just my personal preference, however, i don't mind to follow any team's decision, and i know most devs for removing defview, so i'll approve this PR, but suggest to replace `devfiew` by `sub` function which will deref subscription

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
> but suggest to replace devfiew by sub function which will deref subscription

that's fine, but this PR is not about removing `defview`, it just fixes all these views with frozen state.

> and i know most devs for removing defview

I would also consider some punishment for the retard who introduced `defview` in the first place

**Pull request merged**
