### PR TITLE
Add web3.keycard.signTypedData

### LINKED ISSUE #9275: Implement support for web3.keycard.signTypedData flow
# Feature Issue
One of use cases that should be supported for Keycard is pinless data signing. Signing should work with `signTypedData` API available from `web3.keycard` namespace that is equivalent to `web3.eth.signTypedData` as documented in [EIP-712](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md).

### User Story
As a user, I want to be able to use my keycard without a pin, so making transactions or payments is effortless.

### Description
This can be used in e.g. Point-of-Sale scenarios where merchant owns a device running Status and customer owns a Keycard. It would then enable using Keycard in payment card-like scenarios.

Implementation of this feature will enable the following flow for a customer purchasing goods from merchant:
  - Merchant runs a Dapp within Status
  - Customer wants to buy an item sold by the Dapp (say a cup of coffee)
  - Merchant invokes a Signature request screen from within a Dapp and asks the custom to hold his keycard against merchant's phone
  - Customer's keycard signs the hash and sends it back to the Dapp

**Context:**
  - `web3.eth.signTypedData` has been implemented earlier in https://github.com/status-im/status-react/pull/7680. 
  - a version of pinless signing has been implemented in https://github.com/status-im/web3.js/commits/sign-pinless and https://github.com/status-im/status-react/commits/experiment/sign-pinless

The flow should be the following:
  - Dapp invokes `web3.keycard.signTypedData`
  - Status intercepts the call and opens a `Signature request` screen
  - Hash is generated on the status-go side 
  - Once a card is detected, hash is sent to the Keycard
  - Keycard signs and sends back a signature
  - Pass the signature to the Dapp and show a `Signing OK` message on the screen

A signing screen should resemble the one from Metamask with a hierarchical data display
eth_signTypedData

**UPDATE:** new Figma design [here](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=4313%3A35269).

More details [here](https://notes.status.im/mkFLHD6ORzmCTRYTdk13mA)

### LINKED ISSUE #10205: Update the Keycard request screen to recognize tokens by address
# Feature Issue

The payment request screen should show the amount with decimals and the symbol of the ERC20 token used for the payment.

The current implementation shows the amount without decimals (in the screenshot below it shows 1 and 18 zeros instead of 1), and the token address (instead of showing STT, the SNT test token deployed on Ropsten).

### Acceptance Criteria

Given any token address, the request screen should show  the right amount and symbol based on the values returned after calling the `decimal` and `symbol` methods of the ERC20 contract.

### Notes

The request screen is implemented in the `feature/9275-keycard-signTypedData` branch.

Test app at https://status-im.github.io/keycard-cash-test-dapp/. It's a simple dapp we can use from the Status browser to test this feature.

### PR DESCRIPTION
**Pull request by vitvly**
Fixes #9275 
Fixes #10205 

Without amount: https://drive.google.com/open?id=14FdIJHzTFJlCrwLXjhyTOka1ECl2dFlB
With amount: https://drive.google.com/open?id=1x18JVhYUk359OKaeseiRRtQxQk5kwyo1

### CODE REVIEW

**Comment by flexsurfer** [comment]
@siphiuel is this still relevant?

**Comment by vitvly** [comment]
@flexsurfer yes

**Comment by flexsurfer** [comment]
@siphiuel is this still relevant?

**Comment by vitvly** [comment]
@flexsurfer yes

**Review by rasom — APPROVED** [review]

**Comment by churik** [comment]
@Ferossgp I suppose that it should be tested after merge of https://github.com/status-im/status-react/pull/10015, WDYT?

**Comment by churik** [comment]
@siphiuel please rebase to current `develop` and I'll check PR.
https://github.com/status-im/status-react/pull/10015 is merged.

**Comment by churik** [comment]
@siphiuel 
Can't install app (Got `App is not installed`)

**Comment by churik** [comment]
Blocked by #10178

**Comment by churik** [comment]
@siphiuel please rebase to current develop

**Comment by vitvly** [comment]
@churik done

**Comment by churik** [comment]
@siphiuel 
I don't see status of aend transaction screen - it is hidden below bottom sheet.
photo_2020-03-19 11 05 10
So can't sign any transaction

**Comment by vitvly** [comment]
Tried both in dev mode and in PR build, and it works for me. Tried Ropsten though. Weird.

**Comment by churik** [comment]
Reckecked on last build with https://github.com/status-im/status-react/commit/21ecc7d7f6b5f031784e81ccbef56e2987038fde on Android 10 on new account with Ropsten network.
Reproducible for me on Android 10/ Xiaomi mi note 9.
After tappting Sign up with keycard can see only top of the bottom sheet like in https://github.com/status-im/status-react/pull/9390#issuecomment-601093511

**Comment by vitvly** [comment]
Found an issue, fixed, sorry @churik for back-and-forth.

**Comment by churik** [comment]
@siphiuel tried https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200319-195734-2a295c-pr-universal.apk on Android 10 - got "App is not installed", and on Android 8 - it can be installed, but at attempt to start I've got "App is not responding"
After 2 attempt I can start app on Android  8, but still no success with installation on Android 10. 
Can sucessfully install on same device Status nightly or PR build i.e. from https://github.com/status-im/status-react/pull/9800.
Logcat from Android 10: 
[logcat_10.log](https://github.com/status-im/status-react/files/4368626/logcat_10.log)

**Comment by Serhy** [comment]
Hm.. I can install and run app on Android 8 and 9 fine with this  https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200319-195734-2a295c-pr-universal.apk  build

**Comment by churik** [comment]
Finally I've managed to install it, sorry for confusion.

**Comment by churik** [comment]
Tested on DApp https://status-im.github.io/keycard-cash-test-dapp/ - can sign provided transation.
But I don't see it in Transaction history and changing account for provided DApp seems has no effect - with 0 STT I still can sign transaction.

@siphiuel can you please provide details where I can track this transaction?

**Comment by churik** [comment]
As it turned out, all that I can test it is message signing, it is working.

**Comment by guylouis** [comment]
@siphiuel what is missing here ? thanks

**Comment by vitvly** [comment]
@guylouis found one more issue after rebase, fixing it, then will merge.

**Pull request merged**
