### PR TITLE
Render chat formatting natively

### LINKED ISSUE #8263: Heavily formatted messages slow down message rendering
**_Type_**: Bug

**_Summary_**: When there is a message which requires formatting in chat, it appears on chat view much longer than plain-text messages. More items in a single message require formatting - exponentially more time for message to be parsed and displayed to user. 
When messages are really large and there are a lot of items to process - app freezes during that time (below figures are app-freezes values)

For example, on Samsung Galaxy Note 4 (Android 6.0.1) - slow device:
1) The time it takes for a single message having 100 links and 1000 chars in total (including whitespaces) when navigating from Chats view to public chat with the message -> ~3.5 seconds
2) Same number of characters but when no any formatting is applied to message content takes <0.3s 
3) 5 messages with 200 chars and 20 links each (so 1st case above but split in 5 messages) - takes ~2 seconds for messages to appear
4) 5 messages with 200 chars each (so 2nd case above but split in 5 messages) - takes <0.3 seconds for messages to appear

#### Expected behavior
When user of the `Samsung Galaxy Note 4`-like device navigates to chat with the single message which has any type of formatted text (bold, italic, backquoted, link, tag) repeated 250 times with 2500 chars in total, the time it takes from chat view (actual chat, excluded navigation between 'Chats' -> 'Chat') and the actual message content to appear - is less than 0.3s

#### Actual behavior
When user of the `Samsung Galaxy Note 4`-like device navigates to chat with the single message which has any type of formatted text (bold, italic, backquoted, link, tag) repeated 250 times with 2500 chars in total, the time it takes from chat view (actual chat, excluded navigation between 'Chats' -> 'Chat') and the actual message content to appear is:

| Text | Links | Tags | Bold | Italic | Backquotes | Mix of everything (without text) |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| <0.3s | 26s | 26s | 16s | 16s | 26s | 23s |

VIdeo for above measurements from Galaxy Note 4: https://drive.google.com/file/d/1-0rUsqj5_OjK1HiDqu-AXYLylvyt_ezD/view
Message content used in Video you can get here: https://docs.google.com/spreadsheets/d/1pXvXuwZ0AR-pJ5BPsiZL1a1V5LajLMQAeBd6FsMUN_o/edit?usp=sharing 

### Reproduction

* Open Status and create new account
* Join unique public chat 
* Send message with text required formatting (you can get data from the above link)
* Navigate back to Chats view
* Navigate to chat with the message sent and pay attention until message appears

### Additional Information

* Status version: Develop0.13.0/Release0.12.2
* Operating System: Android and iOS and Desktop

### PR DESCRIPTION
**Pull request by mandrigin**
fixes #8263

What to test:
- Heavily formatted messages (bold, italic) (`#test2` channel)

see the changes here: https://github.com/status-im/react-native/commit/c005d3125e1424a8fb6929b87408f8e7568142e9

status: ready

### CODE REVIEW

**Comment by mandrigin** [comment]
@annadanchenko that is how formatting looks like now: 
image
that's expected

**Comment by yenda** [comment]
Italic is done with tildes '~' in status-react is the change to underscores intentional? 
Also the formatting chokes on messages much longer than the one in the exemple

**Comment by mandrigin** [comment]
@yenda see `#status-core-ui`.
Tildas mean ~strikethrough~(`~strikethrough~`) in markdown, and undescores mean _italic_(`_italic_`), so yes, that is intentional. Re: choking, can you give me an example chatroom with a message like that?

**Comment by mandrigin** [comment]
progress on Android side
image

**Comment by mandrigin** [comment]
@annadanchenko Android should be fully functional at that moment.

@yenda can you send me a link to the chat where this formatting chokes?

**Comment by yenda** [comment]
The #test2 channel from June 5 contains loads of big formatted message, though it barely takes more than a second on my phone so I think it's more obvious on low end devices

**Comment by yenda** [comment]
I tested on Android and this PR doesn't render #test2 the app stops responding

**Comment by yenda** [comment]
Not that the current is much better it does render but it takes a while

**Comment by yenda** [comment]
The PR did render after restart but not much faster than develop. Not sure how you implemented it exactly but would this mean that even native is bad with heavy styling? In that case our best shot would be to use the same approach as with long messages and show less

**Comment by mandrigin** [comment]
@yenda if you don't use a new account at the moment, it will re-use the old (stored in the db) message chunks, so essentially it won't do any formatting natively.
Are you trying on a new account?
It's a WIP PR so I didn't bother about migration just yet.

**Comment by mandrigin** [comment]
also, take into account that it renders 1.5 screen of messages now and not a single message as the old version.

**Comment by annadanchenko** [comment]
@mandrigin waiting for builds to be fixed (build 4 for all platforms failed)

**Comment by yenda** [comment]
After a cold start when the messages are already in db and with an account that only has #test2 channel it takes
- 17s in PR to show the messages after tapping chat
- 30s in develop

So there is an improvement there but still not satisfying enough to call the problem solved because the chat opening shouldn't be disruptable with a single bad message.

Could you also describe how this is implemented natively? I suppose it won't be as easy to expand the markdown support as it is right now?

**Comment by mandrigin** [comment]
@annadanchenko pushed the fix

**Comment by yenda** [comment]
Btw links are not supported in PR this is a blocker

**Comment by mandrigin** [comment]
@yenda it is a WIP pr, just for your information.

**Comment by mandrigin** [comment]
also, links are working already.

**Comment by yenda** [comment]
@mandrigin yes I know you already said that and it's in the title :D I am just giving feedbacks. 

In order to be more fair to your PR in testing you could try only pass the content and not all the stuff related to parsing to the flatlist because that takes bandwidth in the bridge and it's not useful to you

**Comment by yenda** [comment]
Links don't work in build 3, maybe in 5 when it's ready

**Comment by yenda** [comment]
@mandrigin also could this be done as a react-native lib? I don't think upstream will want to merge it considering their current policy of making core as small as possible

**Comment by mandrigin** [comment]
@yenda that isn't easy, because text views get some special treatment from RN to be self-sizeable.

**Comment by mandrigin** [comment]
@annadanchenko okay, attempt no next to fix stuff.

**Comment by yenda** [comment]
Links are working better than in develop now, they can get formatting as well while before they wouldn't be treated as link which is cool.

Still worried about it being a fork of react and not a lib and still unsatisfying perfs

**Comment by mandrigin** [comment]
@yenda I'm not a big fan of patching react native too, if it would be reasonable to avoid it w/o writing a ton of code, I'll do that. For perf measurements, we will see, I need to look at it under profiler, though unlikely my code is that slow, it is a single loop.

**Comment by yenda** [comment]
@mandrigin I looked at your code already and I doubt it has anything to do with the perfs, I think it is either the bridge or the native renderer that chokes on the workload with complex messages. For the bridge there is Snoopy that Roman will write a guide on, or simply remote JS debugging which should help see what goes between the js and native realms.

**Comment by annadanchenko** [comment]
@mandrigin 
1. Error NoSuchKeyException and crash on attempt to delete chat

Steps: Open public chat, e.g. status tap ... and select Delete Chat
Does not happen in last nightly. Galaxy Note 4, Android 6.0.1
```
06-13 16:55:33.980 12574 14331 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
06-13 16:55:33.980 12574 14331 E AndroidRuntime: Process: im.status.ethereum.pr, PID: 12574
06-13 16:55:33.980 12574 14331 E AndroidRuntime: com.facebook.react.bridge.NoSuchKeyException: lineNumber
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:124)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:128)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:182)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
06-13 16:55:33.980 12574 14331 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)

```

**Comment by annadanchenko** [comment]
@mandrigin 
2. Link with two "-" gets italic formatting and no - shown (but it's still valid if open it)
Link https://status.im/build_status/desktop_troubleshooting.html
Screenshot_2019-06-13-20-10-54

**Comment by mandrigin** [comment]
@yenda @annadanchenko I double-checked on a release build under profiler, and that is a native Android `TextView` that is being extremely slow there.

So we probably need to limit this formatting abuse.

image

**Comment by mandrigin** [comment]
Okay, it looks like that is because of how i hide formatting characters. I temporarily disabled it and it made opening `#test2` chatroom much faster for me.

**Comment by mandrigin** [comment]
@annadanchenko can you compare it to `develop` now?

**Comment by yenda** [comment]
@mandrigin works really fast for me the chat starts showing messages in 1 sec instead of 17 before and 30 in develop

**Comment by mandrigin** [comment]
@yenda thanks for the confirmation, I see the same in the Genymotion, a bit less than 1 second to render messages.

Now I need to figure out a better way to hide formatting characters :-D

**Comment by yenda** [comment]
@mandrigin can you give them background color?

**Comment by mandrigin** [comment]
@yenda what do you mean?

**Comment by mandrigin** [comment]
tbh, I would avoid formatting them at all, I tried changing the size to 0, it did hide them, but was super inefficient. If I would be able to actually remove them, it would be cool.

**Comment by yenda** [comment]
@mandrigin I mean you give them the same color as the background so they become invisible but they are still there

**Comment by mandrigin** [comment]
@yenda that will keep blank spaces and I'm  pretty  sure  it  is  annoying to  see spaces  of different  length.

**Comment by yenda** [comment]
Better to try and see, it will be convenient to copy paste at least

**Comment by mandrigin** [comment]
but copy-pasting will use the JS model, so if I remove these chars from the view it should't change anything.

**Comment by mandrigin** [comment]
@annadanchenko now iOS version should parse everything too... I will take a look at the crash, but I think I would like to see some feedback on regressions on the iOS side. I will do some profiling later today too.

**Comment by mandrigin** [comment]
rebased to fix android builds

**Comment by annadanchenko** [comment]
@mandrigin no new regressions on ios found (build 9)

**Comment by mandrigin** [comment]
@annadanchenko I can't reproduce the Android crash myself on Android 9 at least.

**Comment by annadanchenko** [comment]
> @annadanchenko I can't reproduce the Android crash myself on Android 9 at least.

Can reproduce using Android build 10 on real Pixel XL Android 9. 

Steps:
- install app
- create new account
- join #status chat
- wait for chat to be synced, do not do anything else
- tap on ... and tap Delete chat -> error is shown and app crashes

Log: 
[Status.log](https://github.com/status-im/status-react/files/3301462/Status.log)

**Comment by mandrigin** [comment]
@annadanchenko it looks like that is a RN issue fixed in the later release, I pushed the updated version, please re-check when Android builds

**Comment by annadanchenko** [comment]
Issue with crash is fixed, tested in Android build 12.
### issue 3 Bold and Italic is not shown on Android if use several lines
```
*line1 bold*
_line2 Italic_

*line 3 bold*
_line 4 italic_

_You *can* combine them_
```
See last message on the screenshot  below on how it looks like now in Android build 12. Would expect:
 - bold lines are 1 and 3
- italic are 2 and 4
- last line is italic and bold for "can" and italic for the rest (works fine on iOS build 12)
Screenshot_20190618-160523

**Comment by annadanchenko** [comment]
### Issue 4 Several ` are not handled well ( symbol | is shown, no quote)

* If two `` are used 
```
``
New Line between two symbols from each side
``
```
on iOS | is shown and no quote for the line:



on android empty line goes first then text then two symbols `` and no quote 
Screenshot_20190618-174701

* If three ``` are used and line between them

on iOS last two `` are not shown in beginning and et the end (expecting that one ` is used to make a quote and everything between two quotes is left untouched)


on Android  no quote markup is shown, one ` is in the begging and two `` are at the end
Screenshot_20190618-180322

**Comment by mandrigin** [comment]
@annadanchenko new build should solve most of the issues on Android.

**Comment by annadanchenko** [comment]
### Issue 5 Link with underscore is transformed if there is _text before it on Android and iOS
Note that on iOS handling of links with underscore is not fixed yet, so https://github.com/status-im/status-react/pull/8410#issuecomment-501820970 still exists on iOS

1. Send to chat
```
_some text https://status.im/build_status/desktop_troubleshooting.html
```
2. check how it looks like 
Screenshot_20190619-113408

**Comment by annadanchenko** [comment]
@mandrigin can you clarify what to expect in these cases, please?
1. \` one \`
2. \`` two \``
3. \``` three \```
4. \```` four \````
5. \````` five \````` 

this what happens on Android build 13 now
mm

on iOS, build 13:
iosmm

**Comment by mandrigin** [comment]
iOS isn't ready yet. spaces work only when they are attached (unless it is three ticks).

`* bold *` shouldn't format anything where `*bold*` should.

an exception is ```, which considers anything between them as code.

so Android is right.

**Comment by annadanchenko** [comment]
ok, on Android without spaces between ` and word
andr_no spaces

**Comment by mandrigin** [comment]
@annadanchenko yep, that is what is expected, 4 quotes aren't rendered exactly properly, but that is a minor edge case, I'd say.

**Review by rasom — APPROVED** [review]

**Comment by mandrigin** [comment]
Some screenshots:
Simulator Screen Shot - iPhone 8 - 2019-06-20 at 13 06 52

Simulator Screen Shot - iPhone 8 - 2019-06-20 at 13 07 16

**Review by jeluard — APPROVED** [review]

**Comment by annadanchenko** [comment]
build 20 Android and build 25 iOS:

_two__underscores__are__deleted_ transforms to _twounderscoresaredeleted_ I would expect inner underscores to remain so _two__underscores__are__deleted_

**Pull request merged**
