### PR TITLE
Upgrade status-go to 0.56.8

### LINKED ISSUE #11068: Message counter not clears after reading message and relogin to account
# Bug Report

## Problem

There is a specific condition when message unread counter shows in 1-1 chat while all messages are read. 
I noticed it reproduced when contact receives message, sends message and then taps 'Add to contacts' (see steps to reproduce)
Note: if for above case this contact sends a couple of messages to buddy in 1-1 then after re-login unread message counter clears. But if to not send - any relogin doesn't make a difference.
Also, 'Read all messages' options helps in that case.

#### Expected behavior

No unread message counter after all message were read

#### Actual behavior

Unread message counter persists after relogin after all message were read 

ezgif-4-aeacae9eb2d5

### Reproduction
- Create two new accounts: UserA and UserB
- UserA adds UserB by scanning it's QR code
- UserA taps 'Add to contacts' and sends text message to UserB
- UserB opens 1-1 chat with received message and sends text message to UserA
- UserB taps 'Add to contacts' option
- UserB relogins to account 

### Additional Information
- Status version: release/develop 1.5
- Operating System: Android and iOS

Logs:
[unreadcounter.txt](https://github.com/status-im/status-react/files/5057222/unreadcounter.txt)

```
.....
.....

08-11 16:20:20.306 26167 26278 I ReactNativeJS: INFO [status-im.data-store.mailservers:34] - deleted gaps successfully
08-11 16:20:20.308 26167 26278 W ReactNativeJS: WARN [status-im.ethereum.json-rpc:212] - :json-rpc/error wakuext_markMessagesSeen :error {:code -32000, :message "sql: Scan error on column index 9, name \"last_message\": unsupported Scan, storing driver.Value type []uint8 into type *protocol.Message"} :params ["0x044db546bb65e4f25fd5d9101c292b8a10a7ca56d849b3f9e286583a2ff6231699c065c710446dcc3ed304f237029f70f15ce4165aa08116c4f4bf838e99e095a8" #{"0x736f3e1c34c3e2fb2b160d6a22eb854e8e768c76b15b4aaf319bebd1fd058889"}]
...
...
...
```

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #11068

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@cammellos it includes only fix for counter or some other updates of status-go as well?

**Comment by cammellos** [comment]
@churik only fix for counter

**Comment by churik** [comment]
Tested on IOS 13 and Android 10:

- issue is fixed
- https://github.com/status-im/status-react/issues/10798 is still reproducible
- unread counter is updated when going from offline, from the background, when relogin for all types of chats
- device pairing and message counter for group chats, 1-1 chats (no unread counter for own message, updated when receive new message)

**Comment by cammellos** [comment]
Closing as fixes contained in different PR

**Pull request closed without merging**
