### PR TITLE
Fix searchbar show/hide logic

### LINKED ISSUE #7697: Search bar animation behavior
# Problem
The Status Home tab (soon to be Chat) has a searchbar implemented. This searchbar allows to find chats in the chat list and will in the near future also enable finding messages. 

The searchbar was originally intended to behave like: https://www.dropbox.com/s/xyf77rl9jvesh1y/ScreenFlow%20copy%203.mp4?dl=0

For the most part this behavior has been implemented. There are a few issues that remain:

* Search bar does not appear second (or more) times after pull Home screen down gesture been done while Search bar is present on screen: https://github.com/status-im/status-react/issues/7676
* It's cumbersome to hide the searchbar during inactivity, after it's been pulled down in view: https://github.com/status-im/status-react/issues/7643
* More detailes on expected behavior https://github.com/status-im/status-react/issues/7643#issuecomment-468648407

To fix these issues the implementation needs to be adapted and potentially the searchbar needs to be reimplemented in full. 

# Implementation
[@yenda please edit]

# Acceptance Criteria
Implementation solves issues above and behaves like example video when it comes to appear/disappear behavior.

# Notes
# Future Steps

### PR DESCRIPTION
**Pull request by vkjr**
fixes #7697

### Summary

Searchbar now appears when user overdrags chats list and disappears when user scrolls down

https://youtu.be/r8nhTZx_lE4

#### Platforms
- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- open chats list
- scroll uplist to show searchbar
- scroll down list to hide searchbar

status: ready

### CODE REVIEW

**Comment by vkjr** [comment]
@errorists, could you please take a look? Link to screen recording in description.

**Review by flexsurfer — APPROVED** [review]

**Comment by vkjr** [comment]
Tested on ios:
- account can be created
- account can be recovered
- can join public chats and 1-1
- searchbar shows when overdrags chat list
- searchbar hides when scolls chat list down

**Comment by flexsurfer** [comment]
hey @vkjr for such issues we need approve from design and qa teams before merge

**Comment by flexsurfer** [comment]
cc @hesterbruikman @churik @errorists

**Comment by vkjr** [comment]
@flexsurfer, I talked to @churik and she confirmed that e2e tests result for this PR is fine. And as far as I understood we don't require manual qa for small fixes like this. Please correct me if I'm wrong.
As for design approve - my bad.

**Comment by errorists** [comment]
Guys, the implementation is wrong I don’t approve it

**Comment by hesterbruikman** [comment]
@vkjr tried on Android Galaxy S10e. I can't manage to get drag the search bar down down to appear. Can anyone else confirm Android behavior?
https://file.globalupload.io/gclEeFbL4r.mp4

**Comment by vkjr** [comment]
@hesterbruikman, @flexsurfer, @errorists 
Prepared PR to undo changes - #9679

**Pull request merged**
