### PR TITLE
Dropping support for ARM32 iOS devices

### PR DESCRIPTION
**Pull request by jakubgs**
With upgrade to Go and Gomobile we now drop support for `darwin/arm32` builds.
This means all devices like iPhone 5 or older.

### CODE REVIEW

**Comment by jakubgs** [comment]
What I'm wondering is whether we should also disable arm32 builds in XCode configuration:

image

**Review by shivekkhurana — APPROVED** [review]

**Comment by Serhy** [comment]
hey @jakubgs, while on Android (6 and higher) all fine, - but the app crashes on launch on iOS (iOS14), - confirmed with iPhoneX and iPhone11.
To reproduce:
1) Install latest build https://i.diawi.com/9ouEjK
2) Open Status app

Logs from console: 
[iPhoneConsoleCrash2.log](https://github.com/status-im/status-react/files/6391889/iPhoneConsoleCrash2.log)

**Comment by jakubgs** [comment]
Thanks for checking @Serhy. So it looks like this might require some additional fiddling with XCode build settings.

**Comment by Serhy** [comment]
Latest build `0a18197` has the same behavior, - Status crashes once launched: logs are here 
[ios_crash_2.log](https://github.com/status-im/status-react/files/6404626/ios_crash_2.log)
(they are looking like the same, well it's the only logs I'm able to gather from console)

**Comment by jakubgs** [comment]
Some things I tried:

* Removing `armv7` and `armv7s` from `VALID_ARCHS` in `ios/StatusIm.xcodeproj/project.pbxproj`
* Removing all `VALID_ARCHS` settings from `ios/StatusIm.xcodeproj/project.pbxproj`
* Selecting the `Build Active Architectures Only` option in `Architectures` section

None seem to work. I might try reverting 6a677fc3e just to verify that it's the Go update that caused this issue.

**Comment by jakubgs** [comment]
I have dropped 6a677fc3e1dabf323419ec4e2616fa2e597de81e commit temporarily that upgrades Go to `1.16` and drops ARM32 support, and I've verified that without that commit the build works fine on my iPhone 5s.

This means that the issue is clearly caused by the Go and Gomobile upgrade.

**Comment by jakubgs** [comment]
I have tested the changes that drop `armv7` and `armv7s` from XCode configuration in https://github.com/status-im/status-react/commit/1136c58f:
https://ci.status.im/job/status-react/job/manual/148/

And it worked fine on my iPhone 5s, so I don't think any of those changes had an effect.

**Comment by jakubgs** [comment]
I've built `status-go` target for iOS on my branch:

#### `nixpkgs-upgrade`
```
  > du -hsc $(nix-build --no-out-link -A targets.status-go.mobile.ios)              
 97M	/nix/store/0kwyw15dzaqyld36lbcsx16ks60k42zh-status-go-0.79.4-d1dc5f1-ios
 97M	total
```
#### `develop`
```
 > du -hsc $(nix-build --no-out-link -A targets.status-go.mobile.ios)
160M	/nix/store/vfyh6xx12vr9mvs6l6fsk6y8s43x9vrx-status-go-0.79.5-dfd4668-ios
160M	total
```

And the new bundle appears to be noticeable smaller than the old one.

**Comment by jakubgs** [comment]
The list of files looks the same:

#### `nixpkgs-upgrade`
```
 > find $(nix-build --no-out-link -A targets.status-go.mobile.ios) -type f | xargs du -hs
 97M	/nix/store/0kwyw15dzaqyld36lbcsx16ks60k42zh-status-go-0.79.4-d1dc5f1-ios/Statusgo.framework/Versions/A/Statusgo
4.0K	/nix/store/0kwyw15dzaqyld36lbcsx16ks60k42zh-status-go-0.79.4-d1dc5f1-ios/Statusgo.framework/Versions/A/Resources/Info.plist
4.0K	/nix/store/0kwyw15dzaqyld36lbcsx16ks60k42zh-status-go-0.79.4-d1dc5f1-ios/Statusgo.framework/Versions/A/Headers/Statusgo.h
 20K	/nix/store/0kwyw15dzaqyld36lbcsx16ks60k42zh-status-go-0.79.4-d1dc5f1-ios/Statusgo.framework/Versions/A/Headers/Statusgo.objc.h
4.0K	/nix/store/0kwyw15dzaqyld36lbcsx16ks60k42zh-status-go-0.79.4-d1dc5f1-ios/Statusgo.framework/Versions/A/Headers/ref.h
4.0K	/nix/store/0kwyw15dzaqyld36lbcsx16ks60k42zh-status-go-0.79.4-d1dc5f1-ios/Statusgo.framework/Versions/A/Headers/Universe.objc.h
4.0K	/nix/store/0kwyw15dzaqyld36lbcsx16ks60k42zh-status-go-0.79.4-d1dc5f1-ios/Statusgo.framework/Versions/A/Modules/module.modulemap
```
#### `develop`
```
 > find $(nix-build --no-out-link -A targets.status-go.mobile.ios) -type f | xargs du -hs
160M	/nix/store/vfyh6xx12vr9mvs6l6fsk6y8s43x9vrx-status-go-0.79.5-dfd4668-ios/Statusgo.framework/Versions/A/Statusgo
4.0K	/nix/store/vfyh6xx12vr9mvs6l6fsk6y8s43x9vrx-status-go-0.79.5-dfd4668-ios/Statusgo.framework/Versions/A/Resources/Info.plist
4.0K	/nix/store/vfyh6xx12vr9mvs6l6fsk6y8s43x9vrx-status-go-0.79.5-dfd4668-ios/Statusgo.framework/Versions/A/Headers/Statusgo.h
 20K	/nix/store/vfyh6xx12vr9mvs6l6fsk6y8s43x9vrx-status-go-0.79.5-dfd4668-ios/Statusgo.framework/Versions/A/Headers/Statusgo.objc.h
4.0K	/nix/store/vfyh6xx12vr9mvs6l6fsk6y8s43x9vrx-status-go-0.79.5-dfd4668-ios/Statusgo.framework/Versions/A/Headers/ref.h
4.0K	/nix/store/vfyh6xx12vr9mvs6l6fsk6y8s43x9vrx-status-go-0.79.5-dfd4668-ios/Statusgo.framework/Versions/A/Headers/Universe.objc.h
4.0K	/nix/store/vfyh6xx12vr9mvs6l6fsk6y8s43x9vrx-status-go-0.79.5-dfd4668-ios/Statusgo.framework/Versions/A/Modules/module.modulemap
```

It's specifically the `Statusgo` that's bigger in `develop`. Which is to be expected considering dropped architectures.

**Comment by jakubgs** [comment]
I've created a separate PR for just upgrading of Nixpkgs without upgrading Go and dropping ARM32: https://github.com/status-im/status-react/pull/12216

This should make debugging this PR simpler once it's merged.

**Comment by vitvly** [comment]
@jakubgs having issues with ios-arm builds in https://github.com/status-im/status-react/pull/12197: https://ci.status.im/blue/organizations/jenkins/status-react%2Fprs%2Fios/detail/PR-12197/10/
```

[2021-06-10T09:40:48.370Z] /nix/store/yyhkj6i0yh415n5b1cp120v7b820kdd5-gomobile-20200622-33b8054/bin/gomobile: darwin-arm: go build -tags ios -v -ldflags -extldflags=-Wl,--allow-multiple-definition -X github.com/status-im/status-go/params.GitCommit=b808a94dcf308403151783ae12011784cea3281e -X github.com/status-im/status-go/params.Version=develop -s -w -buildmode=c-archive -o /private/tmp/tmp-status-react-jenkins-status-react-prs-ios-PR-12197-10/nix-build-status-go-develop-b808a94-ios.drv-0/gomobile-work/Statusgo-arm.a ./gobind failed: exit status 2
```
Does this mean current PR will address the above as well?

**Comment by jakubgs** [comment]
>Does this mean current PR will address the above as well?

No idea. This PR upgrades to Go `1.16`, and all Go versions after `1.14` drop support for `arm32` for iOS, so if your issue is related to that architecture it might. But currently builds using `status-go` built like that just explode at startup.

**Comment by jakubgs** [comment]
Now that #12216 has been merged I've rebased this and now it's just one commit that bumps Go and disables `arm32`.

Should make it a bit simpler to debug and possibly fix. I might also be able to split it into two commits.

**Comment by jakubgs** [comment]
Holy shit! Looks like Andrea fixed this PR by combining it with his `go-ethereum` upgrade in https://github.com/status-im/status-react/pull/12288.

**Comment by jakubgs** [comment]
Since https://github.com/status-im/status-react/pull/12315 which included changes from this PR was merged this can be closed.

**Pull request closed without merging**
