### PR TITLE
[#10870] "Invalid timbre logging level" after upgrade from 1.4 to 1.4…

### LINKED ISSUE #10870: "Invalid timbre logging level" after upgrade from 1.4 to 1.4.1 or relogin on 1.4.1
# Bug Report

## Problem

After upgrade and login got an error 
IMAGE 2020-06-25 11:58:53

#### Expected behavior
can upgrade normally 

#### Actual behavior
error after upgrade

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Install 1.4 from store
- Upgrade to build from https://ci.status.im/job/status-react/job/release/job/release%252F1.5.x/
- Login

### Additional Information

- Status version:  1.4.1 (builds https://ci.status.im/job/status-react/job/release/job/release%252F1.5.x/)
- Operating System: Android,iOS

#### Logs

```
06-25 11:38:53.952 16546 16636 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :mailserver/check-connection-timeout
06-25 11:39:01.598 16546 16546 D ReactNative: ReactInstanceManager.detachViewFromInstance()
06-25 11:39:01.598 16546 16546 D StatusModule: ******************* ON HOST DESTROY *************************
06-25 11:39:01.601 16546 16636 D ReactNativeJS: DEBUG [status-im.utils.universal-links.core:186] - universal-links: finalizing
06-25 11:39:01.626 16546 16546 E ActivityThread: Activity im.status.ethereum.MainActivity has leaked IntentReceiver im.status.ethereum.keycard.SmartCard@5374d57 that was originally registered here. Are you missing a call to unregisterReceiver()?
06-25 11:39:01.626 16546 16546 E ActivityThread: android.app.IntentReceiverLeaked: Activity im.status.ethereum.MainActivity has leaked IntentReceiver im.status.ethereum.keycard.SmartCard@5374d57 that was originally registered here. Are you missing a call to unregisterReceiver()?
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1596)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1372)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1525)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1498)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1486)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:637)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at im.status.ethereum.keycard.SmartCard.start(SmartCard.java:84)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at im.status.ethereum.keycard.RNStatusKeycardModule.onHostResume(RNStatusKeycardModule.java:47)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:221)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:695)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:616)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:573)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.ReactDelegate.onHostResume(ReactDelegate.java:53)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:99)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.ReactActivity.onResume(ReactActivity.java:57)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.Activity.performResume(Activity.java:8051)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4236)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4278)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.os.Looper.loop(Looper.java:224)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:7520)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
06-25 11:39:01.656 16546 16580 W cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=0 bindings:WM  state:2 counts:0,0,1,0,
06-25 11:39:03.954 16546 16636 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :mailserver/check-connection-timeout
06-25 11:39:13.953 16546 16636 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :mailserver/check-connection-timeout
```

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #10870

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by churik** [comment]
In order to test fix, I've made [manual release build with this branch](https://ci.status.im/job/status-react/job/manual/743/parameters/)
And in this build:
photo_2020-06-26 10 17 44 jpeg 2020-06-26 10-18-14
Expected, that Log level will be disabled by default in release build and INFO in nightly / pr builds.

**Comment by flexsurfer** [comment]
thats good to know, because it was always info in release by default

**Comment by flexsurfer** [comment]
ok @churik now it works like this
1) when you run the app we set react level from config
2) when you login we set log level from multiaccount settings for both go and react

for release build default is disabled, for other builds - info

**Comment by churik** [comment]
So:
### for PR / nightly builds:
1) no way to disable Logs, in case when LOG LEVEL is set to` disabled`, it takes value from config, which is `INFO` by default.
2) setting Log level to `TRACE` or `DEBUG` works for react-native logs and for geth log

### for RELEASE builds
1) DISABLED log level by default, it means that there is no geth log at all, but in Status log you still see some rows with `ReactNativeJS: DEBUG`
So below are 2 files (in 1 case it is reopening app with DISABLED level, in 2 - with DEBUG level)

DEBUG: [StatusDebug.log](https://github.com/status-im/status-react/files/4836915/StatusDebug.log)
DISABLED: [Status.log](https://github.com/status-im/status-react/files/4836916/Status.log)

2) changing log level to DEBUG / TRACE - affects geth log.

As it was the same behaviour in 1.4. - I suggest to leave it as it is right now and create an issue about react-native logs separately.
@hesterbruikman do you mind?

**Comment by churik** [comment]
@flexsurfer let's cherry pick it and I'll start again release testing

**Comment by churik** [comment]
e2e tests are passed, results are not published https://ethstatus.testrail.net/index.php?/runs/view/5664&group_by=cases:section_id&group_order=asc

**Pull request merged**
