### PR TITLE
Update Arabic, French, Spanish(LatAm), Italian, Korean and Chinese

### PR DESCRIPTION
**Pull request by jinhojang6**
Updated the translations for the new copy

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]

**Comment by rachelhamlin** [comment]
@Serhy not a v1 blocker :)

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
@jinhojang6 what's the state of this  PR?

**Comment by jinhojang6** [comment]
@flexsurfer There are a lot of new words and sentences so I will update this PR tomorrow.

**Review by andremedeiros — APPROVED** [review]

**Comment by jinhojang6** [comment]
@churik  Does this PR need some testing?

**Comment by churik** [comment]
@jinhojang6 launching e2e will be enough, I'll handle this PR

**Pull request merged**
