### PR TITLE
[#8939] hide keycard options on ios

### LINKED ISSUE #8939: Hide Keycard options from iOS onboarding + account explorer
PLACEHOLDER

# Problem

Keycard is only eligible for Android devices. 

> Until June this year it was impossible at quite low level for iOS to interconnect with a smartcard like ours. iOS enabled it then in beta. HOwever we have not started the swift SDK that will allow to integrate keyacrd with status. So:
> - today only status android works with keycard
> - we have some work to do to have status iOS to work with keycard
> - the fact that it seems that your keycard works with iOS is because your iPhone might detect the keycard, but it actually can't do anything with it (at most it can pop up the app store on status for now)

## Implementation

Hide any instance of keycard from iOS. For example, during onboarding, the user does not need an option for how to encrypt their key.

https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A15991

## Acceptance Criteria

Rules for the future PR to be accepted.

## Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

## Future Steps

Steps which should be taken after this issue has been resolved.

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #8939

### Summary

Hide keycard options on ios devices since it's only supported on android yet.

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
@dmitryn 
all labels in screens during onboarding are messed up on IOS.

IMG_6423
IMG_6422

**Comment by dmitryn** [comment]
@churik fixed, please take a look

**Comment by churik** [comment]
@dmitryn 
Tested on IOs 11.4.1 that https://github.com/status-im/status-react/pull/8971#issuecomment-530784046 is fixed and there is no option "Keycard" in profile.
For Android I'm not able to set up account with keycard (it is freezing on "Finish up" stage), but it is the same as in nightly.
I think that it is a separate issue.

Is this issue logged?

**Comment by dmitryn** [comment]
@churik keycard integration isn't working in develop/nightly. It will be fixed here https://github.com/status-im/status-react/pull/8764

**Review by yenda — APPROVED** [review]

**Comment by yenda** [comment]
@dmitryn or @jakubgs please merge this we can't

**Comment by dmitryn** [comment]
```
remote: error: GH006: Protected branch update failed for refs/heads/develop.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:status-im/status-react.git
 ! [remote rejected]     develop -> develop (protected branch hook declined)
error: failed to push some refs to 'git@github.com:status-im/status-react.git'
```

**Comment by dmitryn** [comment]
@yenda i cannot merge with script for some reason

**Comment by yenda** [comment]
@dmitryn yeah because your profile is private https://prnt.sc/p5npk7

**Pull request merged**
