### PR TITLE
fix #9003 Recover deleted translations

### LINKED ISSUE #9003: Recover deleted translations
# Problem

this commit removed translations that shouldn't have been removed 7ba83bde74687942c81f015806e4802939d41b6a

## Implementation

recover the following labels:
- not-sent-click
- not-sent-tap
- sent
- sending

### PR DESCRIPTION
**Pull request by yenda**
fix #9003 

## Summary 

replace i18n/message-status-label by regular label to avoid repeating this issue in the future

recover the following labels:
- status-not-sent-click
- status-not-sent-tap
- status-sent

## Testing

apk tested on Android, no more missing label on different message statuses

status: ready

### CODE REVIEW

**Review by vitvly — APPROVED** [review]
We also generate labels in Onboarding views like here https://github.com/status-im/status-react/blob/90b31df572bca733418d804af92f7b7f06fdd165/src/status_im/ui/screens/intro/views.cljs#L309. I can fix this myself - if I understand correctly, we should not use dynamic translation label generation?

**Comment by yenda** [comment]
@siphiuel yes we should not could you list the labels that were generated and send them to me so I can check if some got removed as well?

**Comment by vitvly** [comment]
@yenda I don't think they were as i checked this in onboarding-ui PR. However, here's the list:
```
intro-text
intro-text1
intro-text2
intro-text3
intro-title1
intro-title2
intro-title3
intro-wizard-text1
intro-wizard-text2
intro-wizard-text3
intro-wizard-text4
intro-wizard-text6
intro-wizard-title-alt4
intro-wizard-title-alt5
intro-wizard-title1
intro-wizard-title2
intro-wizard-title3
intro-wizard-title4
intro-wizard-title5
intro-wizard-title6
```

**Comment by vitvly** [comment]
@yenda Oops, clicked the wrong button :)

**Pull request merged**
