### PR TITLE
Bumps galore

### PR DESCRIPTION
**Pull request by jakubgs**
This PR combines all the changes introduced in PRs crated by [dependabot](https://github.com/marketplace/dependabot-preview) from #9111 to #9130 excluding #9119 which breaks desktop builds by upgrading React. It also includes the necessary changes to `ios/Podfile.lock`.
It was created using the [`combine_prs.sh`](https://github.com/status-im/infra-utils/blob/master/github/combine_prs.sh) script with some manual intervention.

I've also added a few more changes:
* Added a `nix-update-pods` target for `Makefile`
* Upgraded Fastlane to `2.133.0`

__Note:__ There is ongoing work on batching those PRs in https://github.com/dependabot/feedback/issues/5.

### CODE REVIEW

**Comment by pedropombeiro** [comment]
Eventually some of the upgrades may lead to:
- not needing AndroidX in-place conversion done by the jetifier plugin, once the last reactnative plugin upgrades.
- updated packages supporting AutoLinking and then we can remove them from the `react-native.config.js` exceptions.

**Review by pedropombeiro — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by churik** [comment]
@jakubgs I believe this one does not require any testing?

**Comment by jakubgs** [comment]
@churik I thought it did.

**Comment by churik** [comment]
@jakubgs I mean manual testing, sorry. If it is required now we should add label `request-manual-qa` because most of PRs skip manual qa stage.

**Comment by jakubgs** [comment]
Ah, I see, sorry for not being aware of that.

**Comment by churik** [comment]
@jakubgs 
can you rebase it please to the latest `develop`?
What I suppose to check:
- android build (by e2e)
- IOS build (basic cases + a bit of exploratory testing)

**Comment by jakubgs** [comment]
@churik rebased.

**Comment by churik** [comment]
Tested on IOS 11.4.1:
- fetching messages from offline
- scanning qr codes from different parts of application
- back up seed phrase
- changing fleet / mailservers
- force logout 
- resending messages
- stickers
- webvies
- universal links
- blocking users, adding / removing from contacts
- touch id 
- validation errors

Also checked that app can be installed on Android 6 (Galaxy S7) and IOS 13 (IPhone XS)

Didn't notice regression.

**Pull request merged**
