### PR TITLE
update open-login-callback after fx/def macro fix

### LINKED ISSUE #8341: Error 'undefined is not a function...' if turn on biometric authentification
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Error undefined is not a function (near '...l(a[234]).default.$p...') is shown if enable biometric authentification on both iOS and Android real devices.
```
06-02 17:28:51.834 28464 28504 I ReactNativeJS: NAME: "TypeError"
06-02 17:28:51.834 28464 28504 I ReactNativeJS: MESSAGE: undefined is not a function (near '...l(a[234]).default.$p...')
06-02 17:28:51.834 28464 28504 I ReactNativeJS: 
06-02 17:28:51.834 28464 28504 I ReactNativeJS: izl@index.android.bundle:11:2661337
06-02 17:28:51.834 28464 28504 I ReactNativeJS: szl@index.android.bundle:11:2662372
06-02 17:28:51.834 28464 28504 I ReactNativeJS: index.android.bundle:11:1309632
06-02 17:28:51.834 28464 28504 I ReactNativeJS: b8n@index.android.bundle:11:1305280
06-02 17:28:51.834 28464 28504 I ReactNativeJS: x8n@index.android.bundle:11:1306508
06-02 17:28:51.834 28464 28504 I ReactNativeJS: F8n@index.android.bundle:11:1308645
06-02 17:28:51.834 28464 28504 I ReactNativeJS: D8n@index.android.bundle:11:1306813
06-02 17:28:51.834 28464 28504 I ReactNativeJS: index.android.bundle:11:1307850
06-02 17:28:51.834 28464 28504 I ReactNativeJS: I8n@index.android.bundle:11:1308511
06-02 17:28:51.834 28464 28504 I ReactNativeJS: n@index.android.bundle:11:1306878
06-02 17:28:51.834 28464 28504 I ReactNativeJS: y@index.android.bundle:83:657
06-02 17:28:51.834 28464 28504 I ReactNativeJS: C@index.android.bundle:83:1021
06-02 17:28:51.834 28464 28504 I ReactNativeJS: callImmediates@index.android.bundle:83:3216
06-02 17:28:51.834 28464 28504 I ReactNativeJS: callImmediates@[native code]
06-02 17:28:51.834 28464 28504 I ReactNativeJS: value@index.android.bundle:19:2873
06-02 17:28:51.834 28464 28504 I ReactNativeJS: index.android.bundle:19:1264
06-02 17:28:51.834 28464 28504 I ReactNativeJS: value@index.android.bundle:19:2565
06-02 17:28:51.834 28464 28504 I ReactNativeJS: value@index.android.bundle:19:1234
06-02 17:28:51.834 28464 28504 I ReactNativeJS: value@[native code]
06-02 17:28:51.834 28464 28504 I ReactNativeJS: value@[native code]
06-02 17:28:51.834 28464 28504 I ReactNativeJS: 
```
#### Expected behavior

[comment]: # (Describe what you expected to happen.)
toggle "Use biometric authentication" is enabled
#### Actual behavior

Error undefined is not a function (near '...l(a[234]).default.$p...')

Screenshot_20190602-173517

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Install Status and create new account
- Open Profile -> Advanced -> enable Development mode
- tap on Use biometric authentification
- check if any error is shown

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly build from 2019/06/02 03:24:41 UTC: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190602-025900-34300c-nightly.apk

[comment]: # (Android or iOS.)
- Operating System: Android 9, real Pixel XL and iOS 12.2, real iphone 7 plus 

#### Logs
[Status.log](https://github.com/status-im/status-react/files/3244937/Status.log)

### PR DESCRIPTION
**Pull request by tbenr**
just updated:
- `open-login-callback` with param destructuring after #8324
- `externs.js` after #8285 
- the way touch-id is required
 
Anastasiya edit: fixes https://github.com/status-im/status-react/issues/8341
status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by asemiankevich** [comment]
@tbenr when enabling biometric auth in profile
image
Please take a look

**Comment by yenda** [comment]
@asemiankevich isn't it reproducible in develop already?

**Comment by tbenr** [comment]
I can't reproduce it in iOS sym, moreover in this PR i modified a fx/def related to login flow, not to biometric enablement... strage...

**Comment by tbenr** [comment]
just rebased

**Comment by yenda** [comment]
@rasom could it be missing externs?

**Comment by tbenr** [comment]
@rasom @yenda 
one thing I see is that the way i require js is different from the other which use `default`:

```
(defn touchid []   (.-default (js/require "react-native-touch-id")))
```
should be:
```
(def touchid-class   (js-require/js-require "react-native-touch-id"))
(defn touchid []        (.-default (touchid-class)))
```
I think to avoid multiple requires when calling touchid multiple times.
but I don't see the connection with this issue.

**Review by mandrigin — APPROVED** [review]

**Comment by rasom** [comment]
@tbenr @yenda the way to debug such issues is to set `:pseudo-names true` in the build so that code will not be obfuscated by google closure https://github.com/status-im/status-react/blob/develop/project.clj#L116

Then error message will probably be more verbose. If that will not help I'll take a look tomorrow.

**Comment by tbenr** [comment]
i recreated the issue installing the pr build on my physical android, which is more explicit.

image

**Comment by yenda** [comment]
@tbenr  try adding `isSupported` and `authenticate` to externs.js

**Comment by tbenr** [comment]
@yenda @rasom @asemiankevich seems to work now

**Review by yenda — APPROVED** [review]

**Comment by asemiankevich** [comment]
@Serhy i think it is false fail but re-run did not help https://github.com/status-im/status-react/pull/8330#issuecomment-498127390.

**Pull request merged**
