### PR TITLE
Fix topbar in new contact

### LINKED ISSUE #11091: QR scanner issues on "Start 1-1 chat" and "Add new contact" screens
# Bug Report

## Problem

Two issues:
1. No QR scanner button on "Add new contact" screen;
2. QR scanner button doesn't work on "Start 1-1 chat" screen.

Regression from [Use topbars from Quo](https://github.com/status-im/status-react/pull/11050)

#### Actual behavior

**1.** 
photo_2020-08-17_17-52-14
**2.** 
Screen Shot 2020-08-17 at 6 04 23 PM

### Additional Information

- Status version: Nightly 17/08
- Operating System: Android, iOS

@Ferossgp

### PR DESCRIPTION
**Pull request by Ferossgp**
Use the new topbar props for `Add new contact` screen

Fixes #11091

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
Failed e2e are not related to PR

**Comment by churik** [comment]
@qoqobolo please, check here also QR code scanner in "Add watch-only account" - it is not working as well on develop

**Comment by qoqobolo** [comment]
@churik you're right, QR code scanner in "Add watch-only account" is not working.
@Ferossgp could you fix it as part of this PR?

**Comment by Ferossgp** [comment]
@churik @qoqobolo fixed

**Pull request merged**
