### PR TITLE
Fix ens names & group chat add-members

### LINKED ISSUE #9815: ENS name of added contact is lost after re-login
# Bug Report

## Problem

When I add a contact finding ENS name, as soon as this contacts adds me in contact list then next time I login to account I don't see ENS name on this contact

#### Expected behavior

ENS name kept after re-login
#### Actual behavior

ENS name of added contact is lost after re-login 

VIdeo: https://drive.google.com/file/d/1aIyyyEtAUdQzS4hbvyZVAYyPxCEejr4U/view?usp=sharing

### Reproduction

- Open Status and recover and account having ENS name (UserA)
- UserA: Add ENS name 
- Create another account (UserB)
- UserB navigates to `+` -> `Start new chat` and searches UserA by entering his ENSname
- UserB sends a text message to UserA
- UserA adds UserB to in contact list by tapping `Add to contacts`
- UserA re-logins to account and checks whether ENS name is still present

### Additional Information

- Status version: develop  `0.14.0 (2020011302)`
- Operating System: Android and iOS

### LINKED ISSUE #9831: "Cannot read property 'toLowerCase'" app crash when tap Add members from `Group Info` view
# Bug Report

## Problem
Crash with error `Cannot read property 'ToLowerCase' of null` on attempt to add members in Group Chat (doesn't matter whether contacts exist to be added or not)

#### Expected behavior
can add member

#### Actual behavior
(iOS view) 
Screenshot 2020-01-15 at 13 41 44

### Reproduction

- Open Status and create new account (UserA)
- UserA adds different user (UserB) in contacts (you may use this public key `0x0490cbe3b256fb631e7c08de7fabf4e93b6857db9e1653ff590c4df7388f9634669932b4388a48cf5020df773c5c1590ffe872e67eca997bfeff02caeea478f014`)
- UserA creates Group Chat with UserB
- UserA from GroupChat navigates to: top-right `...` menu button -> `Group info`
- UserA taps `Add members` button

### Additional Information

- Status version: nightly 15/01/2020
- Operating System: Android and iOS

#### Logs

[Status.log](https://github.com/status-im/status-react/files/4064693/Status.log)

### PR DESCRIPTION
**Pull request by cammellos**
fixes: #9815 
fixes: #9831

status: ready

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] **Docs**: Updated the [documentation](https://status.im/build_status/), if affected
- [ ] **Docs**: Added or updated inline comments explaining intention of the code
- [ ] **Tests**: Ensured that all new UI elements have been assigned accessibility IDs
- [ ] **Tests**: Signaled need for E2E tests with label, if applicable
- [ ] **Tests**: Briefly described what was tested and what platforms were used
- [ ] **UI**: In case of UI changes, ensured that UI matches [Figma](https://www.figma.com/)
- [ ] **UI**: In case of UI changes, requested review from a Core UI designer
- [ ] **UI**: In case of UI changes, included screenshots of implementation

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@cammellos when I start 1-1 chat with valid ENS name, it is still lost after I reopen app.
Shouldn't it be fixed here?
screencast 2020-01-16 17-41-10

**Comment by cammellos** [comment]
@churik I only fixed the scenario described by @Serhy , I will take a look at this one as well

**Comment by churik** [comment]
@cammellos thanks!

**Review by yenda — APPROVED** [review]

**Comment by cammellos** [comment]
@churik should be fixed in the latest build

**Comment by churik** [comment]
@cammellos 
in PR https://github.com/status-im/status-react/issues/9819 becomes more visible.
So in nightly ENS names of others bacome visible after you set own ENS name, on PR they are not visible at all.
Steps are:
- set ENS name 
- join public chat #status 
On nightly you'll see ENS names of others.
In PR - no.

**Comment by churik** [comment]
Issue https://github.com/status-im/status-react/pull/9836#issuecomment-575567672 is not reproducible 100% as it turned out, so will be tackled separately in https://github.com/status-im/status-react/issues/9819.

All described issues are fixed.

**Comment by cammellos** [comment]
Hold on on merging this as still testing some stuff and status-go PR needs merging

**Pull request merged**
