### PR TITLE
[#10860] Rename and move Access keys in onboarding

### LINKED ISSUE #10860: Rename and move Access keys in onboarding
# Problem
The current onboarding flow offers a shortcut to `Access key` in case users already have an account they would like to import. 

Access key can be interpreted as a noun. This has happened at least on occasion: User on discuss: "Currently, if you have more than one “access key” in the Local Status". It can also lead to erroneous translations.

## Solution
- Rename `Access key` to a more accurate and explanatory `Access existing keys`
- Move the button to the `Get your keys` section of Onboarding to more clearly differentiate between a new keypair and using an existing, by placing the options alongside each other
- Replace `Access key` on `Your keys` screen and unlock screen. Copy to be defined

Designs on [Figma](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4540%3A12178)

Frame 164

## Acceptance Criteria
Follow Figma design

## Notes
Issue pairs well with #10220 and #10724

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #10860

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Comment by oskarth** [comment]
Small request - could you please rebase to latest master so this commit https://github.com/status-im/status-react/commit/b5fda1234e5447cbc626059dfc78fcfbabc9e926 gets included? This means we aren't running E2E tests on eth.prod cluster anymore, and since this happens on every push, the impact is quite big. This ensures we have more accurate metrics going forward from Jul 1 onward, which would be awesome. See https://discuss.status.im/t/user-growth-and-retention/1782 for more

EDIT: Since this is a recent PR, it might've been included already. All good if so

**Comment by churik** [comment]
@flexsurfer 
'Get your keys' is not styled (not sure that it is current PR, compared with latest nightly) :
photo_2020-07-01 14 47 14 jpeg 2020-07-01 14-47-34

**Comment by Serhy** [comment]
@churik styling should be fixed in https://github.com/status-im/status-react/pull/10900

**Comment by churik** [comment]
@flexsurfer please mind my commits when merging.
Thank you!

**Review by churik — APPROVED** [review]

**Pull request merged**
