### PR TITLE
[#10969] Replace account cards in wallet with account list layout

### LINKED ISSUE #10969: Replace account cards in wallet with account list layout
# Problem
In case of accounts with high value (e.g. a watch-only account kept on cold storage), the value exceeds the card width and pushes the share icon out of view

Screenshot!UNITO-UNDERSCORE!20200716-225553!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!01

A list layout is better suited to accommodate accounts of different values.

Design on [Figma](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=9777%3A37903)

* [ ] Address is displayed in Inter Status
* [ ] `...` calls bottom sheet with option to `Send` > `Request` > `Share`
* [ ] `Request` calls tx request flow. This is currently not the case
* [ ] adapt design for Keycard accounts; design TBD

## Future Steps

### PR DESCRIPTION
**Pull request by tbenr**
fixes #10969

status: ready

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @tbenr is it still wip ?

**Comment by tbenr** [comment]
hi @flexsurfer yes, I'll move forward this weekend.
btw considering https://github.com/status-im/status-react/issues/10969#issuecomment-691073632 do we need to wait a new design?

**Comment by flexsurfer** [comment]
> btw considering #10969 (comment) do we need to wait a new design?

no we don't:)

**Comment by tbenr** [comment]
https://youtu.be/1H-DLTejOaU

@Ferossgp hi man, i took some of your code from the intro to put the dot pages, but i get a strange behaviour (they initialize with the opposite color) i'm trying to find out what's the problem. Any hint is appreciated if you have time :-)

**Comment by Ferossgp** [comment]
Hi @tbenr! 

Yeah, that's strange - for some reason the `mix-color` picks the wrong value, I see the correct value in `active` after exec. For this case you can use a simple view and replace color in a `if`. I used the animated value because the size of bullet also changes in the intro.

**Comment by tbenr** [comment]
@Ferossgp thanks for the hint, i switched to a non-animated version. The reason why `mix-color ` wasn't working is a mystery.

**Comment by tbenr** [comment]
@flexsurfer this is now ready to be reviewed.
I cant test keycard accounts since nfc of my phone is gone 😞 

@hesterbruikman i haven't integrated the "receive flow" in the bottom-sheet. should be part of this pr?

**Review by flexsurfer — APPROVED** [review]
sorry for the delay :(

**Comment by qoqobolo** [comment]
@tbenr thanks for your work! Can I ask you to rebase it to develop, please?

**Comment by tbenr** [comment]
@qoqobolo Hi, done!

**Comment by churik** [comment]
@tbenr awesome work!
Several questions / improvements:
## ISSUE 1: No 'Keycard' icon on account

**Steps:**

- create multiaccount with keycard
- open wallet
 **Expected result:** keycard account is marked
 **Actual result:**
IMAGE 2020-10-28 11:53:48


## ISSUE 2: Too dark button in dark mode 
Is it OK @errorists ?

## ISSUE 3: After adding new account redirect to first slide in carousel 
Expected that it will be redirected to the view, where I can see added account.
And rendering of wallet view after adding new account is not smooth.
ezgif com-gif-maker (1)
 
As for priorities: for me seems good to have ISSUE 1 fixed, 2-3 are optional.

**Comment by errorists** [comment]
please give a me a minute or two to test this before merging, I already spotted some issues on the screenshots above. thank you!

**Comment by churik** [comment]
It will not merged until e2e are fixed (some of them need change). thank you!

**Comment by tbenr** [comment]
@churik thanks for the feedback! regarding issue 1, since I don't have a working NFC i cant test keycard. I had a discussion with the core team and I thought I had implemented right.

@flexsurfer @Ferossgp any suggestion on how it needs to me modified?
https://github.com/status-im/status-react/pull/11149/files#diff-149eb105e4e8038e101e471862e22db7d1dbb910408b071c1a0c4ac2472bd22eR42

**Comment by churik** [comment]
@tbenr you can test it on android emulator on e2e builds.
Instructions:
- install https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-201026-114322-0a2545-pr-x86.apk
- try to create account with keycard 
- when card is required, press button "conn" in top right corner

**Comment by churik** [comment]
@tbenr let me know when it is ready for testing and before testing please rebase it to recent develop.
Thank you!

**Comment by tbenr** [comment]
> @tbenr let me know when it is ready for testing and before testing please rebase it to recent develop.
> Thank you!

@churik sure i solved the keycard icon issue but i realize that I need to improve the scrollview which is generating some warnings (which may solves issue 3)
i'll ping you when ready

**Comment by tbenr** [comment]
@churik it is ready to be tested: i fixed 1 and improved 3 (no more flashing UI)

**Comment by errorists** [comment]
hey @tbenr can we please make sure the visual design, layout and all values match the ones in Figma before merging? thank you

Screenshot 2020-11-06 at 11 16 34

**Comment by churik** [comment]
e2e are fixed in https://github.com/status-im/status-react/pull/11388 , waiting for fixes that are requested by @errorists 
No issues from QA side, thx @qoqobolo

**Comment by tbenr** [comment]
@errorists @churik I updated the UI and rebased!

**Pull request merged**
