### PR TITLE
Change e2e kickoff column to "E2E Tests"

### PR DESCRIPTION
**Pull request by pedropombeiro**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
Changes Probot config so that e2e tests are kicked off when moving card to `E2E tests` column.

status: ready

### CODE REVIEW

**Review by annadanchenko — APPROVED** [review]

**Comment by pedropombeiro** [comment]
Maybe we can use this PR to test why e2e tests are not getting triggered. Not sure if config is taken from `develop` or from PR branch.

**Comment by pedropombeiro** [comment]
For e2e tests to be triggered, we'll need Jakub to address https://github.com/status-im/infra-misc/issues/16 first. Maybe it's the only thing that needs to be done. Unfortunately he just started his vacations today.

**Comment by annadanchenko** [comment]
@PombeirP now tests are triggered 2-3 times for PRs in Review column, for example: #8009  and #8036 Would expect it's done once and after there are at least 2 approving reviews

**Review by mandrigin — APPROVED** [review]

**Comment by pedropombeiro** [comment]
> @PombeirP now tests are triggered 2-3 times for PRs in Review column, for example: #8009 and #8036 Would expect it's done once and after there are at least 2 approving reviews

My guess is that they're not being removed from the bot queue for some reason, will look into that, should be an easy fix.

**Pull request merged**
