### PR TITLE
[#9987] Stop fetching new blocks while app is not active

### PR DESCRIPTION
**Pull request by rasom**
fixes one of points from #9987 
based on https://github.com/status-im/status-go/pull/1880

for QA:
We stop fetching new transactions when app is in the background thus we need to test that after resuming the app shows new transactions and wallet works properly. 
 
status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@rasom  would you mind to rebase it to latest develop to have new accessibility key?
After this I'll rerun e2e.

**Comment by rasom** [comment]
@churik done

**Comment by churik** [comment]
@rasom 
Contract is not deployed in this PR (on fresh `develop` it is deployed and shown in status test DApp)
*Steps*

- restore multiaccount with ETHro (`road rabbit tuna bacon man raccoon equal note cream rescue core chunk`)
- switch to Ropsten
- open 'status-im.github.io/dapp'  -> Transactions
- allow test dapp access to funds and to profile
- try to deploy a contract

*Expected result:*
Contract deployed at: {hash}

*Actual result:*
endless Mining contract in tx. 
Video / logcat is [here](https://app.saucelabs.com/tests/73293d34cba74d92a0758f7e21e2c593?auth=3487cb4820d5a3d20cb454358048623f#118)

**Comment by rasom** [comment]
it would be weird if this is caused by this pr, but i'll rebase it and check

**Comment by rasom** [comment]
@churik just tested it, works as expected

**Comment by churik** [comment]
Balance is not updated when app goes back from offline and receieves new transaction.
**Steps:**
- User A: send transaction to User B (in my case in 1-1 chat)
- User B: go offline
- User A: wait until transaction will be confirmed
- User B: go online, check transaction history (transaction will appear)
- User B: wait for updated balance

**Expected result:**
balance is updated

**Actual result:**
ezgif com-video-to-gif (1)

**Logs:** (from 08:54 - 09:10)

[geth.log](https://github.com/status-im/status-react/files/4311339/geth.log)
[Status.log](https://github.com/status-im/status-react/files/4311341/Status.log)

**Note:** balance is updated after relogin

**Comment by rasom** [comment]
@churik I've just seen similar behaviour on develop, are you sure it is PR specific?

**Comment by churik** [comment]
@rasom no, I'm not sure. I'll test it on develop as well and let you know.

**Comment by rasom** [comment]
@churik ok there is a bug

**Comment by churik** [comment]
@rasom 
Tested on builds with https://github.com/status-im/status-react/commit/dc342ec89382bd92838a8c68da13619cbcc75534 - issue is still there.
Balance is not updated for receiver and for sender, steps are the same https://github.com/status-im/status-react/pull/10124#issuecomment-596979691

Logs:
[Status.log](https://github.com/status-im/status-react/files/4312941/Status.log)
[geth.log](https://github.com/status-im/status-react/files/4312942/geth.log)

**Comment by rasom** [comment]
@churik why did you remove the label then? I added a new commit, the problem should be fixed now

**Comment by churik** [comment]
@rasom I removed it most of the time before start testing - so in that case I  didn't add it again.
Thx, checking

**Pull request merged**
