### PR TITLE
Add minor improvments to text input

### PR DESCRIPTION
**Pull request by Ferossgp**
If line-height is not defined on text input the text is cropped, to avoid this bug I added default value for 22 pt. 
Added extra touchable padding to text-input.
Added height of min 3 lines of text for seed phrase.

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@Ferossgp 
#### Issue 1: Overlapping on Recipient screen
Wallet -> Send -> Choose recipient -> Enter recipient address
photo_2020-04-07 10 55 12


#### Issue 2: No padding in input fields in Sync Settings
Profile -> Sync settings -> Mailserver -> Add new
or
Profile -> Sync settings -> Devices
photo_2020-04-07 10 55 16

**Comment by churik** [comment]
@Ferossgp 
please ping me when issues will be addressed. Thanks!

**Comment by Ferossgp** [comment]
@churik Issues were addressed

**Comment by churik** [comment]
@Ferossgp on IOS:
photo_2020-04-10 11 41 59
photo_2020-04-10 11 41 56
Is it expected?

**Comment by churik** [comment]
Thanks, all issues are addressed

**Pull request merged**
