### PR TITLE
restart reader according to Activity's lifecycle

### LINKED ISSUE #10758: Can't login or create account with keycard account after logout if push notifications are enabled
# Bug Report

## Problem
At attempt to login with keycard after logout with enabled push notifications can't proceed - card is not recognized.

#### Expected behavior
can login;
if on this step try to create new account using "Generate new key" > keycard, the same issue will appear

#### Actual behavior
https://drive.google.com/open?id=17ZveIvJVq3Ya9aYpARPqNLL_J9RciTtC

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account with keycard 
- Enable push notifications in Profile
- Restart the app (login screen will not be appeared, because status is always active)
- Go to profile -> log out
- Try to login

### Additional Information

- Status version: release 1.4.
[comment]: # (Android or iOS.)
- Operating System: Android

#### Logs

```
06-04 16:18:19.526 15223 15351 D StatusModule: openAccounts
06-04 16:18:23.091 15223 15350 I ReactNativeJS: INFO [status-im.hardwallet.card:50] - [keycard] on-card-connected
06-04 16:18:23.092 15223 15350 I ReactNativeJS: INFO [status-im.hardwallet.card:46] - [keycard] on-card-disconnected
06-04 16:18:31.600 15223 15236 I status.ethereu: Background concurrent copying GC freed 433809(17MB) AllocSpace objects, 13(332KB) LOS objects, 49% free, 9990KB/19MB, paused 153us total 124.265ms
06-04 16:19:02.844 15223 15351 D StatusModule: AppStateChange: background
06-04 16:19:02.878 15223 15351 D StatusModule: AppStateChange: active
06-04 16:19:05.127 15223 15351 D StatusModule: AppStateChange: background
06-04 16:19:05.145 15223 15351 D StatusModule: AppStateChange: active
06-04 16:19:14.730 15223 15350 I ReactNativeJS: INFO [status-im.hardwallet.card:42] - [keycard] remove-event-listener
06-04 16:19:14.732 15223 15350 I ReactNativeJS: INFO [status-im.hardwallet.card:42] - [keycard] remove-event-listener
06-04 16:19:16.617 15223 15350 I ReactNativeJS: INFO [status-im.hardwallet.card:50] - [keycard] on-card-connected
06-04 16:19:16.618 15223 15350 I ReactNativeJS: INFO [status-im.hardwallet.card:46] - [keycard] on-card-disconnected
06-04 16:19:36.457 15223 15351 D StatusModule: AppStateChange: background
06-04 16:19:36.475 15223 15351 D StatusModule: AppStateChange: active
06-04 16:20:30.499 15223 15351 D StatusModule: AppStateChange: background
06-04 16:20:32.655 15223 15351 D StatusModule: AppStateChange: active
06-04 16:21:12.869 15223 11949 W System  : A resource failed to call response.body().close(). 
06-04 16:21:12.869 15223 11949 W System  : A resource failed to call response.body().close(). 
06-04 16:22:41.238 15223 15351 D StatusModule: AppStateChange: background
06-04 16:22:44.213 15223 15351 D StatusModule: AppStateChange: active
06-04 16:22:56.325 15223 15351 D StatusModule: AppStateChange: background
06-04 16:22:56.353 15223 15351 D StatusModule: AppStateChange: active
06-04 16:23:10.706 15223 15350 I ReactNativeJS: INFO [status-im.hardwallet.card:42] - [keycard] remove-event-listener
06-04 16:23:10.707 15223 15350 I ReactNativeJS: INFO [status-im.hardwallet.card:42] - [keycard] remove-event-listener
06-04 16:23:15.369 15223 15350 I ReactNativeJS: INFO [status-im.hardwallet.card:50] - [keycard] on-card-connected
06-04 16:23:15.370 15223 15350 I ReactNativeJS: INFO [status-im.hardwallet.card:46] - [keycard] on-card-disconnected
06-04 16:23:49.302 15223 15351 D StatusModule: AppStateChange: background
06-04 16:23:54.686 15223 15351 D StatusModule: AppStateChange: background
06-04 16:24:33.652 15223 15351 D StatusModule: AppStateChange: active
```

### PR DESCRIPTION
**Pull request by bitgamma**
Fixes https://github.com/status-im/status-react/issues/10758

### CODE REVIEW

**Comment by hesterbruikman** [comment]
Original issue worked for me
Android 10 + JCOP3

- Step 1 Unlock with Keycard
- Step 2 Enable notifications
- Step 3 Sign out
- Step 4 Unlock with Keycard
- Result: Success

I did find a **new issue** with the following steps. Don't know if this can impact release when merged:
- Step 1 Unlock with Keycard
- Step 2 Enable notifications
- Step 3 Close app
- Step 4 Reopen app from launchscreen
- Result: Black screen. Have to 'Force stop' the app and reopen for it to work

Uninstalled Release version to make sure it's not a conflict of having both Release and PR build installed. Didn't make a difference

Frame 1

**Comment by bitgamma** [comment]
@hesterbruikman I can reproduce that too, but also without using Keycard at all (creating an account on device instead of Keycard). Do you have it with other builds too?

**Comment by hesterbruikman** [comment]
@bitgamma I'm not seeing this on the release branch. Will check nightly

**Comment by hesterbruikman** [comment]
Updating from Discord here: Issue is not found on Nightly. 

Another issue on nightly, that could be addressed by this fix, but unclear:
Card is not detected when using `Recover with Keycard`: https://drive.google.com/file/d/1afoUBn2nqgCVsRFWP13fDSdDnRDN1Tg4/view?usp=sharing

**Comment by bitgamma** [comment]
@hesterbruikman @Serhy the latest build should fix the black screen too

**Comment by Serhy** [comment]
Tested with Galaxy S8 and can't reproduce anymore initial #10758 bug with the third build (https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200605-091026-ff82e5-pr-universal.apk)
Can create new account (not-keycard) User1 -> enable Notifications -> Log out off account -> Add new Keycard account (User2) fine.
User2 also enables Push Notifications and logs out of account
Close Status app.
Open Status and login to User1 or User2 (keycard): -  both works
Reopen Status and add third account (a keycard account) - successfully wind up on third profile Chats screen.

**Review by flexsurfer — APPROVED** [review]

**Pull request merged**
