### PR TITLE
keycard onboarding

### LINKED ISSUE #8306: [keycard onboarding] intro and start screens
# Problem
Implement intro and start screens of keycard onboarding flow.

## Implementation
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=928%3A623

### LINKED ISSUE #8307: [keycard onboarding] preparing, pairing and finishing screens
# Problem
Implement preparing, pairing and finishing screens

## Implementation
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A15032

### LINKED ISSUE #8308: [keycard onboarding] puk and pair code screens
# Problem
Implement puk and pair code screens.

## Implementation
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A15335

### LINKED ISSUE #8311: [keycard onboarding] turn on NFC screen
# Problem
Implement turn on NFC screen

## Implementation
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A15388

### LINKED ISSUE #8312: [keycard onboarding] 'connection lost' modal screen
# Problem
Implement 'connection lost' modal screen

## Implementation
If connection with keycard is lost during the interaction, modal screen should be shown.

https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=1328%3A1

### LINKED ISSUE #8314: [keycard onboarding] backup recovery phrase screen
# Problem
Implement backup recovery phrase screen

## Implementation
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A16160

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #8306
fixes #8307
fixes #8308
fixes #8311
fixes #8312
fixes #8314

### Summary

Implements new keycard onboarding screens.

https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A14702&viewport=-720%2C-138%2C0.33876287937164307

### Testing notes

* I'm using old PIN screen as new one is still in development in https://github.com/status-im/status-react/pull/8234 I will take new one from that PR once it's merged.

* Confirm recovery phrase screens have another implementation as we don't have time to implement new drag-n-drop screens for now.

* It's expected that other parts of keycard integration might not work here. Recovery, login and wallet parts will be re-implemented anyway.

#### Platforms

- Android

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by jakubgs** [comment]
Those error make no sense to me:
```
[2019-06-25T09:33:31.826Z] Terminated
[Pipeline] // node
[Pipeline] End of Pipeline
```
Or
```
[Pipeline] End of Pipeline
[2019-06-25T09:30:16.407Z] sh: line 1: 44506 Terminated: 15          sleep 3
```
Very weird.

**Comment by jakubgs** [comment]
Oh I see, because we run tests in parallel the errors appear much earlier:
```

[2019-06-25T09:23:06.393Z] ERROR [status-im.transport.message.core:74] - Something went wrong error 
[2019-06-25T09:23:06.393Z] ERROR [status-im.transport.message.core:74] - Something went wrong nil nil
...
[2019-06-25T09:23:07.059Z] 1 failures, 0 errors.
[2019-06-25T09:23:07.366Z] Error encountered performing task 'doo' with profile(s): 'test'
[2019-06-25T09:23:07.366Z] Subprocess failed
```
That makes more sense.

**Comment by asemiankevich** [comment]
@hesterbruikman @guylouis can we apply new screens for Seed Phrase backup (https://github.com/status-im/status-react/issues/8314) for basic account as well (account with password) to keep the things aligned?

**Comment by asemiankevich** [comment]
screens:

https://github.com/status-im/status-react/issues/8306

image

image


https://github.com/status-im/status-react/issues/8307

image

https://github.com/status-im/status-react/issues/8308

image

image

@dmitryn please check this new line in the middle of the text

https://github.com/status-im/status-react/issues/8311

image

https://github.com/status-im/status-react/issues/8312

image

https://github.com/status-im/status-react/issues/8314

image

@dmitryn new line in the middle:

image


@dmitryn pay attention to the error message here:

image


Overall looks good, please rebase the PR to pick up e2e fixes from develop. 
One more point - unpair card does not work here , please take a look

**Comment by dmitryn** [comment]
@andmironov as you don't have keycard yet and i need to proceed with other parts of keycard integration, i'm going to merge this. We will do another PR with design improvements once you get a keycard.

**Pull request merged**
