### PR TITLE
fix #9903 hide buttons of actions that are not yet implemented

### LINKED ISSUE #9903: Hide options that are not yet built
# Problem

Options that are greyed out in Status are causing confusion among v1 dog fooding users. 

We can hide several of these options for now:

- Option to remove ENS name (from chat key)
- Option to add 'advanced` account types in wallet

The option to release an ENS name is too important to hide. 1) It indicates the date a user registered their name; and 2) a user can release the ENS name by other means, even though we don't have a flow in Status.

**If** the user is past 1 year of registration, could we add a link to [these instructions](https://hackmd.io/QrfTRP6sQ9aQzjFyb_IfRQ?both) inside the copy?

e.g. `To release your username, follow [these instructions](link).` in place of `Username locked...` or whatever the copy for an eligible-to-release name says? :) 

image

### PR DESCRIPTION
**Pull request by yenda**
fix #9903

ready, tested with releasable and non releasable names

Screenshot_1580137484
Screenshot_1580138989
Screenshot_1580139021

### CODE REVIEW

**Comment by rachelhamlin** [comment]
Looks good. I actually want to replace the link with one to the blog though. The URL, once published, is going to be: https://our.status.im/managing-your-ens-name-in-v1/

Should we open the link in Status browser? @yenda

**Comment by yenda** [comment]
@rachelhamlin no we open the link in whatever browser the user has as default to open links

**Review by rachelhamlin — APPROVED** [review]

**Comment by rachelhamlin** [comment]
K, only thing I'm concerned with is the link then.

**Comment by yenda** [comment]
@rachelhamlin ok tell me when it is published then so that I can change it

**Comment by rachelhamlin** [comment]
@yenda I won't publish it until v1 is live or nearly so - but that will be the link, and if something goes wrong with the link, very few people will have the option to release anyway right now. Soo want to just update it so we can merge this?

**Comment by yenda** [comment]
@rachelhamlin ok done

**Review by flexsurfer — APPROVED** [review]

**Comment by rachelhamlin** [comment]
Thanks Eric

**Pull request merged**
