### PR TITLE
cleanup of shell scripts

### PR DESCRIPTION
**Pull request by jakubgs**
This is a general cleanup of `scripts` directory. When you're starting to import multiple files/libraries into your Bash scripts you know you're doing it wrong.

Changes:
- Add missing lazy assignment for `OS_NAME`, fixes double Nix shells
- Moved `scripts/add-nix-gcroots.sh` to `nix/scripts/gcroots.sh`
- Moved Nix package manager setup to `nix/scripts/setup.sh`
- Created `nix/scripts/source.sh` to reuse in all Nix scripts
- Created `STARTING_GUIDE.md` with instructions for contributors
- Created `scripts/colors.sh` for definition of shell colors
- Removed `scripts/setup` in favor of `nix/scripts/setup.sh`
- Removed all of `scripts/lib` since it was useless

### CODE REVIEW

**Comment by rasom** [comment]
@jakubgs 
I get `grep`'s "help" on each command like here (macos):
```
$ make nix-gc
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
...
```

**Comment by jakubgs** [comment]
@rasom what OS?

**Comment by jakubgs** [comment]
@rasom okay, I modified this to not use `grep`, since it's missing `-P` on MacOS:
https://github.com/status-im/status-react/blob/6d8c0912f626de862e1ea3fd4a856334beecf8ac/Makefile#L57-L58

**Review by rasom — COMMENTED** [review]
works fine for me now

**Review by rasom — APPROVED** [review]

**Comment by corpetty** [comment]
attempted from fresh pop_os installed.  Assume dependencies are not there. `make nix-purge` worked fine, `make release-android` errored out,  here is the error:

```
building '/nix/store/9i6kibm7x07pm3qzxcrvyvg9674hz9yn-yarn.nix.drv'...
error: cannot update ref 'refs/heads/v2.5.17': trying to write non-commit object 9ef49ef22471b0eceb3f4ad69b1eb3066a55ec3f to branch 'refs/heads/v2.5.17'
error: while evaluating the attribute 'buildInputs' of the derivation 'status-react-shell' at /home/petty/Github/status-im/status-react/nix/shells.nix:27:5:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'status-react-patched-npm-gradle-modules' at /home/petty/Github/status-im/status-react/nix/mobile/android/maven-and-npm-deps/default.nix:31:9:
while evaluating the attribute 'buildPhase' of the derivation 'StatusIm-Mobile-0.0.1' at /nix/store/1i9r1964vig0hhkks1fb073hly2lbsmb-yarn2nix-source/default.nix:107:14:
while evaluating the attribute 'buildCommand' of the derivation 'offline' at /nix/store/kkiwj0gbmi3ydjr29npaf1dj03dl23yj-nixpkgs-source/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating 'concatMapStrings' at /nix/store/kkiwj0gbmi3ydjr29npaf1dj03dl23yj-nixpkgs-source/lib/strings.nix:31:25, called from /nix/store/kkiwj0gbmi3ydjr29npaf1dj03dl23yj-nixpkgs-source/pkgs/build-support/trivial-builders.nix:308:9:
while evaluating anonymous function at /nix/store/kkiwj0gbmi3ydjr29npaf1dj03dl23yj-nixpkgs-source/pkgs/build-support/trivial-builders.nix:308:31, called from undefined position:
while evaluating 'escapeShellArg' at /nix/store/kkiwj0gbmi3ydjr29npaf1dj03dl23yj-nixpkgs-source/lib/strings.nix:296:20, called from /nix/store/kkiwj0gbmi3ydjr29npaf1dj03dl23yj-nixpkgs-source/pkgs/build-support/trivial-builders.nix:310:19:
while evaluating the attribute 'buildCommand' of the derivation 'react-native-status-keycard.git' at /nix/store/kkiwj0gbmi3ydjr29npaf1dj03dl23yj-nixpkgs-source/pkgs/build-support/trivial-builders.nix:7:14:
program 'git' failed with exit code 1
make: *** [Makefile:168: release-android] Error 1
petty@pop-os:~/Github/status-im/status-react$ 
```

**Comment by corpetty** [comment]
ran again after adding the following line to my `~/.profile` and resourcing: 

`. /home/petty/.nix-profile/etc/profile.d/nix.sh`

Not sure if that fixed it, but it continued without a problem after running `make release-android` again

**Comment by corpetty** [comment]
next error: 
```
copying path '/nix/store/8dp4brpjkvpkzwskchh2pq49nqbgixjs-lein-project-deps' from 'https://nix-cache.status.im'...
error: while setting up the build environment: getting attributes of path '/home/petty/.gradle/status-im.keystore': No such file or directory
Cleanup of /nix/store...
Searching by regex: '.*-status-react-(shell|source|build|patched-npm-gradle-modules).*'
 ? Checking:   /nix/store/4ddgqsz9w1c4nyd9qs53d6i42l1gh0vf-status-react-source-jsbundle
 - Derivation: /nix/store/l3lv118539g1lj0av53si9xc3gwh4cb6-status-react-build-jsbundle-android.drv
 - Source:     /nix/store/4ddgqsz9w1c4nyd9qs53d6i42l1gh0vf-status-react-source-jsbundle
 ! Lock:       /nix/store/i67wsarfyfcprlil0wwh8dnm16i6fczq-status-react-build-jsbundle-android.lock
 ? Checking:   /nix/store/l3lv118539g1lj0av53si9xc3gwh4cb6-status-react-build-jsbundle-android.drv
 - Derivation: /nix/store/n9b07nz40r2dv953n8vs4i1mkpnmcxzn-status-react-build-release-android.drv
 - Source:     /nix/store/l3lv118539g1lj0av53si9xc3gwh4cb6-status-react-build-jsbundle-android.drv
 ? Checking:   /nix/store/n9b07nz40r2dv953n8vs4i1mkpnmcxzn-status-react-build-release-android.drv
 ? Checking:   /nix/store/qvrb59kifzl9i9siifwmqrl839r6qi5c-status-react-source-release-android
 - Derivation: /nix/store/n9b07nz40r2dv953n8vs4i1mkpnmcxzn-status-react-build-release-android.drv
 - Source:     /nix/store/qvrb59kifzl9i9siifwmqrl839r6qi5c-status-react-source-release-android
Deleting...
finding garbage collector roots...
deleting '/nix/store/n9b07nz40r2dv953n8vs4i1mkpnmcxzn-status-react-build-release-android.drv'
deleting '/nix/store/l3lv118539g1lj0av53si9xc3gwh4cb6-status-react-build-jsbundle-android.drv'
deleting '/nix/store/4ddgqsz9w1c4nyd9qs53d6i42l1gh0vf-status-react-source-jsbundle'
deleting '/nix/store/i67wsarfyfcprlil0wwh8dnm16i6fczq-status-react-build-jsbundle-android.lock'
deleting '/nix/store/mjzmpdfnp6r53qg3ff2bfg29h5gj2lm1-status-react-shell.drv'
deleting '/nix/store/q42y33d2qh06f8v8j20pj4jfn898jcbc-status-react-shell.drv'
deleting '/nix/store/qvrb59kifzl9i9siifwmqrl839r6qi5c-status-react-source-release-android'
deleting '/nix/store/trash'
deleting unused links...
note: currently hard linking saves -0.00 MiB
7 store paths deleted, 13.26 MiB freed
Successful cleanup!
make: *** [Makefile:168: release-android] Error 1
```

**Comment by jakubgs** [comment]
@corpetty ah yes, that's fine, you don't have the keystore for a release, build, but that's expected. Thanks.

**Comment by corpetty** [comment]
ok, so I'll approve based on that

**Review by corpetty — APPROVED** [review]
worked on new linux install (pop os 19.10)
- got keystore error but I don't have access to it for release.

**Comment by jakubgs** [comment]
The error:
```
error: cannot update ref 'refs/heads/v2.5.17':
trying to write non-commit object 9ef49ef22471b0eceb3f4ad69b1eb3066a55ec3f
to branch 'refs/heads/v2.5.17'
```
Appears to be coming from the [react-native-status-keycard](https://github.com/status-im/react-native-status-keycard) repo:
The tag:
https://github.com/status-im/react-native-status-keycard/releases/tag/v2.5.17
Points at the commit:
https://github.com/status-im/react-native-status-keycard/commit/8fb12850d72918d3e89e4fcfc8fa699c2ce3f203
Which is different than the mentioned:
```
9ef49ef22471b0eceb3f4ad69b1eb3066a55ec3f
```
Which suggests that the `v2.5.17` tag was at some point `--force` pushed to.
One solution would be to upgrade to the newer tag: [`v2.5.18`](https://github.com/status-im/react-native-status-keycard/releases/tag/v2.5.18)

**Comment by jakubgs** [comment]
It appears to me that we use the `exportKeyWithPath()` method introduced with https://github.com/status-im/react-native-status-keycard/commit/f4d707254a193248f92404e66f746453a2b86cd5 which is what `v2.5.18` is pointing at:
https://github.com/status-im/status-react/blob/67760f2a469c3296a69fa208dd77efb6a953774a/src/status_im/hardwallet/card.cljs#L180
I'll make a separate PR that fixes that.

**Pull request merged**
