### PR TITLE
Update your keys screen

### LINKED ISSUE #9782: Update the "Your keys" screen
Currently, this screen is called "Unlock", let's update it. 

- The screen header should be consistent with the rest of the app;
- The list items in the keys list should be consistent with the rest of the app;
- "Access key" button as well as `...` should be consistent with the rest of the sign in flow;
- Let's update the keycard indicator for it to be consistent with the rest of the app;

Screen Shot 2020-01-09 at 12 46 15

Small screens:
Screen Shot 2020-01-09 at 12 49 51

Figma:
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12

### PR DESCRIPTION
**Pull request by Ferossgp**
Fixes #9782

### CODE REVIEW

**Review by andmironov — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by Serhy** [comment]
@Ferossgp could you please rebase develop ?

**Comment by Serhy** [comment]
Tested on iOS 13 and Android.
From initial issue: 
``` 
- Let's update the keycard indicator for it to be consistent with the rest of the app;`
```
There is a discrepancy between figma in icon for account created from keycard:

Screenshot 2020-02-03 at 17 32 25

**Comment by Ferossgp** [comment]
@Serhy let me add this as a separate task into keycard backlog, this component is also used in different places and I'm not familiar yet with the keycard. 

Added #9969

**Comment by Serhy** [comment]
Awesome! Lets' merge, @Ferossgp ! Thanks!

**Pull request merged**
