### PR TITLE
fix #10591 error when scrolling account view

### LINKED ISSUE #10591: "Cannot call a class as a function" error when scrolling on account view (transaction history or assets)
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: "Cannot call a class as a function" error when scrolling on account view with several assets or in transaction history

#### Expected behavior
no error

#### Actual behavior
photo_2020-05-06 16 01 34

### Reproduction

Steps:
- create new multiaccount
- open wallet > manage assets > add several different assets (>5)
- open Status account
- scroll

### Additional Information

* Status version: nightly 06/05/2020
* Operating System: Android, iOS

#### Logs

[Status-debug-logs-5.zip](https://github.com/status-im/status-react/files/4587213/Status-debug-logs-5.zip)

### PR DESCRIPTION
**Pull request by yenda**
fixes #10591 

### Summary

Steps:

- create new multiaccount
- open wallet > manage assets > add several different assets (>5)
- open Status account
- scroll

### CODE REVIEW

**Comment by flexsurfer** [comment]
@yenda what about other cases transaction history or assets , etc ?

**Comment by hesterbruikman** [comment]
Fyi more horizontal scroll between tx history and assets. Related but of lower prioority atm: https://github.com/status-im/status-react/issues/10305

**Comment by hesterbruikman** [comment]
@yenda all good on iOS as well

**Review by hesterbruikman — APPROVED** [review]

**Review by flexsurfer — CHANGES_REQUESTED** [review]
what about other cases transaction history or assets , etc ?

**Comment by Serhy** [comment]
I've tested with iOS13 and Android 8.1, and Android 9 builds and can't reproduce the bug. 
Scrolling in Account view (Status account/ added Watch only address) on `Assets`, `Collectibles`, `History` tabs works fine. 
 @flexsurfer is that what you were asking in https://github.com/status-im/status-react/pull/10668#pullrequestreview-413495569 comment?

**Review by flexsurfer — APPROVED** [review]

**Pull request merged**
