### PR TITLE
Message input issues

### LINKED ISSUE #14539: The user is not navigated to the new message after a user scrolls up, the message is sent
**Steps to reproduce:**
1. Create several long messages into 1-1 chat
2. Scroll to the up
3. Send a new message

**Actual result:**
The user is not auto-scrolled to the bottom and as a result, the sent message is not visible

https://user-images.githubusercontent.com/52490791/207644938-82a4d9ce-9b3f-4002-a29f-fc01bae3640b.mp4

**Expected result:**
The user auto scrolled to the last message after its sent and as result, the user sees a current message

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #14539, #14534, #14535, #14537, #14542

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

**Review by J-Son89 — CHANGES_REQUESTED** [review]
both of these screens are in status_im/ ui2 ... can you please make migrating these files to status_im2 as part of this work?

ideally we have no files in status_im/ ui2 soon enough and we avoid this confusion.

cc @flexsurfer

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil . Thanx for your work. The testing of the following issues are passed:
- https://github.com/status-im/status-mobile/issues/14539
- https://github.com/status-im/status-mobile/issues/14534
- https://github.com/status-im/status-mobile/issues/14535
- https://github.com/status-im/status-mobile/issues/14537
- https://github.com/status-im/status-mobile/issues/14542

This https://github.com/status-im/status-mobile/issues/14536 ISSUE still reproduced. The textbox is shown as focused after chat is opened as result user can't close it unless starts typing. I described it the the issue

Lets merge current PR and fix this https://github.com/status-im/status-mobile/issues/14536 issue separately

**Comment by flexsurfer** [comment]
@J-Son89 we'll do this soon after this PR is merged

**Review by J-Son89 — APPROVED** [review]

**Comment by ibrkhalil** [comment]
> Hi @ibrkhalil . Thanx for your work. The testing of the following issues are passed:
> 
> * [The user is not navigated to the new message after a user scrolls up, the message is sent #14539](https://github.com/status-im/status-mobile/issues/14539)
> * [The textbox is too little expanded after the text is pasted and it is hard to expand it manually then #14534](https://github.com/status-im/status-mobile/issues/14534)
> * [Cursor is not able to be located during message editing if several rows are in the message #14535](https://github.com/status-im/status-mobile/issues/14535)
> * [All rows of text are not shown if the 'edit' button is tapped on the created message #14537](https://github.com/status-im/status-mobile/issues/14537)
> * [The input textbox is not tappable if message is typed into buffer of the chat, then current chat is reopened #14542](https://github.com/status-im/status-mobile/issues/14542)
> 
> This #14536 ISSUE still reproduced. The textbox is shown as focused after chat is opened as result user can't close it unless starts typing. I described it the the issue
> 
> Lets merge current PR and fix this #14536 issue separately

I believe it's better to merge them all together, I'll do that fix later today

**Review by OmarBasem — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
> I believe it's better to merge them all together, I'll do that fix later today

Ok. Let me know, I will retest input textbox again

**Comment by ibrkhalil** [comment]
> 14536

Kindly check when you have time .. As I can't reproduce .. Please check if it's fixed
Please try to test it on E2E devices @churik 
CC: @VladimrLitvinenko

**Comment by VolodLytvynenko** [comment]
> > 14536
> 
> Kindly check when you have time .. As I can't reproduce .. Please check if it's fixed Please try to test it on E2E devices @churik CC: @VladimrLitvinenko

@ibrkhalil The defect is still reproduced. Created the record how I can reproduce it on Android studio also. The same behavior for real android devices 

https://user-images.githubusercontent.com/52490791/208632829-4630dc67-09e4-48c3-b18f-1ba7a13bac2f.mp4

**Comment by ibrkhalil** [comment]
> > > 14536
> > 
> > 
> > Kindly check when you have time .. As I can't reproduce .. Please check if it's fixed Please try to test it on E2E devices @churik CC: @VladimrLitvinenko
> 
> @ibrkhalil The defect is still reproduced. Created the record how I can reproduce it on Android studio also. The same behavior for real android devices
> 
>  focused_textbox_20.mp4

Hey @VladimrLitvinenko, Sorry, But I still couldn't reproduce, But I tried something that I suspected is the problem .. Kindly check it again when you're free .. Thanks! 🚀

**Comment by ibrkhalil** [comment]
> > > > 14536
> 
> > > 
> 
> > > 
> 
> > > Kindly check when you have time .. As I can't reproduce .. Please check if it's fixed Please try to test it on E2E devices @churik CC: @VladimrLitvinenko
> 
> > 
> 
> > @ibrkhalil The defect is still reproduced. Created the record how I can reproduce it on Android studio also. The same behavior for real android devices
> 
> > 
> 
> >  focused_textbox_20.mp4
> 
> 
> 
> Hey @VladimrLitvinenko, Sorry, But I still couldn't reproduce, But I tried something that I suspected is the problem .. Kindly check it again when you're free .. Thanks! 🚀

If it's still reproducible, we can merge this and I'll continue working on it after new chat flow

**Comment by flexsurfer** [comment]
hey @ibrkhalil this issue looks very similar to https://github.com/status-im/status-mobile/pull/14502 , we had a very weird bug on ios with background

**Comment by ibrkhalil** [comment]
> hey @ibrkhalil this issue looks very similar to https://github.com/status-im/status-mobile/pull/14502 , we had a very weird bug on ios with background

Yes Andrey, It's quite similar .. the issue I suspect is that composer's state (context) updates the :clear key incorrectly .. I think that's the cause because it can't be the other two cases that blue the background (= :state :max) or (= :state :custom-chat-unavailable)

**Comment by VolodLytvynenko** [comment]
Hi, @ibrkhalil current PR is tested and ready to be merged. The issue https://github.com/status-im/status-mobile/issues/14536 can be fixed separately

**Comment by churik** [comment]
@ibrkhalil @VladimrLitvinenko awesome work on this one. Thank you for being patient!

**Pull request merged**
