### PR TITLE
add watch only address using qrcode

### PR DESCRIPTION
**Pull request by tbenr**
when adding a watch-only address I added:

- ability to add via QR code scan
~~avoid adding if address has been already added~~
~~i18n on some hardcoded strings~~ (fixed by latest pr)

status: ready

image

### CODE REVIEW

**Comment by flexsurfer** [comment]
> avoid adding if address has been already added

i believe we have this already, next button is disabled if address has been already added

**Comment by tbenr** [comment]
@flexsurfer oh right it's in the `:add-account-disabled?` sub.
my qr implementation bypass that so i implemented it also in the fx running after

**Review by andmironov — APPROVED** [review]

**Comment by tbenr** [comment]
@andmironov i changed a bit the message and how it is displayed

**Comment by flexsurfer** [comment]
@tbenr could we just insert scanned address into input field? in that case we don't need to duplicate logic and validations

**Comment by tbenr** [comment]
@flexsurfer it was one option but then, as a user, I thought it was better to go straight to next screen. But I can change it, no prob (I should have time this evening).

**Comment by flexsurfer** [comment]
@tbenr yeah i think better to change that, because it would be great if you can review scanned address before adding it, and code will be simpler, thanks!

**Comment by tbenr** [comment]
@flexsurfer done!

**Review by flexsurfer — APPROVED** [review]

**Comment by Serhy** [comment]
Looks great to me on iOS and Android when adding QR code from Status. 
However, I guess at the moment it's not often case when user will need to scan QR codes from Status app account addresses.

Mostly it will be pure address var encoded in QR code (while in Status app has encoded in `ethereum:0x.........@XX` format (where XX is network id). And in that case it fails to add address saying 'Scanned QR code doesn't contain a valid address'

So when scanning QR code (value `ethereum:0xDdc867bAB69c9488E65f610E071752f621C7F504`)
Screenshot 2020-02-13 at 16 02 16
OR 
with the content value (`ethereum:0xDdc867bAB69c9488E65f610E071752f621C7F504@3`)
Screenshot 2020-02-13 at 16 02 32
then it's parses and inserted fine 

But when scanning address (normalised one, - value is` 0xDdc867bAB69c9488E65f610E071752f621C7F504`)
Screenshot 2020-02-13 at 15 52 03
or same but non-normalised 
Screenshot 2020-02-13 at 15 52 36
then 'Scanned QR code doesn't contain a valid address' :(

@tbenr, could you update it please so it could eat pure ETH address as well?

**Comment by tbenr** [comment]
@Serhy done!

**Comment by churik** [comment]
Retested with QRs from the description, with QR `ethereum:0x.........@XX` format on IOS and Android. 
Also checked error handling when scanning invalid QR.
Thank you @tbenr !
Looks good from my side.
It contains also `design-review` label.
@errorists would you mind to take a look?

**Review by errorists — APPROVED** [review]

**Comment by hesterbruikman** [comment]
Not sure if the issue @Serhy raised was resolved in the PR build I just tried. For a 'pure' ETH address without `Ethereum:` prefix I get the error "Scanned QR code doesn't contain valid address"

**Comment by churik** [comment]
@hesterbruikman what build and platform you tried?

**Comment by hesterbruikman** [comment]
Platform: Android
App version: 0.14.0 (20200205205612)
File: StatusIM-200205-205455-290d14-pr-universal.apk

**Comment by churik** [comment]
@hesterbruikman try https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200214-073916-bbb549-pr-universal.apk - this is last one which I tested

**Comment by hesterbruikman** [comment]
Works! Thanks for checking. Sorry I must have scrolled to the wrong date build on mobile 😬

**Pull request merged**
