### PR TITLE
[#9484] Reintroduce back collapsing of long messages in chats

### PR DESCRIPTION
**Pull request by flexsurfer**
max height is 200px

image

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by errorists** [comment]
[Needs a gradient on](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=7687%3A3461) top of the last two lines of text, otherwise this UI doesn't really work that well

**Comment by flexsurfer** [comment]
@errorists @Serhy i've added gradient

**Comment by Serhy** [comment]
@flexsurfer there are three issues found:
**Issue 1** 
When large message received in 1-1 or Group chats, - there is no collapse button shown. Message is cut to the respective number of chars (lines), so it collapsed, but no way to reveal whole message. All fine in public chat though. 
Screenshot 2020-09-17 at 12 47 46


**Issue 2**
 When I long-tap on revealed whole message - there is no Reaction pop-up appears. Screen is shadowing as expected but just no pop-up to React-Copy-Reply. All fine with collapsed message.
37hf8y3grf3rf

**Issue 3** 
Weird behavior with what happens with iOS: when I send from **Android** large message by pasting it with native Android `Paste` - it has no `Collapse` button on iOS side in public chat.
Same message received by Android user (posted by another Android user) in public chat has the collapsing button as expected. Or, it's also fine when both users, - sender and recipient, - are using iOS device. Not even sure which platform the issue is Android or iOS. Below are the steps to reproduce:
1) Open status on iOS (UserIOS) and Android (UserAndroid) and create new accounts on both
2) Both users join same public chat
3) UserAndroid with the native Android `Paste` option pastes any long test in message input and sends message
4) UserIOS checks whether there is a collapsing button present.

**Comment by flexsurfer** [comment]
thanks @Serhy all should be fixed now

**Comment by Serhy** [comment]
@flexsurfer Everything looks good now, above issues are fixed. 
Two cases though, when there is no way to Copy or leave an emoji reaction on long message:
1) Your own message
2020_09_21_12_54_30_trim

2) When reveal the received message after long-tap made when it was collapsed
2020_09_21_12_53_20_trim

In both cases focus is made on message head and the Reaction pop-up is somewhere below of screen. 

While second scenario has easy workaround, - copying your own big message is impossible.

**Comment by flexsurfer** [comment]
thanks @Serhy fixed

**Comment by Serhy** [comment]
Tested with Android 9, Android 8, iOS 14 (Beta) 
All issues are fixed in 1-1/Group/Public chats
- Long messages collapsed and could be revealed through 'Reveal' button (except your own message sent in chat which are showed in full)
- Long tap on any message view (collapsed/full) shows Reactions panel
- Can reply to long messages and I receive PN for them

Thank you a lot @flexsurfer !

**Pull request merged**
