### PR TITLE
[DEBUG]add db debug in dev/e2e

### PR DESCRIPTION
**Pull request by cammellos**
add database logging similar to re-frisk, in e2e and dev builds, helps to debug some state issues.
large logs might be cut off in logcat, but should help in most cases.

status:ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by Serhy** [comment]
We log even seedphrase and passwords now. Fine for e2e, not sure it's OK for develop (means the same will be in nightlies?)

**Comment by cammellos** [comment]
@Serhy I have changed it so only e2e will log everything, seems safe to me as we don't have any confidential information I believe, and can help us debug some issues (for example mailserver issue).
I have also changed default loglevel to `DEBUG` for e2e/develop , update tests.

Not sure what to do about the tests looking for the seed phrase/password, they are useful for checking regressions, but unfortunately with this change they'll break. Don't know what's best, disable logging or keep the tests. What do you think?

**Comment by yenda** [comment]
@Serhy @cammellos nightlies are built with .env or .env.nightly?

**Comment by cammellos** [comment]
@yenda not sure, I'd expect `.env.nightly`

**Pull request closed without merging**
