### PR TITLE
Fixes Unused translations #8727

### LINKED ISSUE #8727: Remove unused strings
# Problem

The following strings are not used in the code anymore and should be removed from
- translations/en.json
- test/cljs/status_im/test/i18n.cljs
- rest of the files in translations if present there (e.g. ko.json, fr.json and the rest)

Strings:
{'no-hashtags-discovered-title', 'no-more-participants-available', 'and-you', 'wallet-transaction-fee', 'contacts-syncronized', 'faucet-error', 'currency-display-name-kyd', 'tribute-to-talk-sign-and-set-tribute', 'wallet-set-up-safe-transactions-title', 'add-existing-multiaccount', 'add-new-contact', 'currency-display-name-gyd', 'leave-confirmation', 'currency-display-name-bmd', 'removed-from-chat', 'device-to-device-warning-content', 'update-status', 'postponed', 'error-unable-to-get-transactions', 'leave-chat', 'search-chats', 'your-wallets', 'delete-group', 'status-not-sent', 'device-to-device-warning-title', 'mute-notifications', 'reorder-groups', 'status-not-sent-tap', 'signing-phrase-warning', 'transaction-moved-title', 'transactions-delete', 'error-cant-send-transaction-offline', 'no-statuses-found', 'available-participants', 'wallet-transaction-fee-details', 'delete-contact-confirmation', 'is-typing', 'create-new-multiaccount', 'wallet-set-up-confirm-description', 'move-to-internal-failure-message', 'status-failed', 'passcode-error', 'leave-group-chat', 'wallet-onboarding-description', 'delete-group-chat-confirmation', 'popular-tags', 'enter-dapp-url', 'wallet-onboarding-set-up', 'secure-your-assets', 'search-tags', 'wallets', 'pin-unblocked', 'add-new-network', 'status-delivered', 'currency-display-name-srd', 'multiaccount-not-listed', 'currency-display-name-mkd', 'unsigned-transaction-expired', 'wallet-deposit', 'enter-valid-public-key', 'suggestions-requests', 'search-for', 'leave-group-title', 'empty-topic', 'status-prompt', 'phone-significant', 'wallet-add-asset', 'existing-networks', 'edit-chats', 'keycard-applet-will-be-installed', 'other-multiaccounts', 'currency-display-name-ltl', 'secret-keys-confirmation-cancel', 'secret-keys-confirmation-confirm', 'transactions-unsigned-empty', 'no-multiaccount-on-card', 'switch-users', 'status-hardwallet-capitalized', 'edit-contacts', 'status-sent', 'delete-contact', 'invalid-phone', 'status-not-sent-without-tap', 'recover-access', 'wallet-set-up-signing-explainer', 'make-sure-you-trust-dapp', 'not-implemented', 'add-a-status', 'currency-display-name-yer', 'new-transaction', 'enter-pin-description', 'address-explication', 'currency-display-name-mnt', 'edit-network-config', 'request-qr-legend', 'no-pairing-on-device', 'transaction-moved-text', 'phone-number', 'not-specified', 'no-multiaccount-on-card-text', 'tribute-to-talk-you-can-leave-a-message', 'debug-enabled', 'edit-network-warning', 'suggestions-commands', 'intro-text-description', 'transactions-sign-later', 'mobile-network-use-mobile-details', 'chat-send-eth', 'faucet-success', 'no-statuses-discovered', 'phone-international', 'sign-later-text', 'here-is-your-signing-phrase', 'remove-from-contacts', 'fetching-messages', 'ens-names', 'ens-username-owned-continue', 'default-dapps-marketplaces', 'leave-public-chat', 'tribute-to-talk-message-placeholder', 'connection-problem', 'edit-group', 'phone-national', 'dapp-profile', 'default-dapps-social-utilities', 'error-processing-json', 'default-dapps-social-networks', 'no-statuses-discovered-body', 'transactions-sign-all', 'wallet-exchange', 'members-none', 'delete-group-confirmation', 'currency-display-name-nio', 'leave-group-chat-confirmation', 'wallet-address-from-clipboard', 'transactions-unsigned', 'wallet-backup-recovery-description', 'sign-later-title', 'process-json', 'multiaccount-not-listed-text', 'notifications-title', 'delete-chat-title', 'paste-json-as-text', 'view-transaction-details', 'existing-mailservers', 'you-will-need-this-code', 'delete-group-prompt', 'transactions-delete-content', 'status-seen', 'contact-already-added', 'choose-from-contacts', 'remove-from-group', 'view-my-wallet', 'wallet-set-up-confirm-title', 'default-dapps-fun-games', 'wallet-set-up-signing-explainer-warning', 'currency-display-name-sos', 'status-seen-by-everyone', 'already-have-multiaccount', 'wallet-choose-from-contacts', 'leave-group-action', 'wallet-send-token', 'syncing-disabled', 'incorrect-code', 'type-a-command', 'currency-display-name-lrd', 'currency-display-name-bzd', 'wallet-browse-photos', 'wallet-onboarding-title', 'search-chat', 'selected-dapps', 'request-feature', 'phone-number-required', 'default-dapps-media', 'begin-keycard-setup-confirmation-text', 'no-hashtags-discovered-body', 'specify-mailserver-address', 'manage-permissions', 'dont-allow', 'add-json-file', 'leave-group-confirmation', 'syncing-enabled', 'shake-your-phone', 'wallet-error', 'topic-format', 'error-cant-sign-message-offline', 'search-contacts', 'unknown-address', 'link-card', 'contacts-group-new-chat', 'wallet-set-up-title', 'reset-default', 'signing-message-phrase-description', 'currency-display-name-gmd', 'status-console', 'currency-display-name-lak', 'buy-with-snt', 'twelve-words-in-correct-order', 'transactions-filter-tokens', 'status-sending', 'default-dapps-exchanges', 'status-not-sent-click', 'specify-bootnode-address', 'empty-chat-description-console', 'tribute-to-talk-sample-text', 'received-invitation', 'delete-chat-action', 'pin-unblocked-description', 'enter-address', 'public-chat-user-count'}

## Acceptance Criteria

Listed strings are not present in the listed files

## Note
unused strings are found by the test test/appium/tests/atomic/test_translations.py

### PR DESCRIPTION
**Pull request by acolytec3**
Fixes #8727 

### Summary

Removes all unused strings identified by test/appium/tests/atomic/test_translations.py

### Review notes
I've removed all the unused strings and make test does not produce any errors when run locally.

### Testing notes
Ran make test and have verified that no failures are produced.

##### Non-functional

 -Removes unused strings from translation jsons

### Steps to test

Run make test-auto and verify that all tests pass.

status: Ready for review

### CODE REVIEW

**Comment by yenda** [comment]
Tests are failing because of:

```
[2019-09-05T01:09:00.113Z] Extra translations in locale :es-419
[2019-09-05T01:09:00.113Z] #{:your-wallets}
[2019-09-05T01:09:00.113Z] 
[2019-09-05T01:09:00.113Z] Extra translations in locale :fa
[2019-09-05T01:09:00.113Z] #{:your-wallets}
[2019-09-05T01:09:00.113Z] 
[2019-09-05T01:09:00.113Z] Extra translations in locale :ko
[2019-09-05T01:09:00.113Z] #{:your-wallets}
[2019-09-05T01:09:00.113Z] 
[2019-09-05T01:09:00.113Z] Extra translations in locale :ms
[2019-09-05T01:09:00.113Z] #{:your-wallets}
[2019-09-05T01:09:00.113Z] 
[2019-09-05T01:09:00.113Z] Extra translations in locale :pl
[2019-09-05T01:09:00.113Z] #{:your-wallets}
[2019-09-05T01:09:00.113Z] 
[2019-09-05T01:09:00.113Z] Extra translations in locale :ru
[2019-09-05T01:09:00.113Z] #{:your-wallets}
[2019-09-05T01:09:00.113Z] 
[2019-09-05T01:09:00.113Z] Extra translations in locale :zh-Hans-CN
[2019-09-05T01:09:00.113Z] #{:your-wallets}
[2019-09-05T01:09:00.113Z] 
```

**Comment by acolytec3** [comment]
@yenda Fixed those items.  All the tests are passing locally now.

**Comment by flexsurfer** [comment]
@acolytec3 could you please resolve conflicts?

**Comment by acolytec3** [comment]
@flexsurfer Sorry, thought I resolved those with my latest push on Saturday but looks like they didn't carry over for some reason.   Will clean it up and push a new commit later today.

**Comment by acolytec3** [comment]
@flexsurfer @yenda  Question on this, I just rebased and pushed a new commit this morning and it looks like there have already been additional commits to the develop branch since then that now have to be merged again.  Is there a point in time where I can rebase once and have it reviewed and merged into the develop branch before any new translations or test strings get added in so I can close this and not have to be continually fixing merge conflicts?

**Comment by yenda** [comment]
@acolytec3 yes sorry we just merged a huge PR that removed the database we were using and there was a few strings that became unused. There shouldn't be a new one anytime soon so you should be fine. To resolve the conflict just remove both what you removed and what was removed.

**Comment by acolytec3** [comment]
@yenda  No worries, just went through and rebased off develop again.  Hopefully cleaned up all the conflicts this time.

**Comment by yenda** [comment]
The linter is complaining, run 'lein cljfmt fix'

**Comment by acolytec3** [comment]
@yenda Run and new commit pushed.  Where is this feedback coming from?  Is it in the Jenkins logs?  Was just curious since I don't seem to have access to those and I didn't see anything like that when I ran the make test-auto command (or at least not that was obvious to me).

**Comment by flexsurfer** [comment]
@acolytec3  could you please resolve conflicts, thanks

**Pull request closed without merging**
