### PR TITLE
Handle links in profile qr code scanner

### LINKED ISSUE #10690: QR code scanner in `Start new chat` gives error scanning from join.status.im
# Bug Report

## Problem
Join.status.im gives a full url to support installing the app if this is not the case yet. The QR code scanner in `Start new chat` > `QR scanner` does not detect full url and gives an error.

This is the case when scanning a ENS name QR and when scanning chat key QR

Screenshot_20200519-170114_Status

#### Expected behavior
QR code reader checks if QR code includes url, if url includes join.status.im remove url and only use chat key, ens name or public chat name.
#### Acceptance Criteria
* QR code scanner in `Start new chat` > `QR scanner` scans users universal links:
`https://join.status.im/0x04286c5fc59fb4234325b874f74ced3fb6a2edd59a4ed9c4e4c585872913c6202a7d51374f359b72c9b79cb0a5eda0ed2f2c4f32bd81ad7059e2165f619e06431f` or 
`https://join.status.im/@statuse2e` or `https://join.status.im/@statuse2e.eth`
then it opens 1-1 chat with that user
* If user scans universal link with own profile PublicKey/ENS then we keep the same behavior as now when scanning own public key (PopUp message "Thats you, to start a chat choose someone else")
* If user scans public chat universal link like `https://join.status.im/markets` then navigation to the respective public chat view happens
* If user scans universal link with Dapp (`https://join.status.im/b/ens.domains`) or any invalid links like `https://join.status.im/0x8A4339aE98df2B2e51E37631C8B4F853048D4556` then same popup message as now notifies user about invalid data in QR code ('Please enter or scan a valid chat key or username')

### Reproduction
- Open Status
- Tap plus button
- Tap start new chat
- Tap QR code scanner
- Scan profile or channel on join.status.im

### Additional Information
- Status version: 1.14.0 nightly
- Operating System: Android & iOS when scanning from join.status.im

### PR DESCRIPTION
**Pull request by Ferossgp**
Fixes #10690

### CODE REVIEW

**Comment by hesterbruikman** [comment]
Worked for me on Android but not on iOS. Here are the logs in case that helps! [status_logs.zip](https://github.com/status-im/status-react/files/4712788/status_logs.zip)

Frame 1

**Comment by Ferossgp** [comment]
@hesterbruikman from logs seems like you have downloaded the previous build on iOs, can you please check with the # 2?

**Comment by hesterbruikman** [comment]
Totally right, sorry about that. Worked with the latest build on iOS as well

**Review by hesterbruikman — APPROVED** [review]
Tested on Android and iOS. Thanks @Ferossgp !

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@hesterbruikman 
in this PR only 1-1 chats are handled (so universal links like `https://join.status.im/u/...`), however in initial issue you are talking about `universal link with Dapp` and `universal link with public chat`.
I'm not sure that Start new chat > Scan QR is appropriate place to have this.
So do we leave the issue opened or create new one for dapp and public chat links?

**Comment by hesterbruikman** [comment]
Thanks @churik I'll create a new issue for dapp and public chat links. Having any scan to open from join.status.im is an improvement I'd rather include sooner rather than later

**Comment by churik** [comment]
checked with:
- universal links with status ENS name
- universal link with ENS name with other domain
- universal link with own profile chat key
-  universal link with other user chat key
- invalid values
- own profile key
- other user profile key

**Comment by churik** [comment]
@Ferossgp 
thanks for PR!
Please merge it to `develop` and cherry-pick to release branch.

**Pull request merged**
