### PR TITLE
[Fixes: #11349] Split large messages in batches

### PR DESCRIPTION
**Pull request by cammellos**
When sending messages in quick succession, it might be that multiple
messages are batched together in datasync, resulting in a single large
payload.

This commit changes the behavior so that we can pass a max-message-size
and we split the message in batches before sending.

status: ready

### CODE REVIEW

**Comment by cammellos** [comment]
@qoqobolo would you mind testing this when you have time to make sure https://github.com/status-im/status-react/issues/11349 is fixed please?
Thank you!

**Comment by qoqobolo** [comment]
@cammellos sure! On it

**Comment by qoqobolo** [comment]
@cammellos can't reproduce #11349, all messages are received. Thanks for the fix!
Should I send it to merge now or work is still in progress? 
> status: wip

**Comment by cammellos** [comment]
@qoqobolo thanks for testing, not yet, I have to merge the status-go PR first, I will take care of it.
Thank you

**Review by rasom — APPROVED** [review]

**Pull request merged**
