### PR TITLE
[#8845] Update list of public chats

### LINKED ISSUE #8845: Update list of public chats
_Acceptance criteria added 31/10/19. Issue ready for pick-up._ [RH]

### Background

Status suggests a list of featured(selected) public chats as below. It will be the first screen for newcomers who want to hang out with existing Status communities.

publc_chats

### Problem

1. Some languages with a number of speakers (e.g. French, German, Portuguese) don't have their own community channels on the suggested list.

2. The list of featured public chats are not categorized and localized. 

3. Some popular topics such as sports, business, politics, or travel could be easier for the general public to engage in the communities but the featured topics don't include them.

### Acceptance Criteria

For v1, update the hardcoded chat list: 

- #introductions
- #chitchat
- #status
- #status-[device language if applicable]
- #crypto 
- #tech
- #music
- #movies
- #support

Display an alternate #status-language channel only if the user has a device language set to Chinese, Japanese, Korean, Russian, Spanish, or Farsi. 

### Future Suggestions

The list of featured public chats could be categorized and include more general topics such as

General
  - Introductions
  - Politics
  - Economy
  - Business
  - Travel
  - Entertainment
  - Sports
  - World News
  - Music
  - Water cooler
  - more general topics..

Languages
  - English
  - Spanish
  - Portuguese
  - German
  - French
 -  Italian
  - Dutch
  - Russian
  - Chinese
  - Korean
  - Japanese
  - Farsi
  - other major languages..
 
Developers
  - blockchain
  - ethereum
  - Web
  - AI
  - VR/AR
  - frontend
  - backend
  - devops
  - dapps
  - cryptolife
  - etc..

Status
  - status
  - status-core
  - status-core-ui
  - status-embark
  - status-keycard
  - status-nimbus
  - status-marketing
  - other Status public chats...

[Design explorations](https://github.com/status-im/status-react/issues/8845#issuecomment-543589234)

Considering the mass adoption after V1 and better user experience, Status has to provide users with more public chats in a more organized and comprehensive manner.

### LINKED ISSUE #9290: New chat window - UI fixes
# Problem
`New chat window,` fixes to: layout, list items, headers, input field, scroll view.

The `New chat window` UI is currently implemented as a new screen, it should instead behave as a modal popover sliding on top of the [+]-button bottom sheet. 

@errorists any prototype or reference for the overlay animation? Assuming on completion both the popover and bottom sheet are dismissed.

Designs: https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=6238%3A266

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #8845
fixes #9290

| English | Russian |
| ------------- | ------------- |
| image | image |

| Deutsch | New chat |
| ------------- | ------------- |
| image | image |

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Comment by errorists** [comment]
One thing to address:
the text labels of all channels should be using the `500` font-weight, or `main-medium` text style. Also, are these touchableOpacity because I see no difference when pressing them?

It's ok for now, nice work Andrey. However I'm marking it as in need of a follow up, our input implementation stops this from working exactly as designed. 

@rachelhamlin last chance to change the text there, you sure it's okay, it was literally my first pass at it? :)

**QA** please test on smaller devices if the keyboard doesn't obstruct the input, if so that's a blocker.

**Comment by errorists** [comment]
@flexsurfer one more thing, I can still see the 1px grey divider between list items under 'New Chat', that should be removed.

**Comment by flexsurfer** [comment]
fixed

**Comment by churik** [comment]
@flexsurfer 
Error at attempt to access profiles of your contacts through New Chat > Contacts > Tapping on user picture.
photo_2019-11-14 11 32 04

@errorists is that OK that we have list of contacts in 2 places (New chat > Contacts and Profile > Contacts), WDYT?

**Comment by errorists** [comment]
> is that OK that we have list of contacts in 2 places (New chat > Contacts and Profile > Contacts)

@churik  It’s ok, this one is only for quick access. The profile one is for managing contacts so blocking, removing, adding new etc. Think of this one as a dialer in your phone, where Profile is the address book.

**Review by errorists — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by flexsurfer** [comment]
@churik thanks, fixed!

**Comment by churik** [comment]
Tested on Android 8 (LG V20), Samsung Galaxy S8 (5.8'') and Google Pixel 2 (5.0''), IPhone 7.
The smallest screen I could found in BrowserStack:
small_pixel
It's scrollable, so this is completely acceptable IMO.
Added https://ethstatus.testrail.net/index.php?/cases/view/6242 for automatization.

Thanks @flexsurfer, amazing work!

**Pull request merged**
