### PR TITLE
[DEBUG] Use "avoid NVM writes" branch

### PR DESCRIPTION
**Pull request by vitvly**
Testing https://github.com/status-im/react-native-status-keycard/pull/23

### CODE REVIEW

**Comment by flexsurfer** [comment]
@siphiuel please rebase

**Comment by vitvly** [comment]
@flexsurfer rebased

**Comment by vitvly** [comment]
Build is successful now :)

**Review by pedropombeiro — APPROVED** [review]
Why is the version going backward?

**Pull request closed without merging**
