### PR TITLE
Update translations for the referral program

### PR DESCRIPTION
**Pull request by jinhojang6**
Updated languages : 

- Latin American Spanish: es_419.json
- Spanish: es.json
- Filipino: fil.json
- Italian: it.json
- Brazilian Portuguese: pt_BR.json
- Portuguese: pt.json
- Russian: ru.json
- Simplified Chinese: zh.json

### CODE REVIEW

**Comment by jinhojang6** [comment]
Waiting for Russian translation updates

**Review by 3esmit — APPROVED** [review]
pt_BR approved.

**Review by hesterbruikman — APPROVED** [review]
Looks good to me! Thanks @jinhojang6

**Comment by jinhojang6** [comment]
All good. Can we move this PR forward? @churik @Serhy

**Comment by churik** [comment]
e2e will pass and I'll merge it

**Pull request merged**
