### PR TITLE
Keycard: updated PUK flow

### LINKED ISSUE #10452: PUK code field is not shown in "Generate account" flow in wallet  if user exceed 3 retries of passcode
# Bug Report

## Problem

6-digit passcode instead of 12-digit PUK when 3 retries of the passcode are exceeded during "Generate account" flow in the wallet
photo_2020-04-28 11 06 28

#### Expected behavior
Can enter PUK-code, change passcode and proceed

#### Actual behavior
user can't generate account, flow is blocked

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account with keycard
- Go to wallet > Generate account > Enter wrong passcode 3 times

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 28/04/2020
- Operating System: Android

### PR DESCRIPTION
**Pull request by rasom**
fix #10452

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
A note for @yenda:
This PR is rather about changing the way how we handle invalid PIN/PUK codes and how we recover frozen multiaccount, it is not specific to #10655 issue.

Previously when multiaccount was frozen (after entering the wrong PIN three times), we asked the user to enter PUK and then to set a new PIN (enter it twice to confirm). But that way was inconsistent to keycard's API because there is no way to verify whether PUK is valid without resetting PIN (there is only `unblockPin` method). To bypass that a default password ("000000") was set, and then we called `resetPin` method to set a new PIn. This way is definitely wrong because if the app is closed before resetting a new PIN user will have "000000" PIN on the card. 

So now, after entering the wrong PIN three times a "frozen card" popover is shown and we propose user at first to enter new pin (twice, with confirmation) and only after that enter PUK so that we can both verify PUK and reset PIN with only one `unblockPin` call.

This PR also contains some changes to `simulated-keycard` ns because I still can't work on galaxy s9 and had to work on it in a simulator. I don't mind if this PR will be closed and you will work on it from scratch, but that's up to you.

Designs can be found in Figma.

**Comment by hesterbruikman** [comment]
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=6815%3A154

**Comment by hesterbruikman** [comment]
🙌 Great work Roman! Here are some issues I noticed. As this is a large PR, let's see what fits and what doesn't.

### Tested
- Onboarding with fresh card
- Uninstall/Install > Pair existing card
- Freeze card on Unlock
- Freeze card on sign tx
- Block card on Unlock

### Issue 1
I'm missing the more detailed heading in the `Reset passcode flow`. Is there a difficulty including this with these screens being used in multiple places?
Frame 180

### Issue 2
Once `reset passcode with PUK code` has successfully been completed, after tapping open on the success screen, I need to tap the card again. Is there anyway around this?

Screen_Recording_20200527-183952_1

### Issue 3
When card is frozen in the app, i.e. on sign tx, and I tap Dismiss on the popover, I would expected an alert in wallet notifying that the card is frozen; with option to Reset card access 
Frame 181


### Issue 4
When card is frozen in the app, i.e. on sign tx, and I tap Dismiss on the popover, underlying Wallet tab changes to Chat
Movie 1_2

### Issue 5
When freezing the card in sign tx, I was not prompted with the Reset card flow, but rather shown the same passcode entry screen. I could use this to enter a new passcode and PUK. Assume this is WIP

### Issue 6
Got a wrong card error when card was frozen and resetting using current implementation described in issue 5. Assuming this will resolve itself if Frozen key during tx sign is WIP

### Issue 7
Transition from Wrong passcode to # of attempts remaining is currently triggered by start of new code entry rather than delay. Mentioning here as the time seemed critical. Almost messed up my last attempt because I didn't see the remaining attempts on time

### Issue 8
Copy: `PUK code does not match` should be `Wrong PUK code`

**Comment by yenda** [comment]
@hesterbruikman 1-7-8 are done now
2 is not worth it imo, this is rare action

**Comment by churik** [comment]
## Issue 9: No wrong PIN error on generating account flow
**Steps:**
- create multiaccount with keycard
- open wallet
- Add account > Generate account
- Enter wrong PIN
No info about wrong PIN is shown, bottom sheet just closed and reopened
After 3 attempts "Keycard is frozen" popup appears

## Issue 10: On changing PIN code app doesn't accept valid PUK and shows invalid amount of remaining attempts

So basically this workflow is broken.
**Steps:**
- create multiaccount with keycard
- go to Settings > change PIN
- Enter new PIN
- on entering PUK code screen enter invalid PUK
ezgif com-video-to-gif (10)

In case of entering valid PUK "Wrong PUK" error is shown

**Comment by guylouis** [comment]
**Issue 10 - complement on the expected behaviour**

If PIN code is not frozen (less than 3 wrong attempts) then when user wants to change his PIN in Settings > change PIN he actually should **not** be asked for his PUK

**Comment by guylouis** [comment]
Also 
- **issue 2** (EDITED) got the same success screen with open/access existing keys option when unblocking the pin on the loging screen. When the unfreezing of PIN is done at other places (using a frozen card and trying to create a new account or trying to sign a tx) the success screen has not the 'open' or 'access existing keys' options

- **issue 3** - I agree this warning would be nice in most of the users situation, but still it's theoretically possible for a user to unfreeze his card with another phone. In this case, the pop-up would remain (unless it's a temporary alert message after user freeze his card) in the UI until the user taps his card again. Which means a wrong information would be displayed until then.

**Comment by hesterbruikman** [comment]
> issue 3 - I agree this warning would be nice in most of the users situation, but still it's theoretically possible for a user to unfreeze his card with another phone. In this case, the pop-up would remain (unless it's a temporary alert message after user freeze his card) in the UI until the user taps his card again. Which means a wrong information would be displayed until then.

Indeed this would be a temporary alert. I imagine this message to only valid be for the duration of the session. Once the app is killed or the user has signed out it will not show again. Agree we can do without it though, if the Reset passcode flow is available for both Frozen and Active state

**Comment by guylouis** [comment]
**issue 5 : could not reproduce it on my end (oneplus6)** 
I blocked the pin in the signtx flow by entering 3 times the wrong PIN, and got the 'keycard is frozen' popup with a link to unfreeze it.

**Comment by churik** [comment]
> **Issue 10 - complement on the expected behaviour**
If PIN code is not frozen (less than 3 wrong attempts) then when user wants to change his PIN in Settings > change PIN he actually should **not** be asked for his PUK

@guylouis so it should not be changed from previous version of workflow about changing PIN (user is asked about current PIN > and then enter and confirm new PIN)?

**Comment by hesterbruikman** [comment]
@churik change passcode should have 3 variations:
- A Active card + app unlocked
Step 1 Enter current passcode
Step 2 Tap card
Step 3 Enter new 6-digit passcode
Step 4 Repeat new 6-digit passcode

- B Frozen card + app unlocked
Step 1 Enter new passcode
Step 2 Confirm new passcode
Step 3 PUK-code entry
Step 4 Tap card

Tab bar is visible

- C Frozen card + app locked
Step 1 Enter new passcode
Step 2 Confirm new passcode
Step 3 PUK-code entry
Step 4 Tap card

Tab bar is not visible

**Comment by churik** [comment]
Thanks for clarification @hesterbruikman! really helpful.

**Comment by churik** [comment]
## Issue 11: # number of remaining attempts are showing too fast if card was already reset
(IMO it is elaborated version of issue 7, created by @hesterbruikman )

**Steps:**
- create multiaccount with keycard
- logout, enter the invalid PIN 3 times -> set new PIN
- login
- open send transaction screen
- enter invalid PIN again

**Expected result:** animation is the same as the first time before card reset
**Actual result:** # of attempts is showing for a moment and disappear.
It is the same for the unlocked and locked apps. Example for the locked app:


## Issue 12: Cancel during login after card resetting leads to "Wrong card" error
Can be related to issue 6.

**Steps:**
- create multiaccount with keycard
- logout, enter wrong PIN 3 times -> set new PIN -> on "Keycard access is reset" screen tap Open 
- as login is pretty slow in this case, tap on cancel
- try to login with new PIN

**Expected result:** can login
**Actual result:**  PIN is asked twice;
after entering PIN got "Wrong card" error
**Logs:** 
[Status-debug-logs-n.zip](https://github.com/status-im/status-react/files/4695209/Status-debug-logs-n.zip)

**Comment by yenda** [comment]
@hesterbruikman could you elaborate on 5 and 6? (Reproduction steps? What is expected?)

**Comment by hesterbruikman** [comment]
### Issue 5
Resolved in last build

### Issue 6
I'll see if I can reproduce as @guylouis also reports getting a wrong card error

**Comment by churik** [comment]
@hesterbruikman issue 6 and issue 12 are not the same?
In case of issue 12 I can reproduce "Wrong card"  error

**Comment by churik** [comment]
## Issue 13: At attempt to pair blocked card labels are overlapping on "Enter PIN" stage

**Steps:**
- get card blocked
- reinstall app
- try to pair card to new device

**Expected result:** "keycard is blocked" error
**Actual result:** "Keycard is frozen", 0 attempts left

ezgif com-video-to-gif (12)

## Issue 14: Keycard reset is not possible during card pairing (and it leads to impossibility to pair card at all)

**Prerequisites:**
- card with stored keys

**Steps:**
- open frow Recover with keycard
- enter valid pair code
- enter invalid PIN 3 times

**Expected result:** can set new PIN
**Actual result:** keyboard is frozen, app is on Step 2 of 2 on "Pairing" flow
Only way is to cancel flow - and anyway you can't pair card anymore, so this flow leads to blocking the card.
Monosnap 2020-05-28 16-02-29

**Comment by hesterbruikman** [comment]
> @hesterbruikman issue 6 and issue 12 are not the same?
> In case of issue 12 I can reproduce "Wrong card" error

Ah you're right, very likely it is. The one I ran into, and I believe @guylouis as well, was when signing tx instead of during login. I think that supports @guylouis's thinking that it could have to do with removing the card 'too soon'

**Comment by rasom** [comment]
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6 (same as 12)
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [x] 12 
- [x] 13
- [ ] 14 (I propose to fix this one separately as well @guylouis @hesterbruikman )

**Comment by hesterbruikman** [comment]
Here's a [video](https://www.evernote.com/shard/s269/client/snv?noteGuid=0f444af9-52a2-4a16-9bda-71282d5183f7&noteKey=b73846f41b60009d&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs269%2Fsh%2F0f444af9-52a2-4a16-9bda-71282d5183f7%2Fb73846f41b60009d&title=Video) for issue 12. Definitely seems **unrelated** to the pace it which the card is tapped/removed from the phone. It's not a total blocker IMO. I can tap Ok, select the multiaccount and unlock the keys. I'd rank it as medium prio, but I suspect it's easier to investigate and resolve now than later

**Review by hesterbruikman — APPROVED** [review]
Great work @yenda @rasom! Thanks for your spot on questions on the flows

**Comment by churik** [comment]
@rasom verified:
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [ ] 7 + 11
Still the same.
ezgif com-video-to-gif (14)
Sometimes animation is too fast to see number of attempts.
- [x] 8
- [x] 9
- [x] 10
- [ ] 6 +12
Reproducible with same steps on build with https://github.com/status-im/status-react/pull/10655/commits/e2c786138d5a7acfb824fcbb642d98e6e9671d92.


- [x] 13

**Comment by rasom** [comment]
> 7 + 11
Still the same.

@yenda can you please take a look again?

**Comment by rasom** [comment]
> 6 +12
Reproducible with same steps on build with

@churik same steps? Can you please add them again? As I see on gif you first disconnected card and then entered pin, right?

**Comment by churik** [comment]
@rasom 
I still can't reproduce it on simple login, 

**Steps:**

- create multiaccount with keycard
- logout, enter wrong PIN 3 times -> set new PIN -> on "Keycard access is reset" screen tap Open
- while "Processing" is shown, put card away and tap "Cancel"
- enter new PIN - it is asked twice and then error appears. 

But well - as I can't reproduce it on login (as you did yesterday) - it doesn't seem really prio for me right now.
cc @hesterbruikman

**Comment by yenda** [comment]
@rasom issue 15 


- I froze the card in a transaction, unfroze, went back to wallet right after without closing the unfrozen screen
- made a new transaction, wrong pin once, then cancelled the transaction
- back to profile tab it was a screen to enter pin with 2 attemps left, I entered the correct one and got the transaction was send popup

**Comment by rasom** [comment]
@yenda @churik 
issue 15 is reproducible with old "change pin" flow as well, so it is not introduced by this PR. I'm working on it and it is definitely a blocker, but it can be handled separately 

in order to reproduce it in `develop`
1. open change pin screen
2. switch to wallet
3. create transaction, try to enter wrong pin
4. switch back to profile tab
5. enter correct pin twice, transaction will be sent

**Comment by rasom** [comment]
15 should be fixed now

**Comment by churik** [comment]
@rasom 
last fix introduced new issue
### issue 16: After canceling bottom sheet and entering pin bottom sheet doesn't appear again
**Steps:**
- create account, log out 
- enter wrong PIN
- cancel bottom sheet
- enter PIN again
**Expected result:** bottom sheet appears
**Actual result:** nothing happens

**Comment by rasom** [comment]
@churik working on it

**Comment by rasom** [comment]
@churik 16 should be fixed now, but we need to check all cases like this one, I tried to do this but probably missed something.

**Comment by churik** [comment]
@rasom 
### ISSUE 17:  unable to create or restore account with keycard storage: app is freezing in "Processing" during account setup 
At attempt to restore account from seed phrase (or creating account) with storage "Keycard" app is not proceeding after "Begin setup" to passcode setup.
**Steps:**
- Access Key > Enter seed phrase > Enter valid seed phrase > Next
- Re-encrypt your keys
- Keycard > Next > Begin Setup
- tap card

Video from nightly:
ezgif com-video-to-gif (15)

Video from PR: 
ezgif com-video-to-gif (16)

So after connecting it freezes in "Processing" state, on nightly app opens passcode entering screen right after "connected".
Logs: 
```
06-01 18:18:57.305 31870 31952 D StatusModule: validateMnemonic
06-01 18:18:57.308 31870 32396 D StatusModule: {"error":""}
06-01 18:18:57.311 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :multiaccounts.recover/phrase-validated
06-01 18:18:57.313 31870 31951 D ReactNativeJS: DEBUG [status-im.multiaccounts.recover.core:105] - [recover] ::import-multiaccount
06-01 18:18:57.313 31870 31951 D ReactNativeJS: DEBUG [status-im.native-module.core:154] - [native-module] multiaccount-import-mnemonic
06-01 18:18:57.314 31870 31952 D StatusModule: multiAccountImportMnemonic
06-01 18:18:57.362 31870 31951 D ReactNativeJS: DEBUG [status-im.native-module.core:104] - [native-module]  multiaccount-derive-addresses
06-01 18:18:57.362 31870 31952 D StatusModule: multiAccountDeriveAddresses
06-01 18:18:57.369 31870 31951 D ReactNativeJS: DEBUG [status-im.native-module.core:344] - [native-module] gfycat-identicon-async
06-01 18:18:57.369 31870 31952 D StatusModule: generateAliasAndIdenticonAsync
06-01 18:18:57.371 31870 32401 D StatusModule: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAl0lEQVR4nOzY0QnCQBAGYRV70QItwwKTapIGcrDHZWH4me/5HhwWljWvRwhDaAyhMYTGEJqYkHf14X/fjt6fcu33+T4r72ImYgiNITTlrTVrtG26tl/MRAyhMURNYiZiCI0hNMu31uh2mr21qv8ER2ImYgiNITTL37Xu2k6r2yxmIobQGKImMRMxhMYQGkNoDKE5AwAA//+4pRxpSDMVNAAAAABJRU5ErkJggg==
06-01 18:18:57.371 31870 32401 D StatusModule: Bulky Able Firecrest
06-01 18:18:57.373 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :status-im.multiaccounts.recover.core/import-multiaccount-success
06-01 18:18:57.374 31870 31951 D ReactNativeJS: DEBUG [status-im.navigation:10] - :navigate-to :recover-multiaccount-success nil
06-01 18:18:57.401 31870 31951 D ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:41] - :on-screen-focus :recover-multiaccount-success
06-01 18:18:57.408 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :screens/on-will-focus
06-01 18:18:57.409 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :set
06-01 18:18:58.800 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :multiaccounts.recover/re-encrypt-pressed
06-01 18:18:58.804 31870 31951 D ReactNativeJS: DEBUG [status-im.navigation:10] - :navigate-to :recover-multiaccount-select-storage nil
06-01 18:18:58.848 31870 31951 D ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:41] - :on-screen-focus :recover-multiaccount-select-storage
06-01 18:18:58.857 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :screens/on-will-focus
06-01 18:18:58.860 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :set
06-01 18:19:00.115 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :intro-wizard/on-key-storage-selected
06-01 18:19:01.027 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :multiaccounts.recover/select-storage-next-pressed
06-01 18:19:01.033 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :recovery.ui/keycard-option-pressed
06-01 18:19:01.036 31870 31951 I ReactNativeJS: INFO [status-im.hardwallet.card:28] - [keycard] check-nfc-enabled
06-01 18:19:01.038 31870 31951 D ReactNativeJS: DEBUG [status-im.navigation:10] - :navigate-to :keycard-onboarding-intro nil
06-01 18:19:01.086 31870 31951 I ReactNativeJS: INFO [status-im.hardwallet.card:33] - [keycard response] check-nfc-enabled
06-01 18:19:01.087 31870 31951 D ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:41] - :on-screen-focus :keycard-onboarding-intro
06-01 18:19:01.093 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :hardwallet.callback/check-nfc-enabled-success
06-01 18:19:01.094 31870 31951 D ReactNativeJS: DEBUG [status-im.hardwallet.core:116] - [hardwallet] check-nfc-enabled-success nfc-enabled? true
06-01 18:19:01.094 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :screens/on-will-focus
06-01 18:19:01.095 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :set
06-01 18:19:02.427 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :keycard.onboarding.intro.ui/begin-setup-pressed
06-01 18:19:02.430 31870 31951 D ReactNativeJS: DEBUG [status-im.hardwallet.common:178] - [hardwallet] show-sheet-with-connection-check card-connected? nil
06-01 18:19:02.432 31870 31951 D ReactNativeJS: DEBUG [status-im.hardwallet.common:132] - [hardwallet] set-on-card-read :hardwallet/check-card-state
06-01 18:19:02.434 31870 31951 D ReactNativeJS: DEBUG [status-im.hardwallet.common:100] - [hardwallet] set-on-card-connected :hardwallet/get-application-info
06-01 18:19:02.497 31870 31951 I ReactNativeJS: INFO [status-im.hardwallet.card:50] - [keycard] on-card-connected
06-01 18:19:02.498 31870 31951 I ReactNativeJS: INFO [status-im.hardwallet.card:46] - [keycard] on-card-disconnected
06-01 18:19:03.895 31870 31966 I NFCCardManager: tag connected
06-01 18:19:03.908 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :hardwallet.callback/on-card-connected
06-01 18:19:03.909 31870 31951 D ReactNativeJS: DEBUG [status-im.hardwallet.core:518] - [hardwallet] card globally connected
06-01 18:19:03.911 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :status-im.hardwallet.common/on-card-connected
06-01 18:19:03.913 31870 31951 D ReactNativeJS: DEBUG [status-im.hardwallet.common:457] - [hardwallet] on-card-connected :hardwallet/get-application-info on-card-read :hardwallet/get-application-info
06-01 18:19:03.914 31870 31951 D ReactNativeJS: DEBUG [status-im.hardwallet.common:108] - [hardwallet] stash-on-card-connected :hardwallet/get-application-info
06-01 18:19:03.923 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :hardwallet/get-application-info
06-01 18:19:03.924 31870 31951 D ReactNativeJS: DEBUG [status-im.hardwallet.common:376] - [hardwallet] get-application-info pairing nil
06-01 18:19:03.925 31870 31951 I ReactNativeJS: INFO [status-im.hardwallet.card:78] - [keycard] get-application-info
06-01 18:19:03.928 31870 32447 D CardChannel: COMMAND CLA: 00 INS: A4 P1: 04 P2: 00 LC: 09
06-01 18:19:03.967 31870 32447 D CardChannel: RESPONSE LEN: 43, SW: 9000 
06-01 18:19:03.967 31870 32447 D CardChannel: -----------------------
06-01 18:19:04.013 31870 32447 I SmartCard: Card initialized? false
06-01 18:19:04.016 31870 31951 I ReactNativeJS: INFO [status-im.hardwallet.card:91] - [keycard response fail] get-application-info
06-01 18:19:04.021 31870 31951 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :hardwallet.callback/on-get-application-info-error
06-01 18:19:04.023 31870 31951 D ReactNativeJS: DEBUG [status-im.hardwallet.common:427] - [hardwallet] application info error  {:code "android.nfc.TagLostException", :error "Tag was lost."}

```
Happened to me several times in a row, I was able to create account on https://github.com/status-im/status-react/pull/10655/commits/f2b913be9296f0873795987041fcbd27c54994a3 commit (but I saw this error few times), but I'm unable to create or restore account at all on last commit: 
https://github.com/status-im/status-react/pull/10655/commits/6f27fd3d200d235d63e3a056f7587118f93e383e

**Comment by churik** [comment]
Testing is still in progress.
So far leftovers: 
- issue 14 will be reported separately
- issue 18: 
1) Profile-> Keycard-> Change PIN -> Enter invalid PIN -> tap on Wallet tan
2) Send Transaction -> proceed to transaction signing -> Enter invalid PIN 2 times > Dismiss Alert -> Cancel on bottom sheet
3) tap on Profile tab -> Enter wrong PIN
IMG_7712
- issue 19: on canceling bottom sheet on PUK entering app proceed to the start of the flow of resetting PIN
**Steps:**
1) enter invalid PIN > 3 times
2) set new PIN
3) enter invalid PUK 
4) Tap "Cancel" on bottom sheet 
**Expected result:** same screen
**Actual result:** step 1/2 in Reset passcode flow

IMO not blockers for this PR and can be fixed later.
cc @hesterbruikman

**Comment by churik** [comment]
@rasom or @yenda  can you take a look?

### issue 20: after entering invalid PIN in Profile > Keycard > Change 6-digit passcode new screen for entering new PIN is not shown
**Steps:**
- create account with keycard
- login
- open Profile > Status keycard > Change passcode
- enter invalid PIN
- tap card
- enter valid PIN

**Expected result:**
can proceed to enter new passcode
**Actual result:**
ezgif com-video-to-gif (17)

So in this case you need to reopen flow to proceed

**Comment by churik** [comment]
### issue 21: after resetting passcode on "add account" can't add account until reopening flow
**Steps:**
- create multiaccount with keycard
- tap on wallet > add new account > enter wrong passcode 3 times > reset passcode
- tap back
- go to wallet tab. Expected, that bottom sheet will be hidden in this case - but in fact it is shown with entered PIN
- enter new PIN

**Expected result:**
new account is added
**Actual result:**
can't add account - after tapping card nothing happens
In order to add a card user should go back and start process again
Video: https://drive.google.com/file/d/1On02Vd5qAC_yW1fQMcE_d7m0qufviKFm/view?usp=sharing

IMO not a blocker for this PR

**Pull request merged**
