### PR TITLE
[#9345] fix some issues on keycard login screen

### LINKED ISSUE #9345: Keycard sign in – "More" button behavior is wrong + breadcrumbs must be dropped
_Part of #9264 keycard sign in epic (mark as checked there, when closing this issue)_

1. On the sign in screen, the **"..."** in the top right corner should open a drop-down with one item only "Get a new key"

Image:
get-a-new-key

Figma:
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12

2. The breadcrumbs that read "Step 1 of 2" should be removed to match the non-Keycard flow.

### PR DESCRIPTION
**Pull request by rasom**
fix #9345 

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Comment by churik** [comment]
@rasom thank you for tackling it.

**1) "Create new key" instead of "Get a new key"** 
In https://github.com/status-im/status-react/issues/9345 I see that in the sign in screen, the "..." in the top right corner should open a drop-down with one item only "Get a new key".
Currently, it opens a screen with "Create new key"
photo_2019-11-15 15 17 40

**2) "Create new key" opens "Store your key on keycard" screen.**
But it may happen that user wants to generate account without keycard, so in this case I expect the same behavior as for "Generate new key":

photo_2019-11-15 15 08 42

**3) Tapping back after tapping on "Create new key" redirects to carousel view instead of login screen**

Steps: 
- create an account with Keycard
- log out
- tap on options > "Create new key"
- tap back

Expected result: login screen
Actual result: 
photo_2019-11-15 15 18 08


@andmironov please fix if smth from above is not expected, thanks!

**Comment by rasom** [comment]
@churik issues should be fixed now

**Comment by rasom** [comment]
@churik hold on, it seems that a new account still can't be created and we probably need to open a different screen when go to "Access key", because there is now way to restore an acc from mnemonic there at the moment.

**Comment by rasom** [comment]
@churik should be fixed now

**Comment by churik** [comment]
Retested failed e2e - all failures are related to balance fetching problems, so they are reproducible from time to time.

**Pull request merged**
