### PR TITLE
[#9748] eip681 parsing uri with whitespaces

### LINKED ISSUE #9748: QR code reader inserts a space before the read address, throws error
# Bug Report

## Problem

When you scan a QR code with a "0x01234..." Ethereum address, Status gives the error "Invalid address" and displays the address with a white space before it, which makes me think that space is interpreted as part of the address.

#### Expected behavior

There's no space in the QR code data, so Status has some glitch. Also, if it *did* have an white spaces before or after, Status should notice it and trim it, and interpret the data afterwards.

#### Actual behavior

Error thrown, see above. Can't proceed with the transaction.

#### Acceptance Criteria

1. No space inserted
2. Spaces at the beginning and the end of the QR code data automatically removed

### Reproduction
- Open Status
- Read a QR code from Etherscan from a random address

### Additional Information

- Status version: 0.14
- Operating System: Android

#### Logs

### PR DESCRIPTION
**Pull request by ghmulti**
Fixes #9748 

Would like to hear feedback from core developers - should the fix(whitespace trimming) be done rather on the view part?

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Comment by 3esmit** [comment]
What exactly changes here? Just some spaces at beginning or end?

**Comment by ghmulti** [comment]
@3esmit correct, spaces at the beginning or end will not affect on address validity

**Review by 3esmit — APPROVED** [review]

**Comment by ghmulti** [comment]
ok, it took _just_ 4 times to sign commit properly  :man_facepalming: :man_facepalming:

**Comment by churik** [comment]
@ghmulti thank you for the contribution and sorry for delay in testing!
Checked build with https://github.com/status-im/status-react/commit/ca50a77feeafb81549a12e45ede44b9f22de1cdb commit.
At attempt tp scan QR with spaces:
image
And still, I see the "Invalid address" error.
Tried scanning from Choose recipient > Scan QR or from "Scan QR" icon on the top bar - same result.

**Comment by ghmulti** [comment]
@churik thanks for feedback - after reading your comment I realized that #9748 issue had actually nothing to do with whitespaces (the way error in the dialog is displayed probably makes this confusion).
I thought initially that qr code had to be formatted according to EIP 681 (with "ethereum:" scheme in front) which kind of makes sense in general except the case when you go to "Choose recipient" menu > Scan QR button (so it is explicitly said that you are scanning the arbitrary valid ethereum address[eip 55] or ens address).

**Comment by flexsurfer** [comment]
@ghmulti is this still relevant? @yenda could you take a look?

**Comment by ghmulti** [comment]
@flexsurfer yes

**Comment by churik** [comment]
> thanks for feedback - after reading your comment I realized that #9748 issue had actually nothing to do with whitespaces (the way error in the dialog is displayed probably makes this confusion).
I thought initially that qr code had to be formatted according to EIP 681 (with "ethereum:" scheme in front) which kind of makes sense in general except the case when you go to "Choose recipient" menu > Scan QR button (so it is explicitly said that you are scanning the arbitrary valid ethereum address[eip 55] or ens address).

So what's next here?
IMO it would be nice to scan addresses with the content value (`ethereum:0xDdc867bAB69c9488E65f610E071752f621C7F504@3`), normalised one (i.e. ` 0xDdc867bAB69c9488E65f610E071752f621C7F504`) or same but non-normalised and put value to `Recipient`
Currently at attempt to scan  ` 0xDdc867bAB69c9488E65f610E071752f621C7F504` I see error `invalid address`

WDYT @flexsurfer ?

**Comment by flexsurfer** [comment]
@churik does this PR fix anything ?

**Comment by churik** [comment]
@flexsurfer no, I don't think so

**Pull request closed without merging**
