### PR TITLE
Upgrade firebase 5.1.1

### PR DESCRIPTION
**Pull request by pedropombeiro**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
Small PR to remove unrelated stuff from https://github.com/status-im/status-react/pull/8545.

### Testing notes

We should test push notifications, especially check if there's no crash on iOS (since that's what the fork we're replacing was fixing).

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by annadanchenko** [comment]
@PombeirP both on nightly and in this PR I have an issue if tap on PN received when android app was closed: https://github.com/status-im/status-react/issues/8550 

I don't think it's a blocker to test this PR as I'm getting the notification but I can't be 100% sure that opening app from PN works fine in this PR because of the mentioned issue.

**Comment by pedropombeiro** [comment]
@annadanchenko is this only happening recently? It looks like the result of a bad refactoring.

**Comment by annadanchenko** [comment]
> @annadanchenko is this only happening recently? It looks like the result of a bad refactoring.

it's working fine in release 0.13.0 but it was out on May 28 that is quite some time ago

**Comment by annadanchenko** [comment]
@PombeirP no PNs are received if messages are sent between 0.13.0 release and this pr. not sure it's expected (in both cases: if app is on background ios/android or closed on android)

**Comment by pedropombeiro** [comment]
@annadanchenko there should be no behavioral changes between current nightly and this PR in terms of notifications. So if you send a message between 0.13.0 release and latest nightly it behaves differently?

**Comment by annadanchenko** [comment]
> @annadanchenko there should be no behavioral changes between current nightly and this PR in terms of notifications. So if you send a message between 0.13.0 release and latest nightly it behaves differently?

yes, it's same with nightly and 0.13.0 so not introduced here

**Comment by pedropombeiro** [comment]
> yes, it's same with nightly and 0.13.0 so not introduced here

That's concerning. If it wasn't introduced by this PR, then we need to check what other changes have been made recently to the PNs code in https://github.com/status-im/status-react/commits/develop/src/status_im/notifications/core.cljs and https://github.com/status-im/status-react/commits/develop/src/status_im/notifications/background.cljs.

**Comment by pedropombeiro** [comment]
Something that might explain not receiving notifications is if the SHA3 calculated by this commit was different that the one in 0.13.0: https://github.com/status-im/status-react/commit/04de022eae5c56b55b99951e65315fabb7e21e78#diff-47fede718382f29c064b23777c288041. In this commit we moved from `dependencies/web3-prototype.sha3` to `dependencies/web3-utils.sha3`. I'd expect it to return the same string, but could be a case difference or something like that. cc @yenda

**Comment by pedropombeiro** [comment]
@annadanchenko if this PR isn't making things worse, I'd suggest merging it so that the Reproducible Android builds PR can become smaller (it is currently based on this branch).

**Pull request merged**
