### PR TITLE
android: add adaptive icon for non-debug builds

### LINKED ISSUE #8098: Update Android app icon as PlayStore demands
# Problem
New app icon specification for Google Play
App icons on Google Play are changing. From June 24, transparent backgrounds will no longer be allowed, and Google Play will dynamically add rounded corners and drop shadows to icons.

Let us know when your icon meets the new specification. If you're not quite ready, you can keep using the old specification for now. We'll automatically scale down your icon on June 24. 

https://developer.android.com/google-play/resources/icon-design-specifications

@hesterbruikman can you have a look if the new icon proposed in PlayStore is ok

### PR DESCRIPTION
**Pull request by mandrigin**
debug icons are the old ones due to the lack of assets

fixes #8098

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by mandrigin** [comment]
@andmironov @errorists  here is the Android build with adaptive icons: https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190520-115722-e6911e-pr.apk

I guess you need Android 9 to test it, but I'd love for one of you to verify that it looks as intended.

**Comment by errorists** [comment]
@mandrigin I have no way to test this, but would you take a _unless I screwed up something really badly it will work_ as a yes? :) To be sure I'd need a screenshot from one of OEMs using adaptive icon shapes like anything Samsung or stock Google.

**Comment by mandrigin** [comment]
@errorists that's how it looks like on my Android emulator with square icons.

image

**Comment by errorists** [comment]
Thanks! it's good, that's what it's about, you're on the third icon shape here

image

**Comment by mandrigin** [comment]
@annadanchenko @Serhy when you will be testing the build, can you put a screenshot with the icon here too? Especially on a Pixel (round icons).

**Comment by asemiankevich** [comment]
Android 8 - Huawei

image

Android 7 - Xiaomi

image

**Comment by mandrigin** [comment]
@errorists it looks like it works :) @asemiankevich I don't think we need any additional testing there. No  other changes were made.

**Comment by corpetty** [comment]
Status PR pixel Android 9 https://imgur.com/UOuw2Ix

**Comment by mandrigin** [comment]
@corpetty 404 :(

**Comment by corpetty** [comment]
edited link, it's fixed.

**Comment by mandrigin** [comment]
@corpetty thanks! yeah, it looks like it works :)

**Comment by annadanchenko** [comment]
pixel xl, android 9

Screenshot_20190520-172134


galaxy s6, android 6.0.1
Screenshot_20190520-172107

**Pull request merged**
