### PR TITLE
Update zh_Hans_CN.json and zh_hans.json 

### PR DESCRIPTION
**Pull request by jinhojang6**
Translated by the Chinese community

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
@jakubgs could you please assist with e2e apk here? https://ci.status.im/job/status-react/job/prs/job/android-e2e/view/change-requests/job/PR-8420/

**Comment by jinhojang6** [comment]
Is it okay to merge this? @asemiankevich

**Comment by asemiankevich** [comment]
> Is it okay to merge this? @asemiankevich

it would be nice to wait for all builds to be created and to run autotests. So, not yet

**Comment by jakubgs** [comment]
I'd recommend rebasing first.

**Comment by asemiankevich** [comment]
@jinhojang6 Jinho, would you mind to rebase please?

**Comment by asemiankevich** [comment]
@jinhojang6 please rebase and squash your commits

**Comment by flexsurfer** [comment]
@jinhojang6 could you rebase please?

**Comment by jinhojang6** [comment]
Oh I am really sorry, I haven't received any notifications on this. Should I close this pull request and submit it again?

**Comment by jakubgs** [comment]
Looks like our tests aren't ready for the new translation:
```
[2019-07-17T17:08:12.283Z] Testing status-im.test.i18n
[2019-07-17T17:08:13.660Z] 
[2019-07-17T17:08:13.660Z] FAIL in (locales-only-have-existing-tran-ids) (cljs/test.cljs:476:9)
[2019-07-17T17:08:13.660Z] Extra translations in locale :zh-Hans-CN
[2019-07-17T17:08:13.660Z] #{:pfs-warning-title :pfs-warning-content :pfs}
[2019-07-17T17:08:13.660Z] 
[2019-07-17T17:08:13.660Z] expected: (spec/valid? :status-im.test.i18n/labels (labels-for-all-locales))
[2019-07-17T17:08:13.661Z]   actual: (not (spec/valid? :status-im.test.i18n/labels ...(omitted)...
```
https://ci.status.im/blue/organizations/jenkins/status-react%2Fprs%2Fandroid/detail/PR-8420/3/pipeline

We might need some additional help from @flexsurfer or maybe @antdanchenko.

**Comment by jinhojang6** [comment]
@flexsurfer @asemiankevich 
Really sorry, I haven't checked your comment for a while. I've rebased it.

**Comment by flexsurfer** [comment]
@jinhojang6 please take a look, you have extra translations which we don't have in english
Extra translations in locale :zh-Hans-CN
[2019-07-17T17:08:13.660Z] #{:pfs-warning-title :pfs-warning-content :pfs}

**Comment by jakubgs** [comment]
Okay, that cleared up the translation test failures, but there's still one for `android-e2e` build:
```
copying path '/nix/store/hmb1vjnss6lkx3kqn7a1hg63y3nqlwlw-ruby2.5.3-unf_ext-0.0.7.6' from 'https://nix-cache.status.im'...
hash mismatch importing path '/nix/store/hmb1vjnss6lkx3kqn7a1hg63y3nqlwlw-ruby2.5.3-unf_ext-0.0.7.6';
  wanted: sha256:1h5a88p6ihnahbdw1wsvyf56abvq49vnfg517ya04li87p1bijx4
  got:    sha256:0c9bi1bfilkjphm6f8y1fp9fp2pgc99ljaqcs38cf87sbxr1i01l
error: build of '/nix/store/xbgkw0207n708xaw0n27yzd9fvns4510-fastlane-2.127.1.drv' failed
```
Looks like some disparity in cache compared to local `/nix/store` contents. I'll try garbage collecting Nix.

**Comment by jakubgs** [comment]
Looks green to me.

**Pull request merged**
