### PR TITLE
[Android] send logs to error-reports@status.im

### PR DESCRIPTION
**Pull request by rasom**
* only email apps are suggested when sharing logs
* recipient field is pre-filled with `error-reports@status.im`

status: ready

### CODE REVIEW

**Comment by jeluard** [comment]
Can you provide some more context? When/what do we send exactly?

**Comment by rasom** [comment]
@jeluard the content is not objective of this PR, see https://github.com/status-im/status-react/issues/6710, https://github.com/status-im/status-react/pull/7137

**Review by pedropombeiro — APPROVED** [review]
lgtm

**Review by mandrigin — APPROVED** [review]
looks good

**Comment by rasom** [comment]
just rebased onto `develop`, probably will help with tests

**Comment by Serhy** [comment]
@rasom that looks good with Android 8, Andriod 9 but two issues:

**(1)** On Android 6.0.1 no fields are pre-populated (neither log package attached) after mail client selected when tap on Send Logs. Doesn't matter whether Storage Permissions are enabled or not (it applies for geth.log file access only but anyway).

Preconditions: 
On Android 6.0.1 device. User logged in to email account (e.g. in gmail)
Steps:
1) Open Status, create new account
2) Navigate to Profile
3) Tap Send Logs -> choose mail client

Actual result: All fields are empty. 
Screenshot 2019-05-08 at 20 20 04

Logcat with logs starting right before the `Send Logs` button is tapped are [here](https://github.com/status-im/status-react/files/3158516/Note4Android6-0-1.log):

**(2)** On Desktop app we also have the ability to send logs. With current changes when tap `Send logs` button - nothing happens. In Status.log it is reflected only with two lines:
```

20:06:14.365 - D - [jsserver] - [status-im.utils.handlers:34] - Handling re-frame event:  :logging.ui/send-logs-pressed
20:06:14.367 - C - [default] - Attempt to invoke "sendLogs(QString)" with 2 arguments

```

I guess with current PR no changes should be on Desktop side: once `Profile` -> `Advanced Settings` -> `Send logs` button pressed, .zip package created and no mail clients are opened. 
Could you fix desktop please?

**Comment by rasom** [comment]
@Serhy the only way I found is to open gmail directly on 6.0.1, otherwise either file can't be attached or non-email apps appear as sharing options. 

Desktop issue should be fixed as well now

**Comment by ghost** [comment]
`mobile_files/yarn.lock` changed. Pinging @jakubgs, @mandrigin, and @corpetty

**Comment by Serhy** [comment]
Looks good for MacOS, Android, iOS. Failed e2e test is not this PR issue (False Fail - faucet was not received)

**Pull request merged**
