### PR TITLE
[Android] default white background on all screens

### PR DESCRIPTION
**Pull request by rasom**
fixes some UI issues

status: ready

### CODE REVIEW

**Review by errorists — APPROVED** [review]

**Review by rachelhamlin — APPROVED** [review]

**Comment by rachelhamlin** [comment]
Thanks @rasom!

**Review by mandrigin — APPROVED** [review]

**Comment by asemiankevich** [comment]
@rasom which issues are fixed here, maybe we have some IDs ? Or any other insight? Thank you!

**Comment by rasom** [comment]
@asemiankevich the complain was that background is transparent in some screens and that's why transitions look ugly. I'm sure you can find such cases in nightly, so these should be fixed

**Comment by hesterbruikman** [comment]
@asemiankevich an example is account explorer on nightly Android. 
- Wallet
- Tap on main account
- Go back from main account to account explorer

**Comment by asemiankevich** [comment]
alright thanks!

**Comment by rasom** [comment]
well actually I don't see any difference in that wallet case...

**Comment by rasom** [comment]
It seems that it is already fixed in `develop` after react-navigation upgrade, so @asemiankevich please compare with release (for instance nav from accounts list to a specific account before login).
 We still need to merge this PR as it removes unnecessary condition.

**Comment by asemiankevich** [comment]
> It seems that it is already fixed in `develop` after react-navigation upgrade, so @asemiankevich please compare with release (for instance nav from accounts list to a specific account before login).
> We still need to merge this PR as it removes unnecessary condition.

i am checking with release now but we dont have the case @hesterbruikman mentioned in release yet.

**Comment by asemiankevich** [comment]
i've checked this PR against nightly and release, (screens mostly) i did not notice any regressions.

**Pull request merged**
