### PR TITLE
Upgrade to RN 0.60.5 and enable Hermes JS engine

### LINKED ISSUE #8665: Fix 64bit apk freezes on arm64 hardware
# Problem

When building the app for 64bit arch as required by Google Play Store, we get freezes on arm64 hardware.
The freezes are random. There is no obvious indicator of a freeze in the logs besides the fact that there is no more js logging statements appearing, or no js logs at all in logcat if the freeze occurs during splash screen.

## Implementation

We have tried:
- upgrading realm to v2.29.1, because it fixes https://github.com/realm/realm-js/issues/2400 , but it didn't help
- adding x86-64 to abi filter https://github.com/status-im/status-react/pull/8326/commits/331a11cf4528752fb2e331684e8f3d1e62005a35 
- removing realm (we've tested version without realm https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190729-090042-498654-pr.apk , from this PR #8528 , it still has the same problem)
- updating to latest JSC https://github.com/status-im/status-react/pull/8528/commits/a1834903b0d6c6f030a60f7763f97fd40c0ec167

Dismissed cause:
- status-go is compiled for all arch already with gomobile so we consider it is not the issue (will try with debug level logs though to make sure it isn't an arch issue on go side)

We need to try:
- considering that it seems like there is no logs for status-go whatsoever in 64bits arch, we need to investigate the reason behind that
- upgrading react-native and using hermes js engine (which is also said to be much faster)

## Acceptance Criteria

No freezes of the 64bits apk on 64bits devices

### LINKED ISSUE #8672: Update react-native to 0.60.5 and use Hermes js engine
# Problem

react-native recently had a major update to 0.60. It brings a lot of improvements, including auto-linking of libraries and an improved JS engine for Android called Hermes

Hermes is the main reason we want to do this upgrade now, because the Play Store now requires to publish 64bits apks starting 1st of August. As of today are experiencing random freezes on 64bits architectures with these apks and we have tried many options already https://github.com/status-im/status-react/issues/8665

This effort will take some time because nix makes the update process less trivial than it uses to be, and we also have a few libraries that are deprecated in favor of community maintain libraries that we need to switch.

## Implementation

- adapt the nix building process
- enable the Hermes JS engine
- move from deprecated core libs to community libs

## TODO (non-exhaustive)

- [x] Initial source-code migration work on status-react
  - [x] Disable auto-linking during the initial migration
- [x] Migration with AndroidX, Jetifier and Hermes disabled
  - [x] Migrate 3rd-party RN modules (includes move from deprecated core libs to community libs)
- [x] Migration with AndroidX and Jetifier enabled
  - [x] Migrate to AndroidX APIs
  - [x] Fix usage of deprecated ListView reported by RN at startup
- [x] (OPTIONAL) Enable auto-linking for all RN modules supporting it
 
- [x] Migrate Nix release-android build
  - [x] Fix Gradle config overrides not applying correctly to subprojects (not an issue outside of Nix pure builds)
  - [x] Account for `:react-native-android:installArchives` not existing anymore
  - [x] Get rid of Realm, as it is hardcoded to use JSC
- [x] migrate to community version of net-info
- [x] Migration with Hermes enabled
  - [x] Remove RAM bundle (https://github.com/status-im/status-react/pull/8863)
- [x] get rid of usage of component-will-mount because it is deprecated (https://github.com/status-im/status-react/pull/8858)
- [x] Fix [issue](https://github.com/facebook/react-native/issues/25601#issuecomment-510856047) running Hermes command in `node_modules/react-native/react.gradle`
- [x] fix migration of react-native-camera (error accessing `.RNCamera`)
- [x] migrate to community version of webviews (might be big)
- [x] Fix CI tests
- [x] Fix Android build on macOS (https://github.com/status-im/status-react/issues/8952)
- [x] Ensure everything works with iOS
- [ ] Ensure everything works with Desktop
  - [ ] net-info replacement for desktop?

## Acceptance Criteria

- project is now using react-native 0.60.5 (including iOS and Desktop)

### PR DESCRIPTION
**Pull request by pedropombeiro**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes https://github.com/status-im/status-react/issues/8672
fixes https://github.com/status-im/status-react/issues/8665

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
This PR fixes the [64-bit issue](https://github.com/status-im/status-react/issues/8665) on Android by enabling Hermes on RN 0.60.5. It has quite a few considerations, since some deprecated components were removed from RN and moved into separate community projects, sometimes with changed APIs (e.g. react-native-camera, react-native-webview).

### Review notes

This PR is based on the branch from https://github.com/status-im/status-react/pull/8932 in order to minimize future merges.

It takes advantage of the new AutoLinking functionality in Realm, so a lot of cruft was removed from gradle and pod files.

A gist of the changes in this PR:
- AutoLinking
- Move to AndroidX libraries
- Move to community version of react-native-camera
- Use newer versions of @react-native-community/netinfo, react-native-mail, react-native-image-crop-picker, react-native-svg, react-native-securerandom, react-native-firebase either due to the fact that they now support AutoLinking or that they use AndroidX
- Added some required changes in react-native-webview-bridge since it didn't support the community webview (would be super-useful to have @rasom's review there since there's an exported variable from the old RN's webview that is no longer present in the community webview)
- `gradle react-native-android:installArchives` no longer exists (the archives are downloaded directly) so had to remove that from the Nix expression
- Changed minSdkVersion from 18 to 23 due to react-native-camera changes
- Am no longer passing `callRPC` to `WebViewBridgePackage`

### Testing notes

Full regression testing (special focus on web browser-related functionality on iOS) 

#### Platforms

- Android
- iOS

##### Non-functional

- CPU performance / speed of the app

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]
merge

**Review by flexsurfer — APPROVED** [review]

**Comment by jakubgs** [comment]
I love how a bot with Pedro's face pings Pedro to approve changes on PR opened by Pedro.

**Comment by yenda** [comment]
@siphiuel in development everything is very slow after login, especially the time it take between the login signal is received and the moment the home screen appears. Maybe you could investigate that

**Comment by vitvly** [comment]
@yenda yes same on my machine

**Review by jakubgs — APPROVED** [review]
Great work Pedro, just great.

**Comment by yenda** [comment]
There might have been some changes to react-native input fields because now the mnemonic input field when recovering an account is multiline which results in bad UI

**Comment by flexsurfer** [comment]
@Serhy could you try a latest working build here, and test performance of chats with lots of new messages as you you've done before? i can see a delay for 1-3s when switching between chats list and chat

**Comment by flexsurfer** [comment]
@PombeirP could you rebase and fix android builds?

**Comment by Serhy** [comment]
> @Serhy could you try a latest working build here, and test performance of chats with lots of new messages as you you've done before?

Sure, better to wait the last working build as there are some more changes vs last Android build at the moment. 
I'll create release build then so we could compare (last performance stats all were done with release builds)

**Comment by pedropombeiro** [comment]
Added a fix to macOS Android builds in https://github.com/status-im/status-react/commit/0fc03176f990ce04a8d410437047e2311e69ff4a, please review. The idea is that since watchman isn't able for some reason to create a socket while inside a Nix sandbox on macOS, we ensure a watchman instance is running outside the sandbox and then pass the socket path to the Nix build script.

**Review by jakubgs — APPROVED** [review]
Ugly exception but nice fix.

**Comment by Serhy** [comment]
In order to check performance I builded release build of feature/upgrade-to-rn-hermes branch (and proceed testing with the release build on Android and iOS)

Status (low, Android) Galaxy Note 4 | Interaction | Foreground | Startup | Sync |  
-- | -- | -- | -- | -- | --
Release build 0.14.0 (July 23, build 10 of release) | 2.86s | <0.1s | 10.24s | 7.93s |  
Release build Hermes (current PR branch) | 2s | <0.1s | 5.33s | **12s** |  

**Sync**: time to receive 200 text message (from single user in public chat) from when 'Connected' status appeared on Chats screen till the `9+` counter is shown (during this point app is frozen)
**Interaction:** time from tap on chat with 200 text messages on Chats screen till the actual chat opened.

What is visibly degraded in performance is the navigation to<->from chat with messages. 
When I measured above activities, which are the same for previous release build(s) (with the same data and actions) I noticed that navigating to `#status` public chat with the similar amount of messages happens ~1s slower. Difference is that in `#status` VS `200messages` (where I tested interaction/navigation time) many messages from different users. So maybe more icons or mixed formatting (e.g. some messages have links) or additional username in that case slowing down navigation between Chats main and chat views even more.

With iOS and Android browser I can send transaction in Mainnet (buy/sell cryptokitty) can transact in Ropsten (all transaction in simpledapp.eth)
Messaging in 1-1, public, group chats are working fine (except lags with navigation described above)

**Comment by pedropombeiro** [comment]
OK current state has macOS Android builds fixed as well as debug builds fixed (currently only using Hermes for release Android builds to avoid the perf penalty of debug Hermes).

**Comment by pedropombeiro** [comment]
Figured out a workaround to allow us to use Hermes on debug builds as well without the slowdown, so I'll add a fixup commit.

**Comment by ghost** [comment]
`desktop_files/yarn.lock` and `mobile_files/yarn.lock` changed. Pinging @jakubgs, @PombeirP, and @corpetty

**Comment by ghost** [comment]
`desktop_files/yarn.lock` and `mobile_files/yarn.lock` changed. Pinging @jakubgs, @PombeirP, and @corpetty

**Review by jakubgs — APPROVED** [review]

**Comment by pedropombeiro** [comment]
@Serhy is testing underway in this PR, or should we start organizing so that devs start testing it?

**Comment by Serhy** [comment]
@PombeirP I'm testing it now. The performance degradation is still present in navigation between Chats <-> chat-with-messages. 
Is it part of this PR to fi or we will look at it separately?

**Comment by flexsurfer** [comment]
@Serhy separately here https://github.com/status-im/status-react/issues/8962

**Comment by vitvly** [comment]
@Serhy will investigate the perf issue separately

**Comment by Serhy** [comment]
Can exchange messages in 1-1/Public/Group chat (custom userpic shared too)
Can receive messages from offline inbox.
No issues with web-browser, can navigate between web-pages, can transact (buy and sell) cryptokitty. Webhistory persist as expected. 
Can block/unblock contact
Can transact in simpledapp.eth under Ropsten network
Can send transaction from Wallet 
Can pair accounts between iOS and Android builds
List of autotest results ran and checked, - no regression (some known issues) https://ethstatus.testrail.net/index.php?/runs/view/4143&group_by=tests:status_id&group_order=desc

I don't see regressions apart performance one which will be looked at separately

**Comment by ghost** [comment]
`desktop_files/yarn.lock` and `mobile_files/yarn.lock` changed. Pinging @jakubgs, @PombeirP, and @corpetty

**Comment by ghost** [comment]
`desktop_files/yarn.lock` and `mobile_files/yarn.lock` changed. Pinging @jakubgs, @PombeirP, and @corpetty

**Comment by ghost** [comment]
`desktop_files/yarn.lock` and `mobile_files/yarn.lock` changed. Pinging @jakubgs, @PombeirP, and @corpetty

**Comment by ghost** [comment]
`desktop_files/yarn.lock` and `mobile_files/yarn.lock` changed. Pinging @jakubgs, @PombeirP, and @corpetty

**Comment by ghost** [comment]
`desktop_files/yarn.lock` and `mobile_files/yarn.lock` changed. Pinging @jakubgs, @PombeirP, and @corpetty

**Comment by ghost** [comment]
`desktop_files/yarn.lock` and `mobile_files/yarn.lock` changed. Pinging @jakubgs, @PombeirP, and @corpetty

**Pull request merged**
