### PR TITLE
Use no backup directory

### PR DESCRIPTION
**Pull request by cammellos**
### Testing
Make sure files are under `no_backup` in android and `~/Library` in `ios`

status: ready

### CODE REVIEW

**Review by pedropombeiro — APPROVED** [review]

**Comment by churik** [comment]
@cammellos any clue where I can find `no_backup` on Android?
on my Android 8 (LG V20) in  `/sdcard/Android/data/im.status.ethereum.pr/files ` is empty.

On IOS all files are under `~/Library/im.status.ethereum`

**Comment by cammellos** [comment]
@churik unless the device is rooted you probably can't check it, unless you
run it in the emulator

**Comment by churik** [comment]
@cammellos running on emulator, still can't see data.
Can you point me where I should check?

**Comment by cammellos** [comment]
i am not home now, but it should be under
 /data/user/0/im.status.ethereum.pr/no_backup or something similar, not under /files, also you need to have created at least one account, just in case

**Comment by churik** [comment]
Thank you, found it. Can confirm that it exists.

**Pull request merged**
