### PR TITLE
security #4 recovery keyboard

### PR DESCRIPTION
**Pull request by flexsurfer**
Fixes https://github.com/status-im/security-reports/issues/4

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by asemiankevich** [comment]
@flexsurfer could you please clarify the expected result here? I can see suggestions in Gboard / SwiftKey boards:

image

image

Galaxy S10

image


On iOS i dont see any suggestions with default keyboard:

image


and can't enable Gboard.

Please clarify

**Comment by flexsurfer** [comment]
@asemiankevich expected result is suggestions should be shown, so we need to find a solution for Android custom keyboards, could you confirm btw that is isn't shown for Android native keyboards?

**Comment by asemiankevich** [comment]
@flexsurfery yeah, for some keyboards like Gboard / SwiftKey / Samsung - suggestions sill shown , and they are defaulted (keyborads i mean) for some devices.

**Comment by flexsurfer** [comment]
@asemiankevich pushed changes

**Comment by asemiankevich** [comment]
1. **G-Board**

image


2. **SwiftKey**

image

3. **Go Board**

image


Looks okay to me on Android 7, 8 and 9 with devices Huawei, Samsung, Xiaomi

**Pull request merged**
