### PR TITLE
nix: fix purge.sh script on Darwin platform

### PR DESCRIPTION
**Pull request by jakubgs**
Darwin lacks `userdel` and Nix users don't appear in `/etc/passwd`.

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Comment by audriu** [comment]
I tried to use this purge script:
```
audriusmolis@Audriuss-MacBook-Pro status-react % git checkout nix/purge-macos
Already on 'nix/purge-macos'
Your branch is up to date with 'origin/nix/purge-macos'.
audriusmolis@Audriuss-MacBook-Pro status-react % nix/scripts/purge.sh        
Unknown Nix installtion type!
Purged all Nix files from your system.
audriusmolis@Audriuss-MacBook-Pro status-react % make run-clojure            
yarn shadow-cljs watch mobile
Unknown Nix installtion type!
make: *** [run-clojure] Error 1
audriusmolis@Audriuss-MacBook-Pro status-react % 
``` 
This is on m1 mac

**Comment by jakubgs** [comment]
@audriu can you try editing `nix/scripts/lib.sh` to add `set -x` to `nix_install_type` function and then source it and use it?
```sh
source nix/scripts/lib.sh
nix_install_type
```
Should show you how exactly it fails, then you could maybe put it in a Gist so I can debug that.

**Comment by audriu** [comment]
> @audriu can you try editing `nix/scripts/lib.sh` to add `set -x` to `nix_install_type` function and then source it and use it?
> 
> ```shell
> source nix/scripts/lib.sh
> nix_install_type
> ```
> 
> Should show you how exactly it fails, then you could maybe put it in a Gist so I can debug that.

I will when next time work on this. Now everything works finally and I don't want to touch it.

**Comment by jakubgs** [comment]
@audriu that's fine, you don't have to purge things. I just want to test how the specific `nix_install_type` function works, which only detects the type of Nix installation, and doesn't actually remove anything, so it's safe.

**Comment by audriu** [comment]
> 

audriusmolis@Audriuss-MacBook-Pro status-react % source nix/scripts/lib.sh
audriusmolis@Audriuss-MacBook-Pro status-react % nix_install_type
+nix_install_type:2> NIX_STORE_DIR_GROUP=+nix_install_type:2> file_group /nix/store
+file_group:1> UNAME=+file_group:1> uname -s
+file_group:1> UNAME=Darwin 
+file_group:2> [[ Darwin == Linux ]]
+file_group:4> [[ Darwin == Darwin ]]
+file_group:5> stat -Lf %Sg /nix/store
+nix_install_type:2> NIX_STORE_DIR_GROUP=nixbld 
+nix_install_type:3> [[ "$(os_name)" -regex-match NixOS+nix_install_type:3> os_name
+os_name:1> source /etc/os-release
+os_name:2> echo ''
+nix_install_type:3> [[ "$(os_name)" -regex-match NixOS ]]
+nix_install_type:6> case nixbld (nixbld)
+nix_install_type:7> echo multi
multi

**Comment by audriu** [comment]
> @audriu that's fine, you don't have to purge things. I just want to test how the specific `nix_install_type` function works, which only detects the type of Nix installation, and doesn't actually remove anything, so it's safe.



```
audriusmolis@Audriuss-MacBook-Pro status-react % make run-clojure
2022-05-04 20:09:18.705 xcodebuild[830:10122] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-04 20:09:18.705 xcodebuild[830:10122] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
yarn shadow-cljs watch mobile
++++ file_group /nix/store
+++++ uname -s
++++ UNAME=Darwin
++++ [[ Darwin == \L\i\n\u\x ]]
++++ [[ Darwin == \D\a\r\w\i\n ]]
++++ stat -Lf %Sg /nix/store
+++ NIX_STORE_DIR_GROUP='(30000)'
++++ os_name
++++ source /etc/os-release
++++ echo ''
+++ [[ '' =~ NixOS ]]
+++ case "${NIX_STORE_DIR_GROUP}" in
+++ echo 'Unknown Nix installtion type!'
Unknown Nix installtion type!
+++ exit 1
make: *** [run-clojure] Error 1
```

This may be some ZSH problem.
     `elif [[ "${UNAME}" == "Darwin" ]]; then` doesn't match
     `elif [[ "${UNAME}" == $(echo "Darwin") ]]; then` and this does

**Comment by jakubgs** [comment]
Thanks, but ZSH should't affect it when it's being used by another script like `nix/scripts/source.sh` which explicitly uses Bash.
Could you also try it in a Bash shell?

Also, why do you keep quoting comments? That only makes sense if you're referring to an older comment.
Otherwise you're just adding noise to the conversation.

**Comment by audriu** [comment]
After adding Bash Shebang to the scripts all works.

**Comment by audriu** [comment]
After you added Bash Shebang to the scripts all works.
Although something is wrong with other scripts and make does not install Nix automatically...
```
audriusmolis@Audriuss-MacBook-Pro status-react % make run-clojure 
2022-05-05 09:09:48.147 xcodebuild[870:10890] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-05 09:09:48.147 xcodebuild[870:10890] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
yarn shadow-cljs watch mobile
No Nix installtion detected!
Nix not available, sourcing profile failed!
make: *** [run-clojure] Error 1
```

**Comment by jakubgs** [comment]
What? But all script already have a shebang. Which script specifically?

**Comment by audriu** [comment]
> Which script specifically?

You added it to `lib.sh`. It did not have it yesterday when I saw it.

**Comment by audriu** [comment]
Even if this script runs without errors, it looks like some residue is still left from nix after running it.
If I remove Nix with these steps https://gist.github.com/chriselsner/3ebe962a4c4bd1f14d39897fc5619732 then it all works fine.

**Comment by jakubgs** [comment]
But `nix/scripts/lib.sh` already has a shebang:
https://github.com/status-im/status-react/blob/411fd843cae47cb67e17d12dde2819b63d9b5221/nix/scripts/lib.sh#L1
So not sure why yours was missing it. Besides, that's a library and should only be sourced anyway.

I really would like to understand why you got the `Unknown Nix installtion type!` error.

**Comment by audriu** [comment]
it had `Unknown Nix installation type!` before you added the shebang. and now error disappeared of course.

**Comment by jakubgs** [comment]
There hasn't been changes to scripts since few months back in https://github.com/status-im/status-react/commit/03119837.

And this PR doesn't add any shebangs either. I don't really know why your case is so special, but we need to figure it out.

**Comment by jakubgs** [comment]
I've added some extra cases to the switch to handle a case when users/group was deleted but the folder remains:
https://github.com/status-im/status-react/blob/f3f102196d01da94ee937f4b8508ca9fb2be23e9/nix/scripts/lib.sh#L28-L30
Because `stat -Lf "%Sg"` will return the GID when group does not exit, and it should always be `30000`.

**Review by cammellos — APPROVED** [review]

**Pull request merged**
