### PR TITLE
drop les

### PR DESCRIPTION
**Pull request by flexsurfer**
upgrade for drop support of the LES fleet #9176

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
Nice! Thanks.

**Comment by oskarth** [comment]
I'm not quite sure why we are doing this? LES is still relevant, it just hasn't been picked up and prioritized since Igor left. Bounties were supposed to be created to fix it but I don't think it happened, and since then it hasn't been on critical path for v1. Removing it seems shortsighted to me. See https://github.com/status-im/status-go/issues/1025

**Comment by oskarth** [comment]
If it is about keeping the UI clean for v1 launch (as opposed to just hiding it in dev mode), I'd suggest hiding it behind a flag, as opposed to just removing it and making it harder for people to fix issues with it (once bounty is up).

**Comment by jakubgs** [comment]
What would be the point of that flag? If we want this functionality in some uncertain future then we can just revert his commit. Otherwise we will just be keeping dead code and maintaining it without using it due to it being available via a flag.

**Comment by flexsurfer** [comment]
@oskarth i would agree with @jakubgs , and part of the code looks stale, should be reimplemented anyway

**Pull request merged**
