### PR TITLE
Update translation

### PR DESCRIPTION
**Pull request by jinhojang6**
Updated langauges

- ar.json (Arabic)
- de.json (German)
- es_419.json (Latin American Spanish)
- es.json (Spanish)
- fil.json (Filipino)
- fr.json (French)
- id.json (Indonesian)
- it.json (Italian)
- ko.json (Korean)
- pt_BR.json (Brazilian Portuguese)
- pt.json (Portuguese)
- ru.json (Russian)
- tr.json (Turkish)
- zh_TW.json (Traditional Chinese)
- zh.json (Chinese)

### CODE REVIEW

**Comment by jinhojang6** [comment]
@hesterbruikman Can this be included in v1.7? I think we should

**Comment by churik** [comment]
@jinhojang6 yes, it will be included for sure.

**Review by churik — APPROVED** [review]

**Comment by jinhojang6** [comment]
Thanks @churik! Can we test this out a couple of days later? Some open-source translators are working on the new copy.

**Comment by churik** [comment]
@jinhojang6 oops, I've merged it, missed your comment. 
Do you need to revert it?

**Comment by jinhojang6** [comment]
No, we don't have to. I can submit another PR with the latest translations. Thanks! @churik

**Pull request merged**
