### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by jinhojang6**
Update translations and add supported languages which was [reverted before](https://github.com/status-im/status-react/commit/5f7c79556739b576ba50129c10372ee230886158#diff-471194b121cea0da9ef1236f48707740).

**Updated languages:** 
- Korean
- Spanish
- Arabic
- Chinese (Simplified, Traditional)
- German
- Turkish
- Brazilian Portuguese
- Tagalog

**Notes:**
- The new copy related to Keycard was not updated except for Korean

### CODE REVIEW

**Comment by hesterbruikman** [comment]
@Ferossgp what would need to change in these translation files to not need the [inline require](https://github.com/status-im/status-react/pull/10726#event-3392684958)?

**Comment by Ferossgp** [comment]
@hesterbruikman I think no changes should be added, cause it does not affect that part of code

**Review by flexsurfer — APPROVED** [review]

**Comment by jinhojang6** [comment]
I will update Spanish translation soon.

What does `no translations should be added?` mean? Can’t we apply this PR to v1.4?

**Comment by Serhy** [comment]
Could start the app and switch to Deutsch language

**Pull request merged**
