### PR TITLE
Update the Korean translations

### PR DESCRIPTION
**Pull request by jinhojang6**
The ko.json file is updated

### CODE REVIEW

**Comment by jinhojang6** [comment]
@jakubgs All the desktop builds failed. Is it okay?

**Comment by jakubgs** [comment]
No worries about that, it's because of 42961f3a0ea92ddb9c0bfe9fce7129de0b7d883f, which broke the desktop builds.

**Review by jakubgs — APPROVED** [review]
I have no idea what I'm looking at.

**Comment by jakubgs** [comment]
Please rebase, #8630 was merged, which should fix the desktop failures.

**Review by pedropombeiro — APPROVED** [review]

**Pull request merged**
