### PR TITLE
[multiaccount] rename account to multiaccount

### PR DESCRIPTION
**Pull request by yenda**
Renaming of account to multiaccount to avoid confusion between multiaccount and chat/wallet accounts

What is done
- everytime account was encountered in the codebase, it was changed to multiaccount if it was about "status account" and left as account if it was about "wallet account"
- dead account.status code was removed
- translation labels have been updated the same way as the codebase. current milestone for translations is now 1.0.0-rc1. some old labels have been removed

### Steps to test
Requires regression testing. It shouldn't change anything but is something has been left out some features might have break. Tested in emulator: join public and 1-1 chat, receive and send message, checked wallet, changed network, logging level, create new account

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]
162 files changed? Nice one!

**Review by vitvly — APPROVED** [review]

**Comment by asemiankevich** [comment]
@yenda lets wait for @Serhy to fix tests here, i will test this branch manually meanwhile

**Comment by gravityblast** [comment]
do we really call it multiaccount? I would call it user, so that we can say Status is multi-user, and each user has many account.
Otherwise we say that Status is multi-multiaccount.

**Comment by Serhy** [comment]
@yenda e2e tests should be fixed.

App crashes when transaction bottom sheet appears after sending `/send ETH 0` message in 1-1 chat or tapping `Sign transaction` from Wallet `Send transaction` view

Screenshot 2019-07-10 at 14 30 55

```

07-10 14:30:20.027 15815 15867 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :wallet.ui/sign-transaction-button-clicked
07-10 14:30:20.149 15815 15867 E ReactNativeJS: re-frame: no subscription handler registered for: :keycard-account?. Returning a nil subscription.
07-10 14:30:20.207 15815 15867 D ReactNativeJS: DEBUG [status-im.utils.universal-links.core:168] - universal-links: finalizing
07-10 14:30:20.306 15815 15867 E ReactNativeJS: Error: No protocol method IDeref.-deref defined for type undefined: 
07-10 14:30:20.306 15815 15867 E ReactNativeJS: 
07-10 14:30:20.306 15815 15867 E ReactNativeJS: This error is located at:
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in sheet (created by Gpc)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in Gpc (created by gP)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in RCTView (at View.js:45)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in View (created by gP)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in RCTView (at View.js:45)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in View (at createAnimatedComponent.js:151)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in AnimatedComponent (created by gP)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in gP (created by rP)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in RCTView (at View.js:45)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in View (created by rP)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in RCTView (at View.js:45)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in View (created by rP)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in rP (created by reagent4)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in reagent4 (created by Hpc)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in Hpc (created by signing)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in signing (created by Ipc)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in Ipc (created by reagent1)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in RCTView (at View.js:45)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in View (created by reagent1)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in reagent1 (created by root)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in root (created by YBc)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in YBc (at renderApplication.js:35)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in RCTView (at View.js:45)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in View (at AppContainer.js:98)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in RCTView (at View.js:45)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in View (at AppContainer.js:115)
07-10 14:30:20.306 15815 15867 E ReactNativeJS:     in AppContainer (at ren
```

**To reproduce:**
1) Install fresh Status build
2) Create new multiaccount
3) Navigate to 1-1 chat with contact
4) Type `/send ETH 0` in message box and tap 'Send' blue button

**Comment by yenda** [comment]
@Serhy fixed

are you looking at fixing the e2e tests?

**Comment by Serhy** [comment]
> @Serhy fixed
> 
> are you looking at fixing the e2e tests?

Yes, they were fixed (latest test results failed with crashing app error on transactionning).
They were fixed but rewrote by your the latest force-push :)  My bad to not alerting you after committing.
Ok, i'll push again

**Comment by yenda** [comment]
@Serhy awesome sorry for not noticing that :D

**Comment by Serhy** [comment]
@yenda could you resolve conflicts please (please mind my commits!)
All e2e should be fixed by now.

**Comment by yenda** [comment]
@Serhy done

**Comment by Serhy** [comment]
@yenda sorry, 'New onboarding' arrived earlier in develop :)
We have to fix the conflicts.

**Comment by yenda** [comment]
@Serhy @flexsurfer rebased

**Comment by flexsurfer** [comment]
@yenda @Serhy could you take a look, it would be great if we could merge this one sooner, thanks

**Comment by yenda** [comment]
@Serhy fixed the linter, probably got wrecked by rebase

**Comment by Serhy** [comment]
@yenda With the latest builds (Android 8, Android 6.0.1 iOS 12.3, MacOS checked):
Nothing happens when I tap the `Access key` button or `Back` button (being on the login screen)
Screenshot 2019-07-16 at 15 31 33
Screenshot 2019-07-16 at 15 31 41

(no issues in nightly build)

**Comment by Serhy** [comment]
From autotests (confirmed also with real device): 
` 'Error: No protocol method IDeref.-deref defined for type undefined:` error followed by app crash when navigate to Wallet main screen

Screenshot 2019-07-16 at 15 39 56

To reproduce:
1) Open Status and create new account
2) Tap 'Wallet' button

**Comment by Serhy** [comment]
There is no list of accounts when creating new multiaccount (`Choose a key and name` view)
**To reproduce:**
1) Open fresh Status build
2) Tap `Get Started` -> tap `Generate a key`

Screenshot 2019-07-16 at 15 52 25

**Comment by Serhy** [comment]
@yenda there are some issues appeared, need your help to fix it...

**Comment by yenda** [comment]
@Serhy yes I'm on it my bad I tested before rebasing and didn't expect so much breakage, I think it is just events that changed name will fix it and test it this time

**Comment by flexsurfer** [comment]
@yenda small conflict

**Comment by yenda** [comment]
@flexsurfer it's not just the conflict there is also loads of usage of account that get added in every PR without making any conflict but effectively breaking the app

**Comment by yenda** [comment]
@Serhy ok rebased and I played around a bit seems ready for deeper testing

**Comment by Serhy** [comment]
Builds failed on unittests step...
```
13:07:01  ERROR [status-im.transport.message.core:67] - Something went wrong error 
13:07:01  ERROR [status-im.transport.message.core:67] - Something went wrong nil nil
```

**Comment by yenda** [comment]
@Serhy this one is normal an error is expected in the test that is just the log statement the issue was some extra koreans translations after the rebase but I had the fix locally already I guess I didn't push properly yesterday

**Comment by Serhy** [comment]
`Conflicting files
test/appium/tests/atomic/chats/test_commands.py`
No worries I'll fix it.

**Comment by Serhy** [comment]
No bugs with the latest builds on iOS and Android. 
MacOS build failing though...

**Comment by yenda** [comment]
@Serhy looks good now can I merge?

**Comment by Serhy** [comment]
Tested MacOS build as well (the one which succeded), no bugs found.
Ready for merge, @yenda !

**Pull request merged**
