### PR TITLE
[#11333] personal_sign method does not work in status

### LINKED ISSUE #11333: personal_sign method does not work in status
# Bug Report
Using the `personal_sign` method does not seem to work within Status while it works from web3 wallets.

## Problem
Using the personal sign method fails to trigger a populated dialog that can be signed by the user.

An overview of the background required to understand the problem.

Attempting to use snapshot.page we discovered that Status is the only wallet unable to sign messages for voting.

A problem description.

Using the following test page: https://danfinlay.github.io/js-eth-personal-sign-examples/

When clicking on `personal_sign` it should trigger a populated dialog to sign (as in metamask). It either fails to trigger or populated an empty dialog box as when attempting to vote using snapshot.

#### Expected behavior

It should populate a dialog box and allow the user to sign it.

#### Actual behavior

Either no dialog box appears or an empty one sign request appears.

### Reproduction

- Open Status
- go to https://danfinlay.github.io/js-eth-personal-sign-examples/
- click "connect".
- click "personal_sign"

### Additional Information

- Operating System: <iOS>

```
...
```

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #11333

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by richard-ramos — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer can we add `personal_sign` method to status simple dapp to have it automated?

**Comment by flexsurfer** [comment]
@churik its already there 
image

**Comment by flexsurfer** [comment]
personal_sign has been working in status long time, we just added an unspecified case to it

**Comment by churik** [comment]
@flexsurfer not sure if I'm doing right steps, but I followed steps from https://github.com/status-im/status-react/issues/11333 with builds https://github.com/status-im/status-react/commit/5cd58320fb2bf663dc75cc9e475f0b93f97ded5a

After tapping "Connect" and allowing access to status wallet  on https://danfinlay.github.io/js-eth-personal-sign-examples/ I tap on "personal_sign". Nothing happened.
I suppose from the issue that dialog box should appear.

Tried on mainnet and ropsten.

**Comment by flexsurfer** [comment]
examples from #11333 are screwed, so here https://gateway.pinata.cloud/ipfs/QmXECbBSchgQja9VQAqQopNTMwtwKcF46BEWrCgkfTJYGN/ you can try sign personal message, in nightly its empty, here it should show text

**Comment by churik** [comment]
@flexsurfer 
https://gateway.pinata.cloud/ipfs/QmXECbBSchgQja9VQAqQopNTMwtwKcF46BEWrCgkfTJYGN/  - "SIGN PERSONAL" works on  Android, but doesn't work for IOS.
Nothing happens on tap after "SIGN PERSONAL"

**Pull request merged**
