### PR TITLE
[keycard] Account generation & tx signing on simulated card

### PR DESCRIPTION
**Pull request by rasom**
This pr allows to generate a new account and sign txs with simulated keycard. This is necessary for e2e tests. Also I'm going to use if for development as in this case real card is not needed and UI can be implemented even on simulator/emulator. 

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@rasom account creation is broken in PR  - when tapping on "Next" button on "Create a password" screen, app doesn't proceed to "Confirm your password" screen

Confirmed on IOS and Android.

**Comment by rasom** [comment]
@churik fixed

**Comment by churik** [comment]
@rasom 
with framework I can't create an account, logout and login as before
1) after account creation - endless spinner and "Offline"
offli

2) after account creation - logout - no account created (redirection to caurousel view)
All details / logs: https://saucelabs.com/jobs/5b520dabf2aa44aa89e5aadb24acff85?auth=e67cc04dc09cc0b61ea864b9d042200f

Test:  test_add_new_keycard_account_and_login
Test is passed on nightly.
Issue is not reproducible with real keycard.

**Comment by rasom** [comment]
@churik on it

**Comment by rasom** [comment]
@churik fixed

**Review by churik — APPROVED** [review]

**Comment by churik** [comment]
Can sign transaction and create new account in e2e builds with simulated keycard.

**Pull request merged**
