### PR TITLE
[wip] install referrer

### PR DESCRIPTION
**Pull request by flexsurfer**
* [x] read referrer
* [ ] call https endpoint

wip

### CODE REVIEW

**Comment by flexsurfer** [comment]
@jakubgs why?

**Comment by jakubgs** [comment]
Because I asked like 3 times in `#core` with this list of branches: 
https://gist.github.com/jakubgs/68283ba8983893dd5696578da6769a4c
If anyone objects. And no one did. So I removed them.
They were all +60 days old based on git author date.

**Comment by jakubgs** [comment]
Ah right, because I refreshed the list which added to it these:
```
change-ios-app-id
ens/remove-name
feature/install-referrer
feature/install-referrer-status-module
fix/listen-to-nfc-status#10011
fix/trim-ens-name#10115
group-chat-creation-ui-2
master
snyk-fix-02e410d84143cc400b019dc62c52a6a1
test/waku-default-eth-test-fleet
upgrade-geth-1.9.11
```
This is the script I used: https://github.com/status-im/infra-utils/blob/master/github/list_old_branches.sh
Feel free to reopen it.

**Comment by Ferossgp** [comment]
@flexsurfer will this PR handle also if the referral comes with an Universal Link (join.status.im/0x000...?invite=f79989f679386be7aa56dc1c4&cid=foo) or only if it is from play store? 
The params support was added here:
https://github.com/status-im/universal-links-handler/issues/31

**Comment by flexsurfer** [comment]
this PR only implements android InstallReferrer, im not sure if we still should have it as separate PR, I'm out of context and doesn't work on it anymore

**Comment by hesterbruikman** [comment]
@flexsurfer @Ferossgp I think only Play Store makes sense. If we reward only for new invites that install the app and purchase Stickerpack, the referral is irrelevant if it doesn't come from the Play Store as it implies the user already had the app installed

**Comment by oskarth** [comment]
Small request - could you please rebase to latest master so this commit https://github.com/status-im/status-react/commit/b5fda1234e5447cbc626059dfc78fcfbabc9e926 gets included? This means we aren't running E2E tests on eth.prod cluster anymore, and since this happens on every push, the impact is quite big. This ensures we have more accurate metrics going forward from Jul 1 onward, which would be awesome. See https://discuss.status.im/t/user-growth-and-retention/1782 for more

**Comment by flexsurfer** [comment]
@Ferossgp is this PR still useful at some point? if so feel free to reopen

**Pull request closed without merging**
