### PR TITLE
Status go/integrate permissions api

### PR DESCRIPTION
**Pull request by yenda**
### Summary

This moves the browser history and dapp permissions data from realm db in status-react to sqlite in status-go

### Testing notes
- only the browser and dapp permissions data are affected
- old browser and dapp permissions data is deleted

#### Platforms
Same effects on all platforms

### Steps to test

- Open Status
- login, visit different websites/dapps, also some that require permissions such as simpledapp.eth
- logout
- login again, history should still be there and accepted permissions shouldn't be asked again

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by Serhy** [comment]
**(ISSUE 1)**
There are cases when we drop the URI after re-login - for both iOS and Android builds (can't get when exactly but here is three scenarios):

### Scenario 1
1) Open Status and navigate to Dapps
2) Tap Dapp Store to open `https://dap.ps`
3) Navigate back to main DApps screen
4) Re-open the app and check on DApps the `https://dap.ps` is present in history record

### Scenario 2
1) Open Status and navigate to Dapps
2) Enter `simpledapp.eth` and submit (accept permission to Wallet and Contact code)
3) Navigate back to main DApps screen
4) Re-open the app and check on DApps the `simpledapp.eth` is present in history record

### Scenario 3
1) Open Status and navigate to Dapps
2) Enter `www.coolsiteoftheday.com` and submit
3) Navigate back to main DApps screen
4) Re-open the app and check on DApps the `http://www.coolsiteoftheday.com` is present in history record

Screenshot 2019-07-25 at 15 00 36



Also, **(ISSUE 2)** it seems browser history is saved per network: if I have several browsing records kept while on Mainnet -> there is no history after re-login under `POA network`. But history reappears back after re-login, again, back under Mainnet (and if I had anything browsed in POA network - browser history sticks to this network). 
Not sure if this consequences we can accept as a new feature :) 
Is it possible to save browsing history disregard which network user is connected to?

**Comment by yenda** [comment]
@dmitryn please review now that Julien is gone it needs another reviewer

**Comment by yenda** [comment]
@Serhy we are going to fix the per network history in a future update of status-go, the dropping URL bug should be fixed now

**Review by cammellos — APPROVED** [review]

**Comment by Serhy** [comment]
Thanks, @yenda, looks good to me with iOS an Android builds now!
For per-network history issue, I'll create separate issue after merge of this one

Autotests failed due to https://github.com/status-im/status-react/issues/8645

**Pull request merged**
