### PR TITLE
[#10718] Update FAQ links

### LINKED ISSUE #10718: Update FAQ links
# Problem
FAQ will be moved to https://status.im/faq/ this requires links to be updated in the app

## Implementation
1. Keycard onboarding > Learn more https://status.im/faq/#keycard
1. `Settings` > `Keycard` > `Help`https://status.im/faq/#keycard
1. `Settings` > `Need help` > `Frequently asked questions`https://status.im/faq/

Frame 1

## Acceptance Criteria
Links to FAQ direct to correct url

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #10718

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by Serhy** [comment]
test_need_help_section test fails because we have not migrated to https://status.im/faq/ (it displays 404). 

@flexsurfer the second item from issue: `Settings > Keycard > Help -> https://status.im/faq/#keycard`, - it still opens `https://keycard.tech` link.

Screenshot 2020-05-29 at 11 01 22

**Comment by flexsurfer** [comment]
thanks @Serhy thats because it links to `https://hardwallet.status.im"` ,that's why i didn't found it :)

**Comment by flexsurfer** [comment]
fixed

**Comment by Serhy** [comment]
Thanks @flexsurfer, I can confirm it's fixed.

**Pull request merged**
