### PR TITLE
fix missing search filter event

### PR DESCRIPTION
**Pull request by yenda**

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Comment by flexsurfer** [comment]
@yenda @Serhy ?

**Comment by Serhy** [comment]
I'm looking... There is something wrong with transaction statuses in 1-1 chats.

**Comment by Serhy** [comment]
@yenda When 1-1 command confirms or declines status then command indication about `Incoming` or `Outgoing` transaction changed to the it's opposite state

1) UserA (with ETH) adds new UserB and they join 1-1 chat
2) UserA sends a `Send` command (`Outgoing transaction` on UserA side)
3) UserB receives it as `Incoming transaction`
4) UserB taps -> any of `Access and share address` OR `Decline`
**Actual result:** On UserA side and UserB side the command message changed status to the opposite one (so UserA who supposed to send transaction gets `Incoming transaction` with the `Sign and send` button and UserB sees on his side `Outgoing transaction`). This is how it looks on UserB side:

**Comment by Serhy** [comment]
> @yenda When 1-1 command confirms or declines status then command indication about `Incoming` or `Outgoing` transaction changed to the it's opposite state
> 
> 1. UserA (with ETH) adds new UserB and they join 1-1 chat
> 2. UserA sends a `Send` command (`Outgoing transaction` on UserA side)
> 3. UserB receives it as `Incoming transaction`
> 4. UserB taps -> any of `Access and share address` OR `Decline`
>    **Actual result:** On UserA side and UserB side the command message changed status to the opposite one (so UserA who supposed to send transaction gets `Incoming transaction` with the `Sign and send` button and UserB sees on his side `Outgoing transaction`). This is how it looks on UserB side:
> 
> 

It's not introduced in this PR (already in develop) 
Create separately https://github.com/status-im/status-react/issues/10608

**Pull request merged**
