### PR TITLE
[WIP] Fix for Issue #8718

### LINKED ISSUE #8718: App is shown in English instead of device language for some languages
### Description

*Type*: Bug
*Summary*: for some languages (translations are presented in https://github.com/status-im/status-react/tree/develop/translations) app is still shown in English after setting device language. Randomly checked several languages - all fine with Russian\Korean (so device settings are applied to app language), but not with French, Vietnamese, Danish.
Reproducible on 0.13.0 and later.

#### Expected behavior
app language is changed

#### Actual behavior
app is still in English

### Reproduction
- Change your phone language to French, Vietnamese or Danish
- Open Status app and check language

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: release 0.13.0, nightly 07/08/2019
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by AlphaSerpentis**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Attempts to fix #8718 

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
Attempts to solve the issue where some languages do not display correctly and default to English.

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

Step 1, configure your device to a different language
Step 2, launch Status
Step 3, verify Status translates to the correct language

status: wip

### CODE REVIEW

**Comment by AlphaSerpentis** [comment]
Unsure if this will affect the entire app at all since I've noticed the other JSON files do not seemingly contain a similar error.

**Comment by churik** [comment]
@AlphaSerpentis 
Thanks!
Tested on IOS on build with https://github.com/status-im/status-react/commit/dd867eebf641bbb9cc26d928c319458c8aff0641 - seems no effect, app is still in English.

**Comment by AlphaSerpentis** [comment]
@churik Darn, I'll see what else I can do. I'm reading up on information related to this.

**Comment by AlphaSerpentis** [comment]
I can't view the log, what does Jenkins say as to why it can't be built?

**Comment by AlphaSerpentis** [comment]
Hey @churik, do you know where I could be going wrong with my approach to this issue? Any possible ideas?

None of the builds cannot be built?

**Comment by jakubgs** [comment]
Please rebase your branch:
```
CONFLICT (content): Merge conflict in prod/status_im/i18n_resources.cljs
```
Also, squash your commits into one.

**Comment by jakubgs** [comment]
Are you sure you rebased this branch on fresh `develop`?
```
CONFLICT (content): Merge conflict in prod/status_im/i18n_resources.cljs
```

**Comment by AlphaSerpentis** [comment]
> Are you sure you rebased this branch on fresh `develop`?
> 
> ```
> CONFLICT (content): Merge conflict in prod/status_im/i18n_resources.cljs
> ```

I don't think I'm doing this correctly, sorry, this is my first time doing such a thing here. Can you help guide me to rebase correctly?

**Comment by jakubgs** [comment]
```
git pull --rebase origin develop
```
But this assumes your `origin` is our repo, not your fork.

Also, to squash your commits see:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by AlphaSerpentis** [comment]
> ```
> git pull --rebase origin develop
> ```
> 
> But this assumes your `origin` is our repo, not your fork.
> 
> Also, to squash your commits see:
> http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
> https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Thank you so much! If someone can test this out, much appreciated!

**Comment by jakubgs** [comment]
You still need a `git rebase -i HEAD~18` and squash all of those commits.

**Comment by jakubgs** [comment]
Last time I recall this PR having 18 commits, now it has 38, how did that happen?

Maybe a video will explain it better: https://www.youtube.com/watch?v=viY1BbKZhSI

**Comment by AlphaSerpentis** [comment]
> Last time I recall this PR having 18 commits, now it has 38, how did that happen?
> 
> Maybe a video will explain it better: https://www.youtube.com/watch?v=viY1BbKZhSI

(I'm really not a GitHub nerd, rip)

Basically I tried rebasing, but GitHub Desktop forced me to pull commits, which were the same thing, so I ended up with this. I'll check the video out and see what I can do.

**Comment by jakubgs** [comment]
I don't know how you've managed this, but your commit is now changing 115 files, and most of those changes are already in `develop`. This PR is definitely wrong right now.

**Comment by AlphaSerpentis** [comment]
> I don't know how you've managed this, but you commit is now changing 115 files, and most of those changes are already in `develop`. This PR is definitely wrong right now.

Should I close this PR, and open up a new one with a fresh branch with the intended changes I wanted to make?

**Comment by jakubgs** [comment]
That might be the simplest thing to do.

**Comment by AlphaSerpentis** [comment]
patch-1 branch messed up will open a new one to stop this mess

**Comment by AlphaSerpentis** [comment]
@jakubgs Can you check this PR: https://github.com/status-im/status-react/pull/9286

Much appreciated!

**Pull request closed without merging**
