### PR TITLE
[refactor] replace web3-prototype

### PR DESCRIPTION
**Pull request by yenda**
- replace web3-prototype wherever possible
- currently only the money namespace is left
for future refactoring, the ideal solution
would be to use strings for big numbers all
the time and only convert for arithmetic operations
- use json-rpc call to replace trivial web3 calls

# Testing

In dev mode:
- checked that the different sha3 function doesn't affect user address generation (this was already caught by unit tests)
- checked that messages are still encoded/decoded properly
- checked that changing network still works and network check is made

Tested on Android emulator
- created account
- joined public and one-to-one chats
- switched to ropsten
- got ETH, sent eth

status: ready

### CODE REVIEW

**Comment by yenda** [comment]
@siphiuel @flexsurfer @jeluard please review

**Review by vitvly — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@yenda can you please rebase to current `develop`?

**Comment by churik** [comment]
Tested on IOS 11.4.1 (IPhone 7), Android 8 (LG V20):
- /send, /request commands in chat on Ropstem and mainnet
- send and request tokens using scan QR from wallet
- chatting in 1-1, public and group chats between PR <-> PR, PR <-> release
- installing gfycat extension
- using Dapps
- transaction from DApp

Smth else should be checked here?

**Comment by yenda** [comment]
@churik no it's great that should cover the changes

**Pull request merged**
