### PR TITLE
Rename package.json.orig to package.json

### PR DESCRIPTION
**Pull request by pedropombeiro**
### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
This allows 3rd party tools like Dependabot to inspect our dependencies

status: ready

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Review by flexsurfer — APPROVED** [review]

**Comment by pedropombeiro** [comment]
@flexsurfer I needed to change the name of the npm modules so there wouldn't be a clash between mobile and desktop in jest-haste-map. I don't think that name is used for anything.

**Comment by pedropombeiro** [comment]
Not sure if this also needs to change: https://github.com/status-im/status-react/blob/fix%2Fpackage-json-name/ios/StatusIm/AppDelegate.m#L59

Will need to check on simulator

**Review by jakubgs — APPROVED** [review]
LGTM, but I've been also thinking that it would be nice to do this too:

* Move stuff from `desktop_files` to the `desktop` folder
* Rename the `mobile_files` to just `mobile`

The top of our repo is far too busy, one less folder is always nice.

**Comment by pedropombeiro** [comment]
I get this when running `make react-native`:

```
jest-haste-map: Haste module naming collision: StatusIm-Mobile
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/mobile_files/package.json
    * <rootDir>/package.json
```

seems more like a warning we can ignore though. What do you guys think?

**Comment by ghost** [comment]
`desktop/js_files/yarn.lock` and `mobile/js_files/yarn.lock` changed. Pinging @jakubgs, @PombeirP, and @corpetty

**Comment by ghost** [comment]
`desktop/js_files/yarn.lock` and `mobile/js_files/yarn.lock` changed. Pinging @jakubgs, @PombeirP, and @corpetty

**Pull request merged**
