### PR TITLE
[DO NOT MERGE!] Hide key storage selection/fingerprint screens temporarily

### LINKED ISSUE #8583: Hide 'key storage' screen from onboarding flow for beta v0.14
# Problem

The new onboarding flow offers users the option to store their key on their device or on keycard. We are not introducing keycard support in beta v0.14 so should hide this screen.

## Implementation

Remove [this screen](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=2175%3A21919) from the onboarding flow for release v0.14.

image

### LINKED ISSUE #8593: Hide Fingerprint feature temporarily
## Problem

For now there is still some discussion as to how fingerprint feature should work, so it has been decided to disable the feature in the upcoming release.

## Implementation

Hide fingerprint screen in the Onboarding wizard, and hide it from the Profile UI.

### PR DESCRIPTION
**Pull request by vitvly**
Fixes #8583 
Fixes #8593

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
@siphiuel is something wrong with translations here?
image


or develop..

**Comment by annadanchenko** [comment]
@asemiankevich on last nightly it looks ok while on same Android device with English-US I can repro issue on this PR

**Comment by asemiankevich** [comment]
> @asemiankevich on last nightly it looks ok while on same Android device with English-US I can repro issue on this PR

well it is the same on IOS @siphiuel please take a look

**Comment by vitvly** [comment]
Sorry, dumb mistake, fixed it.

**Comment by asemiankevich** [comment]
@siphiuel all builds are failed, please take a look

**Comment by flexsurfer** [comment]
@asemiankevich we decided to hide fingerprint screen as well in this PR

**Comment by asemiankevich** [comment]
> @asemiankevich we decided to hide fingerprint screen as well in this PR

why not do do it in separate PR? its not fair to make changes after the branch is tested  :)

**Comment by flexsurfer** [comment]
@asemiankevich two reasons, 1 - because we need this only in release, 2 - because these changes related, and we telling you that we made changes :) so looks fair :) thank you

**Comment by Serhy** [comment]
With iOS, Android builds (tested on iOS 12.3 and Android 8) - no bugs found. 
Two views (`Key storage` and `Fingerprint`) are not shown.
@siphiuel please mind my commit fixing e2e when merging in to release branch

**Pull request merged**
