### PR TITLE
[developerXP] remove unused deps

### PR DESCRIPTION
**Pull request by yenda**
- remove warning for asyncstorage deprecation
- remove unused asyncstorage-down library

### Steps to test

I couldn't find any usage for this library in the codebase so this shouldn't have change anything.
Only requires a basic sanity check
Tested on Android emulator, opening chat, wallet, settings and playing around.

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by yenda** [comment]
@vkjr do you know what's up with the macos build?

@flexsurfer can you update the pods please?

**Comment by vkjr** [comment]
@yenda, no, fail reason is unclear for me

**Comment by yenda** [comment]
@vkjr it looks like cleaning up the yarn.lock made some updates to babel versions could it be related?

**Review by jakubgs — APPROVED** [review]

**Comment by flexsurfer** [comment]
@yenda update the pods ?

**Comment by yenda** [comment]
@flexsurfer yeah it requires some ios magic with podfiles and xbproject or something can you look into it?

**Comment by vkjr** [comment]
@yenda, not sure.
if you want, I can try and build it locally to check

**Comment by yenda** [comment]
@vkjr yes please

**Comment by vkjr** [comment]
Can't build desktop even from `develop` branch. On command `make run-desktop` getting error:
```
Building the app...

stderr maxBuffer length exceeded

RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
    at Socket.onChildStderr (child_process.js:365:14)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)

make: *** [_run-desktop] Error 1
```

@PombeirP, could that be somehow related to nix?

**Comment by pedropombeiro** [comment]
> @PombeirP, could that be somehow related to nix?

I'm looking into this. From what I see, this happens as far back as in ded207ead2226b3141ca2b19b17b147cff297f65, will try to build earlier commits.

**Comment by pedropombeiro** [comment]
I was able to run `run-desktop` on macOS with 5ce43b75.

The `stderr maxBuffer length exceeded` error seems to be fixed on my system if I disable the pure environment on macOS (reverting part of fca01891baae35146216e3f9e0aaa90341ad2dad) and therefore running node.js v12.3.0. Looking at the [changes that happened](https://github.com/nodejs/node/blame/master/lib/child_process.js#L201) in node.js v12, it would actually seem it would make it worse though, but I might be missing something. Maybe increasing the buffer size as detailed [here](https://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process) (although that would require patching either node.js or the library which is using it in this case) or upgrading the node.js version to v12 could allow us to keep pure macOS builds. UPDATE: tried updating node.js to v12.3.1 in a pure environment and still see the issue.
However, I still see this error when running `make react-native-desktop` (same as in https://github.com/facebook/react-native/issues/24182):

```
make[1]: Entering directory '/home/pedro/src/github.com/status-im/status-react'
(node:6182) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/pedro/src/github.com/status-im/status-react/node_modules/react-native/local-cli/core/packager/config.js'
(node:6182) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6182) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
make[1]: Leaving directory '/home/pedro/src/github.com/status-im/status-react'
```
Not sure where the `react-native/local-cli/core/packager` folder comes from, because it isn't present even in 5ce43b75.

**Comment by pedropombeiro** [comment]
I'm curious, has this issue only come up now? The macOS purity commit (fca01891b) has been merged a month ago.

**Comment by yenda** [comment]
@PombeirP maybe because that's the first PR that attemps to cleanup the yarn.lock in a while? not sure id related though

**Comment by pedropombeiro** [comment]
@yenda btw I'm testing with develop. What I mean is that if I check out a commit from nearly a month ago, this problem is already there, so I'm wondering if this just went under the radar all this time, or if it's some other thing that's causing the issue to be reproducible only now.

**Comment by yenda** [comment]
@PombeirP what should be done to get the macos to build?

I need help from @dmitryn @siphiuel or @flexsurfer to fix the ios build

**Comment by pedropombeiro** [comment]
@yenda I think I'll need to revert the PR that made macOS builds pure. I don't really have time right now to debug that, I need to focus on the reproducible Android builds.

**Comment by yenda** [comment]
@PombeirP ok ping me when you're done

**Comment by pedropombeiro** [comment]
Reverting that doesn't fix this error in `make react-native-desktop` though (just the one in `make run-desktop`):
```
(node:48399) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/pedro/Documents/GitHub/status-react/node_modules/react-native/local-cli/core/packager/config.js'
(node:48399) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:48399) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Not sure where this one comes from...

**Comment by pedropombeiro** [comment]
I should have written that way before, I just stumbled across the reason in `scripts/start-react-native.sh`. I'll prepare a branch with the fix for you to cherry pick here.

**Comment by pedropombeiro** [comment]
@yenda can you please try with just the fafe5ca9ece9743471fbdf6cad85338403a7bc2e commit?

**Comment by pedropombeiro** [comment]
nevermind, you'll need the whole origin/test/fix-run-desktop branch

**Comment by flexsurfer** [comment]
@yenda @PombeirP any updates guys ?

**Comment by oskarth** [comment]
No update for a month, I suggest closing this unless we can get it merged this week.

**Comment by yenda** [comment]
@oskarth I will have a look at it tomorrow it was blocked by build issues that might be fixed now

**Pull request closed without merging**
