### PR TITLE
[DO NOT MERGE!] [Fix #8569] Allow to edit custom name again

### LINKED ISSUE #8569: Fix 'my profile' screen for beta v0.14
### User Story

As a beta user, I want the option to set and edit a display name in chat.

### Description

*Type*: Feature/Fix

*Summary*: Partial changes to the profile screen have blocked nightly users from being able to edit display names on mobile.

We are not going to include the ENS resolution feature in beta release 0.14, therefore, we need to re-enable display names.

#### Expected behavior

User can edit display name + image from `My profile` screen. 

#### Actual behavior

On nightly, users can only edit their image or set an ENS name to display in chat.

### PR DESCRIPTION
**Pull request by jeluard**
fixes #8569

### Summary

Do not display ENS name anymore (neither in profile nor chat).
Allow to edit custom name: it should be shown in both chat and profiles.

### Steps to test

- Open Status
- Go to profile, edit name
- See it in profile, displayed in chat messages

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Comment by Serhy** [comment]
Above test_send_eth_in_1_1_chat test (https://github.com/status-im/status-react/pull/8586#issuecomment-512222474) failed due to a transaction that was not mined in time (too low GapPrice was set comparing to actual default GasPrice). Not this PR issue (and I'll update the test today too)

**Comment by asemiankevich** [comment]
@jeluard do you know why all builds failed? Oo

**Comment by jeluard** [comment]
@asemiankevich Fixed now!

**Comment by jeluard** [comment]
@asemiankevich @Serhy Does that look good? :)

**Comment by Serhy** [comment]
I'm looking now to return pair of autotests with checks for custom username.

**Comment by Serhy** [comment]
@jeluard we returned the ability to customise username, but one thing we need to return back too is displaying default username in public chats as well (to eliminate the scenario of contact substitution so that everyone in public chat displayed as 'Sergey') 

Screenshot 2019-07-18 at 15 39 36

**Comment by jeluard** [comment]
@errorists suggested that we only display the custom name now.
There is always the ability to distinguish using the profile details. And I swear I won't use `Sergey` as custom name ;)

**Comment by errorists** [comment]
it's temporary until we finish the switcheroo and remove custom names (again :P ) and succeed them with ENS which is unique so there will be only one `@sergey` to rule them all :) With ENS the idea was to show only the username in chat without the funky name next to it, so I know it's not ideal _now_ but it will be once the transition is complete.

**Comment by rachelhamlin** [comment]
Only issue is that it will be a while before we have ENS resolution working properly, as there are changes required for multi-account, and if we need to cut any more scope from the Clojure side, that'd be a prime target.

@jeluard what else are you working on, is it hard to bring back? Sorry. I'd prefer not to ship something funky for users, not knowing _when_ the transition will be complete. 😕

**Comment by jeluard** [comment]
@rachelhamlin I was planning to drink mojitos in my hammock but I will do it for you!

**Comment by jeluard** [comment]
@Serhy I pushed the relevant changes

**Comment by Serhy** [comment]
Tested on iOS 12.3 and Android 8.1, no bugs found. I'm able to customise username (as in 0.13) from Profile view which is used in chats (public/1-1/group - to those who are in my contact list)
@jeluard could you squash commits please and merge to `release/0.14.0`?

**Pull request merged**
