### PR TITLE
[WIP]add test coverage report and publish to coveralls

### PR DESCRIPTION
**Pull request by tbenr**
@yenda 
This is an experiment to add coveralls report to the current test suite.

@jakubgs for now i added coverage to only android build.

new required env variable:
COVERALLS_REPO_TOKEN 

optionally we can add:
COVERALLS_SERVICE_NAME set to "jenkins"?
COVERALLS_SERVICE_JOB_ID set to a jenkins job id for the current run.

coveralls and nyc addition heavily impacted yarn.lock

status: wip

### CODE REVIEW

**Comment by flexsurfer** [comment]
@jakubgs @yenda could you please take a look

**Comment by jakubgs** [comment]
Well, you seem to have modified `desktop_files/package.json.orig`, but you did not update `desktop_files/yarn.lock`, that's clearly what's causing all the desktop builds to fail.

**Comment by tbenr** [comment]
@jakubgs trying to regenerate it without success.. any suggestions?

I tryed:

```
export TARGET_OS=macos
make shell
```

it creates the yarn links pointing to desktop but then yarn install exits saying lockfile needs to be updated but --frozen-lockfile has been specified.

Then, if I run `yarn install` i get a detox module postinstallation error :(

image

**Comment by jakubgs** [comment]
What folder did you do that in? I cloned your repo, checked out your branch, and tried linking the `desktop_files` in repo root, than did `make shell` and `yarn install`, and I got a perfectly fine update to the `yarn.lock` file.

Here's what I got:
https://gist.github.com/jakubgs/4c7d9c0d3b71a6f2067767d8b0fdcb75

**Comment by tbenr** [comment]
@jakubgs from the project root.. let me try to clear all and redo..

**Comment by tbenr** [comment]
@jakubgs I found the root cause: https://github.com/wix/Detox/issues/1229
I'm have xcode 10.2.1 and detox 9.0.4 doesn't compile.
In the meantime I just applied your patch.

did you find some time to add required env variables?

**Comment by jakubgs** [comment]
Well, `10.2.1` is the version of Xcode that we require:
https://github.com/status-im/status-react/blob/79db8e51077334a7f729d90d886884f0a32403f9/nix/mobile/default.nix#L9
And it should fail with any other version installed.

I don't get your relation to the Detox package because I don't see it being used in our repo nor in this PR.

And about `COVERALLS_REPO_TOKEN`, please write to me in Status 1-on-1 chat to give me the token, I can configure the rest. About the others, I can try adding that now for you. I'll just add a commit on top.

**Comment by jakubgs** [comment]
Oh, actually I can't commit since you are working from a fork, so let me explain what we would need.
First we'd want to replace the `cmn.nix.shell('make coverage')` call with a method:
```groovy
stage('Coverage') {
  steps {
    script { android.coverage() }
  }
}
```
And then add to `ci/android.coverage` something like:
```groovy
def coverage() {
  withCredentials([
    string(credentialsId: 'coveralls-token', variable: 'COVERALLS_REPO_TOKEN'),
  ]) {
    nix.shell('make coverage')
  }
}
```
And in the `environment` block of `ci/Jenkinsfile.android` - probably after line `37` - you should add:
```groovy
/* coverage report identification */
COVERALLS_SERVICE_NAME = "jenkins"
COVERALLS_SERVICE_JOB_ID = BUILD_NUMBER
```
See https://ci.status.im/env-vars.html for source of `BUILD_NUMBER`. You could also use something like:
```
COVERALLS_SERVICE_JOB_ID = "${JOB_NAME}#${BUILD_NUMBER}"
```
If you want to be more clear on the source.

**Comment by tbenr** [comment]
> Well, `10.2.1` is the version of Xcode that we require:
> https://github.com/status-im/status-react/blob/79db8e51077334a7f729d90d886884f0a32403f9/nix/mobile/default.nix#L9
> 
> 
> And it should fail with any other version installed.
> I don't get your relation to the Detox package because I don't see it being used in our repo nor in this PR.

@jakubgs agree with you but this is just what happen to me: linking `package.json.orig` from `desktop_files ` and running `make shell` and `yarn install`

..soon or later I'll figure out..

**Comment by jakubgs** [comment]
Maybe @PombeirP might have some ideas as to what happened to you.

**Comment by jakubgs** [comment]
Btw, your commit isn't signed: https://help.github.com/en/articles/signing-commits

**Comment by tbenr** [comment]
> Btw, your commit isn't signed: https://help.github.com/en/articles/signing-commits

OK, never signed them, good to learn.

I almost did the changes you requested but I don't have access to  https://ci.status.im/env-vars.html 

I think I cannot give you a `COVERALLS_REPO_TOKEN`, the repository owner should login to coveralls.io and integrate it.. this is what i did for my status-react fork.

**Comment by jakubgs** [comment]
>I think I cannot give you a COVERALLS_REPO_TOKEN, the repository owner should login to coveralls.io and integrate it.. this is what i did for my status-react fork.

Ah fair point, forgot you are an external contributor there for a second. Thanks!

>I almost did the changes you requested but I don't have access to https://ci.status.im/env-vars.html

You can look up the same things here:
https://wiki.jenkins.io/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-belowJenkinsSetEnvironmentVariables

**Comment by jakubgs** [comment]
Okay, I've created a credential called `coveralls-token` in our Jenkins setup with the API key.

**Comment by tbenr** [comment]
@jakubgs cool, can you manually restart the android build and post somewhere the logs just to see if it does what we expect?

**Comment by jakubgs** [comment]
Done.

**Comment by jakubgs** [comment]
```
Loading trusted files from base branch develop at 119c5303a4f53964f9e7c4f467fa11bc9e92d3c0 rather than 280af0624141d7588028c39656ac9ad67348d1ce
Obtained ci/Jenkinsfile.android from 119c5303a4f53964f9e7c4f467fa11bc9e92d3c0
‘ci/Jenkinsfile.android’ has been modified in an untrusted revision
```
Looks like Jenkins doesn't trust your version of Jenkinsfile because it comes from a fork, and not from our own `status-react` repo.

**Comment by jakubgs** [comment]
I could make a separate PR based on yours that has the same changes to test if it works.

**Comment by jakubgs** [comment]
Created #8526 which should be identical.

**Comment by jakubgs** [comment]
Looks like #8526 works correctly. We can close this PR and use #8526 as yours, since all I had to do were just small CI adjustments to make it work.

**Comment by vkjr** [comment]
@tbenr, were you able to solve the issue with detox? I have the same by simply running `make startdev-desktop` on clean `develop`. Without any changes.

**Comment by tbenr** [comment]
@vkjr no, I haven't spent time on that... drop a line if you figure out!

**Comment by vkjr** [comment]
@tbenr, should be fixed here - https://github.com/status-im/status-react/pull/8562

**Comment by tbenr** [comment]
@vkjr great, good news

**Pull request closed without merging**
