### PR TITLE
ci: fix what version is set for iOS PR builds

### PR DESCRIPTION
**Pull request by jakubgs**
Related to #10904. Testing if using the right version might fix the iOS PR builds.

Also changes `ios/scripts/set_xcode_version.sh` to fix an issue with:
```
cat: ../../VERSION: No such file or directory
```
Not sure how that was caused, so I'd prefer if someone from Core tested the iOS build locally.

Related: https://github.com/status-im/status-react-jenkins/pull/10

### CODE REVIEW

**Comment by jakubgs** [comment]
Fails in a way that gives no useful information:
```
 ▸ Running script 'Run Script'
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.5.99. (in target 'OpenSSL-Universal' from project 'Pods')

** ARCHIVE FAILED **

The following build commands failed:
PhaseScriptExecution Run\ Script /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-dtstcopzvihllrcwqcupvbhygfpg/Build/Intermediates.noindex/ArchiveIntermediates/StatusImPR/IntermediateBuildFilesPath/StatusIm.build/Release-iphoneos/StatusImPR.build/Script-3AAD2AD724A3A60E0075D594.sh
```

**Comment by jakubgs** [comment]
The `Script-3AAD2AD724A3A60E0075D594.sh` script is actually this:
```sh
#!/bin/sh
#!/usr/bin/env bash

source "${PROJECT_DIR}/scripts/set_xcode_version.sh"
```
Which is our own script:
https://github.com/status-im/status-react/blob/90641596dab1be3c4e1694732e3bb0678e646691/ios/scripts/set_xcode_version.sh#L19-L34

**Comment by jakubgs** [comment]
Okay, managed to get some logs out of it:
```
jenkins@macos-02.ms-eu-dublin.ci.misc:~/workspace/status-react_prs_ios_PR-10907/ios % cat set_xcode_version.log 
+ set -o errexit
+ set -o nounset
+ hash git
+ INFO_PLIST='/Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-dtstcopzvihllrcwqcupvbhygfpg/Build/Intermediates.noindex/ArchiveIntermediates/StatusImPR/InstallationBuildProductsLocation/Applications/Status PR.app/Info.plist'
++ git ls-files -m StatusIm/Info.plist
+ [[ '' = *\I\n\f\o\.\p\l\i\s\t* ]]
++ cat ../../VERSION
cat: ../../VERSION: No such file or directory
+ RELEASE_VERSION=
```

**Comment by jakubgs** [comment]
Oh snap, I think I fixed it. The newest iOS build worked on my iPhone 5s that previously didn't work.

@churik can you check this one?

**Comment by churik** [comment]
@jakubgs 

Tried last build https://i.diawi.com/ffy3yR - doesn't work, https://github.com/status-im/status-react/pull/10904 - the same problem

**Comment by churik** [comment]
Works for me with lat build https://i.diawi.com/Pfbwmc , can install app and create account

**Review by Ferossgp — APPROVED** [review]
:+1:

**Comment by churik** [comment]
Failed e2e are not related to PR

**Pull request merged**
