### PR TITLE
fix #8717 change ens welcome screen

### LINKED ISSUE #8717: Change  "Connect & get paid" to "Chat & transact" in "ens-welcome-point-3-title"
# Problem

There is string "Connect & get paid" in ens welcome screen that can mislead user that he/she can be paid if connect with other users. Please, change it to  "Chat & transact" as it's more fair. Agreed with @rachelhamlin 

String to change:
"ens-welcome-point-3-title" in https://github.com/status-im/status-react/blob/develop/translations/en.json

### PR DESCRIPTION
**Pull request by yenda**
fixes #8717

english only
needs work for translations

image

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by hesterbruikman — APPROVED** [review]
Thanks @yenda, looks good!

**Review by errorists — APPROVED** [review]

**Comment by churik** [comment]
@yenda we should wait for translations for other languages or can merge it as it is?

**Comment by yenda** [comment]
@churik yeah I think there will be some issues with other languages showing the old labels and the new one will be in english, I think I will change the names of the labels so that it's all in english until it is translated

**Comment by churik** [comment]
From @rachelhamlin: Let's just go ahead and merge
I'll add a reminder to the calendar for us to order new translations for the app every so often to keep up with changes like this one

**Comment by yenda** [comment]
@churik @rachelhamlin ok so I changed the labels to use new ones, so that the old ones aren't mixed up with the new ones and show the wrong thing to the user. As a result they will see the welcome screen in english until translations are made

**Comment by rachelhamlin** [comment]
Thank you @yenda.

**Pull request merged**
