### PR TITLE
DO NOT SQUASH Meta wallet transaction history

### LINKED ISSUE #8151: Use status-go subscriptions for wallet
# Problem
As described in https://discuss.status.im/t/proposal-fix-the-transactions-list/1190 the current wallet implementation relies on a loop that pull transaction data from a third party service to fetch the transaction list.

This causes: dependence to a third party service, delays and performance issues. 

An overview of the background required to understand the problem.
A problem description.

## Implementation
As requested in https://discuss.status.im/t/performances-before-moving-communication-protocol-to-status-go/1199 status-go now exposes an api to subscribe to `eth_newFilter`, `eth_newBlockFilter` signals.

The documentation is available here:
https://github.com/status-im/status-go/blob/e541f00e5845f45f471e8c1d39740c8b3a61d6c1/services/subscriptions/README.md

## Acceptance Criteria
The current loop is replaced by these subscription and signals.
Status no longer relies on etherscan for fetching the transaction list

### PR DESCRIPTION
**Pull request by yenda**
This PR is a compilation of the reviewed wallet PRs so that they can be tested at once

fixes #8151 

## #8184 Feature/token transaction signals
part of #8151

* removes fetching of last 100000 blocks of token transfers from
the wallet pull loop
* fetches the last 100000 blocks of token transfers at startup
* replaces pulling by subscriptions to ethlogs for token transfers

## #8221 Feature/transaction signals

* remove the transaction fetching loop entirely to rely only on subscriptions
for live transactions and token transfer updates
* fetch token transfers history via etherscan API to lift the 100000 blocks
limit on token transfers history
* inbound token transfers are caught via a filter on ethlogs
* outbound token transfers and other transactions are caught by filtering
transaction in the current block that have the wallet address as `to` or `from` field

## #8224 Refactor/transaction details

* removing computations from transaction details view and simplifying related subscriptions

## #8230 Refactor transaction history

* Remove computations from views
* Optimize computations in subs
* Fix missing amount and label for unknown ERC20 tokens in transfer history
* clean up transaction history and transaction filters subscriptions
* move ui.screens.wallet.transactions.events to events
* move ui.screens.wallet.db to db

## #8231 Improve wallet update performances

* a few files are moved around because of circular dependencies, this continues migration of wallet and ethereum code into their own module (previous in ui.screens.wallet and utils.ethereums respectively)

`wallet-autoconfig-token` is a very expensive call on mainnet because it checks the balance of every known token. it is called:

* when wallet is refreshed by pulling
* when user goes on any wallet screen

This PR changes that by:

* calling it only when the wallet is initialized and there is no visible-token configuration
* it only calls update-wallet when a new transaction arrives

## #8232 Remove web3 and clean up wallet effects

* introduce json-rpc namespace, which provides `call` and `eth-call`,
a generic way of calling a json-rpc method taking care of conversions
and error handling
* remove web3 usage from wallet
* clean up effects, reducing the amount of computations when login in

## #8233 Remove call-params usage

* use `json-rpc/eth-call` and `wallet/eth-transaction-call` everywhere
* move all conversions to abi-spec

The goal of this PR is to unify the way we interact with contracts, so that future improvements can be made and impact all the callees. `json-rpc/eth-call` is for read only calls and `wallet/eth-transaction-call` is for transnational calls.

# Testing
When testing it is important to compare to what the situation is in develop. If things are not perfect but still equal or slightly improved compare to develop, we should treat them as bugs that I will fix asap in separate PRs, but this one is already very big and sets up the basis for faster future improvements of the wallet by cleaning up all the crap.

I tested all of the following points on Android emulator and One Plus 5T over the different PR, I will test again once build is available for the global rebase and merge.

## Areas to be tested for improvements:

* wallet much faster on slow devices (usual lag on wallet after login should be gone)
* bandwidth consumption (see point below)
* transaction history responsiveness (new transactions show up to 20 sec faster)
* better gas estimation (before it would always show the same number now it is precisely what the transaction should cost)

## Areas to be tested for regressions:

* anything that is related to transactions:
  * wallet
  * transaction history
  * in chat transactions
* anything that is related to ens resolution:
  * add chat by ens name
  * browse dapp by ens name
* stickers

## Bandwidth consumption
I made the following experiment on Android:

* use mobile data and disable sync to reduce the noise from whisper
* recover `satoshi document engage inflict goddess auction rule unfair bid next buddy shy`
* go on ropsten network
* clear history in GlassWire (https://play.google.com/store/apps/details?id=com.glasswire.android&hl=en&rdid=com.glasswire.android&pli=1)
* restart app
* go to wallet history, check transaction details of first transaction, go back to wallet, pull to refresh, go to chat, kill app
* reopen app, go to transaction history, wait 2 minutes, pull to refresh, kill app
* switch 5 times between wallet and chat and wallet and transaction history

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by hesterbruikman** [comment]
Great work! I had a quick look; these are some observations. 
- Very snappy transition from other tabs!
- White background showing on pulldown of Wallet balance
- 'Add custom token' can use some more love:
a) Retains position on list scroll, but has no visual indication of this. Is this as specified? @errorists can you please take a look?
b) If the behavior of Add custom token is that it adds all selected items, I think it needs a stronger conection to the Select boxes. Maybe same row as 'default' title as in one of the design proposals
c) Back button doesn't do anything so get stuck on the Assets screen
- In Transaction history, the date title overalps content on scroll. Ideally, current date remains on a white background at the top and updates on scroll. Like the behavior in dap.ps > View all > scroll

**Comment by errorists** [comment]
@flexsurfer pls pls tag me for a PR review whenever you're doing UI work 🙏 

- The 'Add custom token' button should not have a sticky position, it's just a regular list item that scrolls with the rest of the list

- When I tap 'Add custom token' I'm taken back to the root Wallet screen so 'back', can't really test further than that :(

**Comment by flexsurfer** [comment]
@hesterbruikman @errorists this PR is not related to custom tokens, sorry, it was this one https://github.com/status-im/status-react/pull/8235, i created the issue for leftovers and discussion https://github.com/status-im/status-react/issues/8243

@yenda but looks like after resolving conflicts there are some issues:

1. When I tap 'Add custom token' I'm taken back to the root Wallet screen so 'back', can't really test further than that :(
2. Back button doesn't do anything so get stuck on the Assets screen

**Comment by asemiankevich** [comment]
@yenda for some reason simpledapp.eth is not working here in the PR (works in release and nightly builds).

image

**Comment by flexsurfer** [comment]
> @yenda but looks like after resolving conflicts there are some issues:
> 
> 1. When I tap 'Add custom token' I'm taken back to the root Wallet screen so 'back', can't really test further than that :(
> 2. Back button doesn't do anything so get stuck on the Assets screen

@asemiankevich could you confirm? 
also for wallet refresh on ios we have this issue https://github.com/status-im/status-react/issues/7812

**Comment by asemiankevich** [comment]
> > @yenda but looks like after resolving conflicts there are some issues:
> > 
> > 1. When I tap 'Add custom token' I'm taken back to the root Wallet screen so 'back', can't really test further than that :(
> > 2. Back button doesn't do anything so get stuck on the Assets screen
> 
> @asemiankevich could you confirm?
> also for wallet refresh on ios we have this issue #7812

@flexsurfer yes, i see same issues

**Comment by yenda** [comment]
@asemiankevich @flexsurfer sorry it wasn't meant for testing yet as discussed with @chu I still have two commit to add and some fixes, I just wanted @hesterbruikman to have a look to tell me if she can notice a difference already since she was having big perf issues with previous wallet

**Comment by yenda** [comment]
@churik can you start testing once the build is ready? I think the 2 commits I was planning to add are not worth delaying and can be tested afterward

**Comment by yenda** [comment]
@asemiankevich please proceed with testing this PR. Btw default tokens are removed, so don't expect to see STT on ropsten until you check it, or if you recover an account with STT on it you should see it, that's a feature, the wallet only shows the token you own the first time you set it up on a network, after that if you want to add/remove token it's with manage asset. Because we don't want to be checking the balance of all existing tokens every time we log in. Later one it can be improved by adding tokens based on new transactions.

**Comment by churik** [comment]
@yenda 

#### 1) Error when tap on transaction on Mainnet
**Steps:**
- restore account with transactions
- open transaction history
- tap on any transaction

**Expected result:** no error
**Actual result:** Error: Doesn't support name

[geth.log](https://github.com/status-im/status-react/files/3202341/geth.log)
[Status.log](https://github.com/status-im/status-react/files/3202342/Status.log)

2) Swipe-to-delete gesture is not working (works in nightly). Did we remove it intentionally?

**Comment by yenda** [comment]
@churik 
1. is fixed
2. it was replaced by long press to show contextual menu yesterday

**Comment by churik** [comment]
@yenda 
#### 3) Collectibles are not shown after restoring account
**Steps:**
- restore account with collectibles (in my case CryptoStrikers, Cryptokitties and Ethermons)
- open wallet

**Expected result:** can see collectibles 
**Actual result:** no collectibles are shown

**Comment by asemiankevich** [comment]
@yenda 

4) Stickers icon is not shown as pending (spinner) when i performed transaction to buy it. Also, the button initiates as many transactions as many i tap it. Should be changed to spinner (txn is being mined) and then to Install once txn is mined.

Also, even transaction is mined - stickers are not shown as bought

image

**Comment by asemiankevich** [comment]
@yenda 

5. can't buy ens name - i am not redirected to sign transaction screen by hitting Register

**Comment by flexsurfer** [comment]
@yenda please don't add any new commits here, only fixes for QA,  it's too large , and it will be difficult to test it

**Comment by flexsurfer** [comment]
And if there are no objections let's do not merge this PR before release cut

**Comment by yenda** [comment]
@flexsurfer yes I am not adding any commits just fixing. But I don't see why we wouldn't merge it after testing, there will be additional release testing which is the good opportunity to find if some bugs slip through. Release shouldn't delay development.

Also it is a big PR but it is meant to be merged in multiple commits, so that it is easier to find the origin of issues if some were discovered after merging

**Comment by yenda** [comment]
@asemiankevich
- cryptocollectibles are fixed, 
- stickers I'm not sure is from this PR but since it's behind a flag anyway I propose to open an issue for that. Note that I was able to buy stickers, and once the transaction was mine I was able to install and use it (spamming you as proof :D)
- registration dapp definitely not from this PR, you can test all the bridge calls with simpledapp.eth, if it works there it will work everywhere once the browser bug is fixed

**Comment by annadanchenko** [comment]
> with testing this PR. Btw default tokens are removed, so don't expect to see STT on ropsten until you check it, or if you recover an account with STT on it you should see it, that's a feature, the wallet only shows the token you own the first time you set it up on a network, after that if you want to add/remove token it's with manage asset. Because we don't want to be checking the balance of all existing tokens every time we log in. Later one it can be improved by adding tokens based on new transactions.

@yenda @rachelhamlin users get used to the fact that upon receiving tokens that app supports they would see tokens in the wallet without any extra action. When this PR will  be merged users will get other app behaviour that doesn't seem to me desirable. From this pov, I would not merge PR into upcoming 0.13.0 release but rather in the next one when implementation of " it can be improved by adding tokens based on new transactions." is done

**Comment by yenda** [comment]
@annadanchenko ok then I'm adding this in 15 min

**Comment by yenda** [comment]
@annadanchenko @asemiankevich actually I have an issue with reestablishing previous behavior, because it made managing asset completely useless, since the tokens you uncked would come back every time anyway what is the point? So I propose to make a separate PR for tomorrow that does things properly

You can see that behavior in develop, uncheck your asset, refresh the wallet, they are all back.

**Comment by yenda** [comment]
@annadanchenko @asemiankevich I reintroduced previous behavior for now anyway, but I think it's a bug that should be fixed

**Comment by asemiankevich** [comment]
@yenda when creating new account in last build
image

**Comment by rachelhamlin** [comment]
Thanks for the thorough test notes on this PR @yenda.

@annadanchenko @yenda I'm unclear on the expected behavior for tokens I own. On the build I just tried, the tokens I own displayed as normal and so did tokens I'd displayed but own 0 of. 

Did we use to display certain tokens like STT by default? What's changed, and is it reverted now?

**Comment by yenda** [comment]
what has changed:
- before we there was a few default token that would show up even if you had 0 balance for it, this is gone
what is still the same:
- if you have a balance for a token, it will show up, if you remove it in asset list, it will disappear until the wallet is updated (but the wallet updates less in the PR, only when a new transaction arrives or when a block is missed, not when you pull, because that is not necessary anymore, pulling only refreshes prices)

**Comment by rachelhamlin** [comment]
> what has changed:
> 
> * before we there was a few default token that would show up even if you had 0 balance for it, this is gone
>   what is still the same:
> * if you have a balance for a token, it will show up, if you remove it in asset list, it will disappear until the wallet is updated (but the wallet updates less in the PR, only when a new transaction arrives or when a block is missed, not when you pull, because that is not necessary anymore, pulling only refreshes prices)

Perfect. So wallet update = new tx received, missed block. Would not want to see tokens I had removed reappear in that case.

What about when I update Status though? Will it autodetect all tokens then?

**Comment by yenda** [comment]
> Perfect. So wallet update = new tx received, missed block. Would not want to see tokens I closed reappear in that case.

can you file a bug for that describing the expected behavior? I will fix it in a next PR, this is already a bug in develop atm.

> What about when I update Status though? Will it autodetect all tokens then?
it already does that afaik.

**Comment by rachelhamlin** [comment]
@yenda done with #8254 - feel free to add more details. Thanks.

**Comment by yenda** [comment]
@annadanchenko is it ok to merge now?

**Comment by annadanchenko** [comment]
> @annadanchenko is it ok to merge now?

yes, thanks for waiting!

**Pull request merged**
