### PR TITLE
Navigate to the root screen when pressing active tab 

### PR DESCRIPTION
**Pull request by flexsurfer**
Navigate to the root screen when pressing the active tab

### CODE REVIEW

**Comment by errorists** [comment]
@flexsurfer yo, does that work for all tabs? because it's part of the native tab bar behaviour, if you tap on the currently active tab it takes you to the root level of the tab, regardless how deep you are. So it should have the same effect when in wallet or browsing settings.

**Comment by flexsurfer** [comment]
yes @errorists  thanks

**Comment by errorists** [comment]
beautiful, thank you

**Review by Ferossgp — APPROVED** [review]

**Comment by Serhy** [comment]
Thanks @flexsurfer, tested with iOS14 and Android 9 and Android 8. Also fixed e2e here.

**Pull request merged**
