### PR TITLE
[#9543] Signing phrase popup minor fix

### LINKED ISSUE #9543: Signing phrase popup minor fix
1. Let's treat the tap outside the popup (on the overlay) as "Maybe later" (if it's not treated this way already);
2. Let's show the signing phrase popup next time only when the app is opened again (not each time the wallet tab is opened)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #9543

### CODE REVIEW

**Comment by andmironov** [comment]
Tried this build on ANdroid, got an error when opened the app: 
```
Error. Vector's key for assoc must be a number
```

**Review by andmironov — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by churik** [comment]
> Error. Vector's key for assoc must be a number

@andmironov do you still see this issue? Can't reproduce it on Android 8 and Android 9

**Comment by churik** [comment]
Tested on Android 8, Android 9 and IOS 13.
Looks good to me.
Failed e2e are unrelated.

**Comment by flexsurfer** [comment]
> > Error. Vector's key for assoc must be a number
> 
> @andmironov do you still see this issue? Can't reproduce it on Android 8 and Android 9

@churik it's only possible to reproduce when you upgrade specific version, so that's fine

**Pull request merged**
