### PR TITLE
Update invalid seed phrase copy

### PR DESCRIPTION
**Pull request by acolytec3**
### Summary

English copy for Invalid seed phrase warning that pops when trying to recover a multiaccount with a seed phrase that doesn't conform to BIP39 is inaccurate.  This updates the copy to reflect the actual issue.

#### Platforms

- Android
- iOS

##### Functional

- account recovery

### Steps to test

- Open Status
- Select recover account from seed phrase
- Enter invalid seed phrase and try to proceed
- Should get below error message

Error pop-up should say:
`Invalid seed phrase` 
and message should be
`This seed phrase doesn't match our supported dictionary. Some words may be misspelled.`

status: ready

cc @rachelhamlin

### CODE REVIEW

**Comment by acolytec3** [comment]
@rachelhamlin Here's the PR to update the copy in the english translation for the invalid seed phrase messaging.  Does this look right?

**Comment by rachelhamlin** [comment]
Seeing it in the interface—can we actually tweak @acolytec3? 

`This seed phrase doesn't match our supported dictionary. Some words may be misspelled.`

**Comment by acolytec3** [comment]
@rachelhamlin Done.

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
Ready to be merged.
test is fixed in https://github.com/status-im/status-react/pull/9776

**Pull request merged**
