### PR TITLE
Change status-bar color on theme change

### PR DESCRIPTION
**Pull request by Ferossgp**
Moved fn into separate ns to avoid circular dependency on colors namespace

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by Serhy** [comment]
@Ferossgp On Android Status bar has wrong colour with the latest build: https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200608-150348-94d577-universal.apk

Screenshot_20200609-113547_Status PR

**Comment by Serhy** [comment]
All good with iOS (changing Appearance and when autologin in to account has correct status bar colors)

**Comment by Ferossgp** [comment]
@Serhy pushed a fix

**Comment by Serhy** [comment]
Looks good to me now on Android 8.1 and Android 9! 
Thanks @Ferossgp !

**Pull request merged**
