### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by jinhojang6**
Languages to update

- German
- French
- Italian
- Russian
- Turkish
- Tranditional Chinese

### CODE REVIEW

**Comment by jinhojang6** [comment]
@flexsurfer @rachelhamlin  @hesterbruikman 

On top of this PR, below is the list of reviewed languages
- Simplified Chinese (zh.json)
- Traditional Chinese (zh_TW.json)
- Korean (ko.json)
- French (fr.json)
- Spanish (es.json, es_419.json)
- Italian (it.json)
- Arabic (ar.json)
- Indonesian (id.json)
- Filipino (fil.json)

The languages above have been reviewed by ambassadors and core contributors. The quality of the translation is good until now.

I recommend removing unreviewed languages except for the 7 languages above from the production builds, which can be done at https://github.com/status-im/status-react/blob/9243daa405f0eb810f37863e86445a67b0344e92/prod/status_im/i18n_resources.cljs#L8

What do you think? I think it doesn't look good for newcomers to find a bunch of awkward translation at the beginning (if there is any)

**Review by flexsurfer — APPROVED** [review]

**Review by hesterbruikman — COMMENTED** [review]
100% agree on removing unreviewed languages! 
I actually thought we only supported these languages as described in [FAQ](https://status.im/docs//FAQs.html): English, French, Italian, Chinese, Korean, Japanese, Arabic and Russian

Of these, @rachelhamlin mentioned prioritizing Chinese, Russian, Spanish and Korean
So I suggest we maintain those 4 (Russian to be updated) and only add 100% complete, fully reviewed languages.

**Comment by jinhojang6** [comment]
@hesterbruikman 

Thanks for the feedback! 

It is difficult to get languages translated 100% as they are always updated though :)

Also, we need to update the description on App/Play Store. It says only English is available.

**Comment by jinhojang6** [comment]
If @rachelhamlin approves removing the unreviewed languages at https://github.com/status-im/status-react/blob/9243daa405f0eb810f37863e86445a67b0344e92/prod/status_im/i18n_resources.cljs#L8

, I will update this PR.

**Comment by flexsurfer** [comment]
> Also, we need to update the description on App/Play Store. It says only English is available.

ping @andremedeiros

**Review by rachelhamlin — APPROVED** [review]

**Comment by andremedeiros** [comment]
> It says only English is available.

Interesting. I'll 👀

**Comment by jinhojang6** [comment]
@flexsurfer the ipa file was successfully built but it doesn't work on my iphone. Do I need to remove all the lines for removed languages at https://github.com/status-im/status-react/blob/b001962a821402933cf480bd54c5ad1a06f555fc/prod/status_im/i18n_resources.cljs#L14 as well? It works well on Android

**Comment by jinhojang6** [comment]
@flexsurfer Removed the lines but still doesn't work on iphone.

**Comment by flexsurfer** [comment]
ok will take a look thanks

**Comment by flexsurfer** [comment]
it's not an issue of this PR we have same in nightly

**Comment by flexsurfer** [comment]
@jinhojang6 rebased, should be fixed in latest build when ready

**Comment by jinhojang6** [comment]
@flexsurfer It works now. Thanks!

**Pull request merged**
