### PR TITLE
nix: Upgrade Android SDK, use nixpkgs master

### PR DESCRIPTION
**Pull request by jakubgs**
This makes use of the refactoring of Android SDK done in: https://github.com/NixOS/nixpkgs/pull/89775

Which allows us to drop the use of our own fork of `nixpkgs`.

Android Upgrades:
* Build Tools - `29.0.2` to `30.0.3`
* Platform Tools - `29.0.6` to `30.0.5`
* NDK Bundle - `21.0.6113669` to `21.3.6528147`

Other Upgrades:
* Git - `2.28.0` to `2.29.2`
* Go - `1.14.7` to `1.14.13`
* Clojure - `1.10.1.645` to `1.10.1.763`
* NodeJS - `12.18.3` to `12.20.1`
* Yarn - `1.22.4` to `1.22.10`
* OpenJDK - `8u265-ga` to `8u272-b10`
* PatchElf - `0.11` to `0.12`
* CoreUtils - `8.31` to `8.32`

Status: __READY__

### CODE REVIEW

**Comment by Serhy** [comment]
@jakubgs could you please rebased develop because there fix for ENS names which is also a part we are going to check here

**Comment by Serhy** [comment]
Looks good to me, checked iOS14, Android 8 and Android 9.

**Comment by jakubgs** [comment]
Thanks dude!

**Comment by flexsurfer** [comment]
@jakubgs is this still relevant?

**Comment by jakubgs** [comment]
@flexsurfer of course it's relevant. Did you read the PR description?

>Status: WIP ([#89775](https://github.com/NixOS/nixpkgs/pull/89775) not merged yet)

**Comment by jakubgs** [comment]
@flexsurfer could you check this out? Preferably locally.

I built it locally on my NixOS machine but I'd like to see how it does on a different OS.

**Review by flexsurfer — COMMENTED** [review]
working fine for android on macos, can't check ios because i've switched to xcode12

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
e2e failures are not related to PR.
it was tested so nothing to prevent it from merging

**Pull request merged**
