### PR TITLE
[WIP] Generate ubuntu-server binaries during build

### LINKED ISSUE #8246: Generate ubuntu-server binaries during build
# Problem

Ubuntu-server binaries better to be generated during build because their replacing requires a lot of manual work: generating new binaries, uploading them to servers, changing hashes in nix files.

## Implementation
Here are steps that needed to generate binaries:
1) pkg package should be installed - https://github.com/zeit/pkg
`npm install -g pkg`

2) yarn install should happen before next steps 

3) Patch should be applied to realm file:
`patch node_modules/realm/lib/index.js < patches/change_realm_for_pkg.patch`
`patch file can be found here - https://github.com/status-im/status-react/pull/8244`

4) Binaries should be generated with pkg:
`pkg ubuntu-server.js --targets macos --out-path ./ubuntu-server-binary/macos`
`pkg ubuntu-server.js --targets linux --out-path ./ubuntu-server-binary/linux`
`pkg ubuntu-server.js --targets win --out-path ./ubuntu-server-binary/win`

5) Realm patch should be reverted:
`patch -R node_modules/realm/lib/index.js < patches/change_realm_for_pkg.patch`

## Future Steps

ubuntu-server binaries should be removed from servers

### PR DESCRIPTION
**Pull request by vkjr**
fixes #8246

### Summary

Ubuntu-server binaries better to be generated during build because their replacing requires a lot of manual work: generating new binaries, uploading them to servers, changing hashes in nix files.

#### Platforms

- macOS
- Linux
- Windows

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

- Open Status
- ...
- Step 3, etc.

status: wip

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
Can't find anything wrong with this. Is it ready?

**Comment by vkjr** [comment]
Work on this PR temporarily postponed due to more high-priority tasks. I believe @PombeirP will make more changes to it.

**Comment by flexsurfer** [comment]
@vkjr @PombeirP hey guys any updates?

**Comment by vkjr** [comment]
@flexsurfer, no updates from my side

**Comment by pedropombeiro** [comment]
@flexsurfer I've been focused on reproducible Android builds, so no updates from my side.

**Comment by oskarth** [comment]
Closing as it's been stale for too long, feel free to reopen if this was in error.

**Pull request closed without merging**
