### PR TITLE
App version and more details in logs email

### PR DESCRIPTION
**Pull request by rasom**
status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Comment by mandrigin** [comment]
@flexsurfer can you review only the last commit there? it is based on another branch, so everything else makes no sense to review (it was either merged on reviewed already)

**Review by flexsurfer — APPROVED** [review]

**Comment by mandrigin** [comment]
@rasom is there anything WIP about this PR? I think we can just rebase it on develop, test and merge already. It doesn't seem to be dependent on "Shake to send" feature.

**Comment by rasom** [comment]
@mandrigin rebased

**Comment by churik** [comment]
Tested on IOS 11.4.1 (IPhone 7), Android 8 (LG V20):
- changing log level / network / mailserver > send logs - additional details are added and received;
- sending logs when shaking device;
- sending logs from profile;
- sending device twice in a row;

Looks good to me, thanks @rasom 
If no objections - we can include it to 0.13.0. if it is needed.

cc @annadanchenko @mandrigin

**Pull request merged**
