### PR TITLE
[#10811] There should be an option to continue opening suspicious urls

### LINKED ISSUE #10811: There should be an option to continue opening suspicious urls
# Feature Issue

There should be an option to continue opening suspicious urls

### User Story

Currently if status detects URL as phishing it's not possible to open such URL, there should be an option to continue opening

More details: https://discuss.status.im/t/web3-browser-blocking-content/1761

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #10811

### CODE REVIEW

**Review by Ferossgp — APPROVED** [review]
Overall LGTM! I have only one concern, seems like if you press continue on one website, then it will ignore unsafe links for the whole session? In my experience other browsers do that per domain

**Comment by flexsurfer** [comment]
@Ferossgp good catch

**Comment by flexsurfer** [comment]
fixed

**Review by Ferossgp — APPROVED** [review]
:+1:

**Review by vitvly — APPROVED** [review]

**Comment by oskarth** [comment]
Small request - could you please rebase to latest master so this commit https://github.com/status-im/status-react/commit/b5fda1234e5447cbc626059dfc78fcfbabc9e926 gets included? This means we aren't running E2E tests on eth.prod cluster anymore, and since this happens on every push, the impact is quite big. This ensures we have more accurate metrics going forward from Jul 1 onward, which would be awesome. See https://discuss.status.im/t/user-growth-and-retention/1782 for more

**Comment by Serhy** [comment]
Tested on iOS13 and Android 9, 8
@flexsurfer please mind my commit before merge (updated test to check 'Continue anyway' option)

**Pull request merged**
