### PR TITLE
update react-native-camera

### PR DESCRIPTION
**Pull request by yenda**
### Steps to test

Try scanning QR code and taking profile pictures

status: ready

### CODE REVIEW

**Review by pedropombeiro — APPROVED** [review]

**Comment by flexsurfer** [comment]
this may fix https://github.com/status-im/status-react/issues/8772

**Comment by churik** [comment]
@flexsurfer can you please rebase it and resolve conflicts?

**Comment by flexsurfer** [comment]
@PombeirP @yenda @siphiuel  is this still relevant?

**Comment by vitvly** [comment]
@flexsurfer Superceded by https://github.com/status-im/status-react/pull/8861

**Comment by ghost** [comment]
`mobile_files/yarn.lock` changed. Pinging @jakubgs and @corpetty

**Pull request closed without merging**
