### PR TITLE
Revert "Remove fastlane metadata because no one use it"

### PR DESCRIPTION
**Pull request by jakubgs**
Because as pointed out in [this comment](https://github.com/status-im/status-react/issues/12289#issuecomment-894008069) the lack of fastlane metadata makes F-Droid unable to find out things like app description.

For more details see:
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure

### CODE REVIEW

**Comment by licaon-kter** [comment]
Thanks 

Do note that it will be picked up on the **next** app update.

**Comment by jakubgs** [comment]
@licaon-kter yeah, I expected as much. Thanks for pointing the issue out.

**Comment by jakubgs** [comment]
Looks like this will need some additional work as we updated descriptions in Google Play Store manually.

**Review by flexsurfer — APPROVED** [review]

**Comment by jakubgs** [comment]
I copied the english descriptions and title directly from Play Store:
https://play.google.com/store/apps/details?id=im.status.ethereum

But I don't know how to access any other languages. @jinhojang6 do we have translations of the PlayStore descriptions and titles for other languages? Were those ever updated?

**Comment by jinhojang6** [comment]
Updated the translations. I'm working on some long translations to shorten them

**Comment by jakubgs** [comment]
Thanks @jinhojang6, I squashed my commit into yours to just have two in total. I'll merge once it passes.

**Pull request merged**
