### PR TITLE
Add support for importing keycard account to new device

### LINKED ISSUE #7887: 'PIN does not match' error is shown if PIN is correct but card was removed. Can lead to PIN being blocked
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: If correct PIN was entered to sign a transaction but card was removed before action is completed then 'PIN does not match' error is shown. In case user does not re-enter PIN and just holds card again then app considers that another attempt to enter a wrong PIN was made and show error thta user now has 2 retries to enter valid PIN.

Screenshot!UNITO-UNDERSCORE!20190403-164136

Issues:

1. I would expect some other message like "can't read card, please hold it to the back of your phone". 
1. There are no 6 dots shown that would "invite" user to start typing PIN again. I would expect they are shown together with an error message
1. Most dangerous: if user holds card to the phone again without entering PIN then for some reason it decides that wrong PIN was entered again and shows "You have 2 reties left PIN does not match"
Screenshot!UNITO-UNDERSCORE!20190403-165422

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
1-2. Another message if can't read card

1. If put card back then it uses PIN entered before and validates it 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status and sign in with keycard
* Wallet -> Send transaction -> select some contact and valid ETH amount -> tap Sign Transaction
* do not hold card next to the phone, Enter correct PIN
* when requested to hold card - touch it for a second to the phone and remove
* check error message shown
* hold card back again (do not enter any PIN)
* check error message (in my case it tells that 2 retries are left and PIN is not correct)
* remove card and hold it again
* check error message

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: 0.12.0 apk http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190402-123212-80ef5d-pr.apk
* Operating System: Android 9, Pixel XL

### LINKED ISSUE #7891: App crashes if send transaction from chat signed with keycard
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: App crashes if send transaction from chat:

```
04-03 17:29:43.470 26863 26901 I ReactNativeJS: MESSAGE: Error: Error: Error: Error: There is no route defined for key wallet-transaction-sent.
04-03 17:29:43.470 26863 26901 I ReactNativeJS: Must be one of: 'wallet-send-transaction-modal','wallet-transaction-sent-modal','wallet-transaction-fee','hardwallet-connect','enter-pin'
04-03 17:29:43.470 26863 26901 I ReactNativeJS:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: This error is located at:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in _
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in s
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in u
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in C
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in n
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in E
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in n
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in H
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in L
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in v
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in _
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in s
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent2
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in root
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent1
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: This error is located at:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in s
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in u
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in C
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in n
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in E
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in n
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in H
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in L
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in v
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in _
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in s
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent2
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in root
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent1
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: This error is located at:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in s
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent2
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in root
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent1
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: This error is located at:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent2
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in root
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent1
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS:

```

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
no crash, transaction is sent or error message explaining why it can't be sent

#### Actual behavior
[comment]: # (Describe what actually happened.)
crash

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status and sign in with keycard
* open 1:1 chat with a contact
* send 0.0001 ETHro 
* Sign transaction 
* enter valid PIN
* check if transaction is sent or error message is shown

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: 0.12.0 apk http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190402-123212-80ef5d-pr.apk
* Operating System: Android 9, Pixel XL

#### Logs
[geth.log](https://github.com/status-im/status-react/files/3039469/geth.log)
[Status.log](https://github.com/status-im/status-react/files/3039470/Status.log)

### LINKED ISSUE #7898: PIN value is shown in confirmation popup after changing PIN
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: Remove PIN value (111222 on picture) from confirmation popup shown after user resets his PIN
Screenshot!UNITO-UNDERSCORE!20190403-171114

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
no PIN value is shown in confirmation popup

#### Actual behavior
[comment]: # (Describe what actually happened.)
pin value 111222 is shown 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status, enter wrong PIN 3 times when signing transaction
* Enter PUK to create new PIN
* provide new PIN value
* check confirmation popup content shown after PIN is set

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: 0.12.0 apk http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190402-123212-80ef5d-pr.apk
* Operating System: Android 9, Pixel XL

### LINKED ISSUE #7913: If card has keys on it, there is no way to use it with new device (cannot restore an account with pairing code)
### Description
_Type_: Bug
_Summary_: when I create account with keycard, there is no way to restore it with pairing code.

#### Expected behavior
can restore account

#### Actual behavior
"This card has already an account on it. If you wish to change it, login first and then reset your card".
So if you don't have card-reader or device with initial install - it is dead end for card.

### Reproduction

* Open Status
* Create account with keycard
* Reinstall build or install on another device
* Tap on "I already have an account" > Keycard
* Tap card and enter valid pairing code

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190403-181003-8b6ae2-pr.apk
* Operating System: Android 8, LG V20

### PR DESCRIPTION
**Pull request by dmitryn**
### Summary:

* Add support for importing keycard account to new device (fixes #7913)
* Handle card disconnect when signing (fixes #7887)
* Fix navigation bug (fixes #7891)
* Remove PIN from alert message when changing PIN (fixes #7898)

status: ready

### CODE REVIEW

**Comment by dmitryn** [comment]
Screenshot_20190411-130240

"Import account" screen

**Review by flexsurfer — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by churik** [comment]
Can't create account with empty card (I can successfully create account with same card on build from https://github.com/status-im/status-react/pull/7977)
Steps:
- delete applet from card using keycard-cli
- install https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190416-093125-74ec75-pr.apk
- tap on "Create account", select keycard
- hold card to back of phone

**Expected result:** can create new account 
**Actual result:** "This card has already an account on it" 
**Log:**  [keyc.log](https://github.com/status-im/status-react/files/3089459/keyc.log)

**Comment by dmitryn** [comment]
@churik Let me check if fix made in https://github.com/status-im/status-react/pull/7942 work as it might be similar issue.

**Comment by dmitryn** [comment]
@churik should be fixed now. 
After #7942 has been merged, it's not possible to create account with empty card – you need to have pre-install applet (with usb) on it or have card from factory where applet already installed.

**Comment by asemiankevich** [comment]
@dmitryn can we rebase ? i think we have the fix for navigation when user is not able to recover account -> redirect to home screen when tapping a card. Should be fixed in another PR i believe

**Comment by dmitryn** [comment]
@asemiankevich rebased to latest develop

**Comment by annadanchenko** [comment]
@dmitryn please, make sure that all builds are successful  before moving PR into TO TEST column. Right now, all new builds seem to be failing, so it's impossible to test changes.

Screen Shot 2019-04-29 at 20 56 37

Screen Shot 2019-04-29 at 20 58 14

**Comment by asemiankevich** [comment]
@dmitryn 

1. https://github.com/status-im/status-react/issues/7913 is not fixed. I can't login after i pair the device. 

Steps:

- Open Status
- Create account with keycard
- Reinstall build or install on another device
- Tap on "I already have an account" > Keycard
- Tap card and enter valid pairing code -> Note that user stays on the Hold the keycard screen (why? Probably should log him out?)
- Tap "I already have an account" > Keycard -> Hold the card

Expected: i should be logged in if card is paired already.

2. https://github.com/status-im/status-react/issues/7887 is not fixed. [PIN does not match] if shown when user is on changing PIN flow and tapping the card quickly. Also , there could be an error shown (but hard to reproduce)
image
image

3. https://github.com/status-im/status-react/issues/7891 is not fixed. I can't send tokens , insufficient funds error shown (balance is okay meanwhile) and app crashes when i try to send ETH
image
image

4. https://github.com/status-im/status-react/issues/7898 is not fixed completely because user is not logged out when PIN is changed, should be logged out. Instead he stays on the Hold the card screen.

If possible and makes sense, could you please drop the PR and divide it into small ones, fixing the 1 problem at 1 time? It is difficult to test, also hard to understand what is causing regressions and i assume very hard to support the branch. @annadanchenko would it be better? This PR is in queue for already 2 weeks and seems it could take more. Thanks!

**Comment by dmitryn** [comment]
@asemiankevich ok, i will close this PR and open smaller ones instead.

**Pull request closed without merging**
