### PR TITLE
[#11179] Nicknames in mention suggestions

### LINKED ISSUE #11179: Select and view nickname as mention
# Problem
When users have assigned a nickname, they likely expect to mention people by their nickname and only ever see the nickname as a way to recognize the given user. However, if users enter a nickname this might lead to collisions; People in the chat might have a ENS name that is the same as the nickname. This problem is addressed by letting people select the mention from a suggestion list.

Discussed flow:
- hierarchy Nickname, ENS name, 3-word name is followed in mentions
- when user enters @ mention suggestion list appears
- when user enters @x mention suggestion list appears with relevant users. This can be nickname starting with x or ens name starting with x (collision case) - both will including random name to differentiate
- when user taps on user in mention suggestion list, ENS/3w-name is shown in chat input box, highlighted as mention
- when user hits send, mention is shown in message as nickname

## Acceptance Criteria
User can select nickname as mention and view nickname in chat message

### PR DESCRIPTION
**Pull request by rasom**
fix #11179 

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by hesterbruikman** [comment]
@rasom looks like builds are failing

**Comment by rasom** [comment]
@hesterbruikman on it

**Comment by rasom** [comment]
@hesterbruikman fixed

**Comment by errorists** [comment]
one unrelated comment from me so it doesn't get lost, I can't force autocompletion for words following the first space. so say 'Teenage Mutant Turtle', if I search for 'Turtle' or 'Mutant' it won't show up in autocompletion, not cool. Otherwise works as expected, I get results for nicknames.

**Review by errorists — APPROVED** [review]

**Review by hesterbruikman — APPROVED** [review]
**See next comment - found 2 issues for this PR**

Tested with the following user configs on Android and iOS:
- ENS name
- Random name
- Random name with assigned nickname (contact)
- Random name with assigned nickname (non-contact)

Tested collision by giving random name the same nickname as ENS name of another user. 

Works as expected 
- when user enters @ mention suggestion list appears
- when user enters @x mention suggestion list appears with relevant users. This can be nickname starting with x or ens name starting with x (collision case) - both will including random name to differentiate
- when user taps on user in mention suggestion list, ENS/3w-name is shown in chat input box, highlighted as mention
- when user hits send, mention is shown in message as nickname

**Comment by hesterbruikman** [comment]
Found 3 issues after all:( 1 and 2 have to do with setting nicknames for non-contacts. 3 should probably be handled outside of this PR. cc @churik @Serhy 

### Issue 1
When nickname is not a contact, nickname is not shown in mention suggestion list. 
To reproduce:
- Join random channel with user A
- Assign nickname to user A with user B (do not add to contacts)
- Start text in put `@` to pull up mention suggestion list
- Result: Nickname is not included on mention suggestion list

### Issue 2
Error when mentioning non-contact right after adding nickname

Appears on Android, when mentioning for the first time right after adding a nickname
Works fine after closing and reopening app
To reproduce:
- Join random channel with user A
- Assign nickname to user A with user B (do **not** add to contacts)
- Start text in put `@` to pull up mention suggestion list
- Result: Nickname is not included on mention suggestion list

Screenshot_20200922-180559_Status PR


~~### Issue 3~~ **Can be ignored for now. Edge case that only occurs when using same account on +3 devices
Not receiving mention notification for ENS name**

To reproduce:
- Use account with ENS name as user A on iOS, notifications enabled
- Mention user A with user B

**Comment by rasom** [comment]
@hesterbruikman issues 1 and 2 should be fixed now

**Comment by rasom** [comment]
@hesterbruikman I'm not sure that issue 3 is related to this pr

**Comment by cammellos** [comment]
not related to this pr, likely due to multiple devices and recovery, will
be tracked separately

**Comment by hesterbruikman** [comment]
> @hesterbruikman issues 1 and 2 should be fixed now

Confirmed, thank you @rasom

**Comment by rasom** [comment]
@errorists i just checked and it looks fine on my side image

**Comment by errorists** [comment]
@rasom so you started typing with `a…`? for `Animated`, the first word? on my end if I would start with `p` because I only remember the `Porcupine` part of the username, it wouldn't show the suggestion, and it should.

**Comment by rasom** [comment]
@errorists Oh well, i haven't seen this mentioned anywhere ever, and as soon as I don't have psychic abilities I didn't implement it... :)

Do you else recall if it works this way in any other messenger, I mean that mentions are suggested by matching parts of the name? 

Anyway it is totally unrelated to this pr

**Comment by errorists** [comment]
@rasom it's okay really, I wouldn't expect us to land everything on the first go. I stumbled upon it when creating a bunch of weird nicknames for people. About other messengers I checked Discord and Slack and both work this way, if I try the person's last name and not their first name for example it would also show up in results.

**Comment by rasom** [comment]
@errorists got it, thanks, I will add it separately

**Comment by hesterbruikman** [comment]
> on my end if I would start with p because I only remember the Porcupine part of the username, it wouldn't show the suggestion, and it should.

@rasom @errorists let's leave this as improvement for 1.8 though. This is the last PR to merge before release cut 💪

**Comment by rasom** [comment]
@hesterbruikman yep I understand now that it should, but it has never worked this way and this is unrelated to current pr. I will add this separately

**Comment by Serhy** [comment]
Tested with Android9, Android8, iOS14 and works as it have to:
- Mention by nickname in 1-1/public/group chat for user in Contact and Non-contact works
- No mention by nickname for blocked contact
- Same mention is found when searching by nickname or ENS or three-word name
- In chat for mentioned it's nickname always supersedes ENS and three-word

**Comment by qoqobolo** [comment]
#### ISSUE 3: If add user with ENS name to contacts manually, then his name in the suggestions list in chat view will be gray. 
Android, iOS.

_Steps:_
- Go to Profile -> Add new contact
- Enter ENS name, e.g. `@dikhasi` -> tap **+**
- Open chat view and type `@`to check suggestions list


Screenshot 2020-09-23 at 15 01 34

#### Note

Don't consider this issue as a blocker. Up to you fix it now or later (in this case a separate issue will be created).

**Comment by rasom** [comment]
@qoqobolo issue 3 should be fixed now

**Comment by flexsurfer** [comment]
@rasom ready to be merged

**Comment by rasom** [comment]
I'm afk, will merge in 30 mins

**Comment by rasom** [comment]
@flexsurfer merged

**Pull request merged**
