### PR TITLE
Use regular react-native-webview

### LINKED ISSUE #10560: dragonereum.io doesn't work on Android
# Bug Report

## Problem

https://dapp.dragonereum.io dapp doesn't recognize status as wallet on Android

#### Expected behavior

Dapp asks for permissions

#### Actual behavior

Suggests to download wallet

#### Notes

Probably related to latest webview update and js injection on Android

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

Open dapp.dragonereum.io Dapp in status on Android 10

### LINKED ISSUE #11224: web pages are not rendered on Android, html text is shown instead
# Bug Report

## Problem

when opening web pages in status browser they are not rendered 

image

#### Expected behavior

page is rendered 

/// Samsung Galaxy Note 10 (Android 10)

### PR DESCRIPTION
**Pull request by rasom**
fixes: #10560 
fixes: #11224

### CODE REVIEW

**Comment by flexsurfer** [comment]
just tried works perfect, both https://github.com/status-im/status-react/issues/10560 and https://github.com/status-im/status-react/issues/11224 are fixed

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
@flexsurfer @siphiuel 
so we can't use this one, right?

**Comment by flexsurfer** [comment]
@rasom  ? why we can't ? lets move it to QA

**Comment by rasom** [comment]
@flexsurfer so the only problem we have is that simpledapp.eth doesn't work with this lib? Or that's not an issue?

**Comment by flexsurfer** [comment]
@rasom it works in status for the first time , but doesn't work after reload but that's totally fine

**Comment by vkjr** [comment]
@rasom, there was a security issue in regular `react-native-webview` that was fixed in our implementation. [Details here](https://github.com/status-im/security-reports/issues/24). I think it would be nice to check if it is already resolved in latest updates. 

cc @0kok0

**Comment by Serhy** [comment]
Tested builds with iOS14, Android9, Android8:
Can connect to dragonereum and buy an item there. Can't reproduce #11224. Can load images and different languages webpages and loads fine. Ens dapp loads and reloads fine (apart simpledapp.eth which is dap issue as I understand). Can exchange on uniswap.eth as expected.

But indeed https://github.com/status-im/security-reports/issues/24 is reproducible within this PR (and fine in develop).

**Comment by rasom** [comment]
@vkjr @Serhy I don't have access to this repo status-im/security-reports#24

**Comment by vkjr** [comment]
@rasom, unfortunately I don't have access to repo's settings

**Comment by flexsurfer** [comment]
@Serhy could you try this one https://github.com/status-im/status-react/issues/11283 here ?

**Comment by flexsurfer** [comment]
@rasom @vkjr @siphiuel what do you guys think is we create new fork from latest version of webview and will add only this commit to it https://github.com/status-im/react-native-webview/commit/f7a3d58b2ff85e4e8c2fabe6d49aeb7b6aaedeea ?

**Comment by rasom** [comment]
@flexsurfer im working on this since yesterday

**Comment by rasom** [comment]
@flexsurfer @Serhy updated PR with our fork, that commit should be in place

**Comment by flexsurfer** [comment]
@Serhy could you take a look ?

**Comment by Serhy** [comment]
Looks good to me now, - can't reproduce any of issues now with Android 9, iOS14

**Comment by flexsurfer** [comment]
@rasom lets merge it then :)

**Comment by 0kok0** [comment]
Sorry for being late on this, was quite occupied with bug bounties. Great regression catch @vkjr

**Pull request merged**
