### PR TITLE
Fix text input animations lags

### PR DESCRIPTION
**Pull request by Ferossgp**

### CODE REVIEW

**Comment by Serhy** [comment]
On Android 9 still can reproduce the issue. 
In 1-1 chat (with 30 stickers and 5 images) - scrolled down while keyboard was open and switched to images pad - it collapses sticker/command/image (until re-navigate to chat view)
(tested second Jenkins build https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200804-125414-33ee15-pr-universal.apk)

**Comment by qoqobolo** [comment]
### ISSUE 1

If open chat (any type), open keyboard (set focus on the text input), send the app to the background, and open it again, the input field will be shifted upwards.

**Only Android 8, 10**

ezgif com-resize (12)

### ISSUE 2

If open chat that contains a long message, open keyboard, send the app to the background, reopen it, and switch to sticker pad, then text input and sticker pad will be shifted upwards and overlaid on the chat history.

**Only Android 8, 10**

ezgif com-resize (13)

**Comment by Ferossgp** [comment]
@qoqobolo 

Issue 1 was always present as it is in the tabbar keyboard handling. If we want to fix it, I would do it as a separate task.

Can't replicate 2 on my device, but I pushed a commit that may fix it.

**Comment by churik** [comment]
@Ferossgp 
according to issue 2: still can replicate it on my Xiaomi mi Note 9 (Android 10)
Will ask @Serhy to try on his devices as well.
My main concern that probably it may cause other issues like this, but if it is only me it will likely have lower prio.
@Serhy can you assist please?
@qoqobolo on your devices it is not reproducible, is it right?

**Comment by Serhy** [comment]
I can't reproduce 2nd bug there on Android 8 (Samsung J7) and Android 9 (Galaxy S8).

**Comment by qoqobolo** [comment]
@churik yes, currently can't reproduce issue 2. But now if I switch from keyboard to sticker pad while scrolling long message, sticker/image/command panel height changes, sometimes it's overlapped with main tabs.

Google Pixel 2, Android 10.

BAACAgQAAxkBAAEqDo1fLTNJXumiwIfk3n7bq6QhNzCrggACdAcAAo6vaVFMR8xOpLe0xhoE_1596797912 01

**Comment by Ferossgp** [comment]
@qoqobolo what build id is in latests gif?

**Comment by qoqobolo** [comment]
@Ferossgp it was nightly. My fault, sorry.

**Comment by qoqobolo** [comment]
@Ferossgp I checked issue in the latest gif a few more times, and eventually reproduced it both in build [bc64eb3](https://github.com/status-im/status-react/commit/bc64eb34fea860aa2cc321903e6bcf3f244ac90b) and in nightly. It isn't reproducible every single time though.
Would it be better for you if I create a new separate issue for this case?

**Comment by Serhy** [comment]
Since 2nd issue from https://github.com/status-im/status-react/pull/11033#issuecomment-670462536 is in develop we'll create a separate issue for it. 
The https://github.com/status-im/status-react/issues/11031 has been fixed (can reproduce anymore in 1-1/Public/Group chats on Android 8/Android 9) 

This one is ready for merge.

**Review by flexsurfer — APPROVED** [review]

**Pull request merged**
