### PR TITLE
use react-native-webview community lib

### PR DESCRIPTION
**Pull request by yenda**
react-native core webview is deprecated

### Steps to test

svgs are only used for collectibles so check if dem kitties render properly

status: ready

### CODE REVIEW

**Comment by flexsurfer** [comment]
@yenda  we use webview only in extensions, let's remove it, because we removed extensions

**Comment by flexsurfer** [comment]
also we can remove `status-react/resources/mapview/`

**Review by vitvly — APPROVED** [review]

**Review by pedropombeiro — APPROVED** [review]

**Comment by churik** [comment]
@yenda would you mind to rebase it?

**Comment by yenda** [comment]
I can't I'm afk but it is rebased afaik, might have used wrong apk for e2e

**Comment by flexsurfer** [comment]
@churik please tell me if you need any help with this

**Comment by churik** [comment]
@flexsurfer 
error when opens Collectibles (i.e. Collectibles > CK, or Collectibles > Crytptostrickers) 
photo_2019-08-26 10 38 30
Reproducible on IOS and Android.
Logs: [Status-debug-logs-1.zip](https://github.com/status-im/status-react/files/3540231/Status-debug-logs-1.zip)

**Comment by flexsurfer** [comment]
webview is removed https://github.com/status-im/status-react/pull/8841

**Pull request closed without merging**
