### PR TITLE
[DO NOT MERGE] Release 0.13.2

### LINKED ISSUE #8882: Small copy tweak to v1 notification
# Problem

We want to mention in [this banner](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding), with minimal words, that a user's contact code will also change in v1.

## Implementation

Change this line from:

`Updating to 1.0 will result in a loss of access to this wallet.`

to

`Your contact details will change as well.`

We're justifying replacing the original line because it's not strictly true. A user who updates to v1 without his/her seed phrase will lose access to their wallet -in- Status on -that device- only.

## Acceptance Criteria

Copy change matches exactly.

### LINKED ISSUE #8883: Create 0.13.2 with v1 warning only
# Problem

To spread the word about v1 as much as possible, we want to release [this banner & v1 notification](https://github.com/status-im/status-react/pull/8599) in a build on the latest beta release for iOS (0.13.1). Android not possible due to 64 bit issue.

## Implementation

Isolate [this banner](https://github.com/status-im/status-react/pull/8599) with [copy change](https://github.com/status-im/status-react/issues/8882) into its own branch for release testing on iOS.

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #8882
fixes #8883

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

**Comment by jakubgs** [comment]
Should we even care if Android build works? We can't release for Android in Play Store anyway since we can't do 64 bit builds. We can only release for iOS.

**Comment by pedropombeiro** [comment]
> Should we even care if Android build works? We can't release for Android in Play Store anyway since we can't do 64 bit builds. We can only release for iOS.

Yeah, I don't think the Android build matters for this purpose.

**Comment by asemiankevich** [comment]
@flexsurfer why we are using hardcoded wallet address and dont use user's actual one in the copy?
 
@rachelhamlin 

image

**Comment by flexsurfer** [comment]
@asemiankevich have no idea, good catch!

**Comment by flexsurfer** [comment]
@asemiankevich removed hardcoded number

**Comment by asemiankevich** [comment]
@flexsurfer lets merge to release branch 0.13.2

**Pull request merged**
