### PR TITLE
Fix fingeprint setting in Onboarding

### LINKED ISSUE #8533: [Onboarding] Enable fingerprint login during first-time setup
# Problem

As it stands now, the below piece of functionality:
  - fingerprint work done in https://github.com/status-im/status-react/pull/8127

is not integrated into the onboarding setup flow

## Implementation

Integrate https://github.com/status-im/status-react/pull/8127 with onboarding setup.

Figma screens for reference: https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A14702

### PR DESCRIPTION
**Pull request by vitvly**
Fixes #8533

### CODE REVIEW

**Comment by flexsurfer** [comment]
@siphiuel could you also please move fingerprint option in profile out of dev mode

**Comment by vitvly** [comment]
@flexsurfer done

**Review by flexsurfer — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by annadanchenko** [comment]
@siphiuel 

### Issue 1 No popup asking for fingerprint is shown when creating account

After user taps on Enable fingerprint button screen about enabling notifications is shown, there is no popup asking user for the fingerprint
Video: https://drive.google.com/file/d/1BOY8HayT5FBtROswJ7rIFoXteL9ILUG9/view?usp=sharing
Steps:
1. Install app and run it
2. Tap on Get Started
3. Tap Generate a key
4. Select first name in the list and tap Next
5. Tap next
6. Provide password and tap Next
7. Confirm password and tap Next
8. Tap on Enable Fingerprint

Expected: popup asking user for fingerprint
Currently: app proceeds to the next screen to Enable Notifications

OS, Device: Android 9, real Samsung Galaxy S10

**Comment by annadanchenko** [comment]
Question:  there is no design/specification if user needs to save password and only after this fingerprint can be used to sign in

@flexsurfer proposed: "when you press enable fingerprint native fingerprint popover should appear, and we should save a password, next time login user with fingerprint ,no password needed"

**Comment by annadanchenko** [comment]
I haven't completed testing but looks like we are missing expectations/specification on 
1. what happens after user taps on Enable Fingerprint in new on-boarding
2. if user needs to save password and only after this fingerprint can be used to sign in

**Comment by annadanchenko** [comment]
removed "release" label as it looks like more work then we can do now for 0.14.0 release cc @rachelhamlin

**Review by dmitryn — APPROVED** [review]

**Comment by oskarth** [comment]
@siphiuel What's the state of this PR?

**Comment by flexsurfer** [comment]
we decided to postpone it and reimplement later cc @rachelhamlin @hesterbruikman

**Pull request closed without merging**
