### PR TITLE
ios: fix xcode using system Node.js version

### PR DESCRIPTION
**Pull request by jakubgs**
As discovered in:
* https://github.com/status-im/status-mobile/pull/15225

The attempt to fix this in:
* https://github.com/status-im/status-mobile/pull/15180

But it doesn't appear to work, so instead I'm allowing an override of `NODE_BINARY` variable and spetting it when defining the Nix shell.

### CODE REVIEW

**Comment by jakubgs** [comment]
I added an `env` to the `shellScript` part and found out that Nix env variables are there:
```
 > grep '^NIX_' xcode_rn.env | head -n2
NIX_BUILD_CORES=8
NIX_BINTOOLS_FOR_TARGET=/nix/store/qqah7bv2c3rvfx3g0b15lridvg4wz24l-cctools-binutils-darwin-wrapper-949.0.1
```
But our `NODE_BINARY` env variable is not:
```
 > grep '^NODE_' xcode_rn.env | head -n2 
NODE_NAME=macm1-01
NODE_PATH=/nix/store/z7zh97v0h0h535dzrasq4zc4s4m9v9p8-nodejs-16.17.1/lib/node_modules
```
We can see also that `NODE_OPTIONS` isn't set either.

**Comment by jakubgs** [comment]
But `STATUS_MOBILE_HOME` and `STATUS_GO_IOS_LIBDIR` are:
```
 > grep '^STATUS_MOBILE_HOME' xcode_rn.env 
STATUS_MOBILE_HOME=/Users/jenkins/workspace/status-mobile_prs_ios_PR-15226

 > grep '^STATUS_GO_IOS_LIBDIR' xcode_rn.env
STATUS_GO_IOS_LIBDIR=/nix/store/w8ik394a44sfvrlv2nvzr1sagax3nb2n-status-go-0.135.2-6cdc0ed-ios/Statusgo.xcframework
```
So `shellHook` scripts are clearly working.

**Comment by jakubgs** [comment]
I see, the issue is that variables from other shells are not merged into the main shell when using `inputsFrom`:
```nix
  shellHook = lib.concatStringsSep "\n" (lib.catAttrs "shellHook"
    (lib.reverseList inputsFrom ++ [ attrs ]));
```
https://github.com/NixOS/nixpkgs/blob/04349bc072241575f3f9bd0f476c6a8835f27077/pkgs/build-support/mkshell/default.nix#L41-L42

Only certain things get passed into the final shell:
```nix
  mergeInputs = name:
    (attrs.${name} or [ ]) ++
    (lib.subtractLists inputsFrom (lib.flatten (lib.catAttrs name inputsFrom)));

  rest = builtins.removeAttrs attrs [
    "name"
    "packages"
    "inputsFrom"
    "buildInputs"
    "nativeBuildInputs"
    "propagatedBuildInputs"
    "propagatedNativeBuildInputs"
    "shellHook"
  ];
```
https://github.com/NixOS/nixpkgs/blob/04349bc072241575f3f9bd0f476c6a8835f27077/pkgs/build-support/mkshell/default.nix#L17-L30

Which means we are forced to use `shellHook` if we want merging of shells using `inputsFrom` to work.

**Comment by jakubgs** [comment]
It's worth noting that there's a bunch of Xcode paths put in front of the Nix paths in `PATH`:
```
 > grep '^PATH=' xcode_rn.env | tr ':' '\n' | head -n15
PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/appleinternal/bin
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/bin
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/appleinternal/bin
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/local/bin
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/local/bin
/Applications/Xcode.app/Contents/Developer/usr/bin
/Applications/Xcode.app/Contents/Developer/usr/local/bin
/Users/jenkins/.bundle/ruby/2.7.0/bin
/Users/jenkins/workspace/status-mobile_prs_ios_PR-15226/node_modules/.bin
/nix/store/ysnid4p0w4r9kg9834i327j4lxhcb50f-bash-interactive-5.2-p15/bin
/nix/store/a21jngr2a6gxln6nifn4xw9k5l8kda3l-bash-5.1-p16/bin
```

**Review by J-Son89 — APPROVED** [review]

**Pull request merged**
