### PR TITLE
Update French, Japanese, and Korean translations

### PR DESCRIPTION
**Pull request by jinhojang6**
Translated by the community

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
Don't know any of those languages but LGTM.

**Review by flexsurfer — APPROVED** [review]

**Comment by annadanchenko** [comment]
@jinhojang6 I'd like to modify some Russian translations. It is better to do it in this PR or via Lokalise?

 E.g. "buy-with-snt": "Купить с Помощью СНТ", -> "Купить с Помощью SNT"
   "complete-hardwallet-setup": "Эта карта теперь является неотъемлемой частью вашей безопасности multiaccounts. Транзакции не могут быть отправлены без него." It also needs changes. Would really like to dedicate at least 2-3 hours for the thorough review and update

**Review by annadanchenko — CHANGES_REQUESTED** [review]
there are a number of changes I'd like to do for Russian translation, please let me know if they should be done here or in Lokalise

**Comment by jinhojang6** [comment]
> @jinhojang6 I'd like to modify some Russian translations. It is better to do it in this PR or via Lokalise?
> 
> E.g. "buy-with-snt": "Купить с Помощью СНТ", -> "Купить с Помощью SNT"
> "complete-hardwallet-setup": "Эта карта теперь является неотъемлемой частью вашей безопасности multiaccounts. Транзакции не могут быть отправлены без него." It also needs changes. Would really like to dedicate at least 2-3 hours for the thorough review and update

**Comment by jinhojang6** [comment]
@annadanchenko removed ru.json from this PR. Let's review it more :)

**Review by annadanchenko — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]

**Comment by asemiankevich** [comment]
@jinhojang6 not sure but i still see changes in ru.js file https://github.com/status-im/status-react/pull/8681/files#diff-25b49cf6ec8874f48629f17df03a67b6 , i thought we want to update Russian separately?

**Comment by jinhojang6** [comment]
@annadanchenko @asemiankevich . It is exactly the same as [the original ru.json file](https://github.com/status-im/status-react/blob/develop/translations/ru.json) but Git shows a line break difference. I copied and pasted the original one and overrided with the original ru.json file on this pull request.

Can this way make some problem? If so, let me try to tweak this pull request.

**Comment by jakubgs** [comment]
>Can this way make some problem?

Nope, no problems can be caused by this.

**Comment by churik** [comment]
Failed e2e are not related to PR.

**Comment by flexsurfer** [comment]
@jinhojang6 could you squash commits please

**Comment by jinhojang6** [comment]
@flexsurfer

I squashed the commits but the builds failed with an error `[2019-08-08T01:11:21.550Z] Error encountered performing task 'doo' with profile(s): 'test'`

Do you know where the problem is? I updated the json files with the latest versions but got the same error message.

**Comment by dmitryn** [comment]
This PR broke `lein test-cljs`. Please don't merge PRs with broken tests/builds.

**Comment by flexsurfer** [comment]
@dmitryn right, i forgot that we have tests for translations, we have a very old checkpoint, we have to update it

**Comment by dmitryn** [comment]
@flexsurfer i've fixed translations tests in https://github.com/status-im/status-react/pull/8687 btw

**Comment by flexsurfer** [comment]
@dmitryn could you please make a separate PR ? and we'll merge it because develop is broken

**Pull request merged**
